### ISSUE TITLE
LDAP + TOTP authentication failure

### ISSUE THREAD

**Issue by CSIR-FB** [opnsense/core#4238] opened 2020-08-03 09:29 UTC
Hi All,

This is my first report so I hope I gave enough info.

Asked for help on the forums but no replies from 58x views: https://forum.opnsense.org/index.php?topic=18251.0

I have read:
[-] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[-] I have searched the existing issues and I'm convinced that mine is new.

ldap + totp authentication just give "authentication failure" error.

I have Opnsense 20.1.9 installed, and configured for Radius and LDAP authentication.
The same issue happens version in 18.7 and 19.1

OPNsense 20.1.9-amd64
FreeBSD 11.2-RELEASE-p20-HBSD
OpenSSL 1.1.1g 21 Apr 2020

Authentications types that work:
Local user
Local user + TOTP (Google Authenticator)
Radius user
LDAP user

I did have to install opnsense-patch b2affd1 to get LDAP working. (allow CA cert selection under server)

Then imported the ldap user and generated the QR code.

I cannot get LDAP + TOTP auth to work. Tried token in front and rear of password, and using Google Authenticator, but tried 2FA Authenticator and other compatible totp apps too.
Confirmed that time was in sync. ntp server is set and syncing.

Tester just gives this error:
The following input errors were detected:    Authentication failed.

The log files do not seem to show any errors regarding ldap or totp.

There is nowhere to revert to as I have not been able to get it working.

**To Reproduce**
Install opnsense 20.1 and configure ldap+totp auth server.

**Expected behavior**
Authentication success is expected.

**Relevant log files**
No logs with details.

**Environment**
VMWare ESXi + opnsense 20.1.9 fully updated.

OPNsense 20.1.9-amd64
FreeBSD 11.2-RELEASE-p20-HBSD
OpenSSL 1.1.1g 21 Apr 2020

**Comment by mimugmail** [comment] 2020-08-03 09:40
Can you please close this one here and we stick to the forums. It's not a bug and would bind developer resources to help out.

**Comment by CSIR-FB** [comment] 2020-08-03 10:12
Sure, will do. Seemed no one had answer so logged a issue.
Thank you.

**Comment by CSIR-FB** [comment] 2020-08-05 10:17
Apologies for re-opening this issue.

mimugmail took me through extensive troubleshooting and ldap+totp just refuses to authenticate.
According to tcpdump it looks as if the ldap query is not received by the server when ldap+totp is used.

All the steps taken and tested are documented here: [(https://forum.opnsense.org/index.php?topic=18251.0)]
I tested on 18.7, 19.1, 20.1.9 and 20.7 with same results.

Last test was to install blank 20.1 amd64 and just configure and test ldap+totp. Still fails on totp authentication while all other auths work.

I am happy to re-try the install if someone can give me a working opnsense version number to download.

**Comment by mimugmail** [comment] 2020-08-05 20:53
Hm, this is really weird, I wasn't able to setup ldap+totp on two different systems now (20.7 and 20.1.6), 
I checked the config at a customer site where it's working (20.1.8) and can't find a real difference.
@AdSchellevis do you have a system to test or is there an easy way to diagnose? Otherwise I can give you access to one. It doesn't even try to do a ldap bind.

**Comment by AdSchellevis** [comment] 2020-08-06 06:50
@mimugmail yes I do, still works like a charm, since otp is sort of a decorator it doesn't sound logical if both work separately but not in combination.

**Comment by mimugmail** [comment] 2020-08-06 08:56
@AdSchellevis forget it .. seems it was too late yesterday evening. Sorry for wasting your time ... 

@CSIR-FB I got it working now, on my system the time was 2 minutes behind while grace period is 60sec 


`2020-08-06T10:50:11 | ntpd[13036]: kernel reports TIME_ERROR: 0x4041: Clock Unsynchronized`

Now it works on both systems ... 

If you dont see traffic to ldap your OTP already failed.

**Comment by CSIR-FB** [comment] 2020-08-06 11:42
I have changed ntp time servers but receive the clock unsync error every time I restart ntp:

Aug  6 13:37:00 pta-vpn1-2fa ntpd[27457]: ntpd 4.2.8p15@1.3728-o Tue Jul 28 02:25:36 UTC 2020 (1): Starting
Aug  6 13:37:00 pta-vpn1-2fa ntpd[27457]: Command line: /usr/local/sbin/ntpd -g -c /var/etc/ntpd.conf -p /var/run/ntpd.pid
Aug  6 13:37:00 pta-vpn1-2fa ntpd[27457]: ----------------------------------------------------
Aug  6 13:37:00 pta-vpn1-2fa ntpd[27457]: ntp-4 is maintained by Network Time Foundation,
Aug  6 13:37:00 pta-vpn1-2fa ntpd[27457]: Inc. (NTF), a non-profit 501(c)(3) public-benefit
Aug  6 13:37:00 pta-vpn1-2fa ntpd[27457]: corporation.  Support and training for ntp-4 are
Aug  6 13:37:00 pta-vpn1-2fa ntpd[27457]: available at https://www.nwtime.org/support
Aug  6 13:37:00 pta-vpn1-2fa ntpd[27457]: ----------------------------------------------------
Aug  6 13:37:00 pta-vpn1-2fa ntpd[85528]: proto: precision = 0.977 usec (-20)
Aug  6 13:37:00 pta-vpn1-2fa ntpd[85528]: basedate set to 2020-07-16
Aug  6 13:37:00 pta-vpn1-2fa ntpd[85528]: gps base set to 2020-07-19 (week 2115)
Aug  6 13:37:00 pta-vpn1-2fa ntpd[85528]: restrict: 'monitor' cannot be disabled while 'limited' is enabled
Aug  6 13:37:00 pta-vpn1-2fa ntpd[85528]: Listen and drop on 0 v6wildcard [::]:123
Aug  6 13:37:00 pta-vpn1-2fa ntpd[85528]: Listen and drop on 1 v4wildcard 0.0.0.0:123
Aug  6 13:37:00 pta-vpn1-2fa ntpd[85528]: Listen normally on 2 vmx0 146.64.214.5:123
Aug  6 13:37:00 pta-vpn1-2fa ntpd[85528]: Listen normally on 3 vmx0 [fe80::250:56ff:fe9a:d3b8%1]:123
Aug  6 13:37:00 pta-vpn1-2fa ntpd[85528]: Listen normally on 4 vmx1 146.64.235.125:123
Aug  6 13:37:00 pta-vpn1-2fa ntpd[85528]: Listen normally on 5 vmx1 [fe80::250:56ff:fe9a:2997%2]:123
Aug  6 13:37:00 pta-vpn1-2fa ntpd[85528]: Listen normally on 6 lo0 [::1]:123
Aug  6 13:37:00 pta-vpn1-2fa ntpd[85528]: Listen normally on 7 lo0 127.0.0.1:123
Aug  6 13:37:00 pta-vpn1-2fa ntpd[85528]: Listening on routing socket on fd #28 for interface updates
Aug  6 13:37:00 pta-vpn1-2fa ntpd[85528]: kernel reports TIME_ERROR: 0x2041: Clock Unsynchronized
Aug  6 13:37:00 pta-vpn1-2fa ntpd[85528]: 0.0.0.0 c01d 0d kern kernel time sync enabled
Aug  6 13:37:00 pta-vpn1-2fa ntpd[85528]: kernel reports TIME_ERROR: 0x2041: Clock Unsynchronized
Aug  6 13:37:00 pta-vpn1-2fa ntpd[85528]: 0.0.0.0 c012 02 freq_set kernel 28.417 PPM
Aug  6 13:37:00 pta-vpn1-2fa ntpd[85528]: 0.0.0.0 c016 06 restart
Aug  6 13:37:00 pta-vpn1-2fa ntpd[85528]: DNS time.nmisa.org -> 196.21.187.2
Aug  6 13:37:00 pta-vpn1-2fa ntpd[85528]: 196.21.187.2 8011 81 mobilize assoc 44020
Aug  6 13:37:00 pta-vpn1-2fa ntpd[85528]: DNS tick.meraka.csir.co.za -> 146.64.58.41
Aug  6 13:37:00 pta-vpn1-2fa ntpd[85528]: 146.64.58.41 8011 81 mobilize assoc 44021
Aug  6 13:37:00 pta-vpn1-2fa ntpd[85528]: DNS tock.meraka.csir.co.za -> 146.64.8.7
Aug  6 13:37:00 pta-vpn1-2fa ntpd[85528]: 146.64.8.7 8011 81 mobilize assoc 44022
Aug  6 13:37:01 pta-vpn1-2fa ntpd[85528]: 146.64.8.7 8014 84 reachable
Aug  6 13:37:04 pta-vpn1-2fa ntpd[85528]: 196.21.187.2 8014 84 reachable
Aug  6 13:37:05 pta-vpn1-2fa ntpd[85528]: 146.64.58.41 8014 84 reachable
Aug  6 13:37:07 pta-vpn1-2fa ntpd[85528]: 146.64.8.7 901a 8a sys_peer
Aug  6 13:37:07 pta-vpn1-2fa ntpd[85528]: 0.0.0.0 c615 05 clock_sync


And ntp seems fine according to the Status page.

Status | Server | Ref ID | Stratum | Type | When | Poll | Reach | Delay | Offset | Jitter
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Candidate | 196.21.187.2 | .UTC. | 1 | u | 20 | 64 | 17 | 0.476 | +2.238 | 0.223
Unreach/Pending | 146.64.58.41 | .GPS. | 1 | u | 16 | 64 | 17 | 0.277 | -1.116 | 0.227
Active Peer | 146.64.8.7 | .GPS. | 1 | u | 18 | 64 | 17 | 0.344 | -0.990 | 0.133

Someone else had the same issue but was never answered: https://forum.opnsense.org/index.php?topic=14054.0

**Comment by AdSchellevis** [comment] 2020-12-06 18:31
should be this https://github.com/opnsense/core/issues/4451

**Closed by AdSchellevis** 2020-12-06 18:31 UTC
Labels: support
