### ISSUE TITLE
Track6 issue, RADVD and DHCPD6 conf not being set.

### ISSUE THREAD

**Issue by marjohn56** [opnsense/core#2585] opened 2018-07-30 08:53 UTC
I have a forum user 'space' who has an issue with dhcp6 tracking. It appears that his radvd and dhcpd are not running as the conf files are not being setup. I am able to replicate this problem. Through debugging it seems that although dhcp6 is setting the correct info on the interfaces, this is not being picked up when a call to services_dhcpd_configure() is made, this may be a timing issue. I have a working solution which is to call a new function I have introduced into services.inc which only configures radvd and dhcpd6.

PR to follow

**Comment by fichtner** [comment] 2018-07-30 09:17
why not pin down the race condition and fix it? race condition applies we do all the right things but not in the right order all the time.

**Comment by marjohn56** [comment] 2018-07-30 09:21
Because I am not yet sure it is a race condition. I have a fix but I'm looking around...

**Comment by marjohn56** [comment] 2018-07-30 09:40
Indeed.. a call to reconfigure dhcpd6 and RADVD ONLY ( new function ) like this appears to cure the issue.
It may also help when the prefix changes.
interfaces.inc Line 2586 
`case 'dhcp6':
            log_error("Inteface track6 configure 8");
            if ($linkupevent == true) {
                /*
                 * NOTE: Usually come here from rc.linkup calling so just call directly intead of generating event
                 *  Instead of disrupting all other v4 configuration just restart DHCPv6 client for now
                 *
                 * XXX: Probably DHCPv6 client should handle this autmagically itself?
                 */
                $parentrealif = get_real_interface($lancfg['track6-interface']);
                log_error("Inteface track6 configure 4");
                killbypid("/var/run/dhcp6c_{$parentrealif}.pid", 'HUP');
            } else {
                services_dhcpd6_configure_only(array(),true);`

**Comment by marjohn56** [comment] 2018-07-30 09:42
Just a bit concerned about the blacklist array containing nothing, is that a bit of a no no?

**Comment by fichtner** [comment] 2018-07-30 09:44
array() is the default, no blacklist items

**Comment by marjohn56** [comment] 2018-07-30 09:46
OK, I've tested the fix multiple times, seems to cure it, shall I PR it?

**Comment by fichtner** [comment] 2018-07-30 09:47
sure, but there will be more questions. I've removed it because the calls are buried too deep in the private interface call stack.

**Comment by marjohn56** [comment] 2018-07-30 09:47
Empty blacklist is fine, but we'd need to add to that list in interface_track6_configure() to make it safe.

**Comment by marjohn56** [comment] 2018-07-30 09:50
PR #2586

**Comment by fichtner** [comment] 2018-08-05 12:42
Confirmed fixed by multiple testers. Will be in 18.7.1.

**Closed by fichtner** 2018-08-05 12:42 UTC
Labels: bug
