### ISSUE TITLE
Suricata: Unable to edit action of a single rule when using a policy

### ISSUE THREAD

**Issue by ashceryth** [opnsense/core#4658] opened 2021-02-01 08:16 UTC
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**

With 21.1 it seems to be impossible to override the alert action of a single alert in Suricata at Services > Intrusion Detection > Administration > Rules when there is a policy that overrides the alert action of the ruleset containing the rule. You can set the action from "Drop" to "Alert" and hit "Save" followed by "Apply", but the setting never gets applied (or overwritten by the policy again?). The the action is still "Drop" and the traffic is actually dropped.

The issue is also mentioned here: https://forum.opnsense.org/index.php?topic=21212.0

**To Reproduce**

1. Create a policy to set the rule actions of a ruleset from "Alert" to "Drop"
2. Edit a rule that is included in the overwritten ruleset (https://opnsense.example.com/ui/ids#rules)
3. Set action to "Alert"
4. Hit save and apply
5. Override is not applied

**Expected behavior**

The override gets applied after hitting apply.

**Environment**

OPNsense 21.1-amd64

**Comment by AdSchellevis** [comment] 2021-02-01 09:57
We should move the separate rules to the policy as well to fix this properly. The problem is that it removes the manual rules from the config if their the same as default, which doesn't work if a policy matches on the same case too. A quick temporary fix would be to not try to remove the rule after change, but as with all these manual adjustments it has a high risk of blowing up your config.xml.

Adding the sids to the policies and removing the actions on separate rules is likely the cleanest fix, I don't mind preparing a small fix to keep the current behaviour in between.

The downside of the proper fix is manual adjustments will vanish from the current rule page.

Already thought about this while working on the policies, but tried to limit the scope a bit and made sure the local adjustments are still being processed properly (highest priority), which doesn't help if we don't store them...

**Comment by kulikov-a** [comment] 2021-02-01 17:12
@AdSchellevis 
please can you explain why @ashceryth  case can be workarouned (at least on my test VM) by changing status (enabled\disabled) first? so if default state of rule is "enabled and drop", matched policy action: Alert and GUI won't let me change the action then i can disable it first (rules goes to __manual__), change action to drop (default) and reanable (rule stays in _manual_ policy)?

**Comment by kulikov-a** [comment] 2021-02-01 20:43
I hope now I understand and will not ask a stupid question
@AdSchellevis 
please explain, do you think that saving such rules (with the default parameters, but overlapping the matched policy) will inflate the config more than saving the rules with the current rule-based management approach? (imho there should still be less of them than current "modified" rules on rule-based configs)
and could you consider adding a some "Reset rule" button in "Rule detail" modal to completely reset the rule parameters (delete from config.xml and assign matched policies)?: 
sometimes it can be hard to remember why a rule got into "manual" policy — a change in status or action. and this would make it possible to return the rule to the matching policy for the cases described above (default parameters, but overlapping the matched policy)
thanks!

**Comment by AdSchellevis** [comment] 2021-02-02 07:51
@kulikov-a the problem with the current single rule entries is that a single entry of about 7 bytes (the sid) is encapsulated in a container which is much larger. when moving them to the policies you would logically define a single policy and select multiple sids in it, which consumes way less space (and is easier to validate). 

To some degree I expect complaints if we move the selection out of this window, which is also why I was a bit cautious to add the sids (plus a migration) in the first place, but in reality I don't think there's much choice here.

**Comment by kulikov-a** [comment] 2021-02-02 14:42
@AdSchellevis  thanks!
just trying to get a better understanding of how rules and policy processing works. just tell me if I bore you)
what if the "manual" field is added to the configuration in the "policies" section. and if the user touches the rule (it doesn't matter: changing its parameter from the default settings or vice versa by turning them back), then the user intentionally wants to remove this rule from under the policies and you we can put the rule's sid in this field? then at the time of creating the cache db a "manual" policy can be assigned to these sid's. will it inflate the config less?

**Closed** 2021-02-02 14:54 UTC
Labels: bug

**Comment by AdSchellevis** [comment] 2021-02-02 14:57
@kulikov-a no problem, my original idea just ran into issues due to the Javascript in the browser rending way too slow.  https://github.com/opnsense/core/commit/a2a21829fae11a1ad6d738cbd2c1639687ee6f53 commit makes sure you can still use the custom rule based overrides, do you own maintenance and warn if there are many defined.

**Comment by kulikov-a** [comment] 2021-02-02 15:19
Thanks!! already trying to test
