### ISSUE TITLE
Kernel route for Default-Gateway (static WAN) appears after update to 19.1.7

### ISSUE THREAD

**Issue by clystron** [opnsense/core#3464] opened 2019-05-04 17:12 UTC
I have a firewall running 18.7.10 with static WAN and BGP connected to 2 peers (setup was created with earlier version). BGP is used to manage the default-gateway of the system. After upgrading to 19.1.7 I noticed that there now is an additional Kernel-route present (visible in output of vtysh show ip route) which renders my BGP-setup useless because the BGP-route will not be chosen as long as there is a Kernel-route.

I noticed that the gateway-setting for the WAN-interface is now called "Auto-detect" (I believe this was just empty in the past) and Auto-detect now seems to do something even for statically configured WAN-interfaces. What I need in my setup is a gateway-setting called "None" because BGP handles my routing-table and I do not need a static default-route.

**Comment by fichtner** [comment] 2019-05-04 17:47
Do you have an unused WAN gateway set under System: Gateways: Single? If so, deleting it should probably fix the issue...

**Comment by clystron** [comment] 2019-05-04 17:48
I do have a WAN-gateway but it is used for policy based routing for some special cases so I can not really disable it as a solution. Would it be so bad to just have a setting "none" in addtion to "Auto-detect"? In the older version "Auto-detect" does nothing for a static WAN-interface and that has changed.

**Comment by clystron** [comment] 2019-05-04 17:55
From what I have seen in the code (/usr/local/etc/inc/gwlb.inc) get_interface_gateway uses the first gateway that is not disabled, has an IPv4 address and is on the wanted interface. I can temporarily fix the issue by only considering gateways that have the "default"-flag set but that will probably not survive the next update.
Not all entries in System:Gateways:Single are supposed to end up in the routing-table IMHO...

**Comment by bergfink** [comment] 2019-05-04 18:07
There used to be a "None" and now it's gone ;-)
![image](https://user-images.githubusercontent.com/16165131/57183039-8155fa00-6ea7-11e9-9b14-71cfcfc9cccf.png)

**Comment by fichtner** [comment] 2019-05-04 18:31
Well, it's the same value still, it was simply renamed in the GUI to reflect what it's supposed to do:

https://github.com/opnsense/core/commit/a386ccc2f
https://github.com/opnsense/core/commit/1982779e7

It appears the code underneath was broken for a long time but repaired for 19.1 so I wouldn't want to add a setting that emulates a bug. ;)

Go to Firewall: Settings: Advanced and set "Disable force gateway" to see if that makes a difference.

**Comment by clystron** [comment] 2019-05-04 18:43
"Disable force gateway" is set already, if I recall correctly I needed that right when I started to use BGP.
I fail to understand how not setting a gateway if the setting would be called "None" can be considered a bug. My WAN interface is configured statically and I simply do not want to specify a gateway and I also do not need the system to search for one.

**Comment by fichtner** [comment] 2019-05-04 18:47
We feel the same way. I removed the "incomplete" tag but you assume it's a bug but I have no way of telling because vital information is missing. The whole assumption presented could be wrong. There has to be a rule in /tmp/rules.debug messing this up.

Other people reported shared forwarding being buggy, but nothing substantial so far. You can try disabling that too.

**Comment by mimugmail** [comment] 2019-05-04 18:48
System : Gateways : Single .. there is no gateway ticked with default?

Any logs from system.log? Which gateway is your default when you stop FRR?

**Comment by clystron** [comment] 2019-05-04 18:51
There is no Gateway tagged as default, the system has been running without a static default-gateway in 18.7.xx.
FRR/BGP is working as exected but since there is a kernel route in the system the BGP route is simply not used.

**Comment by clystron** [comment] 2019-05-04 19:06
> 
> 
> We feel the same way. I removed the "incomplete" tag but you assume it's a bug but I have no way of telling because vital information is missing. The whole assumption presented could be wrong. There has to be a rule in /tmp/rules.debug messing this up.
> 

I dont quite understand what you mean. I initially labeled this as a bug because the update broke a working configuration and I pretty sure that the gateway-setting was labeled "None" when I first configured the system. One could also label it a feature because all I need is the possibility to NOT set a static default gateway so that BGP can do its job.

> Other people reported shared forwarding being buggy, but nothing substantial so far. You can try disabling that too.

Should "shared forwarding" influence the static routing-table? From the description that does not appear to be the case, I disabled that and rebootet and unfortunately it did not help.

Disabling the gateway-entry for the firewall rules or removing the "empty($gw)" condition in line 824 of gwlb.inc (function get_interface_gateway) makes the kernel route go away (after a reboot) but both are no permanent solutions. Having the option to set the upstream gateway to "None" would be.

**Comment by clystron** [comment] 2019-05-04 19:17
> 
> Which gateway is your default when you stop FRR?

In 19.1.7 the gateway just stays the same because the static route is still in place, in the previous version the system did not have a default-gateway without FRR running.

**Comment by clystron** [comment] 2019-05-04 19:25
Another hack to get rid of the unwanted route is to put an unreachable far-gateway (tested with 0.0.0.0) with the WAN-interface to the top of the System:Gateway:Single list, that will cause an error when the system tries to use it as a default-gateway and so there is no kernel-route.

All those workarounds point me to the forced "Auto-detect" in get_interface_gateway for static interfaces as the source of my issue. All I can do is find ways for the detection to fail when what I would need is to simply disable it.

**Comment by clystron** [comment] 2019-05-04 19:34
>  There has to be a rule in /tmp/rules.debug messing this up.
> 

I assume you mean rules with a "route-to"? I had issues with that in the past but now the only rules with a "route-to" in /tmp/rules.debug are the ones I need for my special source based routing case and those are like they were in 18.7.10.

**Comment by mimugmail** [comment] 2019-05-04 19:38
Disable FRR, reboot, post system.log please. And screenshot of Gateways please

**Comment by clystron** [comment] 2019-05-04 19:56
May I ask what you are looking for? I am willing to help but I also feel that I have shown the problem in detail. It is no longer possible to have no default-gateway in the system if there is a reachable, enabled (non-default)gateway in System:Gateway:Single for the WAN-interface. That means that the default-gateway received via FRR/BGP is simply ignored.

Rebooting with disabled FRR does not change anything for the routing-table, the unwanted route is still there.

**Comment by clystron** [comment] 2019-05-04 20:39
For reference: this is the commit that introduced auto-detect for a static WAN configuration
https://github.com/opnsense/core/commit/a66c8df416ff0809025baa00193a1796b460d33e

Franco already linked the commit that changed the wording from "None" to "Automatic" (later called "Auto-detect") above.

Changing "None" to "Auto-detect" is a massive change IMHO.

**Comment by fichtner** [comment] 2019-05-04 20:44
I don't agree and I'm unsubscribing now because you are not interested in why this was changed. If 18.7 works for you please use it. Assuming 18.7 == 19.1 is not going to work as an argument as we try to make the code base more robust.

**Comment by clystron** [comment] 2019-05-04 20:47
I do not demand 18.7 to be exactly like 19.1, I am asking how I can make my case work with 19.1.
As far as I have seen so far this is no longer possible and staying on 18.7 forever is not an option.

**Comment by fichtner** [comment] 2019-05-04 20:47
To be thorough, it was documented for 19.1.r1:
 
https://github.com/opnsense/changelog/blob/cb3cc8c420bb7cf6f21ab4bea212f1b1ea01a7b7/doc/19.1/19.1.r1#L30

**Comment by clystron** [comment] 2019-05-04 20:49
Ok, so it was documented, but it was not that obvious that "None" means "Automatic" now. I would like to configure my system to not have a static default-gateway but as I pointed out I can not get rid of all the gateway entries in System;Gateway:Single. How can I achieve this?

**Comment by clystron** [comment] 2019-05-04 20:54
> 
> 
> I don't agree and I'm unsubscribing now because you are not interested in why this was changed. 

You do not have to agree with me on this of course and I never wrote that I am not interested why this was changed. Nonetheless the fact that it was changed causes a problem for me and I would like to resolve that.

**Comment by mimugmail** [comment] 2019-05-05 05:07
I don't ask you these questions just for fun. I need as much informations as possible to not waste time with local testing. Now I can see your problem with auto-detect. 

From a supporter and user perspective this feature it will help more users locking them out theirselfs than it hurts others having no default gateway. As I'm very committed to FRR and BGP I can see your problems, I'll have a look what we can do, but this needs some time.

In general it's better to describe the current problem with all possible informations and impacts, rather than insisting something worked before an upgrade (this should be more a sidenote).

**Comment by fichtner** [comment] 2019-05-05 07:00
I do think the problematic code is this:

https://github.com/opnsense/core/blob/8b63fcded96b1334b15a802e9e7f7f4bdf237649/src/etc/inc/system.inc#L495-L521

Which a system.log would reveal within a minute if we had the snippet. This cannot be about "None" vs. "Auto-detect" because I said nothing changed here WRT your problem.

Deleting the code would probably solve the situation, but may break user setups depending on it so we have to tread carefully.

Do you agree with this analysis? Will you finally share a system.log to let us help you?

**Comment by clystron** [comment] 2019-05-05 08:49
First let me tell you both that I full appreciate the time you are investing here, I will answer your posts separately because I think it is easier to do.
> 
> 
> I don't ask you these questions just for fun. I need as much informations as possible to not waste time with local testing. Now I can see your problem with auto-detect.
>

I understand that but please also understand that I am not comfortable in posting a full system log of a to-be production machine (this problem was detected right before deploying it) without looking it over first. I asked what you are looking for so that I could only post an extract/snippet of the log and possibly save time. 
 
> From a supporter and user perspective this feature it will help more users locking them out theirselfs than it hurts others having no default gateway. As I'm very committed to FRR and BGP I can see your problems, I'll have a look what we can do, but this needs some time.
> 

I think you are going a little bit to far here, any network device will have limited connectivity if configured without a default gateway. Personally I do not think you have to go this far to protect your users from that. 

Second answer incoming...

**Comment by clystron** [comment] 2019-05-05 09:06
> 
> 
> I do think the problematic code is this:
> 
> https://github.com/opnsense/core/blob/8b63fcded96b1334b15a802e9e7f7f4bdf237649/src/etc/inc/system.inc#L495-L521
> 
> Which a system.log would reveal within a minute if we had the snippet. This cannot be about "None" vs. "Auto-detect" because I said nothing changed here WRT your problem.
> 
> Deleting the code would probably solve the situation, but may break user setups depending on it so we have to tread carefully.
> 
> Do you agree with this analysis? Will you finally share a system.log to let us help you?

We are going down the same path here, I focussed on what had changed between 18.7 and 19.1. and thats what lead me into get_interface_gateway which behaves differently in 19.1. and now returns a gateway. If I understood you correctly that change was actually considered more of a bug-fix, so is it not supposed to be possible to have a system without a default-gateway?

I do have those log-entries in the system-log (saying "assuming wan") in both versions, but only in 19.1. does the system detect a gateway to use as default. Again, thats what made me focus on the changes in get_interface_gateway. If you still need a system.log of a fresh boot I will need some time to power up the machine and prepare that for you.

Right now I have set an unreachable gateway as default in the wan-interface to avoid the route being set,
seeing the hardcoded "wan" just gave me another idea, what would happen if there were no interface called "wan"?

**Comment by clystron** [comment] 2019-05-05 09:18
> In general it's better to describe the current problem with all possible informations and impacts, rather than insisting something worked before an upgrade (this should be more a sidenote).

I agree with that, I was not sure initially how to formulate the issue and it seems now that it was not the best idea to focus on the update breaking stuff. The clearest and easiest way I can think of to describe the problem I have is this: I need a way to have no default-gateway route set by the system while still having an active entry in System:Gateways:Single for the wan-interface. The gateway listed there is not supposed to be the default-gateway, it is only used for parts of the traffic.

It seems I was kind of lucky that this has worked before.

**Comment by fichtner** [comment] 2019-05-05 09:29
I’m sorry, I have tried to give community support here and offered technical analysis but we seem to go round in circles and I have to take my time to help other community members now.

**Comment by clystron** [comment] 2019-05-05 09:50
> 
> 
> I’m sorry, I have tried to give community support here and offered technical analysis but we seem to go round in circles and I have to take my time to help other community members now.

I dont really understand how we are going in circles here, I have explained why I have not posted a full system.log yesterday and have asked if you need more information from that log other than the fact that those ROUTING-entries are there.

**Comment by clystron** [comment] 2019-05-05 11:16
> Deleting the code would probably solve the situation, but may break user setups depending on it so we have to tread carefully.
> 
> Do you agree with this analysis? Will you finally share a system.log to let us help you?

Just to be extra-clear: Yes the code you posted causes the problem, I can see that in my system.log.

"opnsense: /usr/local/etc/rc.bootup: ROUTING: no IPv4 default gateway set, assuming wan"

I dont need the system to "assume" and search for a gateway here, having no gateway is what I want.

This functionality has been there for some time, it only now causes the problem because the search for a gateway returns a result since 19.1.

**Comment by clystron** [comment] 2019-05-07 08:07
I have now prepared a simplified test-case for testing, its a basic setup with WAN/LAN interfaces and pretty much everything on default. The "nogateway" setup does not have an entry in System:Gateways:Single and therefor there is no default-gateway route, the "gateway" setup does have an entry that is not flagged as default-gateway and not set as default-gateway for the WAN-interface because its only there for a static route to reach a single network. Yet it gets chosen as default-gateway because of "Auto-detect". I think even if my setup is different this shows the basic issue I have.

[configs.zip](https://github.com/opnsense/core/files/3151433/configs.zip)

**Comment by mimugmail** [comment] 2019-05-07 08:28
@clystron I was already able to reproduce but I need some time to be sure how to go on since 19.7 code will act a bit different than 19.1. 

For now, and unofficial:

- No gateways configured will allow you to have no default gateway which will fit all usual BGP setups (I know, you need it for PBR)
- Unassign WAN and use opt1 and opt2 as you wan interfaces will allow you to use what you want to achieve with 19.1 but not with 19.7, there's a larger rewrite in progress.
- I didn't test your workaround with first far gateway in 19.7 code

Again, the code for "assuming" a gateway is around 10 years old and didn't work at all. With some user reports about related problems this was fixed in 19.1, so please be patient about which way this feature will go.

**Comment by clystron** [comment] 2019-05-07 09:02
Thanks a lot for your efforts, knowing that this is going to be considered for 19.7 is great and I can be patient now....

**Comment by fichtner** [comment] 2019-09-16 19:57
Closing as per https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

**Closed by fichtner** 2019-09-16 19:57 UTC
Labels: support
