### ISSUE TITLE
[Feature Request] OpenVPN Client Export: custom hostname resolution and save configuration options

### ISSUE THREAD

**Issue by ldldr** [opnsense/core#1728] opened 2017-07-19 11:51 UTC
I have seen this feature request before in some forum but I cannot find it anymore.

The attached patch does two things:

1. Any additional configuration options entered on the client export page can now be saved and do not have to be reentered every time.

2. When you have a multi-WAN setup it is desirable to have one OpenVPN server listening on each interface as a load-balancing/failover configuration. This can now be achieved by selecting _Custom setting through additional configuration options_ (see screenshot) and adding the necessary openvpn statements to the additional configuration options, for example:

```
remote vpn1.example.com 1194 udp
remote vpn2.example.com 1194 udp
remote-random
```

Here is the patch against vpn_openvpn_export.php: [vpn_openvpn_export.php.diff](https://gist.github.com/anonymous/45e6e182a217ab2ea170207c963fae0a)

![vpnexport](https://user-images.githubusercontent.com/30259412/28363137-93c4f910-6c7f-11e7-9bf8-13a28ba58e8c.png)

**Comment by AdSchellevis** [comment] 2017-07-19 16:40
I don't think we should save the last entered value for the advanced configuration ,we don't save any of the other options either. We could add the option to skip the hostname resolution and let the user decide for himself like you suggested.
The problem is that the next user has different servers configured and/or other different templates, we already don't fancy the manually inputs, this has a risk of growing complexity on a page that already isn't very pretty.

**Comment by ldldr** [comment] 2017-07-20 06:43
Maybe this is better discussed in the forum so that others can chime in with their ideas.

What is wrong with the _additional configuration options_ field? I don't agree that it is complex. On the other: it is important because it adds additional flexibility needed by most users. Please don't remove that field.

Usually you would have a set of configuration options that will not change when you export another configuration. For example you want to make sure every user uses the same configuration to access opnvpn via vpn. In that way it would actually be best to save all options of the client export page.

I think the desire of many is that they don't have to reenter the _additional configuration options_ (and other options) each time they reload the client export page. It is another step which might be error-prone if you don't copy/paste or you simply forget it. It does not matter so much if you do the exports one in a row but when the last time you exported was several weeks ago you wish you could just recall the last options with a single click.

I am aware that I just made a crude proposition how to approach this problem in the hope that it would be useful for someone and that eventually an improved solution will make it as a feature into opnsense.

BTW I found the user request I mentioned before on the pfSense forum:
https://forum.pfsense.org/index.php?topic=114609.0
https://forum.pfsense.org/index.php?topic=69173.0
https://redmine.pfsense.org/issues/3478

**Comment by jbakuwel** [comment] 2018-02-20 22:57
Hi ldldr, Ad,

I think this is a great idea. I've applied the patch to a couple of OPNsense instances I'm running (and also moved the key-direction directive to before the tls-key as Network Manager ignores it otherwise).

It would be even better if we could save the Additional configuration options for each selected Remote Access Server so these settings can be different for each Remote Access Server.

I speak quite a few programming language but sadly not php and am also not (yet?) familiar with the OPNsense framework. In other words I won't be able to contribute a working patch anytime soon - first need to get over the learning curve.

kind regards,
Jan

**Comment by fichtner** [comment] 2018-10-20 10:09
Closing due to rework happening in 
https://github.com/opnsense/core/issues/2787 right now.

**Closed by fichtner** 2018-10-20 10:09 UTC
