### ISSUE TITLE
nextcloud backup error

### ISSUE THREAD

**Issue by async-it** [opnsense/core#4337] opened 2020-09-09 12:13 UTC
[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
[X] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
This was working till 21.05.2020 (date of my last automatic backup file)
Backup on nextcloud server fail and return an error " Cannot get real username"

**To Reproduce**
1. Go to backups settings
2. Setup nextcloud backup according to the documentation related
3. Apply with "test/setup nextcloud"
4. get error "The following input errors were detected: Saved settings, but remote backup failed."

**Expected behavior**
A backup file should have been created on the Nextcloud user folder

LOGS:
```

2020-09-09T14:03:37 | config[31039] | {"url":"https:\/\/nextcloud.domain.tld\/ocs\/v1.php\/cloud\/user","content_type":null,"http_code":0,"header_size":0,"request_size":0,"filetime":-1,"ssl_verify_result":0,"redirect_count":0,"total_time":60.00872,"namelookup_time":0.03401,"connect_time":0,"pretransfer_time":0,"size_upload":0,"size_download":0,"speed_download":0,"speed_upload":0,"download_content_length":-1,"upload_content_length":-1,"starttransfer_time":0,"redirect_time":0,"redirect_url":"","primary_ip":"","certinfo":[],"primary_port":0,"local_ip":"","local_port":0,"http_version":0,"protocol":0,"ssl_verifyresult":0,"scheme":"","appconnect_time_us":0,"connect_time_us":0,"namelookup_time_us":34010,"pretransfer_time_us":0,"redirect_time_us":0,"starttransfer_time_us":0,"total_time_us":60008720}
-- | -- | --
2020-09-09T14:03:37 | config[31039] | Cannot get real username
```

OPNsense 20.7.2-amd64
FreeBSD 12.1-RELEASE-p8-HBSD
OpenSSL 1.1.1g 21 Apr 2020

Regards 

JS

**Comment by StopTrain** [comment] 2020-09-15 19:42
I'm running Nextcloud as well as OPNsense, both on the latest releases, and I'm not seeing this issue nor has it every stopped for me.

**Comment by async-it** [comment] 2020-09-16 12:44
Very strange as i have 2 setup running the exact same configuration and both fail to backup:
Opnsense OPNsense 20.7.2-amd64
Nextcloud 19.0.3

**Comment by Klaas-** [comment] 2020-09-20 20:12
this seems like a duplicate of #4232

**Closed** 2021-03-23 14:19 UTC
Labels: support
