### ISSUE TITLE
DHCP Server failing to issue system default DNS server

### ISSUE THREAD

**Issue by heyhewmike** [opnsense/core#5942] opened 2022-08-11 01:47 UTC
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

On Version 22.7.1 that I updated to on 10 Aug 2022, I had the DNS Servers left blank in the Services: DHCPv4. The help for that section says "Leave blank to use the system default DNS servers: This interface IP address if a DNS service is enabled or configured global DNS servers." and I am running Unbound DNS as my recursive DNS server. My Windows devices are receiving a IPv6 IP for the DNS providers and not the IPv4 interface IP address.

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

The system was working without issue in with the DNS Server fields in the DHCPv4 Service empty for 3+ years including upgrading to 22.7 when it was released, or shortly(next day) after.

**To Reproduce**

**Ensure that there is a DNS service enabled to mimic my issue.** I am using Unbound DNS as a recursive DNS provider.

1. Go to 'Services: DHCPv4: (Insert your Interface)'
2. Scroll down to 'DNS Servers'
3. Remove any assigned DNS Servers. *This will need to be done to any DHCP range issued IPs being used for testing as well as any Statically DHCP Server Assigned IP Address
4. Save Changes
5. Apply Changes
6. In Windows -- Open Command Prompt, Perform a ipconfig /release & ipconfig /renew. The DHCP Server will issue IPv6 DNS instead of the Interface IPv4 IP Address. Attempt to browse to any website that is not cached, or in host file, and the page will not load with a "Server Not Found" error.

**Expected behavior**

If the DNS servers fields are left empty to have the DHCP Server issue the interface IPv4 ip address as the DNS server

**Describe alternatives you considered**

Manually entering in a DNS provider IP on all manually configured IP Addresses, presently will need to update 300+ IPs.

**Screenshots**

![WiFi-Interface-Config](https://user-images.githubusercontent.com/75391794/184050365-3f73c8b6-fc3b-4e9f-9271-4fffe0a3b13d.PNG)
![DHCP-IPv4-Service](https://user-images.githubusercontent.com/75391794/184050369-cdd185d6-c9a8-4b13-8a77-e8f4c8ce401c.jpg)
![ipconfig](https://user-images.githubusercontent.com/75391794/184050370-957b4d51-dbda-4399-b7f1-94ae5ace3ac6.PNG)
![OPNSense-version](https://user-images.githubusercontent.com/75391794/184050371-9a9a1308-3f32-4716-b21f-4ba12d3e94b0.PNG)

**Relevant log files**

If applicable, information from log files supporting your claim.

**Additional context**

**Environment**

Software version used and hardware type if relevant, e.g.:

OS Version:
OPNsense 22.7.1-amd64
FreeBSD 13.1-RELEASE
OpenSSL 1.1.1q 5 Jul 2022

Hardware:
AMD GX-412TC SOC (4 cores, 4 threads)
pcengine.ch APU4 Board

package info:
dnsmasq  version: 2.86_4,1
isc-dhcp44-server  version: 4.4.2P1_1

**Comment by fichtner** [comment] 2022-08-11 06:46
@heyhewmike looks to be a consequence of 9c6e5f0cfbc8. Can you try to revert and confirm?

    # opnsense-patch 9c6e5f0cfbc8

**Comment by fichtner** [comment] 2022-08-11 06:59
Also then we need to confirm if this is just a zone taint from 85373c7 or if there is a deeper issue. Let's start with verifying that the interface IP is added properly:

    # grep domain-name-servers /var/dhcpd/etc/dhcpd.conf 

That should be the case with and without the previous patch revert on 22.7.1.

**Comment by heyhewmike** [comment] 2022-08-11 13:45
Here is the output of dhcpd.conf along with screenshots.
I did attempt to replicate and can not. I had done a reboot just prior to this original dhcp dns issue. I forgot about the below Unbound service crash due to the scramble I had going on due to the failure of the internet.

Attempt to apply Unbound Blocklist. It failed and crashed Unbound Service.
Unable to restart Unbound.
Rebooted
Unbound service was started upon boot

DHCP issue arose.

[dhcpd.conf-post-downgrade.txt](https://github.com/opnsense/core/files/9309073/dhcpd.conf-post-downgrade.txt)
[dhcpd.conf-pre-downgrade.txt](https://github.com/opnsense/core/files/9309074/dhcpd.conf-pre-downgrade.txt)
![downgrade](https://user-images.githubusercontent.com/75391794/184145850-9562cf47-1b65-4acc-aba0-55e7ace15364.png)

**Comment by fichtner** [comment] 2023-01-23 11:46
@heyhewmike sorry I lost track of our previous agenda :( does this bug still occur? do we want to pick up on the capture debugging? I'm moving this to 23.7 for now.

**Comment by heyhewmike** [comment] 2023-01-25 01:35
Hi @fichtner Oddly enough I did try a few days before your comment. I was unable to get a Public IP. I did not take a packet capture this time.
As a refresher here is a link to my repo that has previous packet captures showing the issues which you are a collaborator on, I can add anyone to the repo or make it public if you don't think it would pose any risks to me to do so.
https://github.com/heyhewmike/packetcaptures

**Comment by dmuensterer** [comment] 2023-07-08 15:01
I can confirm, the issue still exists on OPNSense 23.1

**Comment by fichtner** [comment] 2023-07-18 15:01
@dmuensterer can you be any more precise please. This is not still open because of the initial report.

@heyhewmike I went through the captures I could open (plain pcap) and couldn't find a coherent DHCP request sequence. Different VLANs and priority set was further complicating this as the mismatch might be simpler than expected (VLAN priority 7 was used). But in any case I'd look at the rest if you let me know about the password on the zips.


Cheers,
Franco

**Comment by fichtner** [comment] 2023-09-20 11:47
I can't find any such issue as described in the initial report. One loophole has been closed in 23.1 already. Closing.

**Closed by fichtner** 2023-09-20 11:47 UTC
Labels: cleanup
