### ISSUE TITLE
Static DHCPv6 Mapping for dynamic interface reporting wrong on DNS

### ISSUE THREAD

**Issue by user-0209** [opnsense/core#4712] opened 2021-02-17 12:29 UTC
- [x ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x ] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**
The DHCP6 service is running on a tracking interface. Every now and then the IP provider would assign a new prefix (f.i. 2a02:xxxx:xxxx:xx00/56). Tracking is working (local interface prefix might be 2a02:xxxx:xxxx:xx94/64). Still, I need to assign some static mappings on that interface. The in-page help states, that in that case the IP address can be specified by just giving the static part, i.e. omitting the prefix (f.i. ::40). Btw.: if I'm not mistaken, DHCPv6 is missing from the online documentation.

Indeed, the host will get the IP address assigned (f.i. 2a02:xxxx:xxxx:xx94::40). However, when looking up the hostname, DNS would return the IP6 address exactly as entered into OpnSense (f.i. ::40). The host cannot be looked up and addressed like that, since the prefix is missing on the reported IP address.

**To Reproduce**
On a tracking interface:
1. navigate to Services | DHCPv6 [<ifcname>]
2. for some host add a static mapping
3. specify the hosts IP address in the form ::zzzz, where zzzz should not be in the DHCP server's pool
4. verify that the host is picking up the address after some time (you might want to reduce lease times to few minutes just for the test)
5. nslookup hostname, the returned IP6 address will be just '::zzzz'

**Expected behavior**
The DNS lookup should return a valid IP6 address, i.e. the combination of the interface's prefix + the static mapping address.

**Describe alternatives you considered**
With current behaviour there is no other choice that specifying a complete IP6 address in the static mapping. When the provider assigns a new prefix, the static mappings must be updated manually.

**Screenshots**
-/-

**Relevant log files**
-/-

**Additional context**
Dual stack connection.
See also: https://forum.opnsense.org/index.php?topic=14356.msg66214#msg66214

**Environment**
OPNsense 21.1.1-amd64, but I'm facing this problem since I'm using IP6 (about 4 years).

**Comment by maurice-w** [comment] 2021-02-18 16:18
Duplicate of #4642, which is a duplicate of #3657.

**Comment by marjohn56** [comment] 2021-02-18 17:00
I'll take a look at this over the weekend, see what I can do... break.. screw up.

**Comment by fichtner** [comment] 2021-02-22 11:06
Going close in favour of #4642... PR still applies

**Closed by fichtner** 2021-02-22 11:06 UTC
