### ISSUE TITLE
Bug: widgets do not get removed from dashboard when they are deleted

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/core#611] opened 2016-01-07 12:38 UTC

**Comment by fraenki** [comment] 2016-01-07 13:27
Just tried this myself and the widget was removed permanently. Did you click the `Save settings` button (upper right corner) after removing the widget?

**Comment by fabianfrz** [comment] 2016-01-07 14:50
no it is about removing them from the file system

**Comment by fichtner** [comment] 2016-01-07 14:52
It would be good to know which widget, which version and which browser, I can't reproduce.

**Comment by fabianfrz** [comment] 2016-01-07 15:07
i had this with the captive portal widget. It keeps on the dashboard when the files are deleted (the title bar keeps there). It also happened with a widget I wrote.

I think this happens because the config.xml is not updated in such cases.

**Comment by fabianfrz** [comment] 2016-01-07 15:10
as a result this will be a problem if plugins provide widgets and they will be uninstalled (the heading from the widget keeps there)

**Comment by fichtner** [comment] 2016-01-07 15:12
So it lacks a check whether the widget file is still there. For now, widgets are not pluggable so it works as intended. The structure needs cleanups, I'm marking this a feature ticket for 16.7.

**Comment by fichtner** [comment] 2016-01-07 15:13
Actually, a hotfix for the captive portal issue for 16.1 would be reasonable.

**Comment by fichtner** [comment] 2016-01-08 13:58
Should be fixed and won't need any follow ups.

**Closed** 2016-01-08 13:57 UTC
Labels: enhancement, help wanted
