### ISSUE TITLE
21.7.1: Unbound fails to start up automatically / from GUI

### ISSUE THREAD

**Issue by asche77** [opnsense/core#5150] opened 2021-08-08 12:50 UTC
As per https://forum.opnsense.org/index.php?topic=24264.0:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Description**

Unbound fails to start up (and stay running) when booting OPNsense - it seems to start initially and then fails/stops.
Unbound fails to start up when pressing "start" in the OPNsense GUI.

Background: 
- On 21.1, I used Adguard Home  as DNS server on port 53 and Unbound on Port 5553 for local resolves. Setup worked fine.
- On a fresh install + import config of 21.7, Unbound shows the above behaviour, i.e. it fails to keep running (Adguard does start and keep running).
- **upd**: Manually running "unbound -c /var/unbound/unbound.conf" works and unbound is operative thereafter (until reboot).

**To Reproduce**

1. Use Adguard Home on port 53 and unbound on port 5553.
2. Boot OPNsense.
3. Unbound enters failed state.

**Expected behavior**

Unbound to start, bind to port 5553 and keep running.

**Describe alternatives you considered**

Reboots did not change anything.

**Relevant log files**

`2021-08-08T13:28:07	unbound[2474]	daemonize unbound dhcpd watcher.	`
`2021-08-08T13:28:05	unbound[2663]	daemonize unbound dhcpd watcher.	`
`2021-08-08T13:28:00	unbound[38473]	daemonize unbound dhcpd watcher.	`
`2021-08-08T13:27:52	unbound[60119]	daemonize unbound dhcpd watcher.	`
`2021-08-08T13:27:52	unbound[25826]	[25826:0] info: mesh has 0 recursion states (0 with reply, 0 detached), 0 waiting replies, 0 recursion replies sent, 0 replies dropped, 0 states jostled out	`
`2021-08-08T13:27:52	unbound[25826]	[25826:0] info: server stats for thread 3: requestlist max 0 avg 0 exceeded 0 jostled 0	`
`2021-08-08T13:27:52	unbound[25826]	[25826:0] info: server stats for thread 3: 0 queries, 0 answers from cache, 0 recursions, 0 prefetch, 0 rejected by ip ratelimiting	`
`2021-08-08T13:27:52	unbound[25826]	[25826:0] info: mesh has 0 recursion states (0 with reply, 0 detached), 0 waiting replies, 0 recursion replies sent, 0 replies dropped, 0 states jostled out	`
`2021-08-08T13:27:52	unbound[25826]	[25826:0] info: server stats for thread 2: requestlist max 0 avg 0 exceeded 0 jostled 0	`
`2021-08-08T13:27:52	unbound[25826]	[25826:0] info: server stats for thread 2: 0 queries, 0 answers from cache, 0 recursions, 0 prefetch, 0 rejected by ip ratelimiting	`
`2021-08-08T13:27:52	unbound[25826]	[25826:0] info: mesh has 0 recursion states (0 with reply, 0 detached), 0 waiting replies, 0 recursion replies sent, 0 replies dropped, 0 states jostled out	`
`2021-08-08T13:27:52	unbound[25826]	[25826:0] info: server stats for thread 1: requestlist max 0 avg 0 exceeded 0 jostled 0	`
`2021-08-08T13:27:52	unbound[25826]	[25826:0] info: server stats for thread 1: 0 queries, 0 answers from cache, 0 recursions, 0 prefetch, 0 rejected by ip ratelimiting	`
`2021-08-08T13:27:52	unbound[25826]	[25826:0] info: mesh has 0 recursion states (0 with reply, 0 detached), 0 waiting replies, 0 recursion replies sent, 0 replies dropped, 0 states jostled out	`
`2021-08-08T13:27:52	unbound[25826]	[25826:0] info: server stats for thread 0: requestlist max 0 avg 0 exceeded 0 jostled 0	`
`2021-08-08T13:27:52	unbound[25826]	[25826:0] info: server stats for thread 0: 0 queries, 0 answers from cache, 0 recursions, 0 prefetch, 0 rejected by ip ratelimiting`
`2021-08-08T13:27:51	unbound[25826]	[25826:0] info: service stopped (unbound 1.13.1).	`
`2021-08-08T13:27:51	unbound[25826]	[25826:0] info: control cmd: dump_cache`
`2021-08-08T13:27:45	unbound[25826]	[25826:0] info: start of service (unbound 1.13.1).	`
`2021-08-08T13:27:45	unbound[25826]	[25826:0] notice: init module 2: iterator	`
`2021-08-08T13:27:45	unbound[25826]	[25826:0] notice: init module 1: validator	`
`2021-08-08T13:27:45	unbound[25826]	[25826:0] notice: init module 0: dns64	`
`2021-08-08T13:27:39	unbound[25826]	[25826:0] notice: Restart of unbound 1.13.1.	`
`2021-08-08T13:27:39	unbound[25826]	[25826:0] info: mesh has 0 recursion states (0 with reply, 0 detached), 0 waiting replies, 0 recursion replies sent, 0 replies dropped, 0 states jostled out	`
`2021-08-08T13:27:39	unbound[25826]	[25826:0] info: server stats for thread 3: requestlist max 0 avg 0 exceeded 0 jostled 0	`
`2021-08-08T13:27:39	unbound[25826]	[25826:0] info: server stats for thread 3: 0 queries, 0 answers from cache, 0 recursions, 0 prefetch, 0 rejected by ip ratelimiting	`
`2021-08-08T13:27:39	unbound[25826]	[25826:0] info: mesh has 0 recursion states (0 with reply, 0 detached), 0 waiting replies, 0 recursion replies sent, 0 replies dropped, 0 states jostled out	`
`2021-08-08T13:27:39	unbound[25826]	[25826:0] info: server stats for thread 2: requestlist max 0 avg 0 exceeded 0 jostled 0	`
`2021-08-08T13:27:39	unbound[25826]	[25826:0] info: server stats for thread 2: 0 queries, 0 answers from cache, 0 recursions, 0 prefetch, 0 rejected by ip ratelimiting	`
`2021-08-08T13:27:39	unbound[25826]	[25826:0] info: mesh has 0 recursion states (0 with reply, 0 detached), 0 waiting replies, 0 recursion replies sent, 0 replies dropped, 0 states jostled out	`
`2021-08-08T13:27:39	unbound[25826]	[25826:0] info: server stats for thread 1: requestlist max 0 avg 0 exceeded 0 jostled 0	`
`2021-08-08T13:27:39	unbound[25826]	[25826:0] info: server stats for thread 1: 0 queries, 0 answers from cache, 0 recursions, 0 prefetch, 0 rejected by ip ratelimiting	`
`2021-08-08T13:27:39	unbound[25826]	[25826:0] info: mesh has 0 recursion states (0 with reply, 0 detached), 0 waiting replies, 0 recursion replies sent, 0 replies dropped, 0 states jostled out	`
`2021-08-08T13:27:39	unbound[25826]	[25826:0] info: server stats for thread 0: requestlist max 0 avg 0 exceeded 0 jostled 0	`
`2021-08-08T13:27:39	unbound[25826]	[25826:0] info: server stats for thread 0: 0 queries, 0 answers from cache, 0 recursions, 0 prefetch, 0 rejected by ip ratelimiting	`
`2021-08-08T13:27:38	unbound[25826]	[25826:0] info: service stopped (unbound 1.13.1).	`
`2021-08-08T13:27:38	unbound[25826]	[25826:0] info: start of service (unbound 1.13.1).	`
`2021-08-08T13:27:38	unbound[25826]	[25826:0] notice: init module 2: iterator`
`2021-08-08T13:27:38	unbound[25826]	[25826:0] notice: init module 1: validator	`
`2021-08-08T13:27:38	unbound[25826]	[25826:0] notice: init module 0: dns64	`
`2021-08-08T13:27:31	unbound[66648]	daemonize unbound dhcpd watcher.	`
`2021-08-08T13:27:31	unbound[2967]	[2967:0] info: mesh has 0 recursion states (0 with reply, 0 detached), 0 waiting replies, 0 recursion replies sent, 0 replies dropped, 0 states jostled out	`
`2021-08-08T13:27:31	unbound[2967]	[2967:0] info: server stats for thread 3: requestlist max 0 avg 0 exceeded 0 jostled 0	`
`2021-08-08T13:27:31	unbound[2967]	[2967:0] info: server stats for thread 3: 0 queries, 0 answers from cache, 0 recursions, 0 prefetch, 0 rejected by ip ratelimiting	`
`2021-08-08T13:27:31	unbound[2967]	[2967:0] info: mesh has 0 recursion states (0 with reply, 0 detached), 0 waiting replies, 0 recursion replies sent, 0 replies dropped, 0 states jostled out	`
`2021-08-08T13:27:31	unbound[2967]	[2967:0] info: server stats for thread 2: requestlist max 0 avg 0 exceeded 0 jostled 0	`
`2021-08-08T13:27:31	unbound[2967]	[2967:0] info: server stats for thread 2: 0 queries, 0 answers from cache, 0 recursions, 0 prefetch, 0 rejected by ip ratelimiting	`
`2021-08-08T13:27:31	unbound[2967]	[2967:0] info: mesh has 0 recursion states (0 with reply, 0 detached), 0 waiting replies, 0 recursion replies sent, 0 replies dropped, 0 states jostled out	`
`2021-08-08T13:27:31	unbound[2967]	[2967:0] info: server stats for thread 1: requestlist max 0 avg 0 exceeded 0 jostled 0	`
`2021-08-08T13:27:31	unbound[2967]	[2967:0] info: server stats for thread 1: 0 queries, 0 answers from cache, 0 recursions, 0 prefetch, 0 rejected by ip ratelimiting	`
`2021-08-08T13:27:31	unbound[2967]	[2967:0] info: mesh has 0 recursion states (0 with reply, 0 detached), 0 waiting replies, 0 recursion replies sent, 0 replies dropped, 0 states jostled out	`
`2021-08-08T13:27:31	unbound[2967]	[2967:0] info: server stats for thread 0: requestlist max 0 avg 0 exceeded 0 jostled 0	`
`2021-08-08T13:27:31	unbound[2967]	[2967:0] info: server stats for thread 0: 0 queries, 0 answers from cache, 0 recursions, 0 prefetch, 0 rejected by ip ratelimiting	`
`2021-08-08T13:27:31	unbound[2967]	[2967:0] info: service stopped (unbound 1.13.1).	`
`2021-08-08T13:27:31	unbound[2967]	[2967:0] info: control cmd: dump_cache	`
`2021-08-08T13:27:19	unbound[2967]	[2967:0] info: control cmd: list_local_data	`
`2021-08-08T13:27:19	unbound[2967]	[2967:0] info: start of service (unbound 1.13.1).	`
`2021-08-08T13:27:19	unbound[2967]	[2967:0] notice: init module 2: iterator`
`2021-08-08T13:27:19	unbound[2967]	[2967:0] notice: init module 1: validator	`
`2021-08-08T13:27:19	unbound[2967]	[2967:0] notice: init module 0: dns64	`
`2021-08-08T13:27:12	unbound[87717]	daemonize unbound dhcpd watcher.`
`[*** REBOOT ***]`

**Additional context**

Pressing "start" button in the GUI will only generate the following log entry (nothing more!), but not start unbound up:
`2021-08-08T13:28:07	unbound[2474]	daemonize unbound dhcpd watcher.	`

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 21.7.1-amd64
FreeBSD 12.1-RELEASE-p19-HBSD
OpenSSL 1.1.1k 25 Mar 2021

**Comment by kulikov-a** [comment] 2021-08-08 17:29
hi
can confirm unstableu unbound behavior on OPN restart
(in my test VM unbound is "active" but does not serve requests and does not respond to unbound-control commands)
unbound-control can stop working (the connection starts, but there is not even a tls handshake) right after unbound start and executing a couple of unbound-control commands (list_local_data and load_cache).
need to kill -KILL process and start again
@asche77 can you try with "Flush DNS cache during reload" in SERVICES: UNBOUND DNS: GENERAL?

**Comment by kulikov-a** [comment] 2021-08-08 17:36
**upd**: sorry,  "Flush DNS cache during reload" did not help - on the third reboot the unbound "hangs" again
will dig some more

**Comment by asche77** [comment] 2021-08-08 18:15
Just to add/clarify that manually running "unbound -c /var/unbound/unbound.conf" does start Unbound up (have edited original post). Until the next reboot of course ...

**Comment by kulikov-a** [comment] 2021-08-08 18:43
@asche77  not sure that issues related but have you configure DoT on unbound?

**Comment by asche77** [comment] 2021-08-08 19:28
Hi @kulikov-a, no, no DoT:

`<unbound>`
`    <enable>1</enable>`
 `   <dnssecstripped>1</dnssecstripped>`
  `  <domainoverrides/>`
   ` <custom_options/>`
`    <regdhcp>1</regdhcp>`
 `   <regdhcpstatic>1</regdhcpstatic>`
  `  <txtsupport>1</txtsupport>`
`    <hideidentity>1</hideidentity>`
 `   <hideversion>1</hideversion>`
  `  <prefetch>1</prefetch>`
`    <prefetchkey>1</prefetchkey>`
 `   <cache_max_ttl>28800</cache_max_ttl>`
  `  <cache_min_ttl>600</cache_min_ttl>`
   ` <incoming_num_tcp>10</incoming_num_tcp>`
`    <infra_cache_numhosts>10000</infra_cache_numhosts>`
 `   <infra_host_ttl>900</infra_host_ttl>`
  `  <jostle_timeout>200</jostle_timeout>`
   ` <log_verbosity>2</log_verbosity>`
    `<msgcachesize>4</msgcachesize>`
`    <num_queries_per_thread>4096</num_queries_per_thread>`
 `   <outgoing_num_tcp>10</outgoing_num_tcp>`
  `  <unwanted_reply_threshold/>`
   ` <dnssec>1</dnssec>`
    `<port>5553</port>`
`<hosts>`
`[...]`
`</hosts>`
`    <dns64>1</dns64>`
`    <extended_statistics>1</extended_statistics>`
`    <acls>`
`[...]`
`    </acls>`
`    <qnameminstrict>1</qnameminstrict>`
`    <active_interface>lan,opt1,opt2,opt4,opt3</active_interface>`
`    <cacheflush>1</cacheflush>`
`  </unbound>`

**Comment by cookiemonsteruk** [comment] 2021-08-08 21:14
Is it worth getting the logging up from 2?

**Comment by fichtner** [comment] 2021-08-09 05:53
So unbound is not starting or stops shortly after boot? Have you checked dmesg to see if it crashed?


Cheers,
Franco

**Comment by kulikov-a** [comment] 2021-08-09 20:04
@cookiemonsteruk 

> Is it worth getting the logging up from 2?

I think so.  and may be general log shows some?

and and I apologize to everyone. the problem on my test vm is not related to this one: it seems that the use of the quad9 (9.9.9.9) dot-forwarder led to unstable work of the unbound (still need to check. has something to do with tcp reuse?) on reboot

**Comment by fichtner** [comment] 2021-08-10 06:31
I followed up on the lead that this might be caused by `<dns64>1</dns64>` but that is not the case. I tried squeezing in `<active_interface>lan</active_interface>` but that also doesn't help reproduce.

I'm pretty sure this is some kind of configuration overlap, but someone with the issue needs to please post the actual steps to reproduce this before we can jump into the fixing.


Cheers,
Franco

**Comment by asche77** [comment] 2021-08-10 20:23
> So unbound is not starting or stops shortly after boot? Have you checked dmesg to see if it crashed?
dmesg does not show errors other than "module_register_init: MOD_LOAD (vesa, 0xffffffff812907f0, 0) error 19".

Attaching my dmesg.txt.

[dmesg.txt](https://github.com/opnsense/core/files/6964329/dmesg.txt)

Since it's my home gateway, I am constrained by family re: rebooting at will ...

**Comment by asche77** [comment] 2021-08-10 20:37
> I think so. and may be general log shows some?
[system.log](https://github.com/opnsense/core/files/6964431/system.log)
My system log attached. I tried to anonymise my domain+WiFi name and IP.

**Comment by fichtner** [comment] 2021-08-11 05:09
Not seeing anything out of the ordinary except maybe:

Aug  8 17:51:25 OPNsense opnsense[62675]: /services_unbound.php: Warning! dhcpd_radvd_configure(auto) found no suitable IPv6 address on igb1 

Do you have working IPv6? If not try to disable it on WAN and LAN interfaces..


Cheers,
Franco

**Comment by asche77** [comment] 2021-08-11 08:20
Don't think IPv6 is the problem:
IPv6 "None" on WAN and "track interface" on LAN (have now changed to "none"). 
Firewall setting "Allow IPv6" unchecked.

**Comment by fichtner** [comment] 2021-08-11 08:26
Just trying to make sure...

**Comment by asche77** [comment] 2021-08-11 18:37
Have now rebooted. 

Unbound came up fine ...

(I disabled DNS64 and IPv6 on LAN)

Will post logs later tonight.

**Comment by asche77** [comment] 2021-08-12 16:25
@bedub1 - thanks for reporting in; your issues sound like those I had seen. 

However, I do also use blocklists in unbound and unbound came up fine on reboot yesterday. Things I changed from last reboot:
- enable cacheflush
- disable DNS64
- disable IPv6 by setting "LAN" to "IPv6: none"

Could you check/try if those settings rectify your issue?

**Comment by bedub1** [comment] 2021-08-12 17:26
IPv6 was already disabled for a long time.  I enabled the CacheFlushing, and it rebooted properly.  When I have more time I'll reboot several times, with the CacheFlushing enabled/disabled and see if it's 100% repro.

**Comment by bedub1** [comment] 2021-08-13 17:38
Okay I did 7 reboots.  Enabling DNS Caching Flushing seems to fix the problem, but seems to cause other problems.  

Flush Cache Enabled (Box Checked)
1st reboot - unbound starts, openvpn client shows offline
2nd reboot - unbound starts, openvpn client connects, ntp doesn't start
3rd reboot - unbound starts, openvpn client shows offline

Flush Cache Disabled (Box Unchecked)
0 - disable Flush Cache
1st reboot - Unbound fails to start, openvpn client connects, ntp starts
2nd reboot - Unbound fails to start, openvpn client connects, ntp starts
2nd reboot - Unbound starts, openvpn client connects, ntp starts

0 - Enable Flush Cache
1st reboot - unbound starts, openvpn client shows offline

**Comment by kulikov-a** [comment] 2021-08-13 19:46
@bedub1 @asche77 unbound logs (verb 4 or higher) would be very helpful in trying to understand what's going on when unbound fails to start

**Comment by bedub1** [comment] 2021-08-14 16:14
> 
> 
> @bedub1 @asche77 unbound logs (verb 4 or higher) would be very helpful in trying to understand what's going on when unbound fails to start

Do I need to scrub the logs before attaching?  I looked through it, and the only personal information I see is my LAN IP Address.

**Comment by kulikov-a** [comment] 2021-08-14 17:10
it's up to you imho )

**Comment by asche77** [comment] 2021-08-14 19:30
Logs: I had my top level domain in there, as well as my public IP. I removed both.

**Comment by asche77** [comment] 2021-08-15 09:11
Reboot: I have just rebooted and unbound has come up fine.

Going to try re-enabling my prior settings (cumulatively):

Turning DNS64 back on: unbound eats a lot of cpu initially but comes up fine.

Turning IPv6 on LAN back on (track interface): unbound comes up fine. Unlike before, DHCPv6 server does not show up in services dashboard (before, it did with failed state).

Turning cacheflush back off:  TA-DAH! Unbound fails. Logs attached.

Turning DNS64 and IPv6 track interface back off but leaving cacheflush disabled: TA-DAH! Unbound fails. Logs attached.

Turning cacheflush back on: unbound starting up fine.

**Comment by fichtner** [comment] 2021-08-15 09:30
Can you run the following after a reboot when it doesn't start:

# sh -x /usr/local/opnsense/scripts/unbound/start.sh 

And this is 100% 27.1.1 and not 27.1?

**Comment by asche77** [comment] 2021-08-15 09:35
This is:

<html><body>


Versions | OPNsense 21.7.1-amd64FreeBSD 12.1-RELEASE-p19-HBSDOpenSSL 1.1.1k  25 Mar 2021
-- | --



</body>
</html>

**Comment by asche77** [comment] 2021-08-15 09:40
root@OPNsense:~ # sh -x /usr/local/opnsense/scripts/unbound/start.sh
+ set -e
+ chroot -u unbound -g unbound / /usr/local/sbin/unbound-anchor -a /var/unbound/                                                                              root.key
+ [ ! -f /var/unbound/unbound_control.key ]
+ find /var/unbound/etc -depth 1
+ rm -rf /var/unbound/etc/dot.conf
+ rm -rf /var/unbound/etc/dnsbl.conf
+ rm -rf /var/unbound/etc/miscellaneous.conf
+ find /usr/local/etc/unbound.opnsense.d -depth 1 -name '*.conf'
+ cp /usr/local/etc/unbound.opnsense.d/dot.conf /var/unbound/etc/
+ cp /usr/local/etc/unbound.opnsense.d/miscellaneous.conf /var/unbound/etc/
+ cp /usr/local/etc/unbound.opnsense.d/dnsbl.conf /var/unbound/etc/
+ chown -R unbound:unbound /var/unbound
+ /usr/local/sbin/unbound -c /var/unbound/unbound.conf
+ /usr/local/opnsense/scripts/unbound/cache.sh load
ok
root@OPNsense:~ #

**Comment by fichtner** [comment] 2021-08-15 09:43
It's funny because that's the script it's supposed to run in the first place.

**Comment by asche77** [comment] 2021-08-15 09:45
It's probably the same behaviour as on boot: it runs briefly and then stops/crashes after a few secs.

**Comment by asche77** [comment] 2021-08-15 09:50
reboot with cacheflush = OFF, unbound enters failed state shortly after boot, running manual startup:

`root@OPNsense:/var/log # sh -x /usr/local/opnsense/scripts/unbound/start.sh       `                                                                     + set -e`
`+ chroot -u unbound -g unbound / /usr/local/sbin/unbound-anchor -a /var/unbound/root.key`
`+ [ ! -f /var/unbound/unbound_control.key ]`
`+ find /var/unbound/etc -depth 1`
`+ rm -rf /var/unbound/etc/dot.conf`
`+ rm -rf /var/unbound/etc/dnsbl.conf`
`+ rm -rf /var/unbound/etc/miscellaneous.conf`
`+ find /usr/local/etc/unbound.opnsense.d -depth 1 -name '*.conf'`
`+ cp /usr/local/etc/unbound.opnsense.d/dot.conf /var/unbound/etc/`
`+ cp /usr/local/etc/unbound.opnsense.d/miscellaneous.conf /var/unbound/etc/`
`+ cp /usr/local/etc/unbound.opnsense.d/dnsbl.conf /var/unbound/etc/`
`+ chown -R unbound:unbound /var/unbound`
`+ /usr/local/sbin/unbound -c /var/unbound/unbound.conf`
`[1629020885] unbound[43905:0] debug: creating udp4 socket 192.168.1.1 5553`
`[1629020885] unbound[43905:0] debug: creating tcp4 socket 192.168.1.1 5553`
`[629020885] unbound[43905:0] debug: creating udp4 socket 192.168.200.1 5553`
`[1629020885] unbound[43905:0] debug: creating tcp4 socket 192.168.200.1 5553`
`[1629020885] unbound[43905:0] debug: creating udp4 socket 127.0.0.1 5553`
`[1629020885] unbound[43905:0] debug: creating tcp4 socket 127.0.0.1 5553`
`[1629020885] unbound[43905:0] debug: creating udp4 socket 192.168.1.1 5553`
`[1629020885] unbound[43905:0] debug: creating tcp4 socket 192.168.1.1 5553`
`[1629020885] unbound[43905:0] debug: creating udp4 socket 192.168.200.1 5553`
`[1629020885] unbound[43905:0] debug: creating tcp4 socket 192.168.200.1 5553`
`[1629020885] unbound[43905:0] debug: creating udp4 socket 127.0.0.1 5553`
`[1629020885] unbound[43905:0] debug: creating tcp4 socket 127.0.0.1 5553`
`[1629020885] unbound[43905:0] debug: creating udp4 socket 192.168.1.1 5553`
`[1629020885] unbound[43905:0] debug: creating tcp4 socket 192.168.1.1 5553`
`[1629020885] unbound[43905:0] debug: creating udp4 socket 192.168.200.1 5553`
`[1629020885] unbound[43905:0] debug: creating tcp4 socket 192.168.200.1 5553`
`[1629020885] unbound[43905:0] debug: creating udp4 socket 127.0.0.1 5553`
`[1629020885] unbound[43905:0] debug: creating tcp4 socket 127.0.0.1 5553`
`[1629020885] unbound[43905:0] debug: creating udp4 socket 192.168.1.1 5553`
`[1629020885] unbound[43905:0] debug: creating tcp4 socket 192.168.1.1 5553`
`[1629020885] unbound[43905:0] debug: creating udp4 socket 192.168.200.1 5553`
`[1629020885] unbound[43905:0] debug: creating tcp4 socket 192.168.200.1 5553`
`[1629020885] unbound[43905:0] debug: creating udp4 socket 127.0.0.1 5553`
`[1629020885] unbound[43905:0] debug: creating tcp4 socket 127.0.0.1 5553`
`[1629020885] unbound[43905:0] debug: creating tcp4 socket 127.0.0.1 953`
`[1629020885] unbound[43905:0] debug: setup SSL certificates`
`[1629020885] unbound[43905:0] debug: switching log to syslog`
`+ /usr/local/opnsense/scripts/unbound/cache.sh load`
`ok`
`root@OPNsense:/var/log #`

Unbound is up

**Comment by kulikov-a** [comment] 2021-08-15 11:05
resolver.log looks quite normal. just a few commands to restart are visible (on .bootip, on newwanip etc).
there is no corresponding entries in system.log for 11:52:07 when unbound gracefully stopped

> then it enters red "failed" state
sorry, any chance that its just GUI?  unbound needs some time to start (even more with bla(o)ck-lists) and GUI may show "red stop" until page refresh

**Comment by asche77** [comment] 2021-08-15 11:25
Unfortunately, not only GUI - unbound also stops resolving (i.e. I cannot resolve local DHCP registered hosts).

**Comment by kulikov-a** [comment] 2021-08-15 14:13
sorry, completely copied your config from https://github.com/opnsense/core/issues/5150#issuecomment-894844062 (without cacheflash) and can't reproduce the behavior
any chance that there is an event in the system log explaining the unbound stop at 11:52:07?
`Aug 15 11:52:07 OPNsense unbound[51361]: [51361:0] info: service stopped (unbound 1.13.1). 
Aug 15 11:52:07 OPNsense unbound[51361]: [51361:0] debug: stop threads 
Aug 15 11:52:07 OPNsense unbound[51361]: [51361:0] debug: join 1 
Aug 15 11:52:07 OPNsense unbound[51361]: [51361:2] debug: got control cmd quit 
Aug 15 11:52:07 OPNsense unbound[51361]: [51361:3] debug: got control cmd quit 
Aug 15 11:52:07 OPNsense unbound[51361]: [51361:1] debug: got control cmd quit `

**Comment by kulikov-a** [comment] 2021-08-17 12:08
I apologize for being off-topic, but also related to unbound problems at start..
@fichtner is it possible to take https://github.com/NLnetLabs/unbound/commit/d88f554503cbb31b924087f82ecd774145506a8f into account when you will update the unbound? thnks!

**Comment by somova** [comment] 2021-08-25 08:54
It looks like the problem is that the cache-load command of unbound hangs:

`root@opnsense-host:~ # ps aux -d | grep unbound`
`-- /usr/local/bin/flock -n -E 0 -o /tmp/unbound_start.lock /usr/local/opnsense/scripts/unbound/start.sh`
`...\-- /bin/sh /usr/local/opnsense/scripts/unbound/start.sh`
`.......\-- /bin/sh /usr/local/opnsense/scripts/unbound/cache.sh load`
`...........\-- /usr/local/sbin/unbound-control -c /var/unbound/unbound.conf load_cache`

I could imagine that unbound-control connects to the remote-control port of unbound via localhost to update the cache and in the meantime the state reset function for dial-up connections kills all network connections (including loopback connections). We also see this of broken ssh connections to the console.

By the way, the script "/usr/local/opnsense/scripts/unbound/cache.sh" does not check any return codes of executed commands. This is not a good idea.

**Comment by asche77** [comment] 2021-09-09 08:25
Good news: on 21.7.2 even with cache flush disabled, unbound came up fine.

So can't really add anything to this issue right now.

**Comment by somova** [comment] 2021-09-09 14:20
> Good news: on 21.7.2 even with cache flush disabled, unbound came up fine.

Unfortunately, this issue is not solved. The start of _unbound_ still hung after first boot of Opnsense version 21.7.2.

**Comment by fichtner** [comment] 2021-09-21 12:36
> By the way, the script "/usr/local/opnsense/scripts/unbound/cache.sh" does not check any return codes of executed commands. This is not a good idea.

Politically correct would be to say that if unbound-control fails to dump its cache and then fails to load its dump that is a pretty unusable situation for any caller.

We still need to know why it dumps partial or invalid data or how we could possibly verify that data... ideally hoping the process that knows the data could tell us. ;)

Last but not least cache.sh sets "set -e" which aborts on errors throws by unbound-control, so I guess it doesn't... so we can't check for errors? It's a good suggestion to check for errors, but it's not very well grounded in reality.


Cheers,
Franco

**Comment by glasid** [comment] 2021-10-05 20:29
Based on somova's assumption that the issue might be related to state reset, I ran a few tests.

**Restart of OPNsense _with_ WAN being connected:**
unbound hangs on cache-load command

**Restart of OPNsense _without_ WAN being connected:**
unbound properly starts up

**Reconnecting WAN:**
state reset kicks in, unbound restarts and hangs on cache-load command
 
 
Now disabling "Dynamic state reset" under Firewall -> Settings -> Advanced...

**Restart of OPNsense _with_ WAN being connected:**
unbound properly starts up

So, it could well be that somova is right in his assumption.

**Comment by somova** [comment] 2021-11-22 17:57
Maybe we can link this issue to #5367, because it looks like issues with the dynamic state reset function interfere with the start of unbound.

**Comment by evulhotdog** [comment] 2022-01-07 22:32
I experience this issue and have never had Dynamic state reset enabled, and my Unbound fails to start on boot.

**Comment by fichtner** [comment] 2022-01-08 10:26
@evulhotdog so not your bug, maybe you should take a look at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md


Thanks,
Franco

**Comment by fichtner** [comment] 2022-02-02 08:35
Going to close this via  #5367

**Closed by fichtner** 2022-02-02 08:35 UTC
Labels: support
