### ISSUE TITLE
When adding a DHCP static reservation in Kia the DNS service needs restarting/reloading

### ISSUE THREAD

**Issue by simonmcnair** [opnsense/core#7937] opened 2024-10-02 11:18 UTC
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ yes] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [yes ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**
When I added a DHCP reservation I found I couldn't ping the client.  It appears as if a reload/restart of unbound dns was required.

**To Reproduce**

1.) add dhcp reservation in Kia
2.) try to ping host via DNS
3.) host times out

**Expected behavior**

1.) add dhcp reservation in Kia
2.) try to ping host via DNS
3.) host responds

**Describe alternatives you considered**

A clear and concise description of any alternative solutions or workaround you considered.

**Screenshots**

**Relevant log files**

If applicable, information from log files supporting your claim.

**Additional context**

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.7.8 (amd64).
Intel® Xeon™ E3-1225V5 3.3Ghz Quad Core
Network Intel® I210-AT

**Comment by fichtner** [comment] 2024-10-02 11:32
Working as discussed/intended.

**Comment by simonmcnair** [comment] 2024-10-02 14:11
Surely if you add a lease and it doesn't work it isn't as intended ?  If you need to restart DNS, it should tell you at least ?

**Comment by fichtner** [comment] 2024-10-02 14:24
Docs PR is welcome. Behaviour for static DHCP  leases to DNS services is consistent across the software. Since the two services do not belong together no restart is forced for the other.

**Comment by simonmcnair** [comment] 2024-10-05 15:29
Lots of the other pages have notices saying 'Don't forget to restart the service'.  Can this be added please ?

**Comment by AdSchellevis** [comment] 2024-10-05 15:43
@simonmcnair will do, better for consistency indeed. Let me close this ticket while adding the message

**Closed** 2024-10-05 15:48 UTC
Labels: support

**Comment by simonmcnair** [comment] 2024-10-05 16:03
sorry, it's not that you need to apply them.  You need to restart whichever DNS service you use.

**Comment by AdSchellevis** [comment] 2024-10-05 16:06
The generic apply message is no problem to add (as it was missing), trying to explain dependancies is not something we're considering. The documentation is a better place for that, as @fichtner already mentioned, PR's are welcome.

**Comment by simonmcnair** [comment] 2024-10-05 20:06
Your response is perfectly understandable but a very poor user experience.  When you do something you expect it to take affect.  If it doesn't and you have to troubleshoot and figure stuff out when a warning or notice (without having to look at documentation) would have helped, then you should be asking yourself why.  If adding a DHCP lease reservation requires DNS to be restarted in order for name resolution to work.  Why wouldn't you tell someone ?

**Comment by fichtner** [comment] 2024-10-05 20:14
Your response isn’t great either, but it’s besides the point. Why do you expect a particular service restarting warrants restarting an auxiliary service?

**Comment by simonmcnair** [comment] 2024-10-18 10:32
From a usability perspective if you change something and hit apply, or continue you expect it to take effect.

If something additional is required to make it happen, not telling someone that it is needed is a poor experience.

I can see your point though.  In this specific case once the target has been rebooted and has its DHCP address, if configured, it'll update DNS anyway.

**Comment by fichtner** [comment] 2024-10-18 10:48
This is non-negotiable for apply doing auxiliary reloads of mildly related services. We are to this day fighting side effects stemming from this historic approach of „gluing everything together“.

**Comment by cr4ckDe** [comment] 2024-11-18 06:19
But this is new, right? I know from a fact that I didn't have to restart unbound when adding a static DHCP entry. Since the last big update I have to restart it every time now. And as @simonmcnair says, it's hard to figure out what the problem is if your dns record is in the DHCP list and not reachable -> Which has worked before in previous updates.

Would it be possible to add a checkbox in unbound with gives us the option do decide whether it restarts or not when applying dhcp entries?
