### ISSUE TITLE
states.py - problems with long running sessions

### ISSUE THREAD

**Issue by mlht** [opnsense/core#6008] opened 2022-09-06 16:26 UTC
- [x ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**
My WebGUI (Firewall:Diagnostics:Sessions) shows today "No results found!", which can't be true.
pftop changes the output format on **long running sessions** (even if you set the terminal width to 1000) for Age and Bytes at some point.

![pftop](https://user-images.githubusercontent.com/35572091/188737864-41c2d7b8-31da-4519-a7a3-283dba8be7a1.PNG)

The screenshot shows:
1. The age value changed the format from xx:xx:xx to an integer
2. The bytes value changed from bytes to kilobytes

/usr/local/opnsense/scripts/filter/lib/states.py
The first problem (age) throws an exception at line 206

           for timefield in ['age', 'expire']:
                tmp = record[timefield].split(':')
                record[timefield] = int(tmp[0]) * 3600 + int(tmp[1]) * 60 + int(tmp[2]) if len(tmp) > 2 else 0

The second problem (line 197) returns 0 if the bytes value ends with K
`record['bytes'] = int(parts[idx+4]) if parts[idx+4].isdigit() else 0`

A short test with this line returns the right value
`record['bytes'] = int(parts[idx+4][0:-1])*1024 if (parts[idx+4] == "K") else int(parts[idx+4])`

OPNsense 22.1.10 (amd64, OpenSSL).
FreeBSD 13.0-STABLE

**Comment by kulikov-a** [comment] 2022-09-09 07:48
Hi
didn't check it and it's probably not quite technically correct, but since the format of the specified fields seems to depend on the value of the `-w` argument ([you can check it in the source code](https://github.com/araujobsd/pftop/blob/ab98de9ce24f0b15da5ab677acb50db187ad1094/engine.c)), have you tried to significantly increase it in the `states.py`? (otherwise, to parse large values in these fields, it's necessary to mimic the pftop's conversion logic?)

**Comment by mlht** [comment] 2022-09-09 12:17
At line 166 is the call for pftop in states.py:
sp = subprocess.run(['/usr/local/sbin/pftop', '-w', '1000', '-b','-v', 'long','9999999999999'], capture_output=True, text=True)

-w is set to 1000

I think if age is greater then 999:59:59 it will change to seconds. 3611183s (screenshot from first post) are 1003 hours.
For bytes i saw values until 150MB or so, can't say it exactly.

**Comment by kulikov-a** [comment] 2022-09-09 13:17
I tested and agree: increasing `-w` value does not stop the conversion ​​of the age, pkts and bytes fields for long sessions. this should probably be considered in the `states.py`

**Comment by kulikov-a** [comment] 2022-09-09 14:17
@mlht can you check
opnsense-patch -a kulikov-a dfbf0e0
please for unix timestamp support?
im not sure that converting M, K to bytes in traffic counts is the best idea (it works well now imho)

**Comment by mlht** [comment] 2022-09-09 16:17
Your patch solves the "age" problem (and the exception in python) which is great!

![sess2](https://user-images.githubusercontent.com/35572091/189393161-8e413e03-d19c-42c8-9e23-c65b5a409c68.PNG)

As you can see the bytes value is empty. It took me some time to figure out that the frontend expects a byte value. The frontend then calculates the bytes back to K,M,G.... but states.py returns 0.
frontend: /usr/local/opnsense/mvc/app/views/OPNsense/Diagnostics/fw_pftop.volt

                           bytes: function(column, row) {
                                if (!isNaN(row[column.id]) && row[column.id] > 0) {
                                    let fileSizeTypes = ["", "K", "M", "G", "T", "P", "E", "Z", "Y"];
                                    let ndx = Math.floor(Math.log(row[column.id]) / Math.log(1000) );
                                    if (ndx > 0) {
                                        return  (row[column.id] / Math.pow(1000, ndx)).toFixed(2) + ' ' + fileSizeTypes[ndx];
                                    } else {
                                        return row[column.id].toFixed(2);
                                    }
                                } else {
                                    return "";
                                }

With my modification from my first post we get this output:

![sess1](https://user-images.githubusercontent.com/35572091/189394272-ed72b625-e3a0-4469-abf6-bccb95f2e886.PNG)

**Comment by kulikov-a** [comment] 2022-09-09 16:28
@mlht got it, thanks! (i just dont have this traffic values on test vm to reproduce, sorry)
in this case we also need to be ready for M and G in Bytes column from pftop ([print_fld_sdiv(field_def *fld, u_int64_t size, int div)](https://github.com/araujobsd/pftop/blob/ab98de9ce24f0b15da5ab677acb50db187ad1094/engine.c#L661))
I'll try to add this too and make a pr if @AdSchellevis not mind )

**Comment by AdSchellevis** [comment] 2022-09-12 17:55
@kulikov-a be my guest, I'll wait for your PR to review.

**Comment by AdSchellevis** [comment] 2022-09-17 18:10
closed via https://github.com/opnsense/core/pull/6020

**Closed by AdSchellevis** 2022-09-17 18:10 UTC
