### ISSUE TITLE
Error "Unexpected error, check log for details" when changing nginx settings

### ISSUE THREAD

**Issue by bugspencor** [opnsense/core#8048] opened 2024-11-09 09:18 UTC
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When saving any nginx setting (tested with upstreams, locations, stream servers) I get the error message "Unexpected error, check log for details" when saving the changes. In the browser dev tools I see an HTTP 500 error. I checked the logs, both from OPNsense and nginx, but could not find anything relevant.

Even without changing anything, the error is displayed.

Adding or deleting configs works as expected.

**To Reproduce**

1. Go to 'nginx/Configuration'
2. Edit any configuration (e.g. Location, Stream, Upstream)
3. Click save without making changes
4. See error popup: "Unexpected error, check log for details"

**Expected behavior**

1. When saving without making changes no error should be displayed.
2. More info should be found in the log file as stated by the error message

**Describe alternatives you considered**

Deleting the configuration and adding it again works without errors.

**Screenshots**

![image](https://github.com/user-attachments/assets/601636d5-f0a5-4631-9def-393436ecea89)

**Relevant log files**

no relevant log messages

**Additional context**

- several upstreams, locations, http servers are configured

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 24.7.8 (amd64) (upgraded from previous releases)
VM (Proxmox/KVM), 4G RAM, 2 CPUs

**Comment by AdSchellevis** [comment] 2024-11-09 10:14
duplicate of https://github.com/opnsense/plugins/issues/4342

**Closed by AdSchellevis** 2024-11-09 10:14 UTC
