### ISSUE TITLE
Unbound crashes when changing DHCP lease time

### ISSUE THREAD

**Issue by MrM40** [opnsense/core#3953] opened 2020-02-26 14:16 UTC
Change DHCP setting and save:
![Clipboard02](https://user-images.githubusercontent.com/16258063/75352617-4f84a880-58aa-11ea-9672-6c5495fc23de.jpg)

Crash:
![Clipboard01](https://user-images.githubusercontent.com/16258063/75352495-219f6400-58aa-11ea-9b75-63ea48cae7fd.jpg)

(by the way could you reopen [3478](https://github.com/opnsense/core/issues/3478). Parsing of new DHCP leases to either DNS Unbound or Dnsmasq has never been working correctly, and still doesn't)

**Environment**
OPNsense 19.7.9_1-amd64
FreeBSD 11.2-RELEASE-p16-HBSD
OpenSSL 1.0.2u 20 Dec 2019

**Comment by AdSchellevis** [comment] 2020-02-26 14:23
we're not going to reopen https://github.com/opnsense/core/issues/3478 without further context, it might be a duplicate of  https://github.com/opnsense/core/issues/3730

**Comment by MrM40** [comment] 2020-02-26 15:33
Nope, they are not related. As I said it's about DHCP renewed IPs are not parsed to DNS. I myself have created several cases about it here and in the forum.....let me see if I can find it.

**Comment by AdSchellevis** [comment] 2020-02-26 15:41
marking this as a support ticket, both settings don't seem to have a relation with unbound and there's  not enough context to reproduce anything else here.

**Comment by MrM40** [comment] 2020-02-26 15:42
https://github.com/opnsense/core/issues/1320
Should create a third case?

**Comment by MrM40** [comment] 2020-02-26 15:43
"not enough context to reproduce"?
Have you tried to change the values in DHCP, save, a see if unbound crashes?

**Comment by AdSchellevis** [comment] 2020-02-26 15:43
yes

**Comment by fichtner** [comment] 2020-02-26 15:45
@MrM40 I find the suggestion by unbound pretty good as there is a chance to gather more relevant info that others can't. Thanks!

**Comment by MrM40** [comment] 2020-02-26 15:46
OK, fair enough.
I'll try on another box.

**Comment by fichtner** [comment] 2020-09-06 08:20
Just tried again: can't reproduce. This is on 20.7.2.

**Closed by fichtner** 2020-09-06 08:20 UTC
Labels: support
