### ISSUE TITLE
NAT before IPsec is not functional

### ISSUE THREAD

**Issue by fraenki** [opnsense/core#440] opened 2015-10-19 10:42 UTC
### UPDATE

A limitation of the PF implementation on FreeBSD makes it impossible to apply NAT rules before sending packets through an IPsec tunnel. (I think OpenBSD fixed this limitation in their PF implementation [a while ago](http://undeadly.org/cgi?action=article&sid=20090127205841). Unfortunately, the PF implementation on FreeBSD no longer follows OpenBSD's developments, so it's unlikely that we see this being ported over to FreeBSD.)

There are two steps required to fix this issue:
1. [Patch strongSwan](https://github.com/pfsense/FreeBSD-ports/blob/3faff56ee509fbcfc167c7c6d41f810239cd4e4f/security/strongswan/files/patch-ipsec_nat.diff)
2. Revive [some old code](https://github.com/opnsense/core/blob/19265d25e285287271fc63f4bade2e2ea6af82e1/src/etc/inc/vpn.inc#L656-L666)

@ermal provided a [nice explanation](https://wiki.strongswan.org/issues/951#note-5) how these two things solve this issue. (Note that Ermal did mention "other ways of doing it", so there's likely a different/better solution possible.)

The drawbacks of this fix are obvious: The strongSwan patch will _never_ be included in any upstream release, thus it may break with any new (major) release of strongSwan. And while this solution works very well, it's just a workaround for a limitation in PF/FreeBSD. 

But, to be honest, the inability to use "NAT before IPsec" is a showstopper for me. That's why I'm currently using a custom build of strongSwan alongside a small patch to vpn.inc.
### ORIGINAL REPORT

(for reference only)

If you configure IPsec NAT, the IPsec phase 2 tunnels may become unstable. In my case all phase 2 tunnels remain disconnected:

```
Oct 19 12:09:28 opnsense charon: 15[IKE] <con1-000|1> IKE_SA con1-000[1] established between X[X]...Y[Y]
Oct 19 12:09:28 opnsense charon: 15[IKE] IKE_SA con1-000[1] established between X[X]...Y[Y]
Oct 19 12:09:28 opnsense charon: 15[IKE] <con1-000|1> scheduling reauthentication in 28101s
Oct 19 12:09:28 opnsense charon: 15[IKE] <con1-000|1> maximum IKE_SA lifetime 28641s
Oct 19 12:09:32 opnsense charon: 13[IKE] <con1-000|1> sending retransmit 1 of request message ID 951205933, seq 4
Oct 19 12:09:39 opnsense charon: 12[IKE] <con1-000|1> sending retransmit 2 of request message ID 951205933, seq 4
Oct 19 12:09:52 opnsense charon: 06[IKE] <con1-000|1> sending retransmit 3 of request message ID 951205933, seq 4
Oct 19 12:10:16 opnsense charon: 08[IKE] <con1-000|1> sending retransmit 4 of request message ID 951205933, seq 4
```

The only solution in this case is to disable all IPsec NAT entries, stop ipsec and restart it. Afterwards all phase 2 tunnels will come up immediately. Once all phase 2 tunnels are established, it is possible to enable the IPsec NAT entries again (but this is dangerous because a reconnect of the tunnel is very unlikely to succeed).

We do not have this issue with IPsec NAT disabled.

While debugging #369 with @AdSchellevis we've been wondering why entries to `ipsec.conf` are added for IPsec NAT. Is this actually required for IPsec NAT to work? It seems that this confuses the ipsec daemon.

_To be more precise:_ I do _not_ use the IPsec NAT for _masquerading_ my local networks, but instead to do actual NAT (allow my other local networks to access a remote IPsec network, even if the remote side does know nothing about these local networks). It's exactly what is described [here](https://doc.pfsense.org/index.php/NAT_with_IPsec_Phase_2_Networks) (see "Remote End Notes").

**Comment by AdSchellevis** [comment] 2015-10-19 11:12
@fraenki just checking, but if I'm not mistaken it functions normal if the nat entry is an actual tunnel, but if you want to nat some parts of your network, you can create entries over here which will never be active and may confuse strongswan sometimes, but will do the nat part, because it has nothing to do with ipsec.

The problem over here seems to be, that we can't configure these "do not NAT all my traffic tunnels" in the nat section of the firewall.

Am I right?

**Comment by fraenki** [comment] 2015-10-19 11:33
@AdSchellevis I'm not sure what you mean with _"...if the nat entry is an actual tunnel..."_.

On the other hand, yes, the problem seems to be that we're not able to create similar NAT rules elsewhere. Currently it's only possible on the IPsec phase 2 configuration page.
I've already tried to replace this "IPsec phase 2 NAT" entry with a regular "outbound NAT rule", but this didn't work. I'm not sure what magic was missing to make it work. Maybe it's related to #438?

**Comment by fraenki** [comment] 2015-10-19 11:35
Just "confirmed" this issue with a second tunnel, FWIW. Disabling the IPsec phase 2 NAT entries immediately solved the connection issue.

**Comment by AdSchellevis** [comment] 2015-10-19 11:39
That's good, and yes it's related to the other issue. You can only create NAT rules for tunnels you actually have at the moment, and there doesn't seem to be a logic reason for it.
When the rules are disabled, your situation should work (because it seems to keep the rules, https://github.com/opnsense/core/issues/439), but eventually you need to be able to create outbound nat rules for this.

**Comment by fraenki** [comment] 2015-10-19 12:22
OK, let me summarize what I've tried so far.

I have the following IPsec phase 2 tunnel configured:
- Local network:  192.168.1.0/24
- Remote network: 10.22.13.0/24

But I want to be able to reach the remote network from my second local network, 172.16.2.0/24, too. That's why I've added the following IPsec phase 2 *NAT* configuration:

- Local Network: 172.16.2.0/24
- NAT/BINAT Network: 192.168.1.0/24
- Remote Network: 10.22.13.0/24

This should allow us to access the remote network 10.22.13.0/24 from our second local network 172.16.2.0/24, because it gets NAT to 192.168.1.0/24. You see that a pf NAT rule is added:

```
binat on enc0 inet from 172.16.2.0/24 to 10.22.13.0/24 -> 192.168.1.0/24
```

And it works. But the ipsec daemons gets confused, as described earlier.

That's why I tried the following:
- disabled the IPsec phase 2 NAT configuration
- the pf BINAT rule was still there
- added a reglar outbound NAT rule

Now the pf NAT table looks like this:

```
nat on enc0 inet from 172.16.2.0/24 to 10.22.13.0/24 -> 192.168.1.0/24 port 1024:65535
binat on enc0 inet from 172.16.2.0/24 to 10.22.13.0/24 -> 192.168.1.0/24
```

Unfortunately, the connection from 172.16.2.0/24 to 10.22.13.0/24 stopped working *immediately* after disabling the IPsec phase 2 NAT configuration. 

Is there any way to configure this IPsec NAT without interferring with the ipsec daemon?

**Comment by fraenki** [comment] 2015-11-25 10:31
@AdSchellevis I've seen some ([rather](https://forum.pfsense.org/index.php?topic=49800.msg265106#msg265106) [old](https://forum.pfsense.org/index.php?topic=49800.msg266685#msg266685)) posts stating that PF can't do NAT for IPsec (at least [not on FreeBSD](http://undeadly.org/cgi?action=article&sid=20090127205841)). Is this statement still true? On the other hand some people advise to set `net.inet.ipsec.filtertunnel=1` in this regard... do you have any comments on this to share? :)

**Comment by fraenki** [comment] 2015-11-26 01:23
Setting the sysctl `net.inet.ipsec.filtertunnel` to `1` did not help to solve the NAT issue, but it would allow us to filter the traffic _inside_ the tunnel (as the name suggests).

**Comment by fichtner** [comment] 2016-01-09 08:58
@fraenki what's the status here?

**Comment by fraenki** [comment] 2016-01-11 16:24
@fichtner Currently it cannot be solved so easily. I think I should open a new RFE issue with only details on the technical limitations/issues.

**Comment by fichtner** [comment] 2016-01-11 16:39
We can update the first post if needed, just let me know how to transform the ticket (title+description). would be sad to lose the extra info in the comments.

**Comment by fraenki** [comment] 2016-01-14 18:06
@fichtner I've updated my original submission with the description of the underlying problem.

**Comment by fichtner** [comment] 2016-01-14 18:09
@fraenki thank you :)

**Comment by fraenki** [comment] 2016-02-18 10:57
FWIW, the quick fix ("patch strongSwan, revive some old code") is still working on 16.1.3.

**Comment by fraenki** [comment] 2016-09-26 10:13
more discussion on this topic: https://forum.opnsense.org/index.php?topic=3696.0

**Comment by fraenki** [comment] 2017-03-13 22:15
So it seems that the described fix no longer works on 17.1.x :(
Any idea which change might have caused this breakage?

**Comment by fichtner** [comment] 2017-03-14 06:43
enc(4) was reworked for 11.0, which is probably why this happens. pfSense has patches that may be related, but I don't want to review things that are not in FreeBSD. IPsec is complicated as is :(

**Comment by ermal** [comment] 2017-03-14 06:56
Guys not sure why i get notifications from here but can i be removed?

**Comment by fichtner** [comment] 2017-03-14 07:15
@ermal  there's an unsubscribe button at the top right next to the OP. github mentions are working more sturdily now than they used to ;)

**Comment by fichtner** [comment] 2017-03-14 07:53
@fraenki I tried forcing NATon IPsec device with local address via traffic from a different network, then added a gateway (code edits) to force the packet down the tunnel device, which seems to go through and the other end answers but the return path "hangs" when handing the payload back to the original network. this may be workable still. need to look into it more :)

**Comment by fraenki** [comment] 2017-03-14 10:32
@fichtner Thanks for taking the time to search for a solution. It's very unfortunate that this old issue now turns into a show stopper for us. :( I was OK maintaining our custom package, but non-working "NAT before IPsec" would kill many services on our side.

**Comment by ermal** [comment] 2017-03-14 15:53
@fichtner thanks for the tip i always miss that button.
While here i might give you insight into it.
With FreeBSD 10 the best way is to use the patches i made since the other way of using nat+rdr is very tricky.
With FreeBSD 11-stable you have to be smart and use if_ipsec with routing and send needed traffic to that interface, nat there as usual with any other interface.
The only complication is that you have to manager routes with it.

Have fun and hope it helps.

**Comment by mimugmail** [comment] 2017-07-15 04:28
@fraenki This really means OPN doesn't support scenarios with overlapping networks? :(

**Comment by mimugmail** [comment] 2017-07-17 20:24
@AdSchellevis I digged into this and perhaps near to a solution. I did not enable any binat or something like that. My test setup is

LAN 10.26.2.0 - ROUTER - LAN 10.26.1.0 - OPNSENSE --- VPN --- SOPHOS - LAN 10.24.66.0

So my VPN is 10.26.1.0 to 10.24.66.0 and I want to allow 10.26.2.0 without touching VPN.

What I did was:

kldload ipfw_nat.ko
ipfw nat 1 config ip 10.26.1.1 log reverse
ipfw add 180 nat 1 all from 10.26.2.0/24 to 10.24.66.0/24

Now I'm seeing the packets arriving at vtnet1 (LAN):
root@PB-FW1-FRA:~ # tcpdump -n -i vtnet1
22:22:02.368542 IP 10.26.2.11 > 10.24.66.108: ICMP echo request, id 38914, seq 1792, length 8

And they go through enc0 to the tunnel and the reply is there:
root@PB-FW1-FRA:~ # tcpdump -n -i enc0
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on enc0, link-type ENC (OpenBSD encapsulated IP), capture size 262144 bytes
22:22:52.372686 (authentic,confidential): SPI 0x55c35db5: IP 10.26.1.1 > 10.24.66.108: ICMP echo request, id 64031, seq 14592, length 8
22:22:52.381177 (authentic,confidential): SPI 0xca29fc32: IP 10.24.66.108 > 10.26.1.1: ICMP echo reply, id 64031, seq 14592, length 8


The problem is, that the reply doesn't leave the interface. Isn't there any state tracking within ipfw? Or is there a second nat needed like 10.24.66.0 -> 10.26.1.1 -> 10.26.2.0 (so we would need 1:1 nat pool).

I think this is a good step forward without touching the code.

**Comment by AdSchellevis** [comment] 2017-07-18 16:52
@mimugmail it has been quite some time ago that I did testing on this, but if I'm not mistaken the issue with pf looked similar, the kernel drops the return package.

If you can get it to work with ipfw, we should be able to integrate it into our current template, but so far I haven't seen a working configuration.

**Comment by mimugmail** [comment] 2017-07-19 06:26
@AdSchellevis Thanks for confirming, I did some further debugging and playing around with sysctl, no luck. I'll try my luck at the mailing lists.

**Comment by mimugmail** [comment] 2017-07-19 08:26
@fichtner You are playing around with a custom kernel right? Can you check if this topic is perhaps also related to: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=220217

I was asked at the freebsd-net list

**Comment by fichtner** [comment] 2017-07-19 08:31
it looks as bit like https://forum.opnsense.org/index.php?topic=5416.0 but maybe not relevant here. I will build a test kernel anyway. Thanks for bringing this up.

**Comment by mimugmail** [comment] 2017-07-26 12:36
@AdSchellevis @fraenki 
I have a solution now. 


kldload ipfw_nat
ipfw nat 1 config ip <fw-lan-ip>
ipfw add 179 nat 1 log all from <sourcenet-to-be-nattet> to <dst-net> out xmit enc0
ipfw add 179 nat 1 log all from <dst-net> to <fw-lan-ip> in recv enc0

setkey -PD | grep unique

Get the last number

setkey -v -c
spdadd -4 <sourcenet-to-be-nattet> <dst-net> any -P out ipsec esp/tunnel/<your-wan>-<peer-ip>/unique:<number> ;
^D

setkey -PD 


The only restriction is that you need to enable some kind of shaping in order to have basic ipfw ruleset enabled. @AdSchellevis any chance to get this templated? Perhaps we can also test with pf, but I'm quite unfamiliar with it.

**Comment by AdSchellevis** [comment] 2017-07-26 12:48
@mimugmail I'm not sure it will work with pf, but it's certainly worth a try. as soon as I can find some time I will look into this and find a way to implement it. nice work!

**Comment by fichtner** [comment] 2017-07-26 12:50
I really like this doesn't affect pf-nat and strongswan... It could be a simple policy edit IPsec: Outbound NAT page, it just needs some merging with ipfw ruleset for shaper / cp.

**Comment by AdSchellevis** [comment] 2017-07-26 12:52
it looks promising indeed

**Comment by AdSchellevis** [comment] 2017-07-28 15:16
For reference NAT before ipsec using pf:

register our SA (in setkey -v -c):
`
spdadd -4 <my_local_network> <remote_network> any -P out ipsec esp/tunnel/<my identifier>-<remote identifier>/unique:<key from setkey -PD> ;
`

Next apply nat using pf (in /tmp/rules.debug):
```
nat on enc0 inet from <my_local_network> to <remote_network> -> <my_assigned_network> port 1024:65535
binat on enc0 inet from <my_local_network> to <remote_network> -><my_assigned_network>
```

Now we need to make sure we can add the nat setup using our normal nat rules, so we don't have to clutter our pf code any further (there's still a rewrite of the nat part on my list) and make sure we can register our SAD entry.

**Comment by AdSchellevis** [comment] 2017-07-28 16:00
one addition, if I'm interpreting the documentation correctly (https://www.freebsd.org/cgi/man.cgi?query=setkey&sektion=8), we should be able to register all extra spd entries using:

`spdadd -4 <my_local_network> <remote_network> any -P out ipsec esp/tunnel/<my identifier>-<remote identifier>/require;
`

Which skips the need of finding the correct id, so we should be able to generate a config file directly from the configuration we already know.
This seems to be working on my end.

**Comment by AdSchellevis** [comment] 2017-07-28 16:32
For reference, setup the binat mapping (we should use either nat or binat, this only works on an equally sized network)
![image](https://user-images.githubusercontent.com/9783985/28726700-8d9eb87e-73c2-11e7-957e-cd7b19e2dd5d.png)

So we only need to bootstrap the additional spd entries and we're good to go.

**Comment by mimugmail** [comment] 2017-07-29 05:43
What a beauty! Works perfectly! Thanks @AdSchellevis 

![image](https://user-images.githubusercontent.com/20438689/28742481-a5309b96-7431-11e7-9611-e099a4f03167.png)

**Comment by mimugmail** [comment] 2017-07-29 05:50
Can also confirm require without ID also works! 👍

**Comment by AdSchellevis** [comment] 2017-07-29 08:20
@mimugmail thanks! next steps are adding an option to the phase2 entries for additional spd entries and probably extend the one-to-one to support regular nat too (so you can also use different sized networks).

**Comment by AdSchellevis** [comment] 2017-07-29 12:59
@mimugmail https://github.com/opnsense/core/commit/9351e45d59bd7cfd9e925f6bede4c2bf8156bc48 and https://github.com/opnsense/core/commit/814d18ac37ac477213fcacb43bb5e9920b92f2ff add the first version to add spd entries manually. it still needs a cleanup to record changes, but the rough idea is there.

**Comment by mimugmail** [comment] 2017-07-29 17:12
@AdSchellevis Works great, thanks! 👍

**Comment by AdSchellevis** [comment] 2017-07-30 11:02
@mimugmail nice team effort this is! 
So, cleanup is in too https://github.com/opnsense/core/commit/1fe8341a19ccc4765373696d509f509df9889fcb

In case @fraenki wants to test too, you need to pull in the following changes (in this order):
https://github.com/opnsense/core/commit/9351e45d59bd7cfd9e925f6bede4c2bf8156bc48
https://github.com/opnsense/core/commit/814d18ac37ac477213fcacb43bb5e9920b92f2ff
https://github.com/opnsense/core/commit/1fe8341a19ccc4765373696d509f509df9889fcb
https://github.com/opnsense/core/commit/76839db73ad41b05f49144d0f963b0a150fab880

Last item on my list is to extend the one-on-one nat and then we should close this issue in my opinion.

**Comment by mimugmail** [comment] 2017-07-31 04:30
I applied all patches and will test when I'm in the office.

I think @fraenki first has to update from 16.1 to 17.1 (or .7) for testing it :)

**Comment by fichtner** [comment] 2017-07-31 05:07
I'll add this to 17.7.1 if you all agree, as it doesn't seem to interfere with previous settings.

**Comment by mimugmail** [comment] 2017-07-31 06:59
One-to-one NAT works also with different sized networks. Will there be further changes to the GUI? Then I'll document the steps and @jschellevis can import it to the docs.

As far as I can see this should also allow IPSEC with overlapping networks on both sides, will test this with a second lab ...

**Comment by AdSchellevis** [comment] 2017-07-31 07:09
@mimugmail I think we're done, I don't have anything else planned there.

**Comment by AdSchellevis** [comment] 2017-07-31 07:21
@fichtner 17.7.1 sound good to me, thanks!

**Comment by mimugmail** [comment] 2017-07-31 10:47
@fichtner Would you mind to name @bu7cher (Andrey) in the Changelog as he did most of the research (it's ok for him)?

**Comment by fichtner** [comment] 2017-07-31 12:34
I'll mention in the backport, for the changelog the credits only name code contributions itself.

**Closed** 2017-07-31 20:27 UTC
Labels: feature

**Comment by fraenki** [comment] 2017-08-08 13:53
I can confirm that this NAT-before-IPsec implementation is indeed working for me. Great job, @AdSchellevis and @mimugmail!

There's one limitation that should be mentioned in the help text (and documentation):

```
root@opnsense:~ # /sbin/setkey -f /tmp/setkeyAsL4tW
libipsec: invalid IP address while parsing "host.example.com"
line 1: hostname nor servname provided, or not known at [ out ipsec esp/tunnel/host.example.com-1.2.3.4/require]
parse failed, line 1.
```

This means that it's **required** to use an **IP address** for "My identifier". Anything else, for example "Distinguished name", will not work. (Well, *maybe* it might work to get the IP address from the selected interface for those cases... but I'm not sure.)

**Comment by AdSchellevis** [comment] 2017-08-08 18:16
@fraenki we can hide the option when not valid (! my ip or ip) or add a validation, what do you think?

**Comment by fraenki** [comment] 2017-08-10 22:51
@AdSchellevis I've opened issue #1773, because I've found another limitation and a possible fix.

**Comment by fichtner** [comment] 2018-02-28 07:02
Forum thread https://forum.opnsense.org/index.php?topic=7282.0 asks for official docs

**Comment by mimugmail** [comment] 2018-02-28 07:22
I'll take this one ... long overdue :)
