### ISSUE TITLE
OpenVPN - Change Device from TUN to TAP sets wrong broadcast IP on TAP device.

### ISSUE THREAD

**Issue by matthias1232** [opnsense/core#2469] opened 2018-06-19 21:51 UTC
I created a topology Network with tun device.

10.99.99.0/24

This works.
Client gets first IP 10.99.99.2 etc... Broadcast IP is 10.99.99.255

Later i changed my Server settings to a TAP Device and saved it with the same Subnet.

10.99.99.0/24

Clients gets first IP 10.99.99.2 - But the Broadcast IP is now set to 10.99.99.2

So the first Client who connects to openvpn has no connection. The next Client gets 10.99.99.3 and he can enter into the Network.

Also after a reboot this scenario does not change.

Workaround:
Delete the VPN Server and create a new one with the tap settings.
This sets the broadcast IP correct to 10.99.99.255

**Comment by fichtner** [comment] 2018-08-09 06:39
@matthias1232 does this still happen on 18.7 ? I have been unable to reproduce.

**Comment by fichtner** [comment] 2018-09-08 12:47
closing until feedback comes in

**Closed by fichtner** 2018-09-08 12:47 UTC
Labels: bug
