### ISSUE TITLE
adding / editing outbound_nat rules not possible when wan is set to pppoe

### ISSUE THREAD

**Issue by olliff** [opnsense/core#400] opened 2015-09-24 20:28 UTC
with the release of OPNsense 15.7.14 I noticed an issue while adding / editing (manual) outbound nat rules.
When your wan is set to pppoe and you add a new nat rule on the wan interface you get an error message that you must specify a valid target address. Actually my pppoe connection was up and had a valid ipv4 address at this point. Also the "translation / target" option gets changed from "WAN address" to "Single host or network" with pppoe as it's value, which doesn't make any sense.
This happens even after a fresh install of opnsense, so I assume this is a bug.

<img width="904" alt="screen shot 2015-09-24 at 22 02 45" src="https://cloud.githubusercontent.com/assets/7170155/10085770/49201b94-630b-11e5-822f-fc3beac44d30.png">
<img width="887" alt="screen shot 2015-09-24 at 22 03 10" src="https://cloud.githubusercontent.com/assets/7170155/10085772/495512a4-630b-11e5-8c4a-082123335cab.png">
![screen shot 2015-09-24 at 22 03 35](https://cloud.githubusercontent.com/assets/7170155/10085771/4952ed80-630b-11e5-8101-af4b00e1564c.jpg)

**Comment by AdSchellevis** [comment] 2015-09-25 09:05
@olliff Are you sure this worked like this before 15.7.14? I've checked out the old page and there doesn't seem to be a pppoe interface ip selection in there as well and the validation rules look the same.

**Comment by olliff** [comment] 2015-09-25 20:51
I can create the nat rule in 15.7.11 and 15.7.12 without any problems. With 15.7.13 or .14 the gui has changed, the option to select "Interface Address" as a target disappeared.

**Comment by AdSchellevis** [comment] 2015-09-26 07:02
@olliff I'm still a bit lost as where the pppoe came from in your old config, the "Interface Address" option looks like an empty (no) target in the old code.... 
If you filled in the pppoe yourself, then I understand, and we probably should add the empty option in there as well for clearity, leaving the field empty should solve your issue in this case as well.

**Comment by olliff** [comment] 2015-09-26 09:27
I didn't enter pppoe. It got filled in by the script automatically when I hit Save. I think this is caused by a parsing error of the script. It only occurs when the selected Interface uses pppoe. If the Interface is set to Ethernet with a static IP, the nat rule gets created without errors. I'll join the IRC later today, maybe we can do some more testing and sort it out.

**Comment by AdSchellevis** [comment] 2015-09-27 09:59
I wasn't online yesterday, but I have created a fix which should fix the issue. (https://github.com/opnsense/core/commit/54704d05a2edd30beb5bae4eb6026766d0b5854d)

The steps I've taken to reproduce the issue:

1) download the old edit page into my repo
curl https://raw.githubusercontent.com/opnsense/core/15.7.10/src/www/firewall_nat_out_edit.php > src/www/firewall_nat_out_edit.php
2) edit 1 ppoe rule and set target to interface address
3) copy that config.xml into /tmp
4) edit with our current code and compare the config.xml, there where a number of differences
5) apply new code (the fix)
6) retry save and compare, they look the same now.

@olliff If you have the time, could you try this version by creating a new rule? Although I've no idea where the pppoe comes from in your edit box, it doesn't look like it's supposed to be there.

**Comment by olliff** [comment] 2015-09-27 10:25
Just tested it, it's working for me now. Thanks!

**Comment by AdSchellevis** [comment] 2015-09-27 10:55
You're welcome! closing this one now.

**Closed by AdSchellevis** 2015-09-27 10:55 UTC

**Comment by fichtner** [comment] 2015-09-27 11:24
Will be part of 15.7.15 as well, thanks!
