### ISSUE TITLE
Source Address of Ping Service in Monit

### ISSUE THREAD

**Issue by rkirmis** [opnsense/core#3733] opened 2019-09-28 17:10 UTC
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

**Is your feature request related to a problem? No**

**Describe the solution you'd like**
It would be nice, if it was possible to set the source address for the ping service via GUI.
You need the source address for ping from the firewall through an vpn tunnel.
see https://forum.opnsense.org/index.php?topic=14221.msg65927#msg65927

**Comment by AdSchellevis** [comment] 2019-11-22 17:25
duplicate of https://github.com/opnsense/core/issues/2632 ?

**Closed** 2019-12-06 15:13 UTC
Labels: support
