### ISSUE TITLE
Unbound crashes when Register DHCP leases enabled and leased name contains illegal symbols

### ISSUE THREAD

**Issue by zeon-ua** [opnsense/core#5633] opened 2022-03-18 20:44 UTC
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

In case the user device's hostname contains illegal characters like "MI6-MiPhone:).localdomain" in my case, and there is "Register DHCP leases" option is enabled what happening is Unbound cannot validate its config and just won't be able to restart until you either disable "Register DHCP leases" or the device is disconnected from the network.
Log message:
[91352:0] error: error parsing local-data at 27 'MI6-MiPhone:).localdomain IN A 172.29.100.199': Syntax error, could not parse the RR's type

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

Assign device hostname with some illegal characters.

**Expected behavior**

I would just ignore bad/illegal hostnames and don't put them onto Unbound.

**Describe alternatives you considered**

A clear and concise description of any alternative solutions or workaround you considered.

**Screenshots**

**Relevant log files**

If applicable, information from log files supporting your claim.

**Additional context**

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 22.1.3 (amd64/OpenSSL)
Unbound Version 1.15.0
Intel(R) Xeon(R) CPU X5675

**Comment by AdSchellevis** [comment] 2022-03-19 10:50
duplicate of https://github.com/opnsense/core/issues/5550, better extend test cases there

**Closed by AdSchellevis** 2022-03-19 10:50 UTC
