### ISSUE TITLE
Dpinger failing to properly recover on PPPOE recycling

### ISSUE THREAD

**Issue by cpw** [opnsense/core#4149] opened 2020-06-02 03:17 UTC
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[/] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[/] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
dpinger is not able to recover a PPPOE recycling event. It continues to report `ENETDOWN 50` errors long after the PPPOE connection has recycled and recovered.

This is causing knock on effects, such as failing WAN failovers, because I don't always catch the dpinger offline status before other network events occur.

I am not sure if this has ever worked properly, but this problem is probably the final issue to a "fully robust" setup. I have asked about this problem several times on the forums with little acknowledgement. I'm guessing there's not a lot of knowledge here.

**To Reproduce**
1. Create a PPPOE connection.
2. Enable gateway monitoring for the new PPPOE connection.
3. Make the PPPOE connection "wobble" (forcing a new PPP handshake seems to be the trigger).
4. dpinger will report ENETDOWN errors, or crash. (Crashing is actually preferable, since I can restart automatically with monit and everything will work then).

**Expected behavior**
Dpinger is fully recycled by the PPPOE connection code, when the connection is up and active. (this seems like the most sensible solution, since it probably won't require actually patching dpinger to handle the network connection going away for a short period).

**Relevant log files**
Two log files attached. The pppoe log, showing the pppoe connection recycling a couple of times recently, and the gateway (dpinger) log file, showing PPPOE going into the error 50 state and not recovering until I manually restarted the entire dpinger process.

[pppoe.log](https://github.com/opnsense/core/files/4714507/pppoe.log)
[gateway.log](https://github.com/opnsense/core/files/4714511/gateway.log)

Here's a screenshot from the health monitoring showing how the state was down for the entire period.
![image](https://user-images.githubusercontent.com/1217211/83476170-f787b000-a45d-11ea-9032-36020c8d93fb.png)

**Environment**
OPNsense 20.1.7-amd64
FreeBSD 11.2-RELEASE-p20-HBSD
LibreSSL 3.0.2

**Comment by cpw** [comment] 2020-06-03 02:30
Do you believe that some combination of configuration would resolve this problem? Or do you believe that there is something more fundamental wrong with how dpinger is handling downed interfaces?

Note: the problem happened again today. I cannot control the quality of my upstream PPPOE connection, so it's going to continue to flutter irregularly. I was hoping we could at least make everything recover after the flutter has passed.

**Comment by marjohn56** [comment] 2020-06-03 05:24
I'm on PPPoE and have both v4 and v6 monitors, I don;t get this problem. What I do get occasionally is the v6 monitor not restarting. This is handled by a Monit routine to fire it up.

**Comment by marjohn56** [comment] 2020-06-03 05:48
@cpw - the function to fire up or kill dpinger is in dpinger.inc. The function at line 83 is ( I think ) whats called  by the link that @AdSchellevis gave in the forum. That then calls dpinger_configure_do(). It should shut down and restart dpinger.

**Comment by marjohn56** [comment] 2020-06-03 07:09
@cpw - can you check the process ID of dpinger(s) before and after the pppoe event?

**Comment by marjohn56** [comment] 2020-06-03 12:22
I've created a pppoe server using ubuntu and basically I can suspend the ubuntu vm and dpinger shows packet loss and then offline, if I then restore the VM dpinger shows the packet loss reducing as expected. If I leave the VM down long enough then the link itself times out and the gateway disappears; restoring the VM brings the gateway back and dpinger is back to normal. This is on IPv4  I cannot easily do a v6 emulation!

**Comment by marjohn56** [comment] 2020-06-03 12:25
Forgot to add - All my testing is with 20.7

**Comment by cpw** [comment] 2020-06-03 16:41
The PPPOE interface itself doesn't disappear in you setup? In my scenario, I think the PPPOE itself is disappearing. It's not the gateway going away - its the connection in the OPN box that's failing (as i said, i have an occasionally wobbly uplink, and the dsl modem on my side seems to completely fail, and takes out the PPPOE process on OPN when it goes).

I'm going to try and simulate - i think if i just unpower my dsl modem for a minute, that will cause the failure mode, and i'll report back on the results.

**Comment by cpw** [comment] 2020-06-03 16:59
Well, the phone cable from the DSL modem. If I leave it for a moment (60s PPP timeout), the connection tries to recycle. I've currently got a dpinger in the state where it believes it's offline, but the actual interface is up and running. I can't see why - it hasn't written anything to the gateway log.

**Comment by pete1019** [comment] 2020-06-03 17:01
I have those problems as well. I don't use PPPOE. I get those problems from unplugging or the Tier going offline.
Or i had this problem when both connections showed packet loss and the route was not set properly back to Tier 1 after recover.
That one time: Tier 1 was offline, Tier 2 got Packet los. Route was to Tier 2 but on recover of Tier 2 i had no internet. I think only the recover of Tier 1 fixed.
What helps as well: saving settings on the Interface.

**Comment by marjohn56** [comment] 2020-06-03 17:02
Saving settings on the interface forces an interface reset so it will fix it.

**Comment by marjohn56** [comment] 2020-06-03 17:03
@cpw - ru prepared to try 20.7b?

**Comment by marjohn56** [comment] 2020-06-03 17:07
Well I was doing the pppoe testing using only v4, so this is not that, but it could be something that's been fixed in the kernel.

If you look at the multiwan thread over on the forum it tells you what you need to do to bring it up to date, the image itself dates back a couple of months, but a code-core update and the other stuff will bring it up to date. Worth a try.

**Comment by cpw** [comment] 2020-06-03 17:10
@marjohn56 it'll likely be a day or two before i can test that - I can't just down the internet here for a few hours. Has anything significant changed in the dpinger/monitoring code in 20.7? I wish i understood this codebase better to be able to help more.

**Comment by marjohn56** [comment] 2020-06-03 17:15
Nothing really, that's why I want you to try it with 20.7 as it's FreeBSD 12+, and that has fixed some things.

**Comment by marjohn56** [comment] 2020-06-03 17:19
Check back when you've played some more.

**Comment by cpw** [comment] 2020-06-03 19:06
@marjohn56 i'll see if i can see any errors out of dpinger.inc maybe.. I'll look into the 20.7 upgrade  for sure, but I can't turn that round at the drop of a hat. Editing php i can do ;)

**Comment by marjohn56** [comment] 2020-06-03 19:32
:) practice marks perfect. around 5 minutes to switch my qotom back to 20.1 and the same the other way.

**Comment by cpw** [comment] 2020-06-03 19:48
question: how can I run the dpinger_status function? That seems like it might be somewhat diagnostic of what my dpinger process thinks it's doing. (It's still stuck in down state, even though the intf is up and working).

I've tried using various pluginctl calls, none seem to work..

**Comment by AdSchellevis** [comment] 2020-06-03 20:04
```
pluginctl -r return_gateways_status
```

should do the trick

**Comment by cpw** [comment] 2020-06-03 20:25
Hmmm, that just shows them all down, even though two are up..

**Comment by pete1019** [comment] 2020-06-03 21:53
Maybe my problem is something else? In some cases the default route is not set right. Gateways shows the right Tier as "active" but it's the wrong default route. Whats wrong here? Tried with unbound dns and Dnsmasq DNS. Thanks!

**Comment by pete1019** [comment] 2020-06-07 16:40
I think i found the cause:
Seems Multi WAN is not working properly (or maybe dpinger) if the Interface goes down and back up (unplugging and re plugging).
In my tests i was just unplugging the LAN-cable on the Port.

I think the same happens with PPPOE or anytime the link is down and up again (physically).

This should not happen In my opinion.

Would love to hear from you, thanks.

**Comment by AdSchellevis** [comment] 2020-12-16 09:50
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.

**Closed by AdSchellevis** 2020-12-16 09:50 UTC
Labels: support
