### ISSUE TITLE
Firewall rules for assigned OpenVPN interface don't work for remote-access-tunnel

### ISSUE THREAD

**Issue by spi43984** [opnsense/core#4674] opened 2021-02-05 12:05 UTC
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

[+] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
[+] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**
I am on 21.1.

OpenVPN Remote Access server: fw rules need to be added to generic OpenVPN interface. In case they're added to the assigned specific openvpn interface they don't work.

With OpenVPN Peer to Peer server rules added to the specific, assigned openvpn interface work.

**To Reproduce**

OpenVPN setting, set up a new Remote Access Server, assign ovpnsX as new interface, add WAN rule for openvpn, add firewall rule for new openvpn interface

connect openvpn client, check connectivity - does not work

move rules from new assigned openvpn interface to general openvpn interface
connect openvpn client - connections work

**Expected behavior**
I'd expect the fw rules assigned to the newly assigned openvpn interface to work - but they don't. They need to be added to the generic (group) openvpn interface.

**Additional context**
There are some posts in the forum. Some of them got solved by an update so it seems to be a bug in the sw.
[https://forum.opnsense.org/index.php?topic=9150](url)
[https://forum.opnsense.org/index.php?topic=13313](url)

**Comment by fichtner** [comment] 2021-02-05 12:10
Hi @spi43984,

From my knowledge incoming access is done via the generic group interface always. It never changed.


Cheers,
Franco

**Comment by spi43984** [comment] 2021-02-05 12:14
So what are the assigned openvpn interface then for? AFAIK the rules in the group interface are handled first, the specific interface rules second.

**Comment by fichtner** [comment] 2021-02-05 12:14
You can set outgoing policies there, e.g. for policy routing.

**Comment by spi43984** [comment] 2021-02-05 12:18
Ok, but then the forum posts describe different behavior for different versions. And there is a different behavior between remote access and peer to peer tunnels - in the latter fw rules assigned to the specific interface work.

Cheer,
spi

**Comment by fichtner** [comment] 2021-02-05 12:28
Taking all reports with a grain of salt I think it's just confusing in this case. As I said, always has been this way.

**Comment by spi43984** [comment] 2021-02-05 12:32
Ok. Will consider this in future.

I take this also as an advice to move the peer to peer rules from the specific openvpn interface to the generic interface then?

Cheers,
spi

**Comment by Gauss23** [comment] 2021-02-05 12:42
Looks like a duplicate of:
https://github.com/opnsense/core/issues/4395

**Comment by spi43984** [comment] 2021-02-05 15:42
> Looks like a duplicate of:
> #4395

Cool - checked that. Disabling reply-to in the single rules on the dedicated OpenVPN interface didn't solve my issue.

To get the rules on the dedicated OpenVPN interface work I can do:
1) disable reply-to in FW/Settings/Advanced
2) disable the OpenVPN Gateway (which got automatically configured) under System/Gateways/Single

Or I can move the rules from the dedicated OpenVPN interface to the group one.

I also feel there is less possibility of error if configuring the rules per dedicated OpenVPN interface as the created rules are bound to the interface.

**Comment by JeGr** [comment] 2021-02-06 12:04
> Taking all reports with a grain of salt I think it's just confusing in this case. As I said, always has been this way.

Like I posted on the forums, I'm a bit confused as to why rules on the mapped ovpn[c|s]X interface shouldn't work when the group ones do. They only differ (AFAIR) in the reply-to addition and that shouldn't break rule processing or routing in any way. As you already said in the forums, that logic came from pfSense but there it's handled without problems e.g. I can create an allow rule on either the OpenVPN group interface or the assigned ovpnXY interface and the traffic gets in and out without a problem. So somehow PF or another part of OPNsense is handling the reply-to in a different way? Just trying to understand why it won't just work in both variants. That you need the assigned IFs for the gateway to show up and use in policy based rules - OK. But incoming traffic should be matched and routed/forwarded in both cases without problem, or shouldn't it?

**Comment by spi43984** [comment] 2021-02-06 12:10
> ... As you already said in the forums, that logic came from pfSense but there it's handled without problems e.g. I can create an allow rule on either the OpenVPN group interface or the assigned ovpnXY interface and the traffic gets in and out without a problem. ...
> 

I can confirm that. Checked with pfsense and I can add rules to the assigned interface.

For now I solved that on opnsense by disabling reply-to in FW/Settings/Advanced as I find it more simple and less error-prone having the OpenVPN rules with the assigned interface.

**Comment by Gauss23** [comment] 2021-02-06 12:14
> Cool - checked that. Disabling reply-to in the single rules on the dedicated OpenVPN interface didn't solve my issue.

Did you reset states afterwards? Maybe you had states saved with reply-to. When disabling reply-to helps you, doing it within a specific rule should do it, too.

But like @JeGr said: it would be nice to have this feature without messing around with the reply-to settings.

**Comment by spi43984** [comment] 2021-02-06 12:16
> > Cool - checked that. Disabling reply-to in the single rules on the dedicated OpenVPN interface didn't solve my issue.
> 
> Did you reset states afterwards? Maybe you had states saved with reply-to. When disabling reply-to helps you, doing it within a specific rule should do it, too.

Of course not. Grr. That's probably why it didn't work. I restarted all OpenVPN servers, thought that might be enough.
> 
> But like @JeGr said: it would be nice to have this feature without messing around with the reply-to settings.

I agree.

**Comment by fichtner** [comment] 2021-02-06 14:44
I'm sorry, but what you are looking at is a patched ever after scenario of pfSense that was never contributed to FreeBSD for what I can only guess are quality concerns because I think they do sponsor such a tremendous amount of work there:

https://github.com/fichtner/pfsense-tools/commit/b5e737d015f56

You can see the patch grow in size ever since to now look something like this:

https://github.com/pfsense/FreeBSD-src/commit/3a57a783f7

I realise this sounds snarky as it is intended. But with pfSense CE in the downwards spiral now more than ever we need something that works in FreeBSD for everyone and not this particular path to patch things up because this otherwise annoys users.


Cheers,
Franco

**Comment by JeGr** [comment] 2021-02-06 18:01
Let's wait and see what happens to CE. That's not a topic for here in my humble opinion. 

Yes such a patch as displayed might get annoying with time. But "sitting it out" and doing nothing isn't a real great idea either, is it? So yeah, perhaps an upstream fix is needed, so why not propose or submit one from us/here? Intended snarky remarks on others don't fix problems we have here and personally I don't find it very well rounded, having to disable reply-to in every rule on assigned interfaces. Also customers find the difference in behavior quite irritating especially when they are trying to migrate from perhaps pfSense and using assigned interfaces for good reasons! So yeah, we need something that works, totally agree to that :)

So sadly I don't own the developer skills to help out on that side but can rather test, check it over and drive a patch through its paces. But me and others aren't "demanding" but trying to help. And yes I DO understand being snarky over some things, but comparisons with pfSense will not cease and and will come more and more and I don't think it helps them - or gauss or spi - to point fingers and be snarky ;)

> FreeBSD for everyone and not this particular path to patch things up just because this otherwise "annoys" users unable to configure it "correctly".

So how to do that? reply-to is "a thing" with Multi-WAN and VPN tunnel handling and nicely so. But why is it breaking with those reply-to rules in the first place? I'd simply like to understand why "pf" is failing in that scenario without said patch, as it currently makes no sense to me.

**Comment by fichtner** [comment] 2021-02-06 18:28
> So how to do that? reply-to is "a thing" with Multi-WAN and VPN tunnel handling and nicely so. But why is it breaking with those reply-to rules in the first place? I'd simply like to understand why "pf" is failing in that scenario without said patch, as it currently makes no sense to me.

To my understanding the patch simply disables route-to statements when the routes to the destination are in the local routing table. That is contrary to how pf should enforce route-to when it is set (some sort of soft-off). The only way to emulate it is a local alias table with the routes populated using it to avoid the route-to in the first place (at least static routes, best case dynamic ones but much harder to pull from the system using another nonexistent mechanism).

The other ways to deal with this are documenting this in details, changing defaults or better matching route-to exceptions which lead to more overrides. This is from most preferable to least preferable.

WRT "snarky": I just don't like the opportunistic way of advertising and then forgetting such patches while also silently delivering them to users without raising awareness. There is a wide gap of understanding and you can see that from the multitude of questions and discussions around the subject.

I don't know the exact scope of this, but I also think that there are not 80% of users who run into this issue daily. WE have to make measured decisions based on required work to move forward and between e.g. documentation and adding new functionality the scope needs to be taken into account and it never reached a critical level for implementation (again, user base wise, not complaint wise).


Cheers,
Franco

**Comment by AdSchellevis** [comment] 2021-02-06 18:36
The same discussion comes back every now and then always leads to the same conclusion,  pf is doing the right thing (at least nobody has come with proof that it didn't). 

The current options works for a vast majority of the users, excluding certain traffic from a single rule just isn't easily doable without generating additional rules which will have their own problematic edge cases. For most people it's just as simple as disabling reply-to on the rule in question (it's an existing option and documented https://docs.opnsense.org/manual/firewall.html#policy-based-routing). 

We can argue if reply-to should be set by default or not (if we wouldn't, the next guy comes complaining about his out of the box multi-wan setup), at the end of the day there's always someone unhappy. Personally I don't like automated rules at all, since there's almost always an assumption underneath it.

It might be an option to not only allow to disable `reply-to` on rules (which by the way fixes this for most people), but also optionally set it like one could do for the `route-to`  (gateway) setting, so it's possible to construct the correct ruleset manually for the brave around. But so-far none of the customers we have seen around really needed such a feature in the last 5 years.

Best regards,

Ad

**Comment by JeGr** [comment] 2021-02-06 19:55
> We can argue if reply-to should be set by default or not (if we wouldn't, the next guy comes complaining about his out of the box multi-wan setup), at the end of the day there's always someone unhappy. Personally I don't like automated rules at all, since there's almost always an assumption underneath it.

I don't want to argue a case :) I just try to get to the bottom of what goes wrong. The problem seems to exist when traffic comes into the filter via an OVPN (or wg?) interface. When rulesets on the group IF matches without the reply-to, it flows the right way. With the reply-to on an assigned interface it somehow won't? As the docs state

```By default traffic is always send to the connected gateway on the interface. If for some reason you don’t want to force traffic to that gateway, you can disable this behaviour.```

In the described case the destination is a LAN (without a gateway) and comes from an OVPN interface (that does have a GW and a correct one hopefully). So I'm not trying to argue if OPNsense' implementation is wrong but - as I was building OpenBSD pf based firewalling a long time ago - don't exactly understand why the definition of reply-to in those rules interferes with the traffic from heading the right way in the first place?

Also there's documentation for it, I'm not against using it that way and disable reply-to on those rules. My only concern is having seen many *sense uses, where it's completely fine/normal to use assigned interfaces as to better organize your ruleset and prevent misconfiguration by using "any" on the group interface and I'm just trying to minimize the impact/confusion when configuring OpenVPN by them. :) And as it may well be, that there might be conversions from one sense to another I'll surely note that on my checklist, but just wanted to help smooth things over.

Best regards,
Jens

**Comment by spi43984** [comment] 2021-02-07 00:31
> In the described case the destination is a LAN (without a gateway) and comes from an OVPN interface (that does have a GW and a correct one hopefully). So I'm not trying to argue if OPNsense' implementation is wrong but - as I was building OpenBSD pf based firewalling a long time ago - don't exactly understand why the definition of reply-to in those rules interferes with the traffic from heading the right way in the first place?

I was reading the docs over and over again but it never came to my mind that I'd need to disable reply-to per rule to get my rules working because I wanted the traffic be forced to the interface's gateway. And I assumed (and that might have been the fault) that the interface's gateway is that gateway I defined for my openvpn server, and for which I also assigned an openvpn interface.

**Comment by marcquark** [comment] 2021-04-27 20:56
The discussion about enabling reply-to by default is probably never going to lead anywhere. While i agree that it's weird that it doesn't work, the answer to that probably lies somewhere deep in how OpenVPN interfaces are handled in FreeBSD. I don't know anything about that though.

So far, the documented workaround is to disable the gateways after assigning the interface. It's okay, but definitely not something you'll find and understand from the docs if you don't know where to look. I can't think of a scenario where one would want a gateway for their OpenVPN roadwarrior server. Not least because i also couldn't find any way to get any connections to actually work from a connected client when the reply-to's were present. Also the gateway is OPNsense's IP so it monitors and routes via... itself?

I've suggested changing the gateway creation behaviour before https://github.com/opnsense/core/issues/4485 Maybe that one should be revisited? If it's scoped specifically to roadwarrior servers, it'll surely get rid of a lot of confusion, and not break other setups. I guess a big fat notice of such a change in patch notes can help address that one guy who actually needs the gateway on the assigned roadwarrior interface?

**Closed** 2021-08-11 18:31 UTC
Labels: support
