### ISSUE TITLE
"Add" action buttons displayed inconsistently

### ISSUE THREAD

**Issue by module0x90** [opnsense/core#4381] opened 2020-09-27 14:04 UTC
I am on version OPNsense 20.7.3-amd64.

I noticed for quite a while now, that the "Add" actions are displayed in different ways. I mean "add" a firewall rule, "add" a DNS entry and so on.
The most common display is in the Firewall section, where there is a big fat OPNSense coloured "+ Add" button. Which is nice and you always see it as it's at the top.

These are the other ways the "Add" action is displayed:
* Firewall|Aliases: Just a small, "+" button hidden at the bottom of the list
* Firewall|Shaper: Only a small "+" at the bottom
* DHCPv4|IF: A slightly bigger "+" at the top of the list

I understand, on some (like DHCPv4|IF) the big OPNSense coloured "+ Add" is challenging to incorporate, as there is other information at the top. But then for example "Firewall|Groups" shows it neatly at the top, but "Firewall|Aliases" doesn't, but it could clearly do that...

This is just a suggestion I came across many times and tbh it bugs me everytime... that "Add" button is here and that one ... you have to scroll to the bottom to actually see it.

Cheers

Tom

**Comment by AdSchellevis** [comment] 2020-09-27 16:53
all new style components provide the add/delete actions at the bottom of the grid. we might consider removing the orange buttons in the legacy code at some time.

**Comment by fichtner** [comment] 2020-09-27 17:08
Hi Tom,

This is a duplicate of #4216 I think.


Cheers
Franco

**Closed** 2020-10-04 08:19 UTC
Labels: incomplete
