### ISSUE TITLE
Package request: telegraf

### ISSUE THREAD

**Issue by juggie** [opnsense/core#1626] opened 2017-05-08 02:47 UTC
Hey,

Would it be possible to add telegraf to the package repo?

Thanks.

**Comment by fichtner** [comment] 2017-05-08 04:23
Hi,

telegraf seems a bit heavy on our packages repo.  Would you mind building it
from source locally?  The steps are easy:

# opnsense-code tools ports
# cd /usr/ports/net-mgmt/telegraf
# make install

Updating the package is easy since it's a go package with all of the dependencies
included (if updates are available):

# opnsense-code tools ports
# cd /usr/ports/net-mgmt/telegraf
# make reinstall


Cheers,
Franco

**Comment by juggie** [comment] 2017-05-10 15:18
Hey Franco,

I can do that, If need be.  Can I ask why it is a bit heavy if it is optional?

**Comment by fichtner** [comment] 2017-05-10 15:25
Hi @juggie,

Sure, this is the download list for the package is long:

https://github.com/opnsense/ports/blob/master/net-mgmt/telegraf/distinfo

It's a contained go binary afterwards which is nice though the package is 6MB compressed when built, about 35MB uncompressed. That's 4x 6MB plus extra build time that ends up on the mirrors, which are also used for system upgrades (16.7 -> 17.1 as the first of this type, 17.1 -> 17.7 will follow) which means the extra weight s noticeable in the sets, about 3% increase.

I'm not against this, but for only one request this seems too much to deal with. If we have others who want this and/or build a plugin we should take it in of course to make installing trivial. :)


Cheers,
Franco

**Comment by juggie** [comment] 2017-05-10 15:27
K sounds good.  Let's leave this ticket open for a little bit to see if anyone else wants to make their interest known.

**Comment by fichtner** [comment] 2017-05-10 15:28
agreed, thanks

**Comment by mimugmail** [comment] 2017-05-15 08:23
@juggie What do you want to achieve with Telegraf? 
For me it makes only sense with InfluxDB and Grafana, but I'm interested in your ideas :)

**Comment by juggie** [comment] 2017-05-15 11:24
@mimugmail I wanted to use telegraf to collect stats and send them to influxdb.  And then graph with grafana.  I've got this working with @fichtner instructions above.  I am sure there are tons of custom collection agents that could be created as well eg vpn sessions, firewall events, etc.

**Comment by mimugmail** [comment] 2017-05-15 11:31
@juggie Aaah, you only use it as an agent. I was too focused on Influx and Grafana. 
Good idea for centralizing all stats! 

I'm in for a pkg in the repo 👍 

But to be honest I think there are less than 0,001% that will use it, and also only when there's a plugin and a bit promotion.

**Comment by juggie** [comment] 2017-05-16 00:47
@mimugmail How else can you use telegraf besides an agent really?

So far grafana is collecting some interesting stats.  It would be interesting to write some  custom plugins or just exec scripts even to collect more information.  I see opnsense has an API that I may be able to collect information from, but I am not able to find *ANY* documentation on the end points.

**Comment by mimugmail** [comment] 2017-05-16 07:50
@juggie No, when reading telegraf I thought of a complete local installation of Telegraf, Influx and Grafana on OPN itself.

**Comment by tioan** [comment] 2017-06-17 17:24
I would be interested to use telegraf to push stats to my external influxdb.

**Comment by Ulrar** [comment] 2017-07-31 13:49
Agreed, I was thinking of doing the same. Guess I'll do it by hand for now, but I'd love a package

**Comment by fichtner** [comment] 2017-07-31 13:50
will look at this now that 17.7 is out

**Comment by Ulrar** [comment] 2017-07-31 13:54
Quick question though, your instructions for installing manually might be outdated or something.
`opnsense-code tools ports` says rm: /etc/make.conf: No such file or directory, and /usr/ports still doesn't exist after the download.
Did the way to install ports change ?

**Comment by fichtner** [comment] 2017-07-31 14:00
@Ulrar what OPNsense version are you on? I remember these bugs in opnsense-code, but that was a few months ago. FWIW, this should "fix" it:

    # touch /etc/make.conf
    # opnsense-code tools ports

**Comment by Ulrar** [comment] 2017-07-31 14:01
Oh yeah, that fixes it.
I seem to be on 17.1.r1 still, the update doesn't want to apply .. Not sure why, I'll investigate better tonight. Thanks !

**Comment by fichtner** [comment] 2017-07-31 14:05
@Ulrar uh, 17.1.r1? That shouldn't even exist anymore. You may have missed the upgrade window for this prerelease version. But it can be fixed with a fingerprint fetch and manual upgrade command. I can walk you though it if you want or you can use a newer image + import / install.

**Comment by Ulrar** [comment] 2017-07-31 14:10
Ah ! If I can avoid re-installing that would be great yes, it's my home router so I'd rather avoid risking losing my config and have no internet to figure out the problem.

**Comment by fichtner** [comment] 2017-07-31 14:12
Ok, when you can, post the output of:

    # ls -lah /usr/local/etc/pkg/fingerprints/OPNsense/trusted

.. and check if it's enough to switch the firmware mirror, maybe the old selection is simply not there anymore.

**Comment by Ulrar** [comment] 2017-07-31 14:36
I just tried it again and that's not what the problem is, I get this : 

```
pkg-static: Cannot delete vital package: opnsense!
pkg-static: If you are sure you want to remove opnsense, 
pkg-static: unset the 'vital' flag with: pkg set -v 0 opnsense
Starting web GUI...done.
Generating RRD graphs...done.
***DONE***
```

Admittedly I haven't looked at the doc, maybe I should just unset the vital flag. I just thought I'd take a look at it later, and clearly forgot it for a few months :)

**Comment by fichtner** [comment] 2017-07-31 14:42
I'd have to check what was wrong there, maybe a problem in pkg package manager, can't clearly remember. do not unlock the package as it suggest, it'll remove the GUI and leave the box stranded.

**Comment by fichtner** [comment] 2017-07-31 14:43
Here you go: https://forum.opnsense.org/index.php?topic=4992.0

**Comment by Ulrar** [comment] 2017-07-31 15:27
Two upgrade later, I'm on the latest version and it seems to work fine. The second upgrade to 17.7 took forever, I was actually plugging the serial usb adapter to check what went wrong when it finished booting.

Anyways, everything's good, thanks for the help ! And sorry for hijacking the thread

**Comment by fichtner** [comment] 2017-09-13 19:25
This will happen for 17.7.3...

**Comment by fichtner** [comment] 2017-09-13 20:08
https://github.com/opnsense/tools/commit/2002f25d

**Closed by fichtner** 2017-09-13 20:08 UTC
Labels: feature

**Comment by mimugmail** [comment] 2017-10-08 15:41
@Ulrar @juggie @tioan Would you mind send me an anonymized copy of your telegraf.conf? With your parameters I'd build a plugin ...

**Comment by juggie** [comment] 2017-10-09 02:33
Hey @mimugmail 

I'm running pretty much a stock configuration.  Nothing special besides being pointed at my influxdb server.  The problem w/ telegraf is the configuration options in terms of different output and input plugins are pretty extensive.

**Comment by mimugmail** [comment] 2017-10-09 08:16
@juggie I'd like to see it anyway. With all you 3 conf's I can start with a plugin make all your instances configurable via UI. 

Just send it to:
https://github.com/opnsense/plugins/blob/master/net-mgmt/collectd/Makefile

**Comment by mimugmail** [comment] 2017-10-10 10:02
Do you use haproxy and net plugin? 
I'm currently adding cpu, disk, diskio, mem, swap, processes and system. You need some more?

**Comment by mimugmail** [comment] 2017-10-20 18:47
There's a plugin in devel available. With the latest 17.7.6 you can install it via cli:
`pkg install os-telegraf-devel`

But please backup your own config before. 

Would be happy to get some feedback/reports.

**Comment by Ulrar** [comment] 2018-01-25 12:49
Hey,

Any way to add a filed for https://github.com/influxdata/telegraf/tree/master/plugins/inputs/ping ?
I have a new secondary WAN and I'd like to monitor it a bit, make sure it's stable. I'll configure it by hand but I think it'd make sense to have this in the os package.

**Comment by mimugmail** [comment] 2018-01-25 13:27
Sure, how many options do you need/use? 

```
[[inputs.ping]]
   urls = ["8.8.4.4"]
#   # count = 1
#   ## interval, in s, at which to ping. 0 == default (ping -i <PING_INTERVAL>)
#   # ping_interval = 1.0
#   ## per-ping timeout, in s. 0 == no timeout (ping -W <TIMEOUT>)
#   # timeout = 1.0
#   ## interface to send ping from (ping -I <INTERFACE>)
#   # interface = ""

```

I dont wont to blow it up

**Comment by Ulrar** [comment] 2018-01-25 14:44
Just urls (and count, but I don't think that really matters).
I've tried interface, which would have been great, but it looks like Linux and BSD don't have the same meaning for -I so it doesn't work.

**Comment by finish06** [comment] 2018-03-27 13:48
Is this plugin going to move to production?

**Comment by fichtner** [comment] 2018-03-27 14:10
It has been for several months in 18.1. :)

**Comment by finish06** [comment] 2018-03-27 14:18
I do not see it in the UI plugins or packages section.  Is it a manual install only?

**Comment by fichtner** [comment] 2018-03-27 14:20
Are you using i386 ? Telegraf only works on amd64:

https://github.com/opnsense/ports/blob/47aa039c8c8f361193e18a636760392971ef57ae/net-mgmt/telegraf/Makefile#L15

**Comment by finish06** [comment] 2018-03-27 14:25
Wow @fichtner I found it.  Completely overlooked it for the last 5 minutes....  Thank you for your patience.

**Comment by fichtner** [comment] 2018-03-27 14:26
Yay, happy to help! :)

**Comment by linuxmail** [comment] 2018-04-13 07:25
hi,

just wanted to say: thanks for the Telegraf plugin ! We check out, if OpnSense is better than Pfsense and Telegraf is a requirement.

**Comment by mimugmail** [comment] 2018-04-13 07:31
If you miss a feature in Telegraf just put it here, normally it's quite easy to add ...

**Comment by jabbas** [comment] 2018-10-20 20:52
Hello - nice to have would be having [[inputs.sensors]] - at least for me.

But in the bigger picture - the ability to add custom stuff.

**Comment by mimugmail** [comment] 2018-10-20 21:42
https://forum.opnsense.org/index.php?topic=9886.msg45127#msg45127

**Comment by jabbas** [comment] 2018-10-22 19:50
@mimugmail That would be cool but for IPMI. i just want to know regular sensors from motherboard. Like it can be shown on the dashboard
