### ISSUE TITLE
Multi WAN DNS Servers

### ISSUE THREAD

**Issue by cmb991** [opnsense/core#3606] opened 2019-07-27 19:08 UTC
https://docs.opnsense.org/manual/how-tos/multiwan.html
Step 3 says System > Settings > General
Assign a DNS server to each Gateway (or two DNS servers)

Well when I put 1.1.1.1 in the box and select my WAN1 connection, it saves the 1.1.1.1 but doesn't save WAN1.  It changes back to none.  Also does this for WAN2.  I've tried different combinations, everything in that drop down just changes back to none.

Bug?

**Comment by mr44er** [comment] 2019-07-28 01:05
Same here during my tests yesterday. There is something going on with gateways, which I can't nail down exactly and leave me scratching my head. https://github.com/opnsense/core/issues/3604

OPNsense 19.7.1-amd64
FreeBSD 11.2-RELEASE-p11-HBSD
LibreSSL 2.9.2

**Comment by AdSchellevis** [comment] 2019-07-28 09:02
The second question in our bug report template is there for a very good reason. 

> 
[-] I have searched the existing issues and I'm convinced that mine is new.


duplicate of https://github.com/opnsense/core/issues/3599

Would you be so kind to use our templates in the future?

**Closed by AdSchellevis** 2019-07-28 09:02 UTC

**Comment by cmb991** [comment] 2019-07-28 15:36
You say this is a duplicate issue without elaborating on the issue.  You referenced another ticket that is also closed.  Where is the master ticket with the issue?  I know a lot of these guys are having issues with gateways in IPv6.   I’m only running IPv4 with all IPv6 settings disabled.

**Comment by AdSchellevis** [comment] 2019-07-28 17:30
@cmb991 I think your reading the wrong issue,  https://github.com/opnsense/core/issues/3599 comes with a patch to solve the save issue.... https://github.com/opnsense/core/issues/3599#issuecomment-515393729

**Comment by cmb991** [comment] 2019-07-28 18:28
Thank you for referring to that.  I did not see there was a patch, only saw Done in 20.1 and thought we had to wait :p
