### ISSUE TITLE
Duplicated gateway_item handling

### ISSUE THREAD

**Issue by Astranox** [opnsense/core#6401] opened 2023-03-06 20:38 UTC
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

Somehow changing the IPv6 gateway address duplicated the `gateway_item` entry in the config file.
I can't reproduce the issue, and the only difference in the resulting file seems to be that the old entry doesn't have a `priority` setting.
Attached is the `gateways` part from the not working config. (`aaaa` marks the old gateway address and `bbbb` the new gateway address, I've only changed IP addresses)

[gw.txt](https://github.com/opnsense/core/files/10902434/gw.txt)

In `/interfaces.php?if=wan` it was possible to select any of the two entries, but when saving the old entry was set.
Contrary to this `/system_gateways.php` only listed the new entry.
I was able to fix it by deleting the new GW_WAN_2 entry, which then showed the old GW_WAN_2 entry in the gateway list, which in turn allowed me to delete the old entry and re-add the new one.

**Describe the solution you like**

As I'm not sure why the duplication happened in the first place I think it would be helpful if all `gateway_item` were shown in the gateway list, even duplicated ones.

**Describe alternatives you considered**

Maybe some warning if there are duplicated `gateway_item` entries?

Thanks!

**Comment by fichtner** [comment] 2023-03-07 15:58
Since it's unclear how the duplication went I'm a bit reluctant to "solve" it. Same entry-gateways are normally not permitted and worst case deleting the newer entry allows you to delete the older one and then start from scratch.

The system isn't very nice in implementational terms but changing it always has risk of regression so this is a larger effort to improve it eventually. But I know that we have #6377 on the roadmap so that might happen.


Cheers,
Franco

**Comment by fichtner** [comment] 2023-03-13 08:59
A bit of work was done here #6406. I'm closing this as a duplicate since it's the same issue.

**Closed by fichtner** 2023-03-13 08:59 UTC
Labels: support
