### ISSUE TITLE
OpenVPN stops working - Cannot open TUN/TAP dev /dev/tun1:Device busy (errno=16)

### ISSUE THREAD

**Issue by vladgitdev** [opnsense/core#6659] opened 2023-07-10 16:27 UTC
**Describe the bug**

OpenVPN stops responding randomly more or less every other day. On the dashboard the service appears stopped and if started (from there) it does not start, with message "Cannot open TUN/TAP dev /dev/tun1: Device busy (errno=16)" on the log file.

My OPNsense box has a cron job programmed to reboot every morning. I don't know if problem is associated with reboots since the problem is not present everyday.

My OPNsense was installed a couple of weeks ago. Current version is OPNsense 23.1.11-amd64.

**To Reproduce**

1 Install OPNsense
2. Program a cron job to reboot every morning.
3. Setup OpenVPN trough wizard
4. Wait a couple of days an check the Dashboard. OpenVPN service will be stop and it wont be possible to start it.

**Expected behavior**

OpenVPN service should start normally upon every reboot.

**Describe alternatives you considered**

Running "sudo pkill -9 openvpn" from the console (somehow as mentioned on https://forum.opnsense.org/index.php?topic=23396.0) let me successfully (re)start the service from "Services" on the dashboard . But the problem reappears a couple of days latter. 

**Screenshots**

**Relevant log files**

2023-07-10T10:09:11-06:00	Warning	openvpn_server1	 Could not determine IPv4/IPv6 protocol. Using AF_INET
2023-07-10T10:09:11-06:00	Warning	openvpn_server1	 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
2023-07-10T10:09:11-06:00	Warning	openvpn_server1	 NOTE: your local LAN uses the extremely common subnet address 192.168.0.x or 192.168.1.x.  Be aware that this might create routing conflicts if you connect to the VPN server from public locations such as internet cafes that use the same subnet.
2023-07-10T10:09:11-06:00	Warning	openvpn_server1	 WARNING: --topology net30 support for server configs with IPv4 pools will be removed in a future release. Please migrate to --topology subnet as soon as possible.
2023-07-10T10:09:11-06:00	Warning	openvpn_server1	 WARNING: Compression for receiving enabled. Compression has been used in the past to break encryption. Sent packets are not compressed unless "allow-compression yes" is also set.
**2023-07-10T05:11:54-06:00	Error	openvpn_server1	 Cannot open TUN/TAP dev /dev/tun1: Device busy (errno=16)**
2023-07-10T05:11:54-06:00	Warning	openvpn_server1	 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
2023-07-10T05:11:54-06:00	Warning	openvpn_server1	 NOTE: your local LAN uses the extremely common subnet address 192.168.0.x or 192.168.1.x.  Be aware that this might create routing conflicts if you connect to the VPN server from public locations such as internet cafes that use the same subnet.
2023-07-10T05:11:54-06:00	Warning	openvpn_server1	 WARNING: --topology net30 support for server configs with IPv4 pools will be removed in a future release. Please migrate to --topology subnet as soon as possible.
2023-07-10T05:11:54-06:00	Warning	openvpn_server1	 WARNING: Compression for receiving enabled. Compression has been used in the past to break encryption. Sent packets are not compressed unless "allow-compression yes" is also set.
2023-07-10T05:11:54-06:00	Warning	openvpn_server1	 Could not determine IPv4/IPv6 protocol. Using AF_INET
2023-07-10T05:11:54-06:00	Warning	openvpn_server1	 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
2023-07-10T05:11:54-06:00	Warning	openvpn_server1	 NOTE: your local LAN uses the extremely common subnet address 192.168.0.x or 192.168.1.x.  Be aware that this might create routing conflicts if you connect to the VPN server from public locations such as internet cafes that use the same subnet.
2023-07-10T05:11:54-06:00	Warning	openvpn_server1	 WARNING: --topology net30 support for server configs with IPv4 pools will be removed in a future release. Please migrate to --topology subnet as soon as possible.
2023-07-10T05:11:54-06:00	Warning	openvpn_server1	 WARNING: Compression for receiving enabled. Compression has been used in the past to break encryption. Sent packets are not compressed unless "allow-compression yes" is also set.
2023-07-10T05:11:53-06:00	Error	openvpn_server1	 event_wait : Interrupted system call (fd=-1,code=4)
2023-07-10T05:11:51-06:00	Warning	openvpn_server1	 Could not determine IPv4/IPv6 protocol. Using AF_INET
2023-07-10T05:11:51-06:00	Warning	openvpn_server1	 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
2023-07-10T05:11:51-06:00	Warning	openvpn_server1	 NOTE: your local LAN uses the extremely common subnet address 192.168.0.x or 192.168.1.x.  Be aware that this might create routing conflicts if you connect to the VPN server from public locations such as internet cafes that use the same subnet.
2023-07-10T05:11:51-06:00	Warning	openvpn_server1	 WARNING: --topology net30 support for server configs with IPv4 pools will be removed in a future release. Please migrate to --topology subnet as soon as possible.
2023-07-10T05:11:51-06:00	Warning	openvpn_server1	 WARNING: Compression for receiving enabled. Compression has been used in the past to break encryption. Sent packets are not compressed unless "allow-compression yes" is also set.

**Additional context**

OPNsense run as virtual machine with pass-trough access to a dual port server NIC.

**Environment**

OPNsense 23.1.11 (amd64, OpenSSL 1.1.1u)
VMware ESXi 8.0.0
2 vCPUs (Intel® Xeon™ Xeon(R) CPU E3-1220V5)
Network Intel® I350 (dual port card, pass-trough over ESXi)

**Comment by marcpopp** [comment] 2023-07-16 14:20
We have the same issue on multiple installations. Will contribute more info as needed.

**Comment by undone37** [comment] 2023-07-21 10:12
I can confirm this problem. `killall openvpn` and restarting the service in the GUI fixes the problem for me.
I am getting `Cannot open TUN/TAP dev /dev/tun4: Device busy (errno=16)` in the logs.
This error occurs for all configured OpenVPN clients after a reboot.

**Comment by AdSchellevis** [comment] 2023-07-21 13:36
logs might help, also relevant to know which openvpn processes are active before killing anything and if there are plugins being used that might try to steal the same tun (like wireguard).

**Comment by vladgitdev** [comment] 2023-07-21 17:27
Ok. This is my today's openvpn log, since auto restart (around 5:11 am) and up to kill of the service and manual restart of it on the web UI:

[openvpn_20230721.log](https://github.com/opnsense/core/files/12130918/openvpn_20230721.log)

As mentioned before, the action of killing the active openvpn process and restarting the services, fixes the problem until the next restart. Prior killing the service, the only running opnvpn services was:

root          65381   0.0  0.2 18136  7016  -  Ss   05:11     0:00.04 /usr/local/sbin/openvpn --config /var/etc/openvpn/server1.conf

WireGuard plugin not installed on my OPNsense box. I don't see other processes that can be using the same /dev/tun1 device

**Comment by AdSchellevis** [comment] 2023-07-23 14:17
I don't think the process in question really complained about the device being busy:

```
<28>1 2023-07-21T05:11:54-06:00 QHQ.quest.intranet openvpn_server1 65381 - [meta sequenceId="25"] NOTE: your local LAN uses the extremely common subnet address 192.168.0.x or 192.168.1.x.  Be aware that this might create routing conflicts if you connect to the VPN server from public locations such as internet cafes that use the same subnet.
<28>1 2023-07-21T05:11:54-06:00 QHQ.quest.intranet openvpn_server1 65381 - [meta sequenceId="26"] NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
<29>1 2023-07-21T05:11:54-06:00 QHQ.quest.intranet openvpn_server1 65381 - [meta sequenceId="27"] TUN/TAP device ovpns1 exists previously, keep at program end
<29>1 2023-07-21T05:11:54-06:00 QHQ.quest.intranet openvpn_server1 65381 - [meta sequenceId="28"] TUN/TAP device /dev/tun1 opened
<29>1 2023-07-21T05:11:54-06:00 QHQ.quest.intranet openvpn_server1 65381 - [meta sequenceId="29"] /sbin/ifconfig ovpns1 10.17.0.1 10.17.0.2 mtu 1500 netmask 255.255.255.255 up
<29>1 2023-07-21T05:11:54-06:00 QHQ.quest.intranet openvpn_server1 65381 - [meta sequenceId="30"] /usr/local/etc/inc/plugins.inc.d/openvpn/ovpn-linkup ovpns1 1500 0 10.17.0.1 10.17.0.2 init
<28>1 2023-07-21T05:11:54-06:00 QHQ.quest.intranet openvpn_server1 65381 - [meta sequenceId="41"] Could not determine IPv4/IPv6 protocol. Using AF_INET
<29>1 2023-07-21T05:11:54-06:00 QHQ.quest.intranet openvpn_server1 65381 - [meta sequenceId="42"] UDPv4 link local (bound): [AF_INET]192.168.1.64:1194
<29>1 2023-07-21T05:11:54-06:00 QHQ.quest.intranet openvpn_server1 65381 - [meta sequenceId="43"] UDPv4 link remote: [AF_UNSPEC]
<29>1 2023-07-21T05:11:54-06:00 QHQ.quest.intranet openvpn_server1 65381 - [meta sequenceId="44"] Initialization Sequence Completed
<27>1 2023-07-21T05:14:14-06:00 QHQ.quest.intranet openvpn_server1 65381 - [meta sequenceId="1"] TLS Error: cannot locate HMAC in incoming packet from [AF_INET]x.x.x.x:44397
<27>1 2023-07-21T05:40:31-06:00 QHQ.quest.intranet openvpn_server1 65381 - [meta sequenceId="1"] TLS Error: cannot locate HMAC in incoming packet from [AF_INET]x.x.x.x:36137
<27>1 2023-07-21T11:06:51-06:00 QHQ.quest.intranet openvpn_server1 65381 - [meta sequenceId="1"] event_wait : Interrupted system call (fd=-1,code=4)
<29>1 2023-07-21T11:06:51-06:00 QHQ.quest.intranet openvpn_server1 65381 - [meta sequenceId="2"] /sbin/ifconfig ovpns1 10.17.0.1 -alias
<29>1 2023-07-21T11:06:51-06:00 QHQ.quest.intranet openvpn_server1 65381 - [meta sequenceId="3"] /usr/local/etc/inc/plugins.inc.d/openvpn/ovpn-linkdown ovpns1 1500 0 10.17.0.1 10.17.0.2 init
<29>1 2023-07-21T11:06:51-06:00 QHQ.quest.intranet openvpn_server1 65381 - [meta sequenceId="4"] SIGTERM[hard,] received, process exiting
```
Strange thing is that another process was trying to start and did complain (about the fact that `65381` was active):

```
<27>1 2023-07-21T05:11:54-06:00 QHQ.quest.intranet openvpn_server1 69884 - [meta sequenceId="39"] Cannot open TUN/TAP dev /dev/tun1: Device busy (errno=16)
````

The real question is, why did the server try to start twice. If it booted around 5:00, it almost looks like someone is trying to hook a start manually (custom script perhaps?).  The extra start probably did kill the original server, I just don't think the server is started twice from our end (a client might react to an interface event, servers are skipped if I'm not mistaken).

**Comment by vladgitdev** [comment] 2023-07-28 16:00
Hello @AdSchellevis. Thank you for looking for us into this problem.

Indeed it is strange that there is a second OpenVPN process. I didn't have any custom scripts at that point. Now I have one custom script that kills all openvpn processes, waits a few seconds and starts the service. I set up a cron job that runs it 5 minutes after the daily reboot and, since 4 days ago that I implemented it, I haven't had problems with OpenVPN not being started (actually, the problem is still present on the log for some days, but the cron job that runs my custom script has been taking care of the problem). 

In case it is useful to someone, this is what I did:

##1.  Create directory /usr/local/opnsense/scripts/OPNsense/openvpn-restart and, inside, file rc-wrapper.sh with the following content (I copied it and adapted from another existing script):
```
#!/bin/sh

case "$1" in
stop)
    ;;
reload)
    ;;
restart)
    killall openvpn
    sleep 3
    /usr/local/sbin/openvpn --config /var/etc/openvpn/server1.conf
esac
```

##2.  Create file /usr/local/opnsense/service/conf/actions.d/actions_openvpn-restart.conf with the following content:
```
[restart]
command:/usr/local/opnsense/scripts/OPNsense/openvpn-restart/rc-wrapper.sh restart
parameters:
type:script
description:Restart OpenVPN service
message:restarting openvpn
```

##3.   Restart configd:
`service configd restart`

##4. Create a cron job (on the web ui System/Settings/Cron with the "+" button) with command "Restart OpenVPN service" (the command added above) and set it to run a few minutes after the programmed daily reboot.

Probably not the cleanest solution but it is doing the trick for me for now.

**Comment by AdSchellevis** [comment] 2023-07-29 08:30
It might be an option to try again on 23.7 using the new instances option, if it's locking related, it might react differently.

**Comment by PatrickBeuthling** [comment] 2023-09-18 18:17
Hi, i have a issue that feels related.  
Since around Aug 28, one of the two openvpn tunnels(always the same one) on my opnsens box breaks about once a week.  
At least the last time and today i could observe the same `Cannot open TUN/TAP dev /dev/tun1: Device busy (errno=16)` message in the logs.  
There was still a openvpn process running with server1.conf even though the service was marked as stopped in the dashboard.  
Killing this exact process and starting the service via the dashboard got the tunnel back up.

I attach two logs one from yesterday and one from today. Yesterday everything was working fine, today the tunnel was not working.

[openvpn_20230917.log](https://github.com/opnsense/core/files/12651959/openvpn_20230917.log)
[openvpn_20230918.log](https://github.com/opnsense/core/files/12651961/openvpn_20230918.log)

At 1:59 every morning a have a WAN reconnect which might be important.

**Comment by fichtner** [comment] 2023-09-18 18:36
May be https://github.com/opnsense/core/issues/6861 / d29e65dd0, use:

    # opnsense-patch d29e65dd0


Cheers,
Franco

**Comment by PatrickBeuthling** [comment] 2023-09-18 18:44
Thanks, ill give it a go and let you know if it broke again in a few days.

**Comment by PatrickBeuthling** [comment] 2023-10-17 18:34
Just to give you an update, i did not encounter any issue anymore after applying the patch.

**Closed** 2023-10-18 03:11 UTC
Labels: support

**Comment by hansfranz456** [comment] 2023-10-18 15:25
I have exactly this issue with most recent version of opnsense.
Seems thet this problem is not solved.
Made all updates, reboot, still there.
