### ISSUE TITLE
[17.1.6] DHCPv6 Client bug

### ISSUE THREAD

**Issue by djGrrr** [opnsense/core#1629] opened 2017-05-08 14:52 UTC
Sometimes when you reconfigure an interface with DHCPv6 setup, the dhcp6c process seems to completely ignore the server responses, sometimes for a short period, and sometimes forever, until you reboot. I have attached the logs and a tcpdump of the packets.

```
**New dhcp6c process starts here, and ignores the advertise responses from the server**
May  8 11:47:13 OPNsense-test dhcp6c[63515]: Sending Solicit
May  8 11:47:13 OPNsense-test dhcp6c[63515]: set client ID (len 14)
May  8 11:47:13 OPNsense-test dhcp6c[63515]: set identity association
May  8 11:47:13 OPNsense-test dhcp6c[63515]: set elapsed time (len 2)
May  8 11:47:13 OPNsense-test dhcp6c[63515]: set option request (len 4)
May  8 11:47:13 OPNsense-test dhcp6c[63515]: set IA_PD
May  8 11:47:13 OPNsense-test dhcp6c[63515]: send solicit to ff02::1:2%vtnet0
May  8 11:47:13 OPNsense-test dhcp6c[63515]: reset a timer on vtnet0, state=SOLICIT, timeo=2, retrans=3982
May  8 11:47:17 OPNsense-test dhcp6c[63515]: Sending Solicit
May  8 11:47:17 OPNsense-test dhcp6c[63515]: set client ID (len 14)
May  8 11:47:17 OPNsense-test dhcp6c[63515]: set identity association
May  8 11:47:17 OPNsense-test dhcp6c[63515]: set elapsed time (len 2)
May  8 11:47:17 OPNsense-test dhcp6c[63515]: set option request (len 4)
May  8 11:47:17 OPNsense-test dhcp6c[63515]: set IA_PD
May  8 11:47:17 OPNsense-test dhcp6c[63515]: send solicit to ff02::1:2%vtnet0
May  8 11:47:17 OPNsense-test dhcp6c[63515]: reset a timer on vtnet0, state=SOLICIT, timeo=3, retrans=8065
May  8 11:47:25 OPNsense-test dhcp6c[63515]: Sending Solicit
May  8 11:47:25 OPNsense-test dhcp6c[63515]: set client ID (len 14)
May  8 11:47:25 OPNsense-test dhcp6c[63515]: set identity association
May  8 11:47:25 OPNsense-test dhcp6c[63515]: set elapsed time (len 2)
May  8 11:47:25 OPNsense-test dhcp6c[63515]: set option request (len 4)
May  8 11:47:25 OPNsense-test dhcp6c[63515]: set IA_PD
May  8 11:47:25 OPNsense-test dhcp6c[63515]: send solicit to ff02::1:2%vtnet0
May  8 11:47:25 OPNsense-test dhcp6c[63515]: reset a timer on vtnet0, state=SOLICIT, timeo=4, retrans=16326
May  8 11:47:41 OPNsense-test dhcp6c[63515]: Sending Solicit
May  8 11:47:41 OPNsense-test dhcp6c[63515]: set client ID (len 14)
May  8 11:47:41 OPNsense-test dhcp6c[63515]: set identity association
May  8 11:47:41 OPNsense-test dhcp6c[63515]: set elapsed time (len 2)
May  8 11:47:41 OPNsense-test dhcp6c[63515]: set option request (len 4)
May  8 11:47:41 OPNsense-test dhcp6c[63515]: set IA_PD
May  8 11:47:41 OPNsense-test dhcp6c[63515]: send solicit to ff02::1:2%vtnet0
May  8 11:47:41 OPNsense-test dhcp6c[63515]: reset a timer on vtnet0, state=SOLICIT, timeo=5, retrans=31928

**New dhcp6c process stops ignoring the server responses**
May  8 11:48:13 OPNsense-test dhcp6c[63515]: Sending Solicit
May  8 11:48:13 OPNsense-test dhcp6c[63515]: set client ID (len 14)
May  8 11:48:13 OPNsense-test dhcp6c[63515]: set identity association
May  8 11:48:13 OPNsense-test dhcp6c[63515]: set elapsed time (len 2)
May  8 11:48:13 OPNsense-test dhcp6c[63515]: set option request (len 4)
May  8 11:48:13 OPNsense-test dhcp6c[63515]: set IA_PD
May  8 11:48:13 OPNsense-test dhcp6c[63515]: send solicit to ff02::1:2%vtnet0
May  8 11:48:13 OPNsense-test dhcp6c[63515]: reset a timer on vtnet0, state=SOLICIT, timeo=6, retrans=64469
May  8 11:48:13 OPNsense-test dhcp6c[63515]: receive advertise from fe80::ec4:7aff:fe69:fefa%vtnet0 on vtnet0
May  8 11:48:13 OPNsense-test dhcp6c[63515]: get DHCP option identity association, len 40
May  8 11:48:13 OPNsense-test dhcp6c[63515]:   IA_NA: ID=0, T1=0, T2=0
May  8 11:48:13 OPNsense-test dhcp6c[63515]: get DHCP option IA address, len 24
May  8 11:48:13 OPNsense-test dhcp6c[63515]:   IA_NA address: 2001:470:x:x:e5ca:f39e:27ef:9932 pltime=4500 vltime=7200
May  8 11:48:13 OPNsense-test dhcp6c[63515]: get DHCP option IA_PD, len 41
May  8 11:48:13 OPNsense-test dhcp6c[63515]:   IA_PD: ID=0, T1=0, T2=0
May  8 11:48:13 OPNsense-test dhcp6c[63515]: get DHCP option IA_PD prefix, len 25
May  8 11:48:13 OPNsense-test dhcp6c[63515]:   IA_PD prefix: 2001:470:x:x::/60 pltime=4500 vltime=109770774158368
May  8 11:48:13 OPNsense-test dhcp6c[63515]: get DHCP option client ID, len 14
May  8 11:48:13 OPNsense-test dhcp6c[63515]:   DUID: 00:01:00:01:20:37:5e:d7:52:54:00:63:91:36
May  8 11:48:13 OPNsense-test dhcp6c[63515]: get DHCP option server ID, len 14
May  8 11:48:13 OPNsense-test dhcp6c[63515]:   DUID: 00:01:00:01:1f:fc:3c:71:0c:c4:7a:69:fe:f9
May  8 11:48:13 OPNsense-test dhcp6c[63515]: get DHCP option DNS, len 16
May  8 11:48:13 OPNsense-test dhcp6c[63515]: server ID: 00:01:00:01:1f:fc:3c:71:0c:c4:7a:69:fe:f9, pref=-1
May  8 11:48:13 OPNsense-test dhcp6c[63515]: reset timer for vtnet0 to 0.998642
May  8 11:48:14 OPNsense-test dhcp6c[63515]: picked a server (ID: 00:01:00:01:1f:fc:3c:71:0c:c4:7a:69:fe:f9)
May  8 11:48:14 OPNsense-test dhcp6c[63515]: Sending Request
May  8 11:48:14 OPNsense-test dhcp6c[63515]: a new XID (5ed13a) is generated
May  8 11:48:14 OPNsense-test dhcp6c[63515]: set client ID (len 14)
May  8 11:48:14 OPNsense-test dhcp6c[63515]: set server ID (len 14)
May  8 11:48:14 OPNsense-test dhcp6c[63515]: set IA address
May  8 11:48:14 OPNsense-test dhcp6c[63515]: set identity association
May  8 11:48:14 OPNsense-test dhcp6c[63515]: set elapsed time (len 2)
May  8 11:48:14 OPNsense-test dhcp6c[63515]: set option request (len 4)
May  8 11:48:14 OPNsense-test dhcp6c[63515]: set IA_PD prefix
May  8 11:48:14 OPNsense-test dhcp6c[63515]: set IA_PD
May  8 11:48:14 OPNsense-test dhcp6c[63515]: send request to ff02::1:2%vtnet0
May  8 11:48:14 OPNsense-test dhcp6c[63515]: reset a timer on vtnet0, state=REQUEST, timeo=0, retrans=991
May  8 11:48:14 OPNsense-test dhcp6c[63515]: receive reply from fe80::ec4:7aff:fe69:fefa%vtnet0 on vtnet0
May  8 11:48:14 OPNsense-test dhcp6c[63515]: get DHCP option identity association, len 40
May  8 11:48:14 OPNsense-test dhcp6c[63515]:   IA_NA: ID=0, T1=0, T2=0
May  8 11:48:14 OPNsense-test dhcp6c[63515]: get DHCP option IA address, len 24
May  8 11:48:14 OPNsense-test dhcp6c[63515]:   IA_NA address: 2001:470:x:x:e5ca:f39e:27ef:9932 pltime=4500 vltime=7200
May  8 11:48:14 OPNsense-test dhcp6c[63515]: get DHCP option IA_PD, len 41
May  8 11:48:14 OPNsense-test dhcp6c[63515]:   IA_PD: ID=0, T1=0, T2=0
May  8 11:48:14 OPNsense-test dhcp6c[63515]: get DHCP option IA_PD prefix, len 25
May  8 11:48:14 OPNsense-test dhcp6c[63515]:   IA_PD prefix: 2001:470:x:x::/60 pltime=4500 vltime=7200
May  8 11:48:14 OPNsense-test dhcp6c[63515]: get DHCP option client ID, len 14
May  8 11:48:14 OPNsense-test dhcp6c[63515]:   DUID: 00:01:00:01:20:37:5e:d7:52:54:00:63:91:36
May  8 11:48:14 OPNsense-test dhcp6c[63515]: get DHCP option server ID, len 14
May  8 11:48:14 OPNsense-test dhcp6c[63515]:   DUID: 00:01:00:01:1f:fc:3c:71:0c:c4:7a:69:fe:f9
May  8 11:48:14 OPNsense-test dhcp6c[63515]: get DHCP option DNS, len 16
May  8 11:48:14 OPNsense-test dhcp6c[63515]: dhcp6c Received REQUEST
May  8 11:48:14 OPNsense-test dhcp6c[63515]: nameserver[0] 2001:470:x:x::1
May  8 11:48:14 OPNsense-test dhcp6c[63515]: make an IA: PD-0
May  8 11:48:14 OPNsense-test dhcp6c[63515]: create a prefix 2001:470:xx::/60 pltime=109770774155668, vltime=7200
May  8 11:48:14 OPNsense-test dhcp6c[63515]: add an address 2001:470:x:x:5054:ff:febc:a290/64 on vtnet1
May  8 11:48:14 OPNsense-test dhcp6c[63515]: T1(2250) and/or T2(3600) is locally determined
May  8 11:48:14 OPNsense-test dhcp6c[63515]: make an IA: NA-0
May  8 11:48:14 OPNsense-test dhcp6c[63515]: create an address 2001:470:x:x:e5ca:f39e:27ef:9932 pltime=4500, vltime=6151109130330315808
May  8 11:48:14 OPNsense-test dhcp6c[63515]: add an address 2001:470:x:x:e5ca:f39e:27ef:9932/128 on vtnet0
May  8 11:48:14 OPNsense-test dhcp6c[63515]: T1(2250) and/or T2(3600) is locally determined
May  8 11:48:14 OPNsense-test dhcp6c[63515]: executes /var/etc/dhcp6c_wan_script.sh
May  8 11:48:16 OPNsense-test dhcp6c[63515]: script "/var/etc/dhcp6c_wan_script.sh" terminated
May  8 11:48:16 OPNsense-test dhcp6c[63515]: removing an event on vtnet0, state=REQUEST
May  8 11:48:16 OPNsense-test dhcp6c[63515]: removing server (ID: 00:01:00:01:1f:fc:3c:71:0c:c4:7a:69:fe:f9)
May  8 11:48:16 OPNsense-test dhcp6c[63515]: got an expected reply, sleeping.
```

```
**Old dhcp6c process shutting down, releases previous leases**
11:47:02.304562 IP6 fe80::5054:ff:fe63:9136.546 > ff02::1:2.547: dhcp6 release
11:47:02.304840 IP6 fe80::5054:ff:fe63:9136.546 > ff02::1:2.547: dhcp6 release
11:47:02.305059 IP6 fe80::ec4:7aff:fe69:fefa.547 > fe80::5054:ff:fe63:9136.546: dhcp6 reply
11:47:02.305302 IP6 fe80::ec4:7aff:fe69:fefa.547 > fe80::5054:ff:fe63:9136.546: dhcp6 reply
11:47:03.891323 IP6 fe80::5054:ff:fe63:9136.546 > ff02::1:2.547: dhcp6 release
11:47:03.891700 IP6 fe80::ec4:7aff:fe69:fefa.547 > fe80::5054:ff:fe63:9136.546: dhcp6 reply

**New dhcp6c process starts here, and ignores the advertise responses from the server**
11:47:09.898247 IP6 fe80::5054:ff:fe63:9136.546 > ff02::1:2.547: dhcp6 solicit
11:47:09.898630 IP6 fe80::ec4:7aff:fe69:fefa.547 > fe80::5054:ff:fe63:9136.546: dhcp6 advertise
11:47:11.007249 IP6 fe80::5054:ff:fe63:9136.546 > ff02::1:2.547: dhcp6 solicit
11:47:11.007692 IP6 fe80::ec4:7aff:fe69:fefa.547 > fe80::5054:ff:fe63:9136.546: dhcp6 advertise
11:47:13.096186 IP6 fe80::5054:ff:fe63:9136.546 > ff02::1:2.547: dhcp6 solicit
11:47:13.096613 IP6 fe80::ec4:7aff:fe69:fefa.547 > fe80::5054:ff:fe63:9136.546: dhcp6 advertise
11:47:17.098762 IP6 fe80::5054:ff:fe63:9136.546 > ff02::1:2.547: dhcp6 solicit
11:47:17.099223 IP6 fe80::ec4:7aff:fe69:fefa.547 > fe80::5054:ff:fe63:9136.546: dhcp6 advertise
11:47:25.177256 IP6 fe80::5054:ff:fe63:9136.546 > ff02::1:2.547: dhcp6 solicit
11:47:25.177689 IP6 fe80::ec4:7aff:fe69:fefa.547 > fe80::5054:ff:fe63:9136.546: dhcp6 advertise
11:47:41.508370 IP6 fe80::5054:ff:fe63:9136.546 > ff02::1:2.547: dhcp6 solicit
11:47:41.508849 IP6 fe80::ec4:7aff:fe69:fefa.547 > fe80::5054:ff:fe63:9136.546: dhcp6 advertise

**New dhcp6c process stops ignoring the server responses**
11:48:13.436172 IP6 fe80::5054:ff:fe63:9136.546 > ff02::1:2.547: dhcp6 solicit
11:48:13.436615 IP6 fe80::ec4:7aff:fe69:fefa.547 > fe80::5054:ff:fe63:9136.546: dhcp6 advertise
11:48:14.448199 IP6 fe80::5054:ff:fe63:9136.546 > ff02::1:2.547: dhcp6 request
11:48:14.448746 IP6 fe80::ec4:7aff:fe69:fefa.547 > fe80::5054:ff:fe63:9136.546: dhcp6 reply
```
The client solicit's for a DHCPv6 server, the server responds with an advertise response, and the client proceeds to ignore it. When the client actually starts to work after some time (often fails forever), it replys to the next advertise with the request, and the server replies.

The proper order of things is:
Client sends SOLICIT
Server responds with ADVERTISE
Client respond with REQUEST
Server responds with REPLY
Client configures with information from the REPLY

As you can see from the dhcp6c log from above, the Client seemingly does not even see the ADVERTISE packets from the server and it only shows up once it starts working properly.

I have verified with tcpdump that all packets are seen by the client OPNsense as well as from the main OPNsense.

**Comment by fichtner** [comment] 2017-05-11 20:34
@djGrrr you should really try master, it's gotten a lot better :)

**Comment by Space2Man** [comment] 2017-06-02 10:59
@djGrrr please check with

`sockstat -l | grep :546` 

if other processes are listening on udp6 port 546 as well ...

**Comment by ldldr** [comment] 2017-07-20 09:57
@djGrrr I can confirm your findings. dhcp6c sends SOLICIT but does not respond to the server's ADVERTISE response. I verified that dhcp6c is listening:
```
# sockstat -l | grep :546
root     sleep      96345 7  udp6   *:546                 *:*
root     dhcp6c     35111 8  udp6   *:546                 *:*
root     sh         87133 7  udp6   *:546                 *:*
```

It seems that the DHCP clients available for FreeBSD are broken in one way or another: https://forums.freebsd.org/threads/60168/

Here is a bug of dhcp6c listening on port 31220 instead of 546:
```
tcpdump -i igb2 -vvvn ip6
12:40:04.052260 IP6 (hlim 1, next-header UDP (17) payload length: 36) fe80::ec4:7aff:fe7f:8412.31220 > ff02::1:2.547: [bad udp cksum 0x0a12 -> 0x3a6c!] dhcp6 solicit (xid=35e04e (client-ID hwaddr/time type 1 time 553595220 0cc47a7f8410) (elapsed-time 65535))
12:40:04.057053 IP6 (hlim 64, next-header UDP (17) payload length: 178) fe80::3a10:d5ff:fe6f:291f.547 > fe80::ec4:7aff:fe7f:8412.31220: [udp sum ok] dhcp6 advertise (xid=35e04e (client-ID hwaddr/time type 1 time 553595220 0cc47a7f8410) (server-ID hwaddr type 1 3810d56f291f) (preference 0) (DNS-server fd00::3a10:d5ff:fe6f:291f) (opt_86) (IA_NA IAID:1 T1:1800 T2:2880 (IA_ADDR 2003:5c:xxxx:xxxx:ec4:7aff:fe7f:8412 pltime:3600 vltime:7200)) (IA_PD IAID:1 T1:1800 T2:2880 (IA_PD-prefix 2003:5c:xxxx:xxxx::/62 pltime:3600 vltime:7200)))
```
I killed that specific dhcp6c process but each time I restarted dhcp6c it bound to the wrong port again. Only a reboot fixed this and I haven't observed this issue since. How weird!

I tried dual-dhclient instead of dhcp6c and it always works as supposed:
```
# dual-dhclient -P -d igb2                                                                                 [20/9463]
Internet Systems Consortium DHCP Client 4.3.5
Copyright 2004-2016 Internet Systems Consortium.
All rights reserved.
For info, please visit https://www.isc.org/software/dhcp/

Listening on Socket/igb2
Sending on   Socket/igb2
Created duid "\000\001\000\001!\003'H\014\304z\177\204\022".
PRC: Soliciting for leases (INIT).
XMT: Forming Solicit, 0 ms elapsed.
XMT:  X-- IA_PD 7a:7f:84:12
XMT:  | X-- Request renew in  +3600
XMT:  | X-- Request rebind in +5400
XMT: Solicit on igb2, interval 1060ms.
RCV: Advertise message on igb2 from fe80::3a10:d5ff:fe6f:291f.
RCV:  X-- Preference 0.
RCV:  X-- IA_PD 7a:7f:84:12
RCV:  | X-- starts 1500539593
RCV:  | X-- t1 - renew  +1800
RCV:  | X-- t2 - rebind +2880
RCV:  | X-- [Options]
RCV:  | | X-- IAPREFIX 2003:5c:xxxx:xxxx::/62
RCV:  | | | X-- Preferred lifetime 3600.
RCV:  | | | X-- Max lifetime 7200.
RCV:  X-- Server ID: 00:03:00:01:38:10:d5:6f:29:1f
RCV:  Advertisement recorded.
PRC: Selecting best advertised lease.
PRC: Considering best lease.
PRC:  X-- Initial candidate 00:03:00:01:38:10:d5:6f:29:1f (s: 10104, p: 0).
XMT: Forming Request, 0 ms elapsed.
XMT:  X-- IA_PD 7a:7f:84:12
XMT:  | X-- Requested renew  +3600
XMT:  | X-- Requested rebind +5400
XMT:  | | X-- IAPREFIX 2003:5c:xxxx:xxxx::/62
XMT:  | | | X-- Preferred lifetime +7200
XMT:  | | | X-- Max lifetime +7500
XMT:  V IA_PD appended.
XMT: Request on igb2, interval 1080ms.
RCV: Reply message on igb2 from fe80::3a10:d5ff:fe6f:291f.
RCV:  X-- Preference 0.
RCV:  X-- IA_PD 7a:7f:84:12
RCV:  | X-- starts 1500539594
RCV:  | X-- t1 - renew  +1800
RCV:  | X-- t2 - rebind +2880
RCV:  | X-- [Options]
RCV:  | | X-- IAPREFIX 2003:5c:xxxx:xxxx::/62
RCV:  | | | X-- Preferred lifetime 3600.
RCV:  | | | X-- Max lifetime 7200.
RCV:  X-- Server ID: 00:03:00:01:38:10:d5:6f:29:1f
PRC: Bound to lease 00:03:00:01:38:10:d5:6f:29:1f.
Prefix BOUND6 old= new=2003:5c:xxxx:xxxx::/62
PRC: Renewal event scheduled in 1800 seconds, to run for 1080 seconds.
PRC: Depreference scheduled in 3600 seconds.
PRC: Expiration scheduled in 7200 seconds.
```

```
# tcpdump -i igb2 -vvvn ip6
10:33:13.761497 IP6 (hlim 1, next-header UDP (17) payload length: 60) fe80::ec4:7aff:fe7f:8412.546 > ff02::1:2.547: [udp sum ok] dhcp6 solicit (xid=3bdc8e (client-ID hwaddr/time type 1 time 553854792 0cc47a7f8412) (option-request DNS-server DNS-search-list) (elapsed-time 0) (IA_PD IAID:2055177234 T1:3600 T2:5400))
10:33:13.767142 IP6 (hlim 64, next-header UDP (17) payload length: 134) fe80::3a10:d5ff:fe6f:291f.547 > fe80::ec4:7aff:fe7f:8412.546: [udp sum ok] dhcp6 advertise (xid=3bdc8e (client-ID hwaddr/time type 1 time 553854792 0cc47a7f8412) (server-ID hwaddr type 1 3810d56f291f) (preference 0) (DNS-server fd00::3a10:d5ff:fe6f:291f) (opt_86) (IA_PD IAID:2055177234 T1:1800 T2:2880 (IA_PD-prefix 2003:5c:xxxx:xxxx::/62 pltime:3600 vltime:7200)))
10:33:14.823601 IP6 (hlim 1, next-header UDP (17) payload length: 103) fe80::ec4:7aff:fe7f:8412.546 > ff02::1:2.547: [udp sum ok] dhcp6 request (xid=6b5d58 (client-ID hwaddr/time type 1 time 553854792 0cc47a7f8412) (server-ID hwaddr type 1 3810d56f291f) (option-request DNS-server DNS-search-list) (elapsed-time 0) (IA_PD IAID:2055177234 T1:3600 T2:5400 (IA_PD-prefix 2003:5c:xxxx:xxxx::/62 pltime:7200 vltime:7500)))
10:33:14.835308 IP6 (hlim 64, next-header UDP (17) payload length: 134) fe80::3a10:d5ff:fe6f:291f.547 > fe80::ec4:7aff:fe7f:8412.546: [udp sum ok] dhcp6 reply (xid=6b5d58 (client-ID hwaddr/time type 1 time 553854792 0cc47a7f8412) (server-ID hwaddr type 1 3810d56f291f) (preference 0) (DNS-server fd00::3a10:d5ff:fe6f:291f) (opt_86) (IA_PD IAID:2055177234 T1:1800 T2:2880 (IA_PD-prefix 2003:5c:xxxx:xxxx::/62 pltime:3600 vltime:7200)))
```

Another thing I observed ist that the dhcp6 solicits from dual-dhclient (1st) differ dhcp6c (2nd line):
```
10:33:13.761497 IP6 (hlim 1, next-header UDP (17) payload length: 60) fe80::ec4:7aff:fe7f:8412.546 > ff02::1:2.547: [udp sum ok] dhcp6 solicit (xid=3bdc8e (client-ID hwaddr/time type 1 time 553854792 0cc47a7f8412) (option-request DNS-server DNS-search-list) (elapsed-time 0) (IA_PD IAID:2055177234 T1:3600 T2:5400))
10:31:23.603245 IP6 (hlim 1, next-header UDP (17) payload length: 36) fe80::ec4:7aff:fe7f:8412.546 > ff02::1:2.547: [udp sum ok] dhcp6 solicit (xid=cb1870 (client-ID hwaddr/time type 1 time 553595220 0cc47a7f8410) (elapsed-time 65535))
```
I think dhcp6 should request the prefix assignment explicitly by including an IA_PA in the solicit including an IAID so that the server responds with the corresponding IAID. For example my `/var/etc/dhcp6c_opt1.conf` looks like this:
```
interface igb2 {
        script "/var/etc/dhcp6c_opt1_script.sh";
};
```
And probably should:
```
interface igb2 {
        send ia-pd 42;
        script "/var/etc/dhcp6c_opt1_script.sh";
};
id-assoc pd 42 { };
```

Question: what is the purpose of `/usr/local/etc/rc.newwanipv6`? It logs this:
```
09:41:57 /usr/local/etc/rc.newwanipv6: rc.newwanipv6: Informational is starting igb2.
09:41:57 /usr/local/etc/rc.newwanipv6: rc.newwanipv6: on (IP address: fe80::ec4:7aff:fe7f:8412) (interface: opt1) (real interface: igb2).
09:41:58 /usr/local/etc/rc.newwanipv6: Removing static route for monitor xxx.xxx.xxx.xxx via xxx.xxx.xxx.xxx
09:41:58 /usr/local/etc/rc.newwanipv6: Adding static route for monitor xxx.xxx.xxx.xxx via xxx.xxx.xxx.xxx
09:41:58 /usr/local/etc/rc.newwanipv6: The command '/sbin/ifconfig igb2 inet6 :: delete' returned exit code '1', the output was 'ifconfig: ioctl (SIOCDIFADDR): Can't assign requested address'
09:41:58 /usr/local/etc/rc.newwanipv6: Resyncing OpenVPN instances for interface WAN2.
09:41:59 /usr/local/etc/rc.newwanipv6: Default gateway down setting WAN2_DHCP6 as default!
09:41:59 /usr/local/etc/rc.newwanipv6: Could not find IPv6 gateway for interface(opt1).
09:41:59 /usr/local/etc/rc.newwanipv6: Could not find IPv6 gateway for interface(opt1).
09:41:59 /usr/local/etc/rc.newwanipv6: Could not find IPv6 gateway for interface(opt2).
09:41:59 /usr/local/etc/rc.newwanipv6: Could not find IPv6 gateway for interface(opt2).
```
I have two IPv4 gateways both monitoring an external IP. When I reconfigure WAN2 with DHCPv6 and an IPv6 address is assigned to igb2 the route for the monitoring IP is removed and the gateway is dysfunctional (states goes to pending).

**Comment by fichtner** [comment] 2017-07-20 11:49
Patch here: https://github.com/opnsense/core/issues/1668#issuecomment-316668618

Can we close this ticket and continue in the other one?

**Comment by fichtner** [comment] 2017-07-20 18:45
Three positive tests, I'm closing this duplicate.

**Closed by fichtner** 2017-07-20 18:45 UTC
Labels: bug
