### ISSUE TITLE
Source IP Adress is always 0.0.0.0

### ISSUE THREAD

**Issue by nuv-it** [opnsense/core#6200] opened 2022-12-20 12:34 UTC
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

A clear and concise description of what the bug is, including last known working version (if any).

All packets sent by the OPNsense itself through the LAN interface are sent with the source IP 0.0.0.0 instead of the LAN interface IP. The error only affects packets sent by the OPNsense itself everything else works. 
We suspect that the error occurred when upgrading from version 22.4.3 to version 22.10. But we are not 100% sure, because we cannot revert from 22.10 to 22.4. (If this should be possible after all please an info about it).

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

1. Go to Firewall->Log Files->Live View
2. Set "Source is 0.0.0.0".
3. Open a new tab
4. Go to "Interfaces->Diagnostics->Ping
5. Ping a device in LAN
6. the ping is sent with the source IP 0.0.0.0 (Screenshot)

You can also test any other request sent directly from the OPNsense. The source IP is always 0.0.0.0
If an address outside the LAN is pinged, for example 8.8.8.8, the WAN address configured on the OPNsense is used as the source IP.

**Expected behavior**

All packets sent directly from the OPNsense to the LAN get the IP of the LAN interface as source.

**Alternatives**

We have not found any alternatives or workarounds yet.

If applicable, information from log files supporting your claim.

**Additional context**

The reason why this error is a problem at all is that the OPNsense cannot connect to the server via LDAP to authenticate users for the OpenVPN.

**Environment**

OPNsense DEC750EU 22.10-amd64
FreeBSD 13.1-RELEASE-p5
OpenSSL 1.1.1q 5 Jul 2022
AMD Ryzen Embedded V1500B (4 cores, 8 threads)

<img width="1154" alt="OPNsense Error" src="https://user-images.githubusercontent.com/99482193/208667192-1dec7810-c5af-4eb5-9d46-6d6fcf89596b.png">

**Comment by AdSchellevis** [comment] 2022-12-20 12:42
duplicate https://github.com/opnsense/core/issues/6036 let's keep this in the same ticket, closing this one. See my last comment about the routing table (`netstat -nr`) in https://github.com/opnsense/core/issues/6036#issuecomment-1349476393

**Comment by nuv-it** [comment] 2022-12-20 13:57
I apologize, but the two problems are not identical. The problem in the linked ticket is about the WAN and not about the LAN as described in our case. We have already looked at the linked ticket before creating our own. We had already tested the suggested solutions as far as we could and unfortunately it didn't work.

**Comment by AdSchellevis** [comment] 2022-12-20 15:31
They sound similar, but I don't mind keeping this open as well. Same question as in the other ticket maybe relevant here as well (routing table).

**Comment by nuv-it** [comment] 2022-12-21 15:46
I took a closer look at the routes and noticed a similar phenomenon. Unfortunately, I don't have a before and after comparison but the following route is very similar to the route added to AdSchellvi's routing table:

`Internet:`
`Destination        Gateway            Flags     Netif Expire`
`xxx.xxx.xxx.0/24    link#1             U          igb0`
`xxx.xxx.xxx.1       link#1             UHS         lo0`
`xxx.xxx.xxx.10      link#1             UHS        igb0`  <--


My question would be whether I can simply delete this route, since it overlaps with the other route.

**Comment by AdSchellevis** [comment] 2022-12-21 16:37
@nuv-it if possible, I would try to remove the entry and check if it makes a difference. Is this interface configured via dhcp by the way?

**Comment by AdSchellevis** [comment] 2023-02-07 15:30
I had a similar case with @mimugmail yesterday, was able to reproduce and seemed to be caused by default gateway switching. @fichtner added a patch in https://github.com/opnsense/core/commit/0e286b3a34cf366efa88a2616e1e1a0c22b8180c, if the issue returns after 23.1.1 we can always reopen this ticket.

**Closed by AdSchellevis** 2023-02-07 15:30 UTC
Labels: support
