### ISSUE TITLE
IPsec traffic stalling on 20.7

### ISSUE THREAD

**Issue by fraenki** [opnsense/core#4415] opened 2020-10-14 21:17 UTC
**Describe the bug**
After upgrading from 20.1.4 to 20.7.2 IPsec phase 2 tunnels will randomly stall (IKEv1, mode tunnel IPv4). Only restarting strongswan seems to fix this issue (temporarely).

Several other people have reported the same issue on 20.7. More reports, details, hardware specs, etc. are available in the forums:
https://forum.opnsense.org/index.php?topic=18918.0

**To Reproduce**
1. Establish an IPsec tunnel between two physical OPNsense 20.7 boxes
2. It was better reproducable with IKEv2 (at least in my case)
3. Send enough traffic through the tunnel (200-400 MB in my case)
4. The tunnel completely stalls, no traffic gets through

Downgrading to OPNsense 20.1 immediately fixes this issue (according to other reporters in the forum).

However, @mimugmail tried to reproduce this issue on OPNsense virtual machines, but did not succeed unfortunately. So this issue is _probably_ related to specific vendors/hardware or drivers. Until now all reporters were using Intel NICs.

**Expected behavior**
Traffic should get through the IPsec tunnel, it should not stall after transferring a specific amount of data.

**Relevant log files**
When using IKEv2 strongswan is actually able to detect the problem and restart the SA after a while:

```
Sep  8 17:03:05 charon[62985]: 05[IKE] <con5|1> giving up after 10 path probings
Sep  8 17:03:05 charon[62985]: 05[IKE] <con5|1> restarting CHILD_SA con5 
```

Note that with IKEv1 strongswan will still think that the tunnel is active and alive, so with IKEv1 you need to restart strongswan.
Of course, in both cases this does not really help, because the tunnel will get stuck again after very little traffic.

**Additional context**
I've manually built packages for strongswan 5.8.3 and 5.9.0 and tested them on OPNsense 20.7.2, but this did not change anything.

Other reporters and myself tested several different IPsec settings, but this did not change anything (details of the various settings can be found in the Forum). Changing the options in `Interfaces: Settings` did not help either.

**An interesting observation:** when _one_ box was still running OPNsense 20.1 and only the other box was on OPNsense 20.7, this issue did not occur at all. Only after upgrading _both_ boxes to 20.7 we first experienced this issue. Also this issue does not IPsec connections between OPNsense and other firewalls – those are 100% stable. Only OPNsense-to-OPNsense connections are affected.

**Environment**
My setup:
OPNsense 20.7.2 / 20.7.3 (amd64, OpenSSL).
Supermicro A2SDi-2C-HLN4F (Intel C3338 CPU, Intel C3000 NIC)

Other reporters:
Landitec scope7-1510 (Intel Atom C3558)
Supermicro A2SDi-4C-HLN4F (almost the same as mine)

**Comment by sjansen1** [comment] 2020-10-15 14:37
I have the same issues after Updating to 20.7 between two OPNSense systems (KVM + a SuperMicro A2SDi-H-TP4F) using IKEv1 and IKEv2. Tunnel. Connection stall after around 1-2 minutes and i can see no more IPSEC Traffic on the WAN interface. Restarting the IPSEC connection bring it alive again for 1-2 minutes. Another Tunnel between OPNsense (A2SDi-H-TP4F) and Sophos UTM using IKEv1 works without stalls.

I now switched to Zerotier to connect this two OPNsense boxed and it works fine without any stalls.

**Comment by mimugmail** [comment] 2020-10-15 14:42
@sjansen1 which errors do you have in log?

**Comment by sjansen1** [comment] 2020-10-15 14:52
> @sjansen1 which errors do you have in log?

Sadly i cannot provide more information because this issue startet right after release of 20.7 and i had to use an alternative to IPSEC. I had no errors in the main log, ipsec was shown as "up", connection went dead after 1-2 minutes.

Yes i know this is not really helpful, alles this issues startet right after updating both boxed to 20.7 at the same time without any other modification. Reboots or recreating the whole ipsec config didnt help.

**Comment by mimugmail** [comment] 2020-10-15 19:45
I had a call to Landitec and they told me that they dont have any feedback from customers about such a problem and they sold hundreds of those 1510's the last two months. Probably they'll send me two devices so I can try to reproduce.

**Comment by mimugmail** [comment] 2020-10-16 09:02
I set up a real world VPN mesh:

Unit 1: Supermicro Cluster in Munich, 20.7.2
Unit 2: Jetway Appliance (Core i5) in Berlin, 20.7.3
Unit 3: VM on IONOS, KVM, Frankfurt, 20.7.3
Unit 4: VM on VMware, Munich, 20.7.3
Unit 5: Jetway Appliance (Celeron J3600), Munich, 20.7.2

They are full-meshed, so every device has 4 active VPNs. I'll watch the traffic and logs.
On Monday I'll receive a 1510 from Landitec and install it also to the mesh

**Comment by mimugmail** [comment] 2020-10-16 14:02
OK, it took me quite some time to set this up. The Supermicro device has problems pinging via VPN when mangling source address via ping, all other devices don't have these and when I use a device behind the Supermirco everything is fine. Every VPN to every neighbor is currently up and stable. 

I need some more facts:

1. Does traffic in both directions stall, so does a ping from A to B stall but B to A works? 
2. You experience this always with traffic going THROUGH the firewall, correct?

**Comment by mimugmail** [comment] 2020-10-18 05:49
VPN still stable, if anyone wants to join this mesh for testing just ping me.

**Comment by mimugmail** [comment] 2020-10-19 11:02
Just added a scope7 1510 to the VPN and pushed 8GB of traffic over VPN, no problems.
On this test I used default settings and the scope is behind NAT, other side is respond-only (IKEv2).

**Comment by mimugmail** [comment] 2020-10-20 08:35
VPN still stable between all hosts, I'm treating this as "works-for-me".

These were the hardware details of some appliances:

https://bsd-hardware.info/?probe=8088bf7e60
https://bsd-hardware.info/?probe=630ace9406

**Comment by fraenki** [comment] 2020-11-18 15:14
I'll perform new tests when OPNsense 20.7.5 is released.

**Comment by mimugmail** [comment] 2020-11-18 15:21
I'm still testing with equipment and other ppl affected. 
For one case it was reproducable that a new install of 20.7 (compared to an update of 20.1) fixed the issue.

Any chance to test this?

**Comment by fraenki** [comment] 2020-11-18 15:23
Not in my case, these are all-remote machines, I can't risk a reinstallation – the location is 6 hours away.

**Comment by fraenki** [comment] 2020-11-23 23:44
>  For one case it was reproducable that a new install of 20.7 (compared to an update of 20.1) fixed the issue.

I took the risk and reinstalled the primary firewall. However, even after completing this procedure IPsec traffic is stalling.

However, I've noticed one thing: for the reinstallation of firewall A I had to perform a (CARP) failover to firewall B. When firewall B was the master, then the IPsec traffic was _not_ stalling.

That's extremely strange, because they use the same hardware (Supermicro A2SDi-2C-HLN4F) that was purchased on the same date.

I have no idea how to proceed.

**Comment by fraenki** [comment] 2020-12-14 17:12
We have been able to workaround this issue by changing the following setting...
`System: Settings: Miscellaneous -> Hardware acceleration`
...from `AES-NI CPU-based` to `none`. (Be sure to reboot the firewall afterwards.)

It looks like this is either a FreeBSD/HardenedBSD 12.x bug or related to my hardware platform (Intel Atom C3338, "Denverton" SoC) – in any case it was triggered by the upgrade from FreeBSD 11.2 to 12.1.

**Comment by fichtner** [comment] 2020-12-14 17:47
Are you able to test against a FreeBSD 12.1/12.2 kernel?

**Comment by fraenki** [comment] 2020-12-14 18:00
@fichtner Unfortunately not. :-/ The affected firewalls are on a remote location, testing with plain FreeBSD would be too intrusive and risky.

**Comment by fichtner** [comment] 2020-12-14 19:00
Let me run down the commit history for something that might fit in stable/12

**Comment by fichtner** [comment] 2020-12-14 19:00
PS: Thanks so far!

**Comment by fichtner** [comment] 2020-12-20 20:36
@fraenki this might be a candidate? I don't see a lot of fixes in aesni.ko otherwise https://github.com/freebsd/freebsd/commit/32e5af22ed979

**Comment by fichtner** [comment] 2020-12-20 21:25
@fraenki actually it is the only fix in stable/12 for aesni.ko -- I've pulled it in and it will be in 21.1-RC

**Comment by fraenki** [comment] 2020-12-20 21:25
@fichtner Thanks, I'll probably give 21.1-RC a try.

**Comment by sjansen1** [comment] 2021-01-27 10:18
@fraenki any luck with 21.1-RC or R1? i still have daily stalls between several, OPNsense boxes with 20.7.8 (some systems are hardware and some kvm with aesni passtrough).

**Comment by fichtner** [comment] 2021-01-27 10:19
According to ongoing discussion in FreeBSD the issue persists on 12.2 and up.

**Comment by tomiboy78** [comment] 2021-01-31 15:03
The issue is still present in 21.1 .

**Comment by AdSchellevis** [comment] 2021-01-31 15:05
as expected (see note above from @fichtner), this might also be cpu firmware related, we haven't seen issues on our Xeon machines or any of the AMD powered machine we offer.

**Comment by tomiboy78** [comment] 2021-01-31 15:38
We use the opnsense on a vsphere cluster, with Xeon Gold CPUs and EVC Level "Broadwell". Disable or enable the hardware acceleration doesnt help us.

**Comment by AdSchellevis** [comment] 2021-01-31 15:44
in that case your issue likely isn't related to this ticket. You can always try to open a ticket of your own with all relevant details,  this ticket is merely here for tracking purposes (confirmed behaviour in https://github.com/opnsense/core/issues/4415#issuecomment-744582361)

**Comment by sjansen1** [comment] 2021-02-01 11:07
I have this issue every day, this time there are no Atom based Systems involved. Side A ist OPNsense 21.1 in KVM hosted on a AMD EPYC 7702P System (hoster), Side B is a Sophos UTM 9 on a SG230 Appliance. I have two Phase 2 entries for two different subnets successfull established. Parameters on both sides are the same and renewing works fine.

At some point IPSEC just stalls with no more traffic flowing. Phase 1 and Phase 2 is still showed as up on both sides and i see no complains in the logs on both sides. in VPN / IPSec / Status overview the connections is showing as up and i can see both phases established. On the OPNsense console i see subnet of Side B routet to WAN as it should with IPSEC, so routing table looks fine.

To get this issues fixed, i have to press the green arrow on VPN / IPsec/ Statusoverview, then i see the old and new Phase 2 and traffic starts flowing again, after refreshing the page i see only the new phase two entries as it should be.

I have no idea how to debug this issues :(

**Comment by fichtner** [comment] 2021-02-01 12:21
As internally discussed and confirmed by @fraenki there may be an issue with aesni kernel module or certain hardware since FreeBSD 12 and some people in FreeBSD also report this issue on later 12.x versions... So we will close this now and will include an upstream patch when it becomes available.

For everyone else having issues with IPsec it's healthier to assume the issue is new if disabling aesni doesn't help and should be treated as such when no solved issue exist elsewhere. Otherwise, unfortunately, IPsec is pretty difficult to debug and requires proper support channels to be looked at in detail.


Cheers,
Franco

**Closed** 2021-02-01 12:21 UTC
Labels: upstream

**Comment by fraenki** [comment] 2021-02-01 16:24
All affected users may still discuss this on the **forums**:
https://forum.opnsense.org/index.php?topic=18918.0

Be sure to test the **workaround**:
https://github.com/opnsense/core/issues/4415#issuecomment-744582361
