### ISSUE TITLE
dhcpd6 suddently enabled and handing out leases

### ISSUE THREAD

**Issue by kevenwyld** [opnsense/core#4027] opened 2020-04-10 04:50 UTC
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.
#4025 seems to be similar but not quite the same.

**Describe the bug**
The dhcpd6 service was suddenly enabled and handing out leases after the upgrade to 20.1.4.  I had previously configured SLAAC (a long time ago) and don't remember ever having to do anything with the dhcpd6 service since SLAAC was the default (sortof, I think I had to set track interface for both my physical networks).

Some additional weirdness, if I go to the leases section I can now see the leases that have been handed out.  Clicking the "plus" which would normally allow for setting a static lease in a dhcpv6 environment.  If I click cancel I get dropped back to `https://firewall.local/services_dhcpv6.php?if=lan` which shows dhcpv6 on the lan interface is disabled.

I'm guessing this is due to the following:
`interfaces: use primary IPv6 and support VIP tracking`
referring to [this commit](https://github.com/opnsense/core/commit/556aaaa8c7c1e6ff2bbcfc4f9789bcaa88a1d3e0) however I'm definitely not smart enough to figure out how that relates to my issue, if it even does.

It's possible I'm missing some important basic ipv6 knowledge and this isn't actually a bug.  If so I'm sorry for wasting everyone's time.

I will try a revert when I get a little bit more time to see exactly how it behaved before.

P.S.  I'm a home user with not a ton of experience so I'm sorry if something doesn't make sense.  I'm happy to provide more information.

**To Reproduce**
Steps to reproduce dhcpd6 being enabled:
1. Have previously configured IPv6 tracking the wan interface with a prefix delegation size of 60.
2. Have two physical networks each with a unique IPv6 Prefix ID
2. Upgrade 20.1.3 -> 20.1.4
3. Each machine now gets multiple IPv6 addresses, and the dhcpd6 service shows as running in the services widget.

Steps to reproduce the strange progression of GUI pages:
1. Navigate to /status_dhcpv6_leases.php
2. Click the "plus" on one of the active leases
3. Click the cancel button
4. Get dropped to /services_dhcpv6.php?if=lan showing dhcpd6 is disabled.

**Expected behavior**
Since I'm not in any way an expert I'm not sure what the correct behavior should be.  Though I find it strange that an update enabled a previously non-running service.  IPv6 is, as far as I know, designed to have multiple IPs per interface without issue though so nothing broke from a client perspective.

**Environment**
Software version used and hardware type if relevant.

OPNsense 20.1.4-amd64
FreeBSD 11.2-RELEASE-p18-HBSD
LibreSSL 3.0.2

**Comment by fichtner** [comment] 2020-04-10 10:56
Hi @kevenwyld,

By default we enable IPv6 on WAN and the IPv6 tracker on LAN.

It may very well be that the change inherently changed your observed behaviour, but if you don't use IPv6 it is at least advised to disable the LAN track mode, if not all the IPv6 settings because otherwise if your ISP starts handing out (worst case defunct) IPv6 you'll be looking for the root cause for a while.


Cheeers,
Franco

**Comment by kevenwyld** [comment] 2020-04-10 14:52
@fichtner Thanks for the input.  I do use ipv6 with a /60 assigned from my ISP, Comcast USA.  So turning it off isn't an option here.  The observed behavior before the upgrade was a single address assigned to each device via SLAAC.  Now there are two, one from SLAAC and one from dhcpv6.  Disabling the dhcpd6 server in the services widget effectively reverts to the old behavior for me.

**Comment by fichtner** [comment] 2020-04-10 16:49
The normal way to fix this is to go to your tracked LAN configuration and set "Allow manual adjustment of DHCPv6 and Router Advertisements", which prevents DHCPv6 from auto-configuring. The same applies to router advertisements (radvd), but you can enable them manually at will.

I think it was a bug that was fixed which fixed your setup in the wrong way, but it should be easy enough to configure as required with the above. :)

**Comment by m-schaeffler** [comment] 2020-04-13 17:18
I'm also facing this "issue".
For me the most important question is: Is this a bug and will be fixed or is the new behaviour correct?

**Comment by fichtner** [comment] 2020-04-13 18:15
I already posted the solution. This was a bugfix and the requirement you guys are having can already be achieved as described.

**Comment by kevenwyld** [comment] 2020-04-14 00:37
@fichtner yep that appears to be it.  So not a bug but a feature.  I should probably be using dhcpv6 in my environment anyway so I'm glad it's working as it should now.  Thanks for the help.

There is also this part:

> Some additional weirdness, if I go to the leases section I can now see the leases that have been handed out. Clicking the "plus" which would normally allow for setting a static lease in a dhcpv6 environment. If I click cancel I get dropped back to https://firewall.local/services_dhcpv6.php?if=lan which shows dhcpv6 on the lan interface is disabled.

Is this also working as intended?  I'm not even sure how to get to that page other than by the url above.  There is no settings page under `services -> DHCPv6` even though the service is clearly enabled.  Only `relay` and the aforementioned `leases` page.

If you think all this is how it's suppose to be this can probably be closed.

![services_dhcpv6_screenshot](https://user-images.githubusercontent.com/11936535/79173532-18fce180-7db5-11ea-8c0b-b0a75ec4e059.png)

![services_status_page](https://user-images.githubusercontent.com/11936535/79173698-94f72980-7db5-11ea-8b51-9a709642ed08.png)

![dhcpv6_leases_screenshot](https://user-images.githubusercontent.com/11936535/79173531-17cbb480-7db5-11ea-8092-34668150d324.png)

**Comment by fichtner** [comment] 2020-04-15 11:42
with "Allow manual adjustment of DHCPv6 and Router Advertisements" off this is what it looks like. The leases shouldn't point you to the page, but in this special case the DHCPv6 has an automatic configuration. Hence leases are created, but the settings looks unused.

**Closed** 2020-04-19 22:34 UTC
Labels: support
