### ISSUE TITLE
Port forward NAT rule not cloned correctly

### ISSUE THREAD

**Issue by mauline** [opnsense/core#4872] opened 2021-03-26 15:07 UTC
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ x] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**

Cloning a port forwarding NAT rule with *Filter rule association* set to *None* will result in a cloned rule with "Filter rule association* set to *Add associated filter rule*.

**To Reproduce**

1. Go to *Firewall: NAT: Port Forward*.
2. Create a new NAT rule. Within that rule set *Filter rule association* to *None*.
3. Click *Save*.
4. In the overview go to the NAT rule just created and click on the *Clone* icon.
5. Result: The cloned rule differs from the original in the value of the *Filter rule association* field.

**Expected behavior**

I would expect that the clone is identical to the original in all respects.

**Environment**

Software version used and hardware type if relevant:

OPNsense 21.1.3_3-amd64
PC-Engines APU 4D4.

**Comment by AdSchellevis** [comment] 2021-03-26 15:31
It's intended, the filter rule should normally have a different association

https://github.com/opnsense/core/blob/34698ef09c781919aa151ed72a31804d7a0d9819/src/www/firewall_nat_edit.php#L1045-L1090

**Comment by mauline** [comment] 2021-03-26 16:01
I'm sorry but I don't understand this answer.

I'm creating a NAT rule with some settings, because I need them exactly as they are. Then I clone this rule and find that the clone is actually not a clone. 

And the reason is "the filter rule should normally have a different association"? What does that mean?

Looking up "clone" in [Wikipedia](https://en.wikipedia.org/wiki/Clone_(computing)) reads
> In computing, a clone is hardware or software that is designed to function in exactly the same way as another system.

Would you consider explaining what your answer means in this context?

**Comment by AdSchellevis** [comment] 2021-03-26 16:14
not really, no. just explaining that it clones the rule and not the associated artifacts.  pointing to Wikipedia doesn't really invite offering any more help to be honest.

**Comment by bsd-source** [comment] 2021-03-27 02:42
I would also expect a cloned NAT rule to be an exact clone to include the "associated artifacts". I don't think this is a big issue by any means, but a little coding logic when cloning a NAT wouldn't be a bag thing would it?

Keep up the great work with OPNsense. You guys are awesome!

**Comment by AdSchellevis** [comment] 2021-03-27 07:31
@bsd-source to be honest, if it where up to me there wouldn't be rules generated from here, but that's something we unfortunately inherited. Cloning the associated rule always leads to unexpected behaviour for someone, changing the default however should be rather painless as long as it's one of the selections already available (none, pass or "related new one")

**Comment by mauline** [comment] 2021-03-27 08:46
@bsd-source Please don't let AdSchellevis confuse you - read my bug report instead.

1. The original NAT rule doesn't have any associated artifacts (Filter rule association = None).
2. When "cloning" opnsense **adds** associated artifacts that haven't been present in the original (Filter rule association = Add associated filter rule).

So the issue is not about not cloning associated artifacts, but adding them.

You're right, it's not a very severe bug. But it's a bug nonetheless.

**Comment by AdSchellevis** [comment] 2021-03-27 09:38
merely explaining the differences here to @bsd-source, but since @mauline listening skills don't seem to be improving and remain quite passive aggressive, closing this in the next commit with the option described in my previous comment.

**Closed** 2021-03-27 09:40 UTC
Labels: support
