### ISSUE TITLE
Upgrade 19.7.2->19.7.3 causes traffic to not pass from LAN->WAN

### ISSUE THREAD

**Issue by pyrodex** [opnsense/core#3678] opened 2019-08-29 13:41 UTC
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[-] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[-] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
After upgrading to 19.7.3 from 19.7.2 traffic isn't passing outbound via the WAN. Clients on the LAN can't do a simple ping of 8.8.8.8. Prior to the upgrade this worked and the firewall itself using the WAN interface can ping 8.8.8.8. When doing a ping to 8.8.8.8 as the source interface of the LAN on the firewall the packets don't pass. I have a single WAN connection and use netgraph to bypass AT&T's router/gateway on my fiber connection with wpa_supplicant. 

More than happy to provide config or anything needed just need instructions on how to provde a scrubbed config.

**To Reproduce**
1. Upgrade from 19.7.2 to 19.7.3
2. Reboot per the upgrade
3. Try to ping 8.8.8.8 from a LAN client or sourced from the LAN interface on the firewall

I can roll back using the following steps:
1. "opnsense-revert -r 19.7.2 opnsense'
2. Go to web UI and go to LAN interface and click save then apply.
3. ICMP begins to work for 8.8.8.8 and any future reboots.

**Expected behavior**
Traffic should pass.

**Screenshots**
None at the moment.

**Relevant log files**
Not sure what to collect in the opnsense area to show this issue.

**Additional context**
N/A

**Environment**
Software version used and hardware type if relevant.

I used to run this in ESXi 6.7U3 until this happened and rebuilt on 8/29/2019 on the same hardware as bare metal.

OPNsense 19.7.3-amd64
Intel(R) Xeon(R) D-2146NT CPU @ 2.30GHz (16 cores)
WAN - Intel(R) PRO/1000 Network Connection, Version - 2.5.3-k
LAN (And others) - LOAD BALANCED LAGG on Intel(R) Ethernet Connection 700 Series PF Driver, Version - 1.9.9-k
GEOM MIRROR on 2 x XA960ME10063 SF441121

**Comment by AdSchellevis** [comment] 2019-08-29 13:46
Things worth of comparing are, gateways and their status, outbound nat rules. capturing data on WAN when on 19.7.3 can also help pinpointing the issue.

**Comment by pyrodex** [comment] 2019-08-29 13:48
> Things worth of comparing are, gateways and their status, outbound nat rules. capturing data on WAN when on 19.7.3 can also help pinpointing the issue.

I did a simple upgrade from 19.7.2, everything was healthy in 19.7.2 prior to the upgrade and was healthy according to the GUI after the upgrade. I did check the NAT rules in 19.7.3 via the GUI and it was, and has always been, set to automatic. 

I can revert tonight and capture more but need to know what to capture, commands would be helpful.

**Comment by mimugmail** [comment] 2019-08-29 13:52
Screenshot of outbound NAT before and after, quite sure you'll then find the error.

**Comment by pyrodex** [comment] 2019-08-29 13:55
> Screenshot of outbound NAT before and after, quite sure you'll then find the error.

So you may be onto something...

With 19.7.2:

![Screen Shot 2019-08-29 at 9 53 50 AM](https://user-images.githubusercontent.com/108703/63946353-fe9f0f00-ca42-11e9-8573-4d7f5abea814.png)

With 19.7.3 the same screenshot didn't show the rules. I noticed this in my troubleshooting of 19.7.3 and changed it from Automatic to Hybrid and then back hoping it would show something under automatic but it didn't. Seems like 19.7.3 wiped out my automatic rules. Any reason why?

**Comment by pyrodex** [comment] 2019-08-29 22:23
Confirmed that with 19.7.3 Outbound automatic NAT rules disappear...

<img width="1383" alt="Screen Shot 2019-08-29 at 6 22 35 PM" src="https://user-images.githubusercontent.com/108703/63980567-0cc44e00-ca8a-11e9-9af9-e3e2c6990b8e.png">

**Comment by pyrodex** [comment] 2019-08-29 22:30
Could https://github.com/opnsense/core/commit/a91babfcba546a7fb198597a9d78bcf66081e223 be the cause?

**Comment by AdSchellevis** [comment] 2019-08-30 08:25
@pyrodex I'll have to look at it, in your case it likely is. easy to test with 

```
opnsense-patch  a91babf
```

Question is why, in 19.7.2 we added more than intended, this should have reverted to pre-19.7 behaviour, I'll have to check here.

What kind of connection do you use?

**Comment by AdSchellevis** [comment] 2019-08-30 08:49
Logic looks reasonable to me, when the gateway is dynamic (dhcp) or static and assigned in the interface, it should be included.

https://github.com/opnsense/core/blob/612cdd511807e7f4c807d18cb4d07096abd6f9ff/src/opnsense/mvc/app/library/OPNsense/Routing/Gateways.php#L413

Maybe a screenshot of the interface settings might help.

**Comment by pyrodex** [comment] 2019-08-30 12:15
> Logic looks reasonable to me, when the gateway is dynamic (dhcp) or static and assigned in the interface, it should be included.
> 
> https://github.com/opnsense/core/blob/612cdd511807e7f4c807d18cb4d07096abd6f9ff/src/opnsense/mvc/app/library/OPNsense/Routing/Gateways.php#L413
> 
> Maybe a screenshot of the interface settings might help.

WAN settings attached:

<img width="745" alt="Screen Shot 2019-08-30 at 8 15 24 AM" src="https://user-images.githubusercontent.com/108703/64019917-5c446180-cafe-11e9-91d5-fb692aa85abd.png">
<img width="736" alt="Screen Shot 2019-08-30 at 8 15 09 AM" src="https://user-images.githubusercontent.com/108703/64019918-5cdcf800-cafe-11e9-82d6-9849ab076fc9.png">

**Comment by AdSchellevis** [comment] 2019-08-30 12:25
hmm, can you share a screenshot of your gateway overview as well?  (System->Gateways->Single)

**Comment by pyrodex** [comment] 2019-08-30 12:36
> hmm, can you share a screenshot of your gateway overview as well? (System->Gateways->Single)

Sure:

<img width="1392" alt="Screen Shot 2019-08-30 at 8 35 27 AM" src="https://user-images.githubusercontent.com/108703/64021103-310f4180-cb01-11e9-8921-e37fafd7a024.png">

**Comment by AdSchellevis** [comment] 2019-08-30 13:15
the last line is a bit odd, but it shouldn't really make a difference here. Unfortunately I can't replicate your issue on my end.

**Comment by pyrodex** [comment] 2019-08-30 13:45
> the last line is a bit odd, but it shouldn't really make a difference here. Unfortunately I can't replicate your issue on my end.

I think that was due to me doing reverts and not rebooting. I just rebooted this morning and now it looks like this:

<img width="1392" alt="Screen Shot 2019-08-30 at 9 35 03 AM" src="https://user-images.githubusercontent.com/108703/64025532-e1ce0e80-cb0a-11e9-97ad-28331478d393.png">

**Comment by pyrodex** [comment] 2019-08-30 14:48
> `opnsense-patch a91babf`

I just did this and rebooted but the issue isn't there anymore, granted I am still running 19.7.2 opnsense plus this patch but everything else is 19.7.3.

**Comment by AdSchellevis** [comment] 2019-08-30 19:17
19.7.2 + patch? that would install it, in stead of uninstalling.

**Comment by pyrodex** [comment] 2019-08-30 20:37
> 
> 
> 19.7.2 + patch? that would install it, in stead of uninstalling.

I was reverting the opnsense package using opnsense-revert to 19.7.2 and then to test the NAT experience I added the patch  you suggested, is there something else to do in a diff order?

**Comment by AdSchellevis** [comment] 2019-08-31 08:48
I'm not sure, 19.7.2 + patch would suggest your issue isn't in the patch, can you check if `/usr/local/opnsense/mvc/app/library/OPNsense/Routing/Gateways.php` contains the `only_configured` attribute now? (assuming that your setup is functional now)

**Comment by pyrodex** [comment] 2019-09-03 12:17
I rebuilt my OPNSense on 19.7.0 and then re-imported my configuration and now only have one WAN interface. The IPv6 is now gone and not sure what happened but after that I upgraded to 19.7.3 without the prior issues. Maybe there was some bad data in the configuration that caused my issue?

**Comment by AdSchellevis** [comment] 2019-09-03 12:22
good to hear it's solved, no idea what happened, but if we can't reproduce it, we might as well close the issue. Thanks for your feedback.

**Closed by AdSchellevis** 2019-09-03 12:22 UTC
Labels: support
