### ISSUE TITLE
DNS:implement remote DNS-blacklists (like pi-hole)

### ISSUE THREAD

**Issue by wytchmaster** [opnsense/core#1945] opened 2017-11-20 13:32 UTC
It would be a great feature, if one can use remote DNS-blacklists in unbound and/or dnsmasq. Maybe it is possible to implement something like pi-hole https://pi-hole.net/). This makes a lot of sense, when blacklisting a lot of domains, especially when in a corporate environment.

**Comment by fabianfrz** [comment] 2017-11-26 11:41
this might be a duplicate of opnsense/plugins#229

**Comment by jumbi77** [comment] 2018-02-22 13:11
+1
Is that on the roadmap for 18.7 or planned for later releases?

**Comment by AdSchellevis** [comment] 2018-03-25 15:19
tracked in https://github.com/opnsense/plugins/issues/229

**Closed by AdSchellevis** 2018-03-25 15:19 UTC
