### ISSUE TITLE
Web UI fails to start - cert.pem corrupted

### ISSUE THREAD

**Issue by monreal** [opnsense/core#3208] opened 2019-02-09 08:36 UTC
Yesterday I deleted a few interfaces from my OPNsense box when the Web UI suddenly became inaccessible. I tried to log in via SSH, which still works. I restarted the services using the console menu and found one error:

`Starting web GUI...failed.`

Digging further I found this error in the system log:

```
Feb  8 23:30:14 wally opnsense: /usr/local/etc/rc.bootup: The command '/usr/local/sbin/lighttpd -f /var/etc/lighty-webConfigurator.conf' returned exit code '255', the output was '2019-02
-08 23:30:14: (mod_openssl.c.487) SSL: couldn't read private key from '/var/etc/cert.pem' 2019-02-08 23:30:14: (server.c.1183) Initialization of plugins failed. Going down.'
Feb  8 23:30:14 wally kernel: failed.
```

Checking the cert.pem file using cat I get this:
```
[...]
k7nixdB9DA/7DzXMTM6hKKCXa7F5EO+Ai2QGI0VZ5/oiR/2kGOZuGmoGn3tO5pZ
R2R+wNO2u69Pp9l00KxHM5YErra7QISpKr8yHUUXuvB4zX6ZFJYWGBMe6vu/8hTR
kDAqJA3rlToFO9Ny8i7AVhOSfdBda4TjxbkarAG+h5Cfcf7P6rEwQzBOmUboEIzg
mrSEbTrwlII0fxJesSQvIjG/7QGSNqLeQssJCqpriysP9rddsCv4tggIepSkikX3
DiAhZVSIG(��(�h�r�r�x4��(���m1��������"}�h��M^ٽ<�'��U����<��ɔ�]�)��0�U�!͠�5�9��Y�MeT��iai���ŝ-مU��ѕQd��e��h)�)��=Q�������	5a�$��͵=1���!E]�%�]�ŝ���YD��A���!��9��M�ə�@)���QIe�aa���<ݡ=)�-!���M���5��8͕��I��� 
[...]
```

So the cert.pem file seems to have gotten corrupted somehow I guess.

Is there a way to generate a new cert.pem file?

**Comment by monreal** [comment] 2019-02-09 09:29
Update: I restored a backup and was able to log in to the Web UI again. I saved the cert.pem, restored the previous state, replaced the cert.pem, verified it was the correct one, restarted and found the cert.pem corrupted again. Any idea what could be wrong?

**Comment by monreal** [comment] 2019-02-09 12:47
I just went with the working backup and now have a working setup again. Still I wonder how this could have happened...

**Comment by fichtner** [comment] 2019-02-10 16:49
Strange. So when "Starting web GUI..." is printed it should write the cert.pem again. That would either mean:

The cert was damaged in the config.xml, but this is unlikely. The other idea is that the cert is no longer in config.xml so cert is not rewritten and at some point cert.pem got corrupted by the file system.

Do you have an idea what would be more likely?

**Comment by monreal** [comment] 2019-02-10 19:33
I just compared the stored certs... see for yourself (this is obviously only a part of the whole string): 

`EaUFoWlZTSUNpQTJCNnBFU1FuVlg4enE4YmQxUUdlQzFpSjlMREx2QW9JQkFRREJWTkljeVM0TlJkc0xYMWFqCmg4VWVlb`

`EaUFoWlZTSUconf_commit: copying 0 rawops from 0x38f01e740e0 (ifc) to 0x38f01e2b080 (ifp)4VWVlb`

How could the conf_commit thing end up inside the conf file?

**Comment by fichtner** [comment] 2019-02-11 07:19
Looks like a file system corruption indeed. How long is your config history? Maybe you can find a change that was done by a particular page that seemed to change this for the worse?

In any case we're unable to fix this in code unless we know what to reproduce. If you're ok with it I'd like to close the issue.

**Comment by monreal** [comment] 2019-02-11 22:24
Does OPNsense store more configs than the ones shown by opnsense-shell? The latter only seems to show the last 18 configs and those are already too new and do not include the corruption. 

On my nightly config backups I see the corruption first appear on the 20190209 backup. The diff between 20190208 and 20190208 is not that big, but I did quite some changes to interfaces/vlans on this test system: [config.xml.diff.txt](https://github.com/opnsense/core/files/2853296/config.xml.diff.txt)

If this is not useful for you feel free to close.

**Comment by fichtner** [comment] 2019-02-12 07:58
The GUI (system: configuration: history) will show more history, used to be 30, nowadays 60 I think. But that only catches individuals changes so it might only be a few days depending on the firewall usage.

The SSL part was omitted from the diff, but it’s a corruption on read for sure, one that luckily didn’t corrupt the whole XML. But maybe also unlucky as a full corruption would lead to a backup revert where the good value was still intact.

Will close and thanks for the additional info. I’ll keep this under observation when doing configuration changes on my test setup, but I don’t expect it’s likely run into it again.


Cheers,
Franco

**Closed by fichtner** 2019-02-12 07:58 UTC
Labels: support
