### ISSUE TITLE
dhcp domain overrides do not register in unbound

### ISSUE THREAD

**Issue by Knaui** [opnsense/core#5033] opened 2021-06-04 19:17 UTC
local domain alternatives/overrides between dhcp service and unbound are not working.

opnsense version 21.1 

might be related to dhcp/unbound problems in #1465, #2946

the following behaviour is bugged:

steps to reproduce (listed domain names are examples, obviously...)
1.
system domain name: sysdom.lokal
>>> Services: DHCPv4: Interfacename
entering alternative Domain name: altdom.lokal
clientpc gets dhcp lease
>>> Services: Unbound DNS: General :
(DHCP Registration checked, DHCP Static Mappings checked, DNS Query Forwarding checked, Local Zone Type: transparent)
unbound does not resolve clientpc.altdom.lokal but forwards it to my external dns where the query cannot be resolved
unbound does instead resolve clientpc.sysdom.lokal

2.
>>> Services: DHCPv4: Interfacename: Static DHCP Mapping
setting up a dhcp static lease for clientpc and alternate domain with MAC but without static IP address (dynamic assignment of pool) is bugged
alternate domain is not registered/resolved locally by unbound
clientpc gets dhcp lease
unbound does not resolve clientpc.altdom.lokal but forwards it to my external dns where the query cannot be resolved
unbound does instead resolve clientpc.sysdom.lokal

3.
using 
>>> Services: Unbound DNS: Overrides : Host Overrides
works 
if I enter 
clientpc.altdom.lokal
as an alternative to
clientpc.sysdom.lokal
but manually adding IP for each pc defeats the purpose of dhcp and is not a solution
also I dont necessarily want several domains assigned to each clientpc...

4.
what currently works without Overrides setup in Unbound:
>>> Services: DHCPv4: Interfacename: Static DHCP Mapping
setting up a dhcp static lease for clientpc and alternate domain with MAC and static IP address outside of the pool
only then the alternate domain is registered/resolved locally by unbound
correct result:
clientpc.altdom.lokal is resolved locally 
clientpc.sysdom.lokal does not exist and therefor is not resolved

**above example (4) is currently the only way to achive
several domain names in a local network that I could get to work**

everything else failed as explained above

**Comment by bstaeheli** [comment] 2021-06-08 06:51
Same problem here. The hostname of the dhcp client ist not discoverable in the "dhcpd.leases".

**Comment by fichtner** [comment] 2021-06-08 08:41
> Same problem here. The hostname of the dhcp client ist not discoverable in the "dhcpd.leases".

Wouldn't that mean the client does not send the hostname?

**Comment by bstaeheli** [comment] 2021-06-08 18:23
> Wouldn't that mean the client does not send the hostname?

Maybe. Not sure, how unbound knows the hostname of a client with a fixed dhcp address. Fact is, that since the last update unbound don't know fixed dhcp devices.

**Comment by fichtner** [comment] 2021-06-08 18:57
It's really not easy to guess from "same problem here", but if you could mention 21.1.6 specifically that would make it easy to find a candidate...

https://github.com/opnsense/core/issues/5027#issuecomment-853357331

**Comment by bstaeheli** [comment] 2021-06-08 19:20
@fichtner you were right, with the mentioned patch the problem is resolved. Thank you!

**Comment by Knaui** [comment] 2021-06-22 12:22
thanks for your help!
have updated to the latest version. 
will test it and will post my results, hopefully soon.

**Comment by hemirunner426** [comment] 2021-08-05 21:57
Just tested this on 21.7.1. 

Here is an example:
OPNSense System Domain: mynetwork.lan

PC1: DHCP hands out mynetwork.lan as a domain. 
PC2: VLAN DHCP hands out vlan.mynetwork.lan as a domain.

PC1 will resolve PC2 as pc2.mynetwork.lan.  If PC2 is static, the FQDN will resolve correctly on PC1.

**Comment by fichtner** [comment] 2021-08-06 04:44
I’m going to close this ticket because more fixes exist in the development version already and these reports are not complete.

**Closed by fichtner** 2021-08-06 04:44 UTC
Labels: support

**Comment by fichtner** [comment] 2021-08-06 06:28
https://github.com/opnsense/core/issues/5118
