### ISSUE TITLE
External SSL Certificate Broken after Update to 2.7.3

### ISSUE THREAD

**Issue by FromageBlue** [opnsense/core#4417] opened 2020-10-16 13:00 UTC
**Describe the bug**
When using the WebUI to upgrade from 20.7.1 to 20.7.3, the update process starts and doesn't seem to end. WebUI continues to say "Updating, please wait..." and Update Button has the "in-progress" animation running. Update log ends with a "**Message from py37-urllib3-1.25.10,1**" and that's it. The Changelog tab still indicates 20.7.1 as installed, but logging into console indicates 20.7.3. If you use a valid external SSL certificate and you reload the webpage, there is now a SSL error with the domain certificate. OPNsense is no longer using the external SSL certificate which prevents firefox from accessing it with its configured FQDN. If you login via the IP, it will use the self-signed certificate provided by OPNsense. Under "System: Trust: Certificates", the external SSL certificate is shown as "In-Use", but doesn't work.

**To Reproduce**
1. Use firefox 81.0 (64-bit) on Linux.
2. Login to OPNsense
3. Go to System: Firmware
4. Click on Update Now

**Expected behavior**
Update should complete successfully and the external SSL certificate should continue to work.

**Screenshots**

**Relevant log files**
GOT REQUEST TO UPGRADE: all
Updating OPNsense repository catalogue...
OPNsense repository is up to date.
All repositories are up to date.
Updating OPNsense repository catalogue...
OPNsense repository is up to date.
All repositories are up to date.
Checking for upgrades (40 candidates): .......... done
Processing candidates (40 candidates): .......... done
The following 40 package(s) will be affected (of 0 checked):

Installed packages to be UPGRADED:
	ca_root_nss: 3.55 -> 3.57
	curl: 7.71.1 -> 7.72.0
	isc-dhcp44-relay: 4.4.2 -> 4.4.2_1
	isc-dhcp44-server: 4.4.2 -> 4.4.2_1
	json-c: 0.14 -> 0.15
	libffi: 3.3 -> 3.3_1
	mpd5: 5.8_10 -> 5.9
	nspr: 4.27 -> 4.29
	nss: 3.55 -> 3.57
	openldap-sasl-client: 2.4.50 -> 2.4.51
	opnsense: 20.7.1 -> 20.7.3
	opnsense-update: 20.7.1 -> 20.7.3
	os-dyndns: 1.22 -> 1.23
	php73: 7.3.20 -> 7.3.22
	php73-ctype: 7.3.20 -> 7.3.22
	php73-curl: 7.3.20 -> 7.3.22
	php73-dom: 7.3.20 -> 7.3.22
	php73-filter: 7.3.20 -> 7.3.22
	php73-gettext: 7.3.20 -> 7.3.22
	php73-hash: 7.3.20 -> 7.3.22
	php73-json: 7.3.20 -> 7.3.22
	php73-ldap: 7.3.20 -> 7.3.22
	php73-openssl: 7.3.20 -> 7.3.22
	php73-pdo: 7.3.20 -> 7.3.22
	php73-session: 7.3.20 -> 7.3.22
	php73-simplexml: 7.3.20 -> 7.3.22
	php73-sockets: 7.3.20 -> 7.3.22
	php73-sqlite3: 7.3.20 -> 7.3.22
	php73-xml: 7.3.20 -> 7.3.22
	php73-zlib: 7.3.20 -> 7.3.22
	py37-cffi: 1.14.1 -> 1.14.3
	py37-six: 1.14.0 -> 1.15.0
	py37-sqlite3: 3.7.8_7 -> 3.7.9_7
	py37-urllib3: 1.25.7,1 -> 1.25.10,1
	python37: 3.7.8_1 -> 3.7.9
	rate: 0.9_1 -> 0.9_2
	sqlite3: 3.32.3_2,1 -> 3.33.0,1
	squid: 4.12 -> 4.13
	syslog-ng327: 3.27.1_1 -> 3.27.1_2
	unbound: 1.10.1 -> 1.11.0

Number of packages to be upgraded: 40

38 MiB to be downloaded.
[1/40] Fetching unbound-1.11.0.txz: .......... done
[2/40] Fetching syslog-ng327-3.27.1_2.txz: .......... done
[3/40] Fetching squid-4.13.txz: .......... done
[4/40] Fetching sqlite3-3.33.0,1.txz: .......... done
[5/40] Fetching rate-0.9_2.txz: ....... done
[6/40] Fetching python37-3.7.9.txz: .......... done
[7/40] Fetching py37-urllib3-1.25.10,1.txz: .......... done
[8/40] Fetching py37-sqlite3-3.7.9_7.txz: .... done
[9/40] Fetching py37-six-1.15.0.txz: ... done
[10/40] Fetching py37-cffi-1.14.3.txz: .......... done
[11/40] Fetching php73-zlib-7.3.22.txz: ... done
[12/40] Fetching php73-xml-7.3.22.txz: ... done
[13/40] Fetching php73-sqlite3-7.3.22.txz: ... done
[14/40] Fetching php73-sockets-7.3.22.txz: ..... done
[15/40] Fetching php73-simplexml-7.3.22.txz: ... done
[16/40] Fetching php73-session-7.3.22.txz: ..... done
[17/40] Fetching php73-pdo-7.3.22.txz: ...... done
[18/40] Fetching php73-openssl-7.3.22.txz: ........ done
[19/40] Fetching php73-ldap-7.3.22.txz: .... done
[20/40] Fetching php73-json-7.3.22.txz: ... done
[21/40] Fetching php73-hash-7.3.22.txz: .......... done
[22/40] Fetching php73-gettext-7.3.22.txz: . done
[23/40] Fetching php73-filter-7.3.22.txz: ... done
[24/40] Fetching php73-dom-7.3.22.txz: ........ done
[25/40] Fetching php73-curl-7.3.22.txz: .... done
[26/40] Fetching php73-ctype-7.3.22.txz: . done
[27/40] Fetching php73-7.3.22.txz: .......... done
[28/40] Fetching os-dyndns-1.23.txz: .... done
[29/40] Fetching opnsense-update-20.7.3.txz: ........ done
[30/40] Fetching opnsense-20.7.3.txz: .......... done
[31/40] Fetching openldap-sasl-client-2.4.51.txz: .......... done
[32/40] Fetching nss-3.57.txz: .......... done
[33/40] Fetching nspr-4.29.txz: .......... done
[34/40] Fetching mpd5-5.9.txz: .......... done
[35/40] Fetching libffi-3.3_1.txz: ..... done
[36/40] Fetching json-c-0.15.txz: ......... done
[37/40] Fetching isc-dhcp44-server-4.4.2_1.txz: .......... done
[38/40] Fetching isc-dhcp44-relay-4.4.2_1.txz: .......... done
[39/40] Fetching curl-7.72.0.txz: .......... done
[40/40] Fetching ca_root_nss-3.57.txz: .......... done
Checking integrity... done (0 conflicting)
[1/40] Upgrading libffi from 3.3 to 3.3_1...
[1/40] Extracting libffi-3.3_1: .......... done
[2/40] Upgrading python37 from 3.7.8_1 to 3.7.9...
[2/40] Extracting python37-3.7.9: .......... done
[3/40] Upgrading py37-six from 1.14.0 to 1.15.0...
[3/40] Extracting py37-six-1.15.0: .......... done
[4/40] Upgrading py37-cffi from 1.14.1 to 1.14.3...
[4/40] Extracting py37-cffi-1.14.3: .......... done
[5/40] Upgrading sqlite3 from 3.32.3_2,1 to 3.33.0,1...
[5/40] Extracting sqlite3-3.33.0,1: .......... done
[6/40] Upgrading php73 from 7.3.20 to 7.3.22...
[6/40] Extracting php73-7.3.22: .......... done
[7/40] Upgrading nspr from 4.27 to 4.29...
[7/40] Extracting nspr-4.29: .......... done
[8/40] Upgrading ca_root_nss from 3.55 to 3.57...
[8/40] Extracting ca_root_nss-3.57: ...... done
[9/40] Upgrading py37-urllib3 from 1.25.7,1 to 1.25.10,1...
[9/40] Extracting py37-urllib3-1.25.10,1: .......... done
[10/40] Upgrading php73-pdo from 7.3.20 to 7.3.22...
[10/40] Extracting php73-pdo-7.3.22: .......... done
[11/40] Upgrading php73-json from 7.3.20 to 7.3.22...
[11/40] Extracting php73-json-7.3.22: .......... done
[12/40] Upgrading php73-hash from 7.3.20 to 7.3.22...
[12/40] Extracting php73-hash-7.3.22: .......... done
[13/40] Upgrading openldap-sasl-client from 2.4.50 to 2.4.51...
[13/40] Extracting openldap-sasl-client-2.4.51: .......... done
[14/40] Upgrading nss from 3.55 to 3.57...
[14/40] Extracting nss-3.57: .......... done
[15/40] Upgrading json-c from 0.14 to 0.15...
[15/40] Extracting json-c-0.15: .......... done
[16/40] Upgrading curl from 7.71.1 to 7.72.0...
[16/40] Extracting curl-7.72.0: .......... done
[17/40] Upgrading unbound from 1.10.1 to 1.11.0...
===> Creating groups.
Using existing group 'unbound'.
===> Creating users
Using existing user 'unbound'.
[17/40] Extracting unbound-1.11.0: .......... done
[18/40] Upgrading syslog-ng327 from 3.27.1_1 to 3.27.1_2...
[18/40] Extracting syslog-ng327-3.27.1_2: .......... done
You may need to manually remove /usr/local/etc/syslog-ng.conf if it is no longer needed.
[19/40] Upgrading squid from 4.12 to 4.13...
===> Creating groups.
Using existing group 'squid'.
===> Creating users
Using existing user 'squid'.
===> Creating homedir(s)
===> Pre-installation configuration for squid-4.13
[19/40] Extracting squid-4.13: .......... done
You may need to manually remove /usr/local/etc/squid/squid.conf if it is no longer needed.
[20/40] Upgrading rate from 0.9_1 to 0.9_2...
[20/40] Extracting rate-0.9_2: ..... done
[21/40] Upgrading py37-sqlite3 from 3.7.8_7 to 3.7.9_7...
[21/40] Extracting py37-sqlite3-3.7.9_7: ........ done
[22/40] Upgrading php73-zlib from 7.3.20 to 7.3.22...
[22/40] Extracting php73-zlib-7.3.22: ....... done
[23/40] Upgrading php73-xml from 7.3.20 to 7.3.22...
[23/40] Extracting php73-xml-7.3.22: ........ done
[24/40] Upgrading php73-sqlite3 from 7.3.20 to 7.3.22...
[24/40] Extracting php73-sqlite3-7.3.22: ........ done
[25/40] Upgrading php73-sockets from 7.3.20 to 7.3.22...
[25/40] Extracting php73-sockets-7.3.22: .......... done
[26/40] Upgrading php73-simplexml from 7.3.20 to 7.3.22...
[26/40] Extracting php73-simplexml-7.3.22: ......... done
[27/40] Upgrading php73-session from 7.3.20 to 7.3.22...
[27/40] Extracting php73-session-7.3.22: .......... done
[28/40] Upgrading php73-openssl from 7.3.20 to 7.3.22...
[28/40] Extracting php73-openssl-7.3.22: ....... done
[29/40] Upgrading php73-ldap from 7.3.20 to 7.3.22...
[29/40] Extracting php73-ldap-7.3.22: ....... done
[30/40] Upgrading php73-gettext from 7.3.20 to 7.3.22...
[30/40] Extracting php73-gettext-7.3.22: ....... done
[31/40] Upgrading php73-filter from 7.3.20 to 7.3.22...
[31/40] Extracting php73-filter-7.3.22: ........ done
[32/40] Upgrading php73-dom from 7.3.20 to 7.3.22...
[32/40] Extracting php73-dom-7.3.22: .......... done
[33/40] Upgrading php73-curl from 7.3.20 to 7.3.22...
[33/40] Extracting php73-curl-7.3.22: ....... done
[34/40] Upgrading php73-ctype from 7.3.20 to 7.3.22...
[34/40] Extracting php73-ctype-7.3.22: ....... done
[35/40] Upgrading opnsense-update from 20.7.1 to 20.7.3...
[35/40] Extracting opnsense-update-20.7.3: .......... done
[36/40] Upgrading mpd5 from 5.8_10 to 5.9...
[36/40] Extracting mpd5-5.9: ......... done
[37/40] Upgrading isc-dhcp44-server from 4.4.2 to 4.4.2_1...
===> Creating groups.
Using existing group 'dhcpd'.
===> Creating users
Using existing user 'dhcpd'.
[37/40] Extracting isc-dhcp44-server-4.4.2_1: .......... done
[38/40] Upgrading isc-dhcp44-relay from 4.4.2 to 4.4.2_1...
[38/40] Extracting isc-dhcp44-relay-4.4.2_1: ....... done
[39/40] Upgrading os-dyndns from 1.22 to 1.23...
[39/40] Extracting os-dyndns-1.23: .......... done
Stopping configd...done
Starting configd.
Reloading plugin configuration
Configuring system logging...done.
[40/40] Upgrading opnsense from 20.7.1 to 20.7.3...
[40/40] Extracting opnsense-20.7.3: .......... done
Stopping configd...done
Resetting root shell
Updating /etc/shells
Unhooking from /etc/rc
Unhooking from /etc/rc.shutdown
Updating /etc/shells
Registering root shell
Hooking into /etc/rc
Hooking into /etc/rc.shutdown
Starting configd.
Keep version OPNsense\Monit\Monit (1.0.8)
Keep version OPNsense\Firewall\Alias (1.0.0)
Keep version OPNsense\OpenVPN\Export (0.0.1)
Keep version OPNsense\CaptivePortal\CaptivePortal (1.0.0)
Migrated OPNsense\Interfaces\VxLan from 0.0.0 to 1.0.1
Migrated OPNsense\Interfaces\Loopback from 0.0.0 to 1.0.0
Keep version OPNsense\Cron\Cron (1.0.1)
Keep version OPNsense\IPsec\IPsec (0.0.0)
Keep version OPNsense\Backup\NextcloudSettings (1.0.0)
Keep version OPNsense\TrafficShaper\TrafficShaper (1.0.3)
Keep version OPNsense\Syslog\Syslog (1.0.0)
Keep version OPNsense\IDS\IDS (1.0.5)
Keep version OPNsense\Proxy\Proxy (1.0.3)
Keep version OPNsense\Diagnostics\Netflow (1.0.1)
Keep version OPNsense\Routes\Route (1.0.0)
Keep version OPNsense\Unboundplus\Miscellaneous (0.0.2)
Keep version OPNsense\Unboundplus\Dnsbl (0.0.1)
Writing firmware setting...done.
Writing trust files...done.
Configuring login behaviour...done.
Configuring system logging...done.
=====
Message from py37-urllib3-1.25.10,1:

--
Since version 1.25 HTTPS connections are now verified by default which is done
via "cert_reqs = 'CERT_REQUIRED'".  While certificate verification can be
disabled via "cert_reqs = 'CERT_NONE'", it's highly recommended to leave it on.

Various consumers of net/py-urllib3 already have implemented routines that
either explicitly enable or disable HTTPS certificate verification (e.g. via
configuration settings, CLI arguments, etc.).

Yet it may happen that there are still some consumers which don't explicitly
enable/disable certificate verification for HTTPS connections which could then
lead to errors (as is often the case with self-signed certificates).

In case of an error one should try first to temporarily disable certificate
verification of the problematic urllib3 consumer to see if that approach will
remedy the issue.
=====
Message from opnsense-20.7.3:

--
The lion sleeps tonight

**Additional context**

**Environment**
OPNsense 20.7.1-amd64
FreeBSD 12.1-RELEASE-p8-HBSD
OpenSSL 1.1.1g 21 Apr 2020

**Comment by AdSchellevis** [comment] 2020-10-16 13:17
highly likely duplicate of https://github.com/opnsense/core/issues/4397

**Closed** 2021-04-15 11:24 UTC
Labels: support
