### ISSUE TITLE
Possible regression of Unbound since 18.7.6

### ISSUE THREAD

**Issue by soder10** [opnsense/core#2894] opened 2018-11-10 10:03 UTC
Hello devs,

since upgraded to 18.7.6 that introduced unbound 1.8.1, I face "frequent" DNS resolver service shutdowns. Checking the Unbound log I dont see any reason why the service suddenly stopped itself, rendering all name resolution stop.

All I could find in the unbound log is this line:

Nov 10 10:35:53 | unbound: [67269:0] fatal error: Could not read config file: /unbound.conf. Maybe try unbound -dd, it stays on the commandline to see more errors, or unbound-checkconf

When this is observed, and I manually try to start the service again, it starts successfully, and seems to be working for a couple of days, then stops suddently again.

I tried set the logging level2 to get more logs, but in this case everye single name resolution attempt is alao logged, and it will be difficult to catch the event that has anything to do with the stop/crash.

Where is the unbound log stored in the underlying system, so I could use some clever grep to extra t meaningful entries?

**Comment by fichtner** [comment] 2018-11-10 10:05
It looks like an issue with Unbound 1.8. 1.7 was reported to work fine. Our integration didn't change in this regard. You could verify this theory by reverting to 1.7:

    # opnsense-revert -r 18.7.5 unbound


Cheers,
Franco

**Comment by soder10** [comment] 2018-11-10 10:15
Thanks, with 1.7 I didnt face such issue. I will try to revert back to that older unbound version. After rollback should I take care of anything regarding this package is no longer in sync with what is nornally shipped with 18.7.6+ ?

**Comment by fichtner** [comment] 2018-11-10 10:18
Reload Unbound manually to load the previous version. Code-wise both are compatible.

On next OPNsense update, however, it will try to install 1.8 again so you can lock the package from System: Firmware: Packages to prevent such an update. It could be that the update will stall in this case. Unbound is intertwined in some other packages... but nothing bad happens as it just won't update in this case.

This is just for confirmation. I do believe it needs to be reported to upstream developers that something is wrong with 1.8.

**Comment by soder10** [comment] 2018-11-12 10:29
Is there anything to check in the logs in case the next time it stops (was it a graceful stop by some opnsense service, or it died ungracefully by its own) ? Or this is more related to Unbound devs?

Ps. The unbound log is located at /var/log/resolver.log in case someone wants to read it from CLI (took me some time to figure out this fact)

**Comment by soder10** [comment] 2018-11-14 12:01
It happened again a couple of minutes ago. I added some DHCP static mapping, applied the change. This seemed trigger the restart of Unbound as well. I could see in the log, that the last line was this same error, as I reported the last time:

Nov 14 12:29:03 	unbound: [58191:0] fatal error: Could not read config file: /unbound.conf. Maybe try unbound -dd, it stays on the commandline to see more errors, or unbound-checkconf
Nov 14 12:29:03 	unbound: [58191:0] notice: Restart of unbound 1.8.1.

Seems this fatal error blocked Unbound from successfully starting. Strange thing, if I press the service start from GUI, it starts without issues.

**Comment by soder10** [comment] 2018-11-14 12:42
Yep, its reproducible every single time I apply config.

**Comment by EugenMayer** [comment] 2018-11-21 08:18
@fichtner IMHO i would expect this to be a timing issue during the generation of the unbound configuration.

Since it happens from time to time, it should be expected to the DHCP hostname auto-registering in ubound which causes that. Maybe in 1.8. they changed the timings / blocking mechanism during the reload or they just "hard bind" to the inode of the configuration, while we "replace" the file with a new one during the generation of the configuration - and the new unbound version is more sensible to that.

I am pretty sure this is not an upstream bug or at least if, it would be a "freebsd" related upstream bug and that just sounds rather unlikely. 

I am currently waiting for arm32/arm64 alpine to get fixed on docker.hub so i can package 1.8 so i could try to reproduce this on https://github.com/EugenMayer/docker-unbound .. but i have to wait. I could though try this with amd64 since i already packaged `eugenmayer/unbound:1.8`. Maybe we can isolate the issue better with a docker-image, especially for reproduction, be it a upstream issue or a opsense issue.

**Comment by soder10** [comment] 2018-11-24 10:45
Guys, while you are investigating this issue: 
can you recommend me how to schedule "CRON - unbound service restart" every day at midnight and sometime during the day? Users are complaining to throw away this router and bring the former Asus soho box back, because the internet is practically dead until I manually start the unbound service from GUI. I hope scheduled service restart multiple times per day can keep the service alive without this sudden stop triggered.

I checked System\Settings\Cron \ Add new job --> but I can only find 8-10 predefined jobs, none of them are custom service restart. Dont want to mess with anything non-GUI way unless someone can give me 2-3 lines of clear instruction.
Thanks guys!

**Comment by soder10** [comment] 2018-11-24 10:49
Forgot to say: I was afraid of rolling back to unbound 1.7, fearing what may break when the next opnsense upgrade tries to reinstall it / tries to skip that out-of-sync package. So yes, I am still on this buggy 1.8.1, and if you need any log to capture the stop-reason, let me know.

**Comment by fichtner** [comment] 2018-11-24 10:52
the command to restart unbound is "/usr/local/sbin/pluginctl dns", just add it to /etc/crontab (the next firmware update will overwrite crontab, but if you're looking for a solution until unbound is updated that's probably it)

**Comment by EugenMayer** [comment] 2018-11-24 10:52
Rather use monit to monitor and restart the service if port 53 is dead? Monit is part of the plugins, so this should be easy and far better then the cron based restart, since it instantly  self heals

**Comment by soder10** [comment] 2018-11-24 11:21
@EugenMayer : thanks for the hint, monit should be the real solution, and would prefer that definitely. Unfortunately I dont have the spare time to become expert of the nuances of monit, meanwhile the next time unbound stops, angry users would throw the firewall to the trash. So would like something very basic and very reliable to restart that damn unbound.

**Comment by soder10** [comment] 2018-12-01 10:44
Small update: it seems it is triggered on Saturday, around 10:36 am. That is the 3rd Saturday morning when it happens, always around this 10:36 am time.

**Comment by soder10** [comment] 2018-12-08 09:46
Just as I expected: happened today again, at exactly 1 week later.
I checked what was happening: I get a PPPOE disconnect event (most probably my ISP drops my connection after 1 week uptime, dont know for sure who initiates that)

//the last line before the current issue is from dec1, when the previous disconnect-reconnect event happened, so betwen the 2 events there is exactly 1 week silence //
Dec  8 10:37:07 FW01 ppp: [wan_link0] LCP: rec'd Terminate Request #2 (Opened)
Dec  8 10:37:07 FW01 ppp: [wan_link0] LCP: state change Opened --> Stopping
Dec  8 10:37:07 FW01 ppp: [wan_link0] Link: Leave bundle "wan"
Dec  8 10:37:07 FW01 ppp: [wan] Bundle: Status update: up 0 links, total bandwidth 9600 bps
Dec  8 10:37:07 FW01 ppp: [wan] IPCP: Close event
Dec  8 10:37:07 FW01 ppp: [wan] IPCP: state change Opened --> Closing
Dec  8 10:37:07 FW01 ppp: [wan] IPCP: SendTerminateReq #16
Dec  8 10:37:07 FW01 ppp: [wan] IPCP: LayerDown
Dec  8 10:37:08 FW01 ppp: [wan] IPV6CP: Close event
Dec  8 10:37:08 FW01 ppp: [wan] IPV6CP: state change Opened --> Closing
Dec  8 10:37:08 FW01 ppp: [wan] IPV6CP: SendTerminateReq #8
Dec  8 10:37:08 FW01 ppp: [wan] IPV6CP: LayerDown
Dec  8 10:37:09 FW01 ppp: [wan] IFACE: Down event
Dec  8 10:37:09 FW01 ppp: [wan] IFACE: Rename interface pppoe0 to pppoe0
Dec  8 10:37:09 FW01 ppp: [wan] IPCP: Down event
Dec  8 10:37:09 FW01 ppp: [wan] IPCP: LayerFinish
Dec  8 10:37:09 FW01 ppp: [wan] IPCP: state change Closing --> Initial
Dec  8 10:37:09 FW01 ppp: [wan] IPV6CP: Down event
Dec  8 10:37:09 FW01 ppp: [wan] IPV6CP: LayerFinish
Dec  8 10:37:09 FW01 ppp: [wan] Bundle: No NCPs left. Closing links...
Dec  8 10:37:09 FW01 ppp: [wan] IPV6CP: state change Closing --> Initial
Dec  8 10:37:09 FW01 ppp: [wan_link0] LCP: SendTerminateAck #16
Dec  8 10:37:09 FW01 ppp: [wan_link0] LCP: LayerDown
Dec  8 10:37:10 FW01 ppp: [wan_link0] PPPoE: connection closed
Dec  8 10:37:10 FW01 ppp: [wan_link0] Link: DOWN event
Dec  8 10:37:10 FW01 ppp: [wan_link0] LCP: Down event
Dec  8 10:37:10 FW01 ppp: [wan_link0] LCP: state change Stopping --> Starting
Dec  8 10:37:10 FW01 ppp: [wan_link0] Link: reconnection attempt 1 in 2 seconds
// then the reconnect finishes successfully //

During this exact time, unbound is stopped, and fails to restart correctly, with the same error message posted in my initial post.

**Comment by fichtner** [comment] 2018-12-08 09:51
You probably set explicit Unbound Interfaces?

**Comment by soder10** [comment] 2018-12-08 09:57
You are correct, I mentioned recently to protect DNS by not even listening on WAN. But after you said it may silently break things, I reverted that config back, so it listens on ALL since a couple of weeks.

**Comment by fichtner** [comment] 2018-12-08 09:58
Hmmm, maybe your reconnect comes back with the same IP? it might be that it doesn't know that it must rerun configuration when the IP is back

**Comment by soder10** [comment] 2018-12-08 10:01
Nope, it gets a completely different IP after the succesful reconnect.

**Comment by fichtner** [comment] 2018-12-08 10:08
Ok, I'm testing Unbound 1.8.2 just now, but here's another patch that will help recover from a crashed unbound in your particular case (listen "all"): 3d8fd0088af

    # opnsense-patch 3d8fd0088af

**Comment by soder10** [comment] 2018-12-08 10:21
Thanks, I applied the patch (seems succesfully). Did a forced pppoe disconnect -> unbound stopped and could not start with the same error message.
 But after approx 1 minute, it tried another attempt to start, and finally it started.

**Comment by soder10** [comment] 2018-12-08 10:39
I see what you mean: this patch is a workaround, the real issue is why does unbound search for the config file at the wrong location?

**Comment by fichtner** [comment] 2018-12-08 10:41
https://github.com/opnsense/core/blob/3d8fd0088af70fbcd511f6766ae24f4c25c7c124/src/etc/inc/plugins.inc.d/unbound.inc#L464

That's the only spot we ever start Unbound and as you can see it has a full path to the file. The chroot directive is inside unbound.conf, so how Unbound can say "./unbound.conf" is not found while adhering to the information *inside* the file is beyond me. :D

**Comment by soder10** [comment] 2018-12-08 10:50
The only speciality I have is the following in the Custom options section:

include: /usr/local/etc/unbound/unbound_advertisement_serverlist_2018.11.28.txt
extended-statistics: yes
( I have a suspicion the 1st line is causibg the problem)

I did a quick test and removed these 2 lines, saved the change, applied it, then disconnect-reconnect ppoe -> seems unbound started correctly this time

**Comment by fichtner** [comment] 2018-12-08 10:52
you should place this file in /var/unbound/ with chown unbound:unbound to be sure...

**Comment by soder10** [comment] 2018-12-08 10:54
The only problem my /var is on tmpfs, so the next reboot wipes it. Yet another syshook script?

**Comment by fichtner** [comment] 2018-12-08 10:55
symlink might work. it's your setup :)

**Comment by fichtner** [comment] 2018-12-28 16:53
The right time is whenever you update the file you push it to /var/unbound and then run "pluginctl dns". 

I'm sorry, there's nothing else we can try here in an open source scope. The discussed workaround goes into 18.7.10.

**Closed by fichtner** 2018-12-28 16:53 UTC
Labels: support

**Comment by soder10** [comment] 2019-01-02 19:07
@fichtner: can you tell me, at which stage of the boot process /syshook script run do you generate the unbound.conf file that gets copied to /var/unbound? I would need to hack into that step to add the extra file copy from persistent filesystem to /var/unbound tmpfs, and the unbound service will find that copied file when it is getting started. At least thats my understanding.

**Comment by fichtner** [comment] 2019-01-02 19:09
use "start" syshook, /var/unbound will be populated and running

copy the file

run "pluginctl dns" to restart unbound.

**Comment by soder10** [comment] 2019-01-02 19:11
Cool, I will try to implement this and hope it will work :)

**Comment by fichtner** [comment] 2019-01-02 19:15
it should. if not let me know :)

**Comment by soder10** [comment] 2019-01-03 05:00
I have to wait couple of days (most probably until the weekend) for this. When is the 18.7.10 planned, so I could merge the 2 action?

**Comment by fichtner** [comment] 2019-01-03 10:39
Preliminary target for 18.7.10 is Tuesday (Jan 8)

**Comment by soder10** [comment] 2019-01-04 19:54
Thanks, will wait for it then, before going for custom scripting.
