### ISSUE TITLE
Disconnecting huawei e3372h Hilink modem from USB port crashes OPNsense

### ISSUE THREAD

**Issue by bonjour81** [opnsense/core#3802] opened 2019-11-08 09:57 UTC
I have a huawei LTE  USB modem e3372h hilink mode.
I succeeded in connecting it as a working (online) gateway.

If I physically disconnect (ie: remove from USB port) the modem while gateway is enabled, OPNsense crashes:
- Does not answer anymore to ping from LAN (ping 192.168.1.254)
- Does not answer anymore to ssh
- web GUI not available anymore
- LAN DHCP not available anymore (for example, new wifi connection from android device won't receive any IP)

A power cycling (reboot) is necessary to recover.

So far, I have not tested/checked:
- Disconnecting USB with gateway disabled.
- Local access (with screen/keyboard connected to OPNsense device) when "crashed".

Let me know if I can provide more information/tests.

OPNsense version: 19.7 (up to date), but issue was also on 19.1.

**Comment by bonjour81** [comment] 2019-11-23 13:45
Hi,
Is there any tests I could do or log file I could check or share to help on this ?
Best regards,

**Comment by bonjour81** [comment] 2019-11-30 15:01
Hello ?

**Comment by hippi-viking** [comment] 2020-01-06 12:12
Hello,

Are you the one who started the similar [thread](https://forum.opnsense.org/index.php?topic=14908.msg69168#msg69168) on the OPNSense forum?
I am having the same issue (I am the one who wrote the last two replies).
I suspect this might be an overload issue with the gateway selection script. The last time the firewall crashed because of this (just a few hours ago) was stranger than usual: after a roughly month of uptime the phone crashed, but the firewall did not crash right away. The other (cable) uplink went down after the phone crashed, reissuing a DHCP request solved it for a while (I also had to restart suricata to unblock the cable interface). But the firewall still crashed after about 5 minutes so it seems the overload issue is still there.

**Comment by bonjour81** [comment] 2020-01-06 14:54
Hi! 
Yes, I'm the same guy. I discover your messages on opnsense forum ( sorry, I don't know why, notification was disabled on forum, so i was not aware of your comments).

Good to know I'm not alone...even if the issue is not solved yet.

Both the forum and here are pretty quiet :)

**Comment by cryptoluks** [comment] 2020-05-06 18:57
Hi,

I recently switched from pfSense to OPNsense and I am now struggling with the same issue.

Using a Huawei 3372 in stick mode which worked perfectly fine with pfSense 2.4.5.

With OPNsense, I needed to manually load  the `cdce` kernel module. Without, no `ue0` interface came up. (Just put `if_cdce_load="YES"` in your `/boot/loader.conf.local` or better save it as a tunable via the web interface.

Now back to topic. I tested it not intensively, as it is my productive system, but it seems that the panic only occurs when gateway monitoring is active. @bonjour81 @hippi-viking can you confirm this?

I was also able to capture some traces.

```
ugen0.2: <MOBILE MOBILE> at usbus0 (disconnected)
u3g0: at uhub0, port 3, addr 1 (disconnected)
u3g0: detached
cdce0: at uhub0, port 3, addr 1 (disconnected)
cdce0: detached
panic: sbsndptr: sockbuf 0xfffff800079b4878 and mbuf 0xfffff800079a1300 clashing
[..snip..]
```
[dump.txt](https://github.com/opnsense/core/files/4588889/dump.txt)

**Comment by bonjour81** [comment] 2020-05-06 19:51
Hi, I have changed my setup. You may have a look [here](https://forum.opnsense.org/index.php?topic=14908.msg75294#msg75294).
I added a TL-MR3020 between opnsense and the e3372, this way I connect opnsense by RJ45 instead of USB.
If you follow the link you can see an other user did it with a TL-MR3420.
So, as far as I know, the issue is still open, but using such devices is a possible work around.
It will add an additional NAT layer, but it may be not critical, considering you cannot open port and access your LAN from 4G in most situation.

**Comment by cryptoluks** [comment] 2020-05-07 08:59
> Hi, I have changed my setup. You may have a look [here](https://forum.opnsense.org/index.php?topic=14908.msg75294#msg75294).
> I added a TL-MR3020 between opnsense and the e3372, this way I connect opnsense by RJ45 instead of USB.
> If you follow the link you can see an other user did it with a TL-MR3420.
> So, as far as I know, the issue is still open, but using such devices is a possible work around.
> It will add an additional NAT layer, but it may be not critical, considering you cannot open port and access your LAN from 4G in most situation.

Thanks for your response. Okay this seems to be a nice workaround. But I am not quite sure if this travel router also works out of the box with CDC NCM Huawei "stick mode", as you said you're using  the stick with Hilink mode.

And for the time I just will keep gateway monitoring disabled to prevent the kernel panic when removing the stick. Seems to work..

I think with the dump maybe one of the maintainers can have a quick look into this? @fichtner @AdSchellevis what do you think of [dump.txt](https://github.com/opnsense/core/files/4588889/dump.txt)? :innocent:

**Comment by hippi-viking** [comment] 2020-05-13 09:12
Hi @cryptoluks, :)

I confirm I have gateway monitoring enabled on my WAN interfaces (mobile included). Does the panic not occur for you when gateway monitoring is inactive on the specific interface (or any interface at all)?

**Comment by AdSchellevis** [comment] 2020-05-13 09:15
just to rule out it's related to this https://github.com/opnsense/src/issues/52 , can you try to disable shared forwarding (Firewall -> Settings -> Advanced)

**Comment by cryptoluks** [comment] 2020-05-13 09:21
> I confirm I have gateway monitoring enabled on my WAN interfaces (mobile included). Does the panic not occur for you when gateway monitoring is inactive on the specific interface (or all your interfaces)?

Yes, I have monitoring disabled for just the WWAN / LTE interface (WAN monitoring is on).

> just to rule out it's related to this opnsense/src#52 , can you try to disable shared forwarding (Firewall -> Settings -> Advanced)

I will test it later this day.

**Comment by fichtner** [comment] 2020-05-13 09:43
I can attest to crashes on boot in relation to gateway monitoring (icmp), more so on 20.7 Beta than 20.1 but it fits the problem and fix proposed. This would be nice indeed.

**Comment by cryptoluks** [comment] 2020-05-14 09:24
Okay I was not able to reproduce the crash yesterday at all, even with "shared forwarding" and gateway monitoring enabled. That's strange. I did not change much since I was able to trigger the kernel panic about a week ago, where crashes were very consistent when gateway monitoring was enabled.

Maybe I need more states on the WWAN interface than just the ICMP monitoring to trigger the panic? Hm.. I am a bit clueless now.

Will try again soon.

**Comment by fichtner** [comment] 2020-05-14 09:53
I think the point is interfaces going up and down, either on boot naturally or during unreliable times in the network. When you have any policy route through an interface that is temporary down the crash can happen.

**Comment by stachi** [comment] 2020-05-18 07:01
Have the same Problem with a PPPoE connection. If gateway monitoring is enabled and the connection goes down, a kernel panic occurs. With gateway monitoring disabled all works fine (except Multi WAN of course). I got this error since 18.1 and it still happens in 20.1

**Comment by fichtner** [comment] 2020-05-18 15:19
The kernel patch will be in 20.1.7 this week. Fingers crossed....

**Comment by AdSchellevis** [comment] 2020-05-18 18:23
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.

**Closed by AdSchellevis** 2020-05-18 18:23 UTC
Labels: support
