### ISSUE TITLE
getserviceproviders.php instead of index.php

### ISSUE THREAD

**Issue by andreas-p** [opnsense/core#724] opened 2016-01-29 10:00 UTC
When navigating to https://firewall/ I'm getting redirectd to https://firewall/getserviceproviders.php; I'd have to specify index.php explicitely.

**Comment by AdSchellevis** [comment] 2016-01-29 10:23
looks like a browser cache issue...

**Comment by andreas-p** [comment] 2016-01-29 10:35
I don't think it's a browser cache issue.
I got this the very first time I used Safari to connect to the firewall after logging in as well; usually I'm using Firefox.

**Comment by fichtner** [comment] 2016-01-29 10:38
Is this with a root user or user-defined account (e.g. non-admin with limited access)?

**Comment by andreas-p** [comment] 2016-01-29 10:51
That's the difference: root is ok, but with a slightly restricted user I get that redirect.
The restricted user still has lobby and dashboard access; just some never-to-use menu items removed.

**Comment by fichtner** [comment] 2016-01-29 10:59
The order in which the pages are being redirected may be fixed by the order they were selected individually. Try unsetting "WebCfg - AJAX: Get Service Providers" privilege, save and then reapply. It should now point to a different page after login?

**Comment by andreas-p** [comment] 2016-01-29 11:07
Right: Now I get some stats, which is probably the menu entry WebCfg - AJAX: Get Stats which follows the GetServiceProviders privilege.

**Comment by fichtner** [comment] 2016-01-29 11:09
I fear a larger rework of this area is needed to fix the issue, including the already reported https://github.com/opnsense/core/issues/709

**Comment by AdSchellevis** [comment] 2016-02-09 16:07
Redirecting to the first authenticated item in the list isn't really that bad, when the initial page isn't accessible you can't do anything else given the current data at hand (or you should store the initial page somewhere, which kind of looks like an overkill for something that's already working).

For reference, 
https://github.com/opnsense/core/blob/16.1/src/etc/inc/authgui.inc#L270-L281

I propose we close this issue.

**Comment by andreas-p** [comment] 2016-02-09 18:18
I'd propose to redirect to /index.html instead (in my case, / was called).
When another inaccessible page was navigated, it should give some error page instead.
That's the way a standard web server would handle this, and it appears reasonable for opnsense as well.

**Comment by AdSchellevis** [comment] 2016-02-09 18:35
That would break acl usage for the users which aren't allowed to access the index, for example users which may only create new captive portal vouchers.
Your problem looks like a configuration issue, because the acl "WebCfg - Dashboard (all)" explicitly allows the index.html page (which is called when navigating to /).

I just tested this on my machine, and when "WebCfg - Dashboard (all)" is in your ACL, it just functions without issues (not trying to resolve the first accessible page, because index.html is requested).

**Comment by andreas-p** [comment] 2016-02-09 18:40
Just checked: WebCfg - Dashboard (all) privilege is assigned correctly.

**Comment by AdSchellevis** [comment] 2016-02-09 18:49
at group or user level?

**Comment by AdSchellevis** [comment] 2016-02-09 18:54
You could repeat the same test as I did and see if you experience issues then:

1) create a new user, no groups
2) add :  "WebCfg - System: CA Manager" and "WebCfg - Dashboard (all)"

And try to login using that new user.

**Closed** 2016-02-11 17:30 UTC

**Comment by andreas-p** [comment] 2016-02-11 18:59
I don't have any assignments on user level, all on group level. The inherited privileges show a couple of User privs, and then WebCfg - AJAX: Get Stats which is the one I'm redirected to now;  I DO consider /getstats.php as bad.

**Comment by AdSchellevis** [comment] 2016-02-11 19:29
I've tested the same on group level ("WebCfg - System: CA Manager" + "WebCfg - Dashboard (all)"), all works as expected on my end.
The default behaviour is not going to change (redirect to the first accessible page if the index isn't accessible) , if there's an issue with a specific ACL or an inability to order things correctly, I have no problem looking into it. 
If you expect help on this issue, you really need to specify the conditions better, this way it's turning into guesswork of what issue you might experience.

All tests I have performed on my end (which include the dashboard acl) always seem to get redirected to the right page, where / points to /index.php.

I hope you understand that registering issues without enough backlog for another person to reproduce it is costing too much time to track.

**Comment by andreas-p** [comment] 2016-02-12 15:21
I'd really appreciate if an issue wouldn't be closed until it's resolved; this clearly isn't. I feel reminded of unpleasant experiences of an ancestor project...

I created a new group and assigned all privileges, then removed unwanted later. This leads to 
    <group>
      <name>Standard</name>
      <description>Normal admin with slimmed menu</description>
      <gid>2000</gid>
      <priv>user-shell-access</priv>
      <priv>user-ipsec-xauth-dialin</priv>
      <priv>user-l2tp-dialin</priv>
      <priv>user-pppoe-dialin</priv>
      <priv>user-pptp-dialin</priv>
      <priv>page-getstats</priv>
      <priv>page-diagnostics-crash-reporter</priv>
      <priv>page-dashboard-all</priv>
      <priv>page-dashboard-widgets</priv>
      <priv>page-diagnostics-arptable</priv>
      ...
Removing any page-XXX privileges before page-dashboard-all or adding it as first one might be a workaround, but not a fix. Same for error redirection: if a page is inaccessible, it should display an error page, not redirect somewhere else unexpectedly.

**Comment by AdSchellevis** [comment] 2016-02-12 16:18
To be very honest, I really think you're not being very fair here... 
I did put a lot of time in your issue, which wasn't concrete enough to solve. 
We disagree about the standard behaviour if a page is not accessible, but I'm 100% sure a lot of users expect the behaviour as it is intended now (redirect to an accessible page after login).

With the last content provided I'm finally able to reproduce your issue of not being able to access /, so I will try to solve your issue, but some apology from your side would certainly be appreciated.

**Comment by andreas-p** [comment] 2016-02-12 17:28
Well I've become a little sensitive from bugs being closed prematurely from pfsense stuff. 
Requesting more specific information about my error situation is totally feasible, but somes I can't answer immediately. Why not wait for some time until there's some feedback from the bug issuer (at least some weeks)?
Please note that actually THREE issues are present:
- redirect from / to index.html, if page-dashboard-all is allowed but not page-all (this original issue)
- redirect from / to something sensible if page-dashboard all not allowed. 
- redirect to error page if arbitrary page not allowed. I'll be opening another bug on this.
