### ISSUE TITLE
DHCPv6 not possible to set domain name

### ISSUE THREAD

**Issue by 53c70r** [opnsense/core#5078] opened 2021-07-01 13:56 UTC
It is not possible to set specific domain name "foo" on interfaces differing from the global default domain name "bar" therefore unbound does not register "hostname.foo".
This setup is possible for DHCPv4 where you can specify different domain names for different interfaces.
("hostname.bar" resolves to the correct ipv6 address)

**Comment by fichtner** [comment] 2021-07-01 15:12
> therefore unbound does not register "hostname.foo".

This is really convoluted. Is this about static or dynamic leases?


Cheers,
Franco

**Comment by 53c70r** [comment] 2021-07-01 15:39
In fact static leases but I'll check tomorrow if this applies to dynamic leases too.

**Comment by fichtner** [comment] 2021-07-02 07:53
Ok, static ones I'm interested in. Dynamic ones can't really work because we can't map the clients to interfaces easily. Make sure to check 21.1.7 as I did a lot of work on this in 21.1.6/21.1.7.

**Comment by 53c70r** [comment] 2021-07-02 11:26
I am always running on latest releases.
It seams like merge #3946 does not work for me.
I would expect the same behavior as ipv4 dhcp option "domain name" set when adding one domain name like "intranet" to resolve to "hostname.intranet".
This behavior works for me perfectly for ipv4 dhcp but does not work for ipv6 static mappings.

**Comment by fichtner** [comment] 2021-07-02 11:31
Let's talk about how to reproduce your issue first before we dive into why it's broken.

**Comment by 53c70r** [comment] 2021-07-02 11:38
Global domain is set to "default".
RA is set to "Managed".
DNSSL of RA is empty.
DNSSL of DHCPv6 interface "intranet" is "intranet".
Unbound config enabled:
- Register DHCP leases 
- Register DHCP static mappings
- Register IPv6 link-local addresses

Expected behavior for static dhcpv6 lease "hostname"
hostname.intranet resolves to AAAA record.

Actual behavior:
hostname.intranet does not resolve to AAAA record.
hostname.default resolves to AAAA record.

**Comment by fichtner** [comment] 2021-07-02 12:27
Well, I don't know about resolving but I can observe it works as expected from the configuration side:

    # grep -nir intranet /var/unbound/host_entries.conf 
    47:local-data-ptr: "2003:cd:8700:2dfc::b35a givemehost.intranet"
    48:local-data: "givemehost.intranet IN AAAA 2003:cd:8700:2dfc::b35a"

The question is if DHCP leases interfere with static mappings and/or if the resolver assumption is not entirely correct.

**Comment by 53c70r** [comment] 2021-07-02 12:32
Well that is interesting for me it shows the same as yours but intranet is "default" in my config.
Is there any way to flush this configs?

**Comment by fichtner** [comment] 2021-07-02 12:33
# pluginctl dns

**Comment by fichtner** [comment] 2021-07-02 12:33
(although the outcome is probably the same)

**Comment by 53c70r** [comment] 2021-07-02 12:36
Still it uses the default instead of "intranet".
Actually how does host_entries.conf gets created?

**Comment by fichtner** [comment] 2021-07-02 12:39
Somewhere around here:

    # vi +657 /usr/local/etc/inc/plugins.inc.d/unbound.inc

**Comment by 53c70r** [comment] 2021-07-02 13:44
Actually the code in /usr/local/etc/inc/plugins.inc.d/dhcpd.inc falls into the "else" block for the if statement on line 1925, pls verify if you can reproduce if you use the following ipv6 address:
fc01:0:40:1:e51d:738a:2584:508f

**Comment by 53c70r** [comment] 2021-07-02 13:45
For me this IPv6 Address results in an empty string.

**Comment by fichtner** [comment] 2021-07-02 13:55
It looks like you are using "Allow manual adjustment of DHCPv6 and Router Advertisements" in your interface track settings?

**Comment by fichtner** [comment] 2021-07-02 14:01
@53c70r can you try this patch efe7114

**Comment by 53c70r** [comment] 2021-07-02 14:17
Does not work since ipaddrv6 is empty before the expansion.

**Comment by 53c70r** [comment] 2021-07-02 14:18
> Allow manual adjustment of DHCPv6 and Router Advertisements

Where exactly do I find this setting?

**Comment by 53c70r** [comment] 2021-07-05 07:04
Using overrides in Unbound works fine but automatic domain assignment via search list setting of dhcpv6 does not work still.

**Comment by fichtner** [comment] 2021-07-05 07:13
You have to understand that I can't possibly debug "does not work still" and my community support time is not endless.

**Comment by fichtner** [comment] 2021-07-05 10:35
Doesn't matter since you said "Does not work since ipaddrv6 is empty before the expansion."

**Comment by 53c70r** [comment] 2021-07-08 11:35
I use explicit overrides now on unbound for AAAA records. If this is the desired procedure I'll close the ticket.

**Comment by fichtner** [comment] 2021-07-08 12:02
I'm still unsure what the issue is with the dhcpd code. I haven't gotten any other reports regarding this. It would be better to close if you found a good way that works.

**Comment by fichtner** [comment] 2021-07-13 07:15
@53c70r could it be this then: d2a183a7a8ee9a

    # opnsense-patch d2a183a


Cheers,
Franco

**Comment by 53c70r** [comment] 2021-07-13 13:54
This patch fixes the problem.

**Comment by fichtner** [comment] 2021-07-13 13:55
Thanks, totally struck out on this one. Will be in 21.1.9 and 21.7-RC2.

**Closed** 2021-07-13 13:55 UTC
Labels: bug
