### ISSUE TITLE
Adding a Static Mapping from DHCPv4/6 Leases Page Redirects to the Dashboard

### ISSUE THREAD

**Issue by dlcasto** [opnsense/core#6780] opened 2023-08-25 13:51 UTC
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When attempting to add a DHCP static mapping from the Leases page, you are redirected to the OPNsense Dashboard rather than the create a static mapping page with the MAC address prepopulated.

Both DHCPv4 and DHCPv6 Leases pages are affected.

This is likely another bug due to the MVC refactor of the DHCP Leases page.

**To Reproduce**

1. Go to the Services > DHCPv4 > Leases page (or DHCPv6)
2. Click on the "+" button to add a static mapping
3. You are redirected to the Dashboard instead of the create static mapping page with the MAC address prepopulated

**Expected behavior**

The create static mapping page should be opened with the MAC address prepopulated.

**Describe alternatives you considered**

There are no alternatives since previous functionality was broken by recent changes to the Leases page.

**Environment**

OPNsense 23.7.2 (amd64, OpenSSL).

**Comment by swhite2** [comment] 2023-08-25 14:03
Duplicate of https://github.com/opnsense/core/issues/6779

**Closed by swhite2** 2023-08-25 14:03 UTC

**Comment by dlcasto** [comment] 2023-08-25 14:11
Sorry, I thought I had looked for another bug for this. I must've overlooked it.

**Comment by swhite2** [comment] 2023-08-25 14:26
I assumed so, thanks for taking the time to write it up anyway :)
