### ISSUE TITLE
Only receive direction is captured by packet capture

### ISSUE THREAD

**Issue by ghost** [opnsense/core#1632] opened 2017-05-09 18:08 UTC
Version: 17.1.6
URL: https://192.168.1.1/diag_packet_capture.php

When I use the packet capture it captured only the receive direction, but I need both directions.
Example:
20:03:24.451730 IP 192.168.1.4.16956 > 192.168.1.1.53: UDP, length 37
20:03:24.896679 IP 192.168.1.4.51763 > 192.168.1.1.53: UDP, length 44
20:03:27.903316 IP 192.168.1.4.26805 > 192.168.1.1.53: UDP, length 31

It's a bug or a feature? ;-)

**Comment by AdSchellevis** [comment] 2017-05-09 18:13
@CyberC123 what filter's have you setup?

**Comment by CyberC123** [comment] 2017-05-09 18:41
Interface 	 	 	LAN
Promiscuous 	 	unchecked
Address Family 	any
Protocol 	 	 	any
Host Address 	 	
Port  	 		53
Packet Length 	 	
Count 	 	 	100
Level of Detail 	 	full
Reverse DNS Lookup 	unchecked

**Comment by AdSchellevis** [comment] 2017-05-09 18:47
maybe your traffic is returning via another path? 
same kind of test on my end
![image](https://cloud.githubusercontent.com/assets/9783985/25867050/b9edf164-34f8-11e7-9689-06a636143c5e.png)

**Comment by CyberC123** [comment] 2017-05-09 19:39
The client is only on LAN interfaces connected. Which path can go otherwise?:(
Only on WAN interface both directions are recorded.

**Comment by AdSchellevis** [comment] 2017-05-09 19:45
You'll probably have to investigate some more on your end, it's unlikely an issue with OPNsense (checked two boxes, both working fine).

**Comment by CyberC123** [comment] 2017-05-09 19:54
okay, thanks for your quickly help.

**Comment by CyberC123** [comment] 2018-03-18 08:01
When the IDS is running on the LAN interface, captured only the receive direction.
If I disable the IDS on LAN, the packet capture operates normal.

**Comment by AdSchellevis** [comment] 2018-03-25 15:15
looks like https://github.com/opnsense/core/issues/1913 is the same issue, likely a bug in netmap preventing packets from passing through in some scenario's.

**Comment by fichtner** [comment] 2018-03-25 18:34
it this IPS mode on or off?

**Comment by CyberC123** [comment] 2018-03-26 15:57
The IPS mode is on

**Comment by AdSchellevis** [comment] 2018-08-24 07:36
Finally got a bit of time to look into this one, the issue lies in the netmap pcap support introduced in FreeBSD 11, just build a kernel with `PCAP_SUPPORT_NETMAP=0` which works like it should.

We might consider turning netmap pcap support off in our standard kernel, although this has a performance penalty. I haven't measured anything yet, but I'm not sure if netmap+pcap and suricata can work in combination. @fichtner what do you think.

**Comment by fichtner** [comment] 2018-08-24 19:27
Better to turn it off. Pcap speed is what it is. It shouldn’t be super fast to begin with. Also don’t want to taint this with netmap code paths for the obvious reason of not pulling in regressions like this one. How ironic. ;)

**Comment by AdSchellevis** [comment] 2018-08-25 08:03
@fichtner I was thinking the same thing, need to do some testing, but will commit the config change when I'm ready.

**Comment by mimugmail** [comment] 2018-08-28 10:02
I'd love to test this too, have many customer where I only see one direction when IPS is enabled, so not sure if IPS will stay untouched with this kernel change.

**Comment by AdSchellevis** [comment] 2018-08-28 10:03
@mimugmail suricata with netmap should stay as it is, IDS mode might be slower (not sure yet)

**Comment by mimugmail** [comment] 2018-08-28 10:05
But it's reproduceable that when Suricata is enabled, I can only see packets in one direction in tcpdump. As soon as I disable Suri I can see them ...

**Comment by fichtner** [comment] 2018-08-28 10:11
IMO it’s a bug that when netmap was pulled into FreeBSD 11 this feature was automatically pulled in as well. 😔

**Comment by mimugmail** [comment] 2018-08-28 10:13
Ok, just let me know when there's a kernel to test before public release. :)

**Comment by fichtner** [comment] 2018-08-28 10:14
Monday. :)

**Comment by AdSchellevis** [comment] 2018-08-28 11:32
@fichtner @mimugmail sorry, I seemed to have tested something wrong. Looking at the source it seems unlikely that pcap/netmap is responsible for this https://github.com/opnsense/src/blob/8d1a9170bd4d9d50ffeecc2c8366ec34b8ebdb02/lib/libpcap/pcap-netmap.c#L238-L239

I'll revert the changed configuration.

**Comment by AdSchellevis** [comment] 2018-08-29 16:47
For reference, just tried a stock FreeBSD 11.2 + suricata 4.0.5, which seem to have the exact same issue.

```
FreeBSD xxxx 11.2-RELEASE-p2 FreeBSD 11.2-RELEASE-p2 #0: Tue Aug 14 21:45:40 UTC 2018     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64
```

**Comment by fichtner** [comment] 2018-08-29 16:55
I‘m entirely sure this is a netmap issue where the enabled netmap mode is directing packets away from the pcap tap position possibly pushing it to the hardware directly so it’s more of a core netmap issue not providing a callback to pcap/bpf. That would maybe also mean dhclient doesn’t work on WAN if IPS is on?

**Comment by AdSchellevis** [comment] 2018-08-29 16:58
the odd thing is that I haven't seen dhcp issues yet, haven't heard about them either. just to be sure, I can do some additional testing with FreeBSD 10.4 and suricata to see if indeed all of FreeBSD 11 is suffering from the same issue.

**Comment by AdSchellevis** [comment] 2018-08-31 09:13
FreeBSD 10.4 same issue

```
FreeBSD freebsd_104 10.4-RELEASE FreeBSD 10.4-RELEASE #0 70b85f0b9a9(release/10.4.0): Thu Aug 30 18:52:18 CEST 2018     root@freebsd_104:/usr/obj/usr/src/sys/SMP  amd64
```

**Comment by AdSchellevis** [comment] 2018-08-31 10:12
ok, just went back to OPNsense version 16.7 which seemed to have the same issue. I had the assumption that this was a new issue, but I can't find a scenario where did functioned properly.

**Comment by mimugmail** [comment] 2018-08-31 10:19
What about 12.0? This netmap thing is unpredictable, same to Intel X710 cards stopping to work in IPS mode or virtio nic drivers

**Comment by AdSchellevis** [comment] 2018-09-02 14:47
Tried the latest FreeBSD 12 kernel, but unfortunately netmap doesn't appear to be working at all there (using suricata).

**Comment by fichtner** [comment] 2018-09-22 23:42
I suspect this will help https://github.com/opnsense/src/commit/6fcf512a

Every native driver and the generic driver need to be fixed in order for this to work for everybody as expected. I'm testing re(4) tomorrow so this is more or less a POC, not a full fix.

**Comment by AdSchellevis** [comment] 2018-09-23 06:48
that would be cool!

**Comment by AdSchellevis** [comment] 2018-09-23 15:58
@fichtner both em and igb suffer have the issue, I can easily test em from my dev vm.

**Comment by marjohn56** [comment] 2018-10-11 10:48
Is this related?

https://forum.opnsense.org/index.php?topic=7666.msg45184#msg45184

**Comment by fichtner** [comment] 2018-10-11 10:51
I'm not sure. Which NIC driver is this? The bug affects outgoing traffic visibility but shouldn't block packets from going out unless there is a second issue with the Netmap / Intel combination.

**Comment by mimugmail** [comment] 2018-10-11 10:55
@marjohn56 was able to reproduce with IPS enabled, when only in IDS mode it works. Must be something related to netmap

**Comment by fichtner** [comment] 2018-10-11 11:28
i211s is igb?

**Comment by marjohn56** [comment] 2018-10-11 11:31
fink so.

**Comment by marjohn56** [comment] 2018-10-11 11:36
OK, there are dhcp6 solicit packets going out. Need to rig up another ethernet port to see what's happing... another report soon..

**Comment by marjohn56** [comment] 2018-10-11 13:07
Well dhcp6c packets go out according to wireshark, and they are responded to. Internal packet capture shows no dhcp6c at all, in either direction. dhcpd logs show dhcp6c running and sending solicits.

**Comment by mimugmail** [comment] 2018-10-11 13:14
Thats exactly the issue, its not displayed via tcpdump, but in general it's working

**Comment by marjohn56** [comment] 2018-10-11 14:02
Except that it isn't, well not dhcp6c anyway. This is even more bizarre than it first appears. If IPS is turned off then the dhcp6 server responds with a REQUEST as expected, if it's turned on, then it does not respond at all, yet the solicit packets look identical to me.

**Comment by marjohn56** [comment] 2018-10-11 14:14
Here are the packet captures, just filtered on dhcp6

[packets.zip](https://github.com/opnsense/core/files/2469262/packets.zip)

**Comment by marjohn56** [comment] 2018-10-11 14:32
Let me just give the setup an method used to capture these. packet capture is directly on the switch, so I am seeing the traffic from the whole LAN side of my network, hence the filter for dhcpv6 only. Process is unset IPS, kill dhcp6c and then start capture, we see the solicit and the request respons. Now turn on IPS, kill dhcp6c and restart the capture and restart dhcp6c, we see the solicits, we never see a request response.

**Comment by fichtner** [comment] 2018-10-11 14:36
do you capture on the box or in front? maybe the server answers but suricata discards the response silently. that was always the suspicion in earlier reports regarding "IPv6 not working with IPS"

**Comment by marjohn56** [comment] 2018-10-11 14:52
Watch my lips..." Oh I should add these are wireshark captures.... not internal." :)

**Comment by fichtner** [comment] 2018-10-11 15:10
I am inclined to believe you :)

**Comment by marjohn56** [comment] 2018-10-11 15:30
However, I see no reason why the server should respond when IPS is off and ignore it when IPS is on. Perhaps someone else can verify this to prove I'm not completely barking.

**Comment by AdSchellevis** [comment] 2018-12-11 14:41
tested, it is.

**Closed** 2018-12-12 22:09 UTC
Labels: upstream

**Comment by marjohn56** [comment] 2018-12-12 22:22
Nice one Ad...
