### ISSUE TITLE
IPsec VPN Status Overview empty

### ISSUE THREAD

**Issue by scalfitura** [opnsense/core#1981] opened 2017-12-08 10:28 UTC
I'm facing the following error:

The "VPN: IPsec: Status Overview" page is completely empty, I have 7 VPN tunnels whit around 60 phase 2 entries. All VPN tunnels are working correctly.

I did of course already some research trying to solve it and I found this 'old' bug on GitHub:

https://github.com/opnsense/core/issues/634

This bug should be solved in version 16.1.9, I'm running 17.7.8 (latest version and I'm running on officially supported hardware). When I manually try to execute the following script I get this output:

root@opnsense:~ # /usr/local/opnsense/scripts/ipsec/list_status.py
Traceback (most recent call last):
  File "/usr/local/opnsense/scripts/ipsec/list_status.py", line 83, in <module>
    for sas in s.list_sas():
  File "/usr/local/opnsense/scripts/ipsec/vici/session.py", line 334, in streamed_request
    self._register_unregister(event_stream_type, False);
  File "/usr/local/opnsense/scripts/ipsec/vici/session.py", line 250, in _register_unregister
    confirm=Packet.EVENT_CONFIRM,
vici.exception.SessionException: Unexpected response type 112, expected '5' (EVENT_CONFIRM)

Restarting the "Strongswan" service doesn't solve the problem, and I can reproduce the problem on multiple devices, so it doesn't seem to be limited to 1 installation.

Is this still a bug in "Strongswan" or "just" a small GUI issue?

related forum thread: https://forum.opnsense.org/index.php?topic=6518.0

**Comment by fichtner** [comment] 2017-12-08 10:30
Hi @scalfitura,

This is probably a problem in our backend reader not supporting the latest strongSwan version fully. We'll investigate, thanks for the ping!


Cheers,
Franco

**Comment by AdSchellevis** [comment] 2017-12-12 19:32
@scalfitura can you try this?

`opnsense-patch c202aee90`

I couldn't reproduce the issue, but there was a version upgrade for the vici python binding available (https://github.com/opnsense/core/commit/c202aee9049684831d68bf4a99c88da9d2a45700)

**Comment by fichtner** [comment] 2017-12-12 19:46
Interesting, is this not shipped by strongswan itself? should be bundle this as a port / with the port instead?

**Comment by AdSchellevis** [comment] 2017-12-13 07:32
@fichtner it's available as pip package https://pypi.python.org/pypi/vici/ we could probably wrap in into a port, but as far as I know it's not there by default.

**Comment by fichtner** [comment] 2017-12-16 17:48
It was shipped in 17.7.10, I'm closing this opportunistically, but all feedback or reopening is ok. :)

**Closed by fichtner** 2017-12-16 17:48 UTC
Labels: bug
