### ISSUE TITLE
Annoying bug - openvpn running but status always red

### ISSUE THREAD

**Issue by theq86** [opnsense/core#2243] opened 2018-03-06 19:19 UTC
Hey,

for decades now I have a little problem. I'm using OpenVPN server and changed the default port.
When I boot up OPNsense in 9 of 10 boots the OpenVPN connection status tells me, there would be no server instance running. But in fact it runs. And also works. It was never a problem for me until I granted 2 other users vpn access and I really like to see when they are connected,

Somehow the ui does not correctly detect openvpn running. Any idea?

**Comment by fichtner** [comment] 2018-03-09 08:13
Is that the same as ? https://github.com/opnsense/core/issues/1931

**Comment by stefanb2** [comment] 2018-03-13 07:57
I have the same issue with a fresh 18.1 install, updated to 18.1.4. I have two OPNsense instances which are connected via a OpenVPN Peer-2-Peer (SSL/TLS) UDP tunnel, using the non-standard port `51194` on the server side. The connection is up & running, stable and several 100s of MBs have been transferred through it.

The client shows correctly that the connection is up (green icon) and the transferred byte counters get updated.

On the server side the connection is shown as offline (red icon) and the byte counters are 0.

I followed https://forum.opnsense.org/index.php?topic=6376.0 and checked the PID file:

```
# ps auxww | grep openvpn          
root    39402   0.0  0.1 1086500  7340  -  Ss   17:42      0:13.40 /usr/local/sbin/openvpn --config /var/etc/openvpn/server1.conf
# cat /var/run/openvpn_server1.pid
39402
```

That looks correct to me and I do not see any connection restarts.

BTW: I also have a 2nd OpenVPN server running, using non-standard port `51195`, for RoadWarriors. For that server the status is correctly shown as far as I can tell, i.e. the dashboard shows all connected clients.

**Comment by stefanb2** [comment] 2018-03-13 09:15
I added a log_error() call to openvpn_get_client_status() and get this:

```
Mar 13 11:03:23 | opnsense: /status_openvpn.php: OpenVPN client debug: SERVER UDP:51194 line END^M
Mar 13 11:03:23 | opnsense: /status_openvpn.php: OpenVPN client debug: SERVER UDP:51194 line 1520869830,WAIT,,,,,,^M
Mar 13 11:03:23 | opnsense: /status_openvpn.php: OpenVPN client debug: SERVER UDP:51194 line >INFO:OpenVPN Management Interface  Version 1 -- type 'help' for more info^M
```

The timestamp of the `WAIT` looks correct. The connection was started at that time from the client side.

According to https://openvpn.net/index.php/open-source/documentation/miscellaneous/79-management-interface.html `WAIT` is a client only state. Why would the server return it?

**Comment by stefanb2** [comment] 2018-03-13 13:25
OK, after a litle digging I think I found the root cause: we only send `state 1` which unfortunately only returns the last state transition, but not the full one. `state all` returns this:

```
1520869377,CONNECTING,,,,,,
1520869377,ASSIGN_IP,,10.10.254.1,,,,
1520869377,ADD_ROUTES,,,,,,
1520869440,AUTH,,,,,,
1520869440,WAIT,,,,,,
1520869441,CONNECTED,SUCCESS,10.10.254.1,86.60.143.206,6563,62.121.61.82,51194
1520869478,WAIT,,,,,,
1520869830,WAIT,,,,,,
```

So I patched /usr/local/etc/inc/plugins.inc.d/openvpn.inc like this:

```
--- /usr/local/etc/inc/plugins.inc.d/openvpn.inc.ORIG   2018-03-13 15:18:24.732693000 +0200
+++ /usr/local/etc/inc/plugins.inc.d/openvpn.inc        2018-03-13 15:20:11.717695000 +0200
@@ -1353,7 +1353,7 @@
     if ($fp) {
         stream_set_timeout($fp, 1);
         /* send our status request */
-        fputs($fp, "state 1\n");
+        fputs($fp, "state all\n");
 
         /* recv all response lines */
         while (!feof($fp)) {
```

et voilá: the status display shows up and byte counts :-)

```
SERVER UDP:51194 	XX.XX.XX.XX 	10.10.254.1 	2018-03-12 17:44:01 	321.31 MB 	56.68 MB 	up
```

**Comment by AdSchellevis** [comment] 2018-03-13 13:34
@stefanb2 nice catch, there's some more room for other improvements there as well, let me do some refactoring and offer you a new patch when it's ready.

**Comment by stefanb2** [comment] 2018-03-13 13:40
I compared the status on the client side and the server side. The time stamps show a 6 minutes difference. I.e. the client "starting time" corresponds to the time stamp of the last `WAIT` in the above list, whereas the server "starting time" is taken from the `CONNECTING` line.

**Comment by AdSchellevis** [comment] 2018-03-13 13:44
@stefanb2 can you try https://github.com/opnsense/core/commit/7ff5ec234029f345008d107fb67275d1098b29cc ?

**Comment by stefanb2** [comment] 2018-03-13 13:50
@AdSchellevis reverted to the original code and then applied the patch. Status is shown correctly now.

Time difference is still there, but that can be fixed in another change.

**Comment by AdSchellevis** [comment] 2018-03-13 13:55
ah, my mistake, "connect_time" isn't really the connect time here, it's the last event time it seems. I can move it out of the if condition, so it shows the actual time (from the last event)

**Comment by AdSchellevis** [comment] 2018-03-13 14:00
@stefanb2 this https://github.com/opnsense/core/commit/e8846eaf0cf4d214caeeecb902ce1b13897c7b9e should return the last known timestamp

**Comment by stefanb2** [comment] 2018-03-13 14:19
Works like a charm. Thank you!

**Comment by AdSchellevis** [comment] 2018-03-13 14:20
you're welcome

**Closed by AdSchellevis** 2018-03-13 14:20 UTC
Labels: bug

**Comment by theq86** [comment] 2018-03-13 20:09
I applied both patches and it seems not to work for me. I think I have to dig into it as well. But I can not before the weekend.

**Comment by stefanb2** [comment] 2018-03-14 07:27
@theq86 please start by executing `nc -U /var/etc/openvpn/server<NUMBER>.sock` on the machine. Once the connection to the management interface has been opened enter `state all` to retrieve the full status of the connection.

If your output is not similar to https://github.com/opnsense/core/issues/2243#issuecomment-372663668 then your issue must be caused by something else.

**Comment by theq86** [comment] 2018-03-15 06:28
@stefanb2 When I execute that I get an empty response

**Comment by stefanb2** [comment] 2018-03-15 06:44
Are you sure you requested the status from the correct server (that is if you have more than one server set up on your machine)? Is the tunnel active?

If this is the correct server and the tunnel is active then it is no surprise that your status display is empty: the OpenVPN server doesn't report any status for the connection! That would be a different problem then what the 2 patches fixed.

**Comment by theq86** [comment] 2018-03-15 06:50
Ok, my problem is, that even with no client connected to my OpenVPN server (I only have 1) the OPNsense tells me it cannot connect to the daemon and in the gui it appears the openvpn service is down.

**Comment by MUSHROOMHOME** [comment] 2018-04-02 10:13
OK.
What the fuck.......
I have installed a lot of different firewalls and now i try opnsense and found out that this happens.....
i have installed openVPN on two Ubuntu servers end it works like a charm (different network).
so my VPN provider is up and running no problem or issues there....
so i know that all the other releases from firewall distros (freebsd) have issues with the "promiscuous mode enabled" thats not the case here.
i am no newbee to Linux-->Debian-->Ubuntu derivate.
when i try to find the openvpn connection i get different PIDś 
root@FireWall:~ # ps auxww | grep openvpn
root    46293   0.0  0.3 1080528  2860  0  S+   12:09    0:00.00 grep openvpn
root@FireWall:~ # ps auxww | grep openvpn
root    46650   0.0  0.3 1080528  2864  0  S+   12:09    0:00.00 grep openvpn
root@FireWall:~ # ps auxww | grep openvpn
root    46924   0.0  0.3 1080528  2864  0  S+   12:09    0:00.00 grep openvpn
same hits under 3 seconds.....
i cant start killing loads of processes.
so im stuck with openvpn daemon dead......
![openvpn](https://user-images.githubusercontent.com/16468900/38192828-25423ede-366f-11e8-97e2-38bf5808320b.jpeg)

**Comment by moonman** [comment] 2018-06-17 19:55
Exactly the same problem. It happens when Peer to Peer (Shared key) is selected in client settings.
