### ISSUE TITLE
Bug: Pulldown menus - Last entry not shown completely

### ISSUE THREAD

**Issue by b2000699** [opnsense/core#848] opened 2016-03-22 19:17 UTC
OPNsense 16.1.7-amd64 & Firefox 45.0.1:

When pulling down pull-down-menus with a lot of entries, such as /Firewall/Rules/Edit rule/Protocol, the last entry at the bottom of the pull-down-menu is only shown half, i.e. it is cut off horizontally approximately at it's middle line.
Another example would be "Destination" in the same menu.

Cheers

**Comment by thelinuxfr** [comment] 2016-03-22 21:05
Same issue on OPNsense 16.7.a_648-0c6e70a3c [16.7.a_456-01b168c51]

![issue-848](https://cloud.githubusercontent.com/assets/43656/13967940/0ce02802-f07a-11e5-8bbe-2236c14b9571.png)

**Comment by fichtner** [comment] 2016-03-25 16:39
The current fix forces reversed artefacts such as the following:

<img width="121" alt="screen shot 2016-03-25 at 5 35 49 pm" src="https://cloud.githubusercontent.com/assets/1915288/14048730/52d61aaa-f2b0-11e5-8e42-467413f704df.png">

I've said this before on the PR: having the last item "cut off" looks a bit weird but is in some UIs used to indicate that further entries are available. I am unsure whether it should be fixed or kept as is.

**Comment by fichtner** [comment] 2016-04-10 17:07
some attempts have been made, but this won't fix easily. for better or for worse assume this working as intended.

**Closed by fichtner** 2016-04-10 17:07 UTC
