### ISSUE TITLE
Error message when updating from console

### ISSUE THREAD

**Issue by MNMtm** [opnsense/core#216] opened 2015-06-18 09:51 UTC
Installed a fresh OPNsense 15.1.12 on a NetBoard-A10 with 16 GB SD-card.
Issued an Upgrade from console. System started checking repository, found no new updates.
Restarted webconfigurator and prompted a kernel update available.
System started downloading new kernel and base files and continued installing the update.
However, while applying base-15.1.12-amd64.txz, the system reported: ./mnt/: Can't restore time and after a while:

tar: Error exit delayed from previous errors.
failed

Now I'm not sure if the base-15.1.12-amd64.txz was applied successfully.

Screen dump:
=======================================================
Enter an option: 12

This will automatically fetch all available updates, apply them,
and reboot if necessary.  Proceed with this action? [y/N]: y

Updating OPNsense repository catalogue...
Fetching meta.txz: 100%    1 KiB   1.5kB/s    00:01
Fetching packagesite.txz: 100%   64 KiB  65.0kB/s    00:01
Processing entries: 100%
OPNsense repository update completed. 217 packages processed.
Updating OPNsense repository catalogue...
OPNsense repository is up-to-date.
All repositories are up-to-date.
Updating database digests format: 100%
Checking for upgrades (81 candidates): 100%
Processing candidates (81 candidates): 100%
Checking integrity... done (0 conflicting)
Your packages are up to date.
Checking integrity... done (0 conflicting)
Nothing to do.
Nothing to do.

Restarting webConfigurator...done.

There are updates available.
!!!!!!!!!!!!! ATTENTION !!!!!!!!!!!!!!!!!
! A kernel/base upgrade is in progress. !
!  Please do not turn off the system.   !
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Fetching kernel-15.1.12-amd64.txz... ok
Fetching base-15.1.12-amd64.txz... ok
Fetching base-15.1.12-amd64.obsolete... ok
Applying kernel-15.1.12-amd64.txz... ok
Applying base-15.1.12-amd64.txz... ./mnt/: Can't restore time

tar: Error exit delayed from previous errors.
failed

*** Welcome to OPNsense 15.1.12-eac7cdde6 (amd64) on OPNsense ***

 WAN (em1)       -> v4/DHCP4: 172.18.0.188/24
 LAN (em0)       -> v4: 192.168.1.1/24

 0) Logout                             7) Ping host
 1) Assign Interfaces                  8) Shell
 2) Set interface(s) IP address        9) pfTop
 3) Reset the root password           10) Filter Logs
 4) Reset to factory defaults         11) Restart web interface
 5) Reboot system                     12) Upgrade from console
 6) Halt system                       13) Restore a configuration

Enter an option:
=======================================================

**Comment by fichtner** [comment] 2015-06-18 10:04
Hi, I'll try to reproduce this. A small issue remained that did not register the kernel and base version as the new firmware system expects it to which leads to the reapplication of the existing kernel and base, but you'll likely run into the /mnt issue anyway later. Your current system is ok and up to date in any case. I'll report back soon.

**Comment by fichtner** [comment] 2015-06-18 10:10
Tried this on a VM and the A10, but couldn't reproduce. Is this an USB serial install or a nano image directly dd'ed to the SD card?

**Comment by fichtner** [comment] 2015-06-18 10:18
Having no luck even with "noatime". The following in the shell should work (no reboot necessary):

    # rm -r /mnt
    # opnsense-update -bk
    # opnsense-update -bk

The second invoke should let you know there is nothing more to do.

**Comment by MNMtm** [comment] 2015-06-18 10:46
I installed OPNsense using the USB serial install, quick install option.
Forgot to mention that I set OPNsense to use memory disks for /tmp (128MB) and /var (256MB), prior to initiating the update.

**Comment by fichtner** [comment] 2015-06-18 10:49
Ok, did you also reboot to make the /tmp and /var changes permanent?

**Comment by MNMtm** [comment] 2015-06-18 11:19
Not sure, but I think I didn't.
Tried the same steps after setting /tmp and /var to memory disks and a reboot on a PcEngines APU and it updates the kernel without any warnings or errors.
Will try another update test on a NetBoard-A10 with 16GB SD-card, WITHOUT setting de /tmp and /var first.

**Comment by fichtner** [comment] 2015-06-18 11:21
Great, thanks for your help so far. :)

**Comment by MNMtm** [comment] 2015-06-19 08:29
Odd... Haven't been able to reproduce the problem myself.
Scenarios I've tried:
- clean install, no adjustments to /tmp and /var settings: kernel update okay;
- clean install, set /tmp to 128MB and /var to 256MB memory disk, no reboot: kernel update okay;
- clean install, set /tmp to 128MB and /var to 256MB memory disk, with reboot: kernel update okay.

So what went wrong in yesterday's installation, I don't know.

**Comment by fichtner** [comment] 2015-06-19 13:07
Maybe a hiccup with ntpd resetting time? I am in the dark here.

It's the only occurrence that I know of since we've implemented the firmware upgrades.

**Comment by jschellevis** [comment] 2015-06-19 13:43
Close?

> Op 19 jun. 2015, om 15:07 heeft Franco Fichtner <notifications@github.com> het volgende geschreven:
> 
> Maybe a hiccup with ntpd resetting time? I am in the dark here.
> 
> It's the only occurrence that I know of since we've implemented the firmware upgrades.
>

**Comment by fichtner** [comment] 2015-06-19 16:24
Up to @MNMtm :)

**Comment by jschellevis** [comment] 2015-06-23 15:41
I spoke with him and he does not now what happened the first time.. problem can't be reproduced. 
I'll close it for now. Can always reopen if there is a need for it.

**Closed by jschellevis** 2015-06-23 15:41 UTC
Labels: bug
