### ISSUE TITLE
dpinger fails to start with DHCPv6 on WAN

### ISSUE THREAD

**Issue by abplfab** [opnsense/core#3583] opened 2019-07-18 09:21 UTC
If WAN is set to DHCPv6 (with options "Request only an IPv6 prefix", "Prefix delegation size 60") dpinger fails to start with a PHP Error.
In my case WAN gets IPv6 fe80::20d:b9ff:fe48:58bc from the cable modem.
Workaround: set "Monitor IP" on the WAN_DHCP6 Gateway to some reachable IPv6 Address
OPNsense 19.7

**Comment by maurice-w** [comment] 2019-07-18 16:40
I have the same issue, it affects all gateways with link-local addresses (including static ones): https://forum.opnsense.org/index.php?topic=13515.0
Seems to be caused by improper handling of zone indices. Worked in 19.1.

**Comment by mr44er** [comment] 2019-07-19 01:14
Same here.

I had suddenly **2** stopped instances of dpinger for WAN_DHCP6 which can't work.

My workaround so far was disabling interface, delete the double entries for gateways, reboot, enabling interface, gateway monitoring off.

**Comment by mr44er** [comment] 2019-07-19 15:34
There's something more going on with the gateways and giving priority.

I played a bit around and noticed that I can't set priority for dynamically created GWs over PPPoE. ipv4 and ipv6 GWs are set to 254 after connection goes up.

I changed to lower level (50) to give my PPPoE higher prio. It doesn't let me do this, because far gateway is unticked (GW-IP from ISP). Second try with activating far gateway does create a new gateway (with GW-IP given from ISP set to static) and whole connection goes nuts, because both dynamically created GWs are completely gone.

I deactivated PPPoE-IF completely and you can see (red dot) the leftover GW-IP.

Second thing is wrong displaying in WebIF. vigornic shows as active, but never was ticked as upstream-GW, but gw_winsim is.

Change default gw is activated under system->settings if that info is needed.

![Screenshot_20190719_164740](https://user-images.githubusercontent.com/46787531/61547013-ccb18a80-aa4a-11e9-98bb-745d58b74ecf.png)

**Comment by maurice-w** [comment] 2019-07-27 13:29
Seems to be fixed in 19.7.1 (well, works for me). I guess this line from the changelog refers to it:
`system: scoped IPv6 "%" could confuse mwexecf(), use plain mwexec() instead`
Can someone confirm and close?

**Comment by mr44er** [comment] 2019-07-27 13:33
Yeah, works now for me, too but I have now a new one with 2 WANs. :)
-> https://github.com/opnsense/core/issues/3601

**Comment by fichtner** [comment] 2019-07-27 13:54
Thanks for confirming.

**Closed by fichtner** 2019-07-27 13:54 UTC
Labels: bug
