### ISSUE TITLE
GUI: Firewall Logs - wrong icon for "pass"

### ISSUE THREAD

**Issue by fraenki** [opnsense/core#269] opened 2015-07-22 08:58 UTC
I've noticed that under _Status -> System logs -> Firewall_ the icon for "blocked" and "passed" traffic is the same:

![pass_not_block](https://cloud.githubusercontent.com/assets/909706/8821740/45a6572c-3060-11e5-8acc-11149ab970ae.png)

I would expect that blocked traffic is indicated by a red "x" and passed traffic by a green tick/check.

**Comment by fabianfrz** [comment] 2015-07-22 11:19
should be possible - I also dislike the '/'

**Comment by fabianfrz** [comment] 2015-07-22 12:05
created a pull request - please check it

**Comment by fabianfrz** [comment] 2015-07-22 12:11
this is a duplicate of #206

**Comment by fichtner** [comment] 2015-07-22 12:31
Thanks, closing now.

**Closed by fichtner** 2015-07-22 12:31 UTC
