### ISSUE TITLE
Problems while setting up VLAN on WAN

### ISSUE THREAD

**Issue by havarh** [opnsense/core#51] opened 2015-02-19 23:18 UTC
PS! I've tested this set up on pfSense, and it works there. I've tested with the same config file.

I've tried to set up a VLAN on the WAN interface to use as an admin interface. I have a fixed IP on the VLAN, and have added firewall rules for remote admin on that interface. The VLAN is tagged on the switch port. Also tried with trunking. This firewall is behind a FortiGate firewall, where the VLAN is defined.
I've uploaded a test config file, which I haven't actually tested yet, but it's a similar setup as the one I had problems with.
https://dl.dropboxusercontent.com/u/4412405/config-OPNsense.localdomain-20150220000819-VLAN-problems.xml
PS! There is, of course, no DHCP server set up on this VLAN.

![admin access on vlan42 - rules](https://cloud.githubusercontent.com/assets/11080415/6278202/4c7eb9a6-b895-11e4-93e8-3d546b2307e6.png)

**Comment by havarh** [comment] 2015-02-19 23:24
On my pfSense setup I later set up another VLAN on the bge0 interface, and I'm now using that as the WAN interface.
That is, under "Interfaces: Assign network ports", I've set up "VLAN 45 on bge0" as the WAN interface.
The bge0 network port isn't assigned to any interfaces.

**Comment by jschellevis** [comment] 2015-02-20 10:18
I have tested with both your configuration file as with a fresh setup and my own similar but manual configuration. In any case the vlan for remote access on the WAN port works fine and I can ping and access the GUI. 

The issue you had is probably caused by something else in your original configuration file.
I would suggest to try and set it up manually without importing pfSense configuration file and see if that works.

Since I cannot reproduce the issue I will close it for now. Feel free to reopen it if you find the issue to be still present and can provide additional information to test it. Thanks for your feedback!

**Closed by jschellevis** 2015-02-20 10:18 UTC

**Comment by havarh** [comment] 2015-02-20 15:21
This was a brand new config file. I didn't import it from pfSense. What I did was set up the exact same config on pfSense. But I'll try to experiment more on this when I have the time.

**Comment by jschellevis** [comment] 2015-02-20 17:05
Ok perhaps wait until 15.1.6 and test again... Thanks for your help.
