### ISSUE TITLE
Web UI performance decreases with many static routes

### ISSUE THREAD

**Issue by doublej74** [opnsense/core#333] opened 2015-08-21 04:26 UTC
Since all the static routes are maintained in the config.xml, this file grows with new static routes.
I'm in a situation where I have 3500+ static routes, so the xml becomes around 20000 lines (routing countries IP ranges).

Since the file is rewritten with every change and read many times during page loads, the UI becomes very slow. Response times of 20/30 seconds on a dual core.

Since my scenario is probably not main stream, it might be considered a minor issue.
However, the config.xml's size is an influence to the performance of the web ui.

**Comment by fichtner** [comment] 2016-02-16 05:34
The issue is known for all the static PHP pages, the MVC pages behave better in that regard, but until we've migrated all functionality it will take time. Closing this as this is too broad of a meta-issue to be tracked (or closed in the next year).

**Closed by fichtner** 2016-02-16 05:34 UTC
