### ISSUE TITLE
Alias DropDown is truncated in Internet Explorer 11 on Windows 8

### ISSUE THREAD

**Issue by GuybrushX** [opnsense/core#773] opened 2016-02-11 08:30 UTC
![opnsense - truncated dropdown](https://cloud.githubusercontent.com/assets/17174280/12971990/8ee9b4f6-d0a1-11e5-98a6-a5e11b6fdf9f.png)

As you see the small orange bar at the bottom - I can only select this item when I know the name and search for it.

At the moment there are 3 items in the aliases list and I didn't test any other browsers so far.

The screenshot was taken in the "Outbound NAT -> Edit" rule. Both the Source and Destination DropDown lists are affected.

**Comment by AdSchellevis** [comment] 2016-02-12 09:04
Can you test if this issue exists on other pages using the same dropdown option? It might be IE specific for the selectpicker component.
We're using this component for the searchable select boxes https://github.com/silviomoreto/bootstrap-select

**Comment by GuybrushX** [comment] 2016-02-22 19:29
I checked again: I'm using Windows 8 with IE11 and it is wrong also for the dropdown in Firewall: NAT: Port Forward for interfaces and the protocol.

So it looks like it's wrong for most lists which need a scrollbar. As you see the bottom arrow isn't fully visible in my screenshot, too.

One dropdown with a scrollbar which is working is under OpenVPN -> Servers -> Encryption algorithm.

I also added the IP of the OPNsense box to the trusted sites but without a difference.

Hope that helps to track that issue down.

**Comment by AdSchellevis** [comment] 2016-02-23 15:11
@GuybrushX Thank you very much for your feedback, I found the issue, it seemed to be caused by a missing height property on a span tag. 
(source of issue https://github.com/opnsense/core/blob/16.1/src/opnsense/www/js/bootstrap-select.js#L768-L769)

The following commit will close this issue.

**Closed** 2016-02-23 15:12 UTC
