### ISSUE TITLE
24.7 Dashboard widgets dont load.

### ISSUE THREAD

**Issue by awptechnologies** [opnsense/core#7662] opened 2024-07-26 19:35 UTC
After upgrade to 24.7 the new dashboard is beautiful. The only issue is alot of them fail to load with a red !  Im guessing they are still working out some bugs but i figured i would post just incase someone else is having issue or if the developers dont know about it. There are no steps to reproduce just login and the dashboard fails to load. This is over my reverse proxy and when i go to the gui through the ip address.

Type 	opnsense 	
Version 	24.7_5 	
Architecture 	amd64 	
Commit 	6578c5a18 	
Mirror 	https://pkg.opnsense.org/FreeBSD:14:amd64/24.7 	
Repositories 	OPNsense 	
Updated on 	Fri Jul 26 03:03:38 EDT 2024 	
Checked on 	Fri Jul 26 15:31:19 EDT 2024

**Comment by AdSchellevis** [comment] 2024-07-27 06:53
sounds like a duplicate of https://github.com/opnsense/core/issues/7651

**Closed by AdSchellevis** 2024-07-27 06:53 UTC
Labels: incomplete
