### ISSUE TITLE
DHCP6 service not handing out address after some time

### ISSUE THREAD

**Issue by user-0209** [opnsense/core#4770] opened 2021-03-01 12:52 UTC
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**
After some time the DHCP6 service is not handing out IPv6 address after some time (which is a couple of hours).

I'm running a dual stack network with several sub-networks, all tracking the WAN interface. For my NAS I made a static reservation, both in IPv4 and IPv6. After some time the NAS lost the IPv6 address. Restarting the DHCP6 service cures the problem after a couple of minutes.

The problem was also there in previous versions. I hoped to circumvent it with a cron job that restarts opnSense every night. However, it happened again after only few hours of uptime.  

For easier testing of all IPv6 management, I had reduced default lease time and max lease time to 600/900 secs.

**To Reproduce**

1. make a static reservation for some host
2. observe the hosts IPv6 address, verify it gets the reservation assigned
After some time the reserved IP address is not with the host anymore

**Expected behavior**

The host should retain the reserved address.

**Describe alternatives you considered**

Rebooting opnSense once a day did not cure the problem.
Restarting DHCP6 service manually reassigns the address.
Restarting radvd alone doesn't help.

**Screenshots**
When host lost the address:
`2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether **:**:**:**:**:** brd ff:ff:ff:ff:ff:ff
    inet 172.27.12.77/24 brd 172.27.12.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 2a02:****:****:***c:dea6:32ff:fe60:c351/64 scope global dynamic mngtmpaddr noprefixroute 
       valid_lft 86374sec preferred_lft 14374sec
    inet6 fe80::dea6:32ff:fe60:c351/64 scope link 
       valid_lft forever preferred_lft forever
`
After restarting DHCP6:
`2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether **:**:**:**:**:** brd ff:ff:ff:ff:ff:ff
    inet 172.27.12.77/24 brd 172.27.12.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 2a02:****:****:***c::77/128 scope global dynamic noprefixroute 
       valid_lft 598sec preferred_lft 373sec
    inet6 2a02:****:****:***c:dea6:32ff:fe60:c351/64 scope global dynamic mngtmpaddr noprefixroute 
       valid_lft 86369sec preferred_lft 14369sec
    inet6 fe80::dea6:32ff:fe60:c351/64 scope link 
       valid_lft forever preferred_lft forever
`
**Relevant log files**
DHCP6 related log entries since restart:
`2021-03-01T05:01:33	opnsense[65486]	/usr/local/etc/rc.routing_configure: The DMZ_DHCP6 monitor address is empty, skipping.
2021-03-01T05:01:33	opnsense[65486]	/usr/local/etc/rc.routing_configure: The DMZ_DHCP6_test monitor address is empty, skipping.
2021-03-01T05:01:25	opnsense[78750]	/usr/local/etc/rc.newwanipv6: The DMZ_DHCP6 monitor address is empty, skipping.
2021-03-01T05:01:25	opnsense[78750]	/usr/local/etc/rc.newwanipv6: The DMZ_DHCP6_test monitor address is empty, skipping.
2021-03-01T05:01:16	opnsense[35345]	/usr/local/etc/rc.bootup: The DMZ_DHCP6 monitor address is empty, skipping.
2021-03-01T05:01:16	opnsense[35345]	/usr/local/etc/rc.bootup: The DMZ_DHCP6_test monitor address is empty, skipping.
2021-03-01T05:01:15	dhcp6c[20668]	dhcp6c REQUEST on em0 - running newipv6
2021-03-01T05:01:14	dhcp6c[48410]	RTSOLD script - Sending SIGHUP to dhcp6c
2021-03-01T05:01:13	dhcp6c[419]	transmit failed: Can't assign requested address
2021-03-01T05:01:12	dhcp6c[24833]	RTSOLD script - Starting dhcp6 client
`

**Additional context**

Client is a Raspberry Pi4 running Ubuntu 20.04

**Environment**
OPNsense 21.1.1-amd64FreeBSD 12.1-RELEASE-p13-HBSDOpenSSL 1.1.1i  8 Dec 2020
CPU type | Intel(R) Core(TM) i3-4010U CPU @ 1.70GHz (4 cores)
OPNsense is running in a VM on this host (home network)

**Comment by maurice-w** [comment] 2021-03-01 15:38
Duplicate of #4691?

**Comment by fichtner** [comment] 2021-03-01 15:42
I think so, yes.

**Closed** 2021-09-21 13:42 UTC
Labels: support
