### ISSUE TITLE
gateway status monitoring does not work - apinger: Exiting on signal 15

### ISSUE THREAD

**Issue by brillb** [opnsense/core#1941] opened 2017-11-19 18:26 UTC
Version:  OPNsense 17.7.7_1-amd64

I have different gateways with more/less preferable paths to different routes.  I use gateway groups to group my gateways and allow me to specify first preference, 2nd preference, etc to each destination.  When one gateway goes down, the config should allow the opnsense router to roll easily to the next preference device.
However, apinger gateway monitoring does not work.  My log entries are filled with:
apinger: Exiting on signal 15.
this happens roughly once a minute.  apinger never marks any gateway is down.  If I want to roll to a backup gateway, I have to manually mark it as down.

Here's a full example log:

Nov 19 13:21:40 | apinger: Starting Alarm Pinger, apinger(44510)
Nov 19 13:21:40 | apinger: Exiting on signal 15.
Nov 19 13:21:04 | apinger: rrdtool respawning too fast, waiting 300s.
Nov 19 13:21:04 | apinger: Error while feeding rrdtool: Broken pipe
Nov 19 13:20:04 | apinger: Starting Alarm Pinger, apinger(7725)
Nov 19 13:20:04 | apinger: Exiting on signal 15.
Nov 19 13:19:28 | apinger: rrdtool respawning too fast, waiting 300s.
Nov 19 13:19:28 | apinger: Error while feeding rrdtool: Broken pipe
Nov 19 13:18:28 | apinger: Starting Alarm Pinger, apinger(7139)
Nov 19 13:18:28 | apinger: Exiting on signal 15.
Nov 19 13:17:52 | apinger: rrdtool respawning too fast, waiting 300s.
Nov 19 13:17:52 | apinger: Error while feeding rrdtool: Broken pipe
Nov 19 13:16:52 | apinger: Starting Alarm Pinger, apinger(41697)
Nov 19 13:16:52 | apinger: Exiting on signal 15.

And a sample gateway status:

WAN_DHCP | 192.168.100.1 | 203.24.49.7 | 0.0 ms | 0.0 % | Online | Interface WAN_DHCP Gateway

(note that the above gateway is actually down right now, even though it is reported as "online" - apinger just isn't working)

**Comment by AdSchellevis** [comment] 2017-11-19 18:37
likely an issue with rrdtool, is there other software installed on this machine?

**Comment by brillb** [comment] 2017-11-19 18:41
Nope, totally default install of opnsense

**Comment by brillb** [comment] 2017-11-19 18:42
the graphs under "reporting>health>quality" are all blank, as well.  Although the other tabs (packets, system, etc) do have good graphs.

**Comment by brillb** [comment] 2017-11-19 19:37
I disabled rrdtool in reporting>settings, then rebooted the router.  Same result, apinger exiting on signal 15 and error while feeding rrdtool, broken pipe.  I'd think with rrdtool off it should disable any attempt to report?

Is there a workaround where I can disable apinger's feed out to rrdtool?

**Comment by fichtner** [comment] 2017-11-19 19:40
Can you try to reinstall apinger and rrdtool from the firmware packages tab and reboot?

apinger has some built-in funkiness for rrdtool, not sure if it fully disables or not.

**Comment by brillb** [comment] 2017-11-19 20:31
Tried it.  No luck.  apinger actually seems to work fine (well, not crash) as long as the gateway is up.  As soon as the gateway goes down, though, the signal 15 crash happens.

**Comment by brillb** [comment] 2017-12-13 22:00
Any thoughts? Anything I can check or try?

**Comment by fichtner** [comment] 2017-12-14 07:36
@brillb can you tell us more about your multi-wan setup, specifically wan parst, their configuration and upstream devices (routers, modems, etc.) to make a useful assessment

**Comment by brillb** [comment] 2017-12-17 05:27
The router is a physical machine with four Intel gigabit nics.  One to the inside, one to a cable modem (primary), and one to a dsl modem (backup).  It's just simple DHCP on both outside interfaces.  

I have it set to ping the dns server at each ISP as the tracking ip for each interface, and /32 route entries for the two dns servers to make sure that the route to each dns server uses the correct interface.

The two gateways are in a gateway group with one at tier 1 and the other at tier 2. 

If I unplug the primary interface so it goes hard down everything fails over fine.  It's just when apinger needs to be used that there is a problem.  I think the problem is just that apinger crashes on this platform (Celeron j1900) if it doesn't get a ping reply. The other logic seems to work fine.

**Comment by fichtner** [comment] 2017-12-21 16:51
Well, something is certainly off here. Do you require RRD graphing? You could try to turn this off to see if it helps...

**Comment by brillb** [comment] 2017-12-21 19:10
Nope, don't require RRD.  I've tried turning RRD and all reporting off, and it crashes exactly the same either way.  I think the rrdtool pipe messages are probably misdirecting, it seems like apinger just can't handle the "failed" state.

**Comment by fichtner** [comment] 2017-12-27 16:57
Hmm, maybe it's finally time to move from apinger to dpinger. I have no idea what's going on here. :(

**Comment by cordelster** [comment] 2018-02-24 05:04
I have the same issue with apinger producing the same message with OPNs 18.1.2_2
Have attempted disabling rrd, disabling Gateway monitoring, and half dozen other settings that I believed might have any potential, yet the apinger error persists in both my gateway logs and through syslog.
  
Logs:
`````
Feb 23 20:52:13 | apinger: rrdtool respawning too fast, waiting 300s.
Feb 23 20:51:13 | apinger: Error while feeding rrdtool: Broken pipe
Feb 23 20:47:13 | apinger: rrdtool respawning too fast, waiting 300s.
Feb 23 20:46:13 | apinger: Error while feeding rrdtool: Broken pipe
Feb 23 20:42:13 | apinger: rrdtool respawning too fast, waiting 300s.
`````
```
Versions | OPNsense 18.1.2_2-amd64FreeBSD 11.1-RELEASE-p6OpenSSL 1.0.2n  7 Dec 2017
CPU Type | AMD GX-412TC SOC (4 cores)
PCengines APU3
Single WAN no failover configured.
```

**Comment by brillb** [comment] 2018-02-24 05:33
As a follow up, same for me too, also upgraded to 18.1.2.  Importantly, this isn't just cosmetic - the failover doesn't work right still, as well.

**Comment by cordelster** [comment] 2018-02-24 18:39
I think I got this to finally go away.
 I went through all my interface setting through the GUI and clicked save. In the Reporting/Setting/Reports window, I could see an interface "opt1" that did not exist in my configuration. Once I went through all the interface settings I could find and resaved them, I was able to go into Reporting/Setting and reset RRD and the opt1 interface dropped from the reports table. Clicked save, and it's been about 12 hours now without a single error. Please assume if you have no followup I have this corrected.
I am subscribed so if anyone requires any more detail, I certainly respond.
But in general, I just went through almost every setting in the system and resaved everything I found with interfaces, then reset RRD Data and saved.

**Comment by cordelster** [comment] 2018-02-25 04:08
Unfortunately it is back and I spoke to soon as you can see from the log:

```
Feb 23 21:42:09 sec apinger: Exiting on signal 15.
Feb 23 21:42:09 sec apinger: Starting Alarm Pinger, apinger(54972)
Feb 24 13:49:17 sec apinger: Exiting on signal 15.
Feb 24 13:49:17 sec apinger: Starting Alarm Pinger, apinger(46739)
Feb 24 13:50:07 sec apinger: Error while feeding rrdtool: Broken pipe
Feb 24 13:51:07 sec apinger: rrdtool respawning too fast, waiting 300s.
Feb 24 13:56:17 sec apinger: Error while feeding rrdtool: Broken pipe
Feb 24 13:57:17 sec apinger: rrdtool respawning too fast, waiting 300s.
```

So is the rouge interface showing in Reporting|Settings|Collected Reports table attached highlighted image...
![opns-reporting-settings](https://user-images.githubusercontent.com/4791031/36637974-393a48d6-199c-11e8-97df-46b64f53bc7c.jpeg)

apinger.conf looks as expected with only one interface that's correctly populated.
[apinger.txt](https://github.com/opnsense/core/files/1755712/apinger.txt)

How do I go about trying to find how this keeps getting populated?
I'm more than willing to assist in chasing this down, I just need  some pointers on where to approximately start looking. 


```
root@sec:/home/cx # ps -Axl |grep ping
  100 24129 34350   0  20  0 1099884   5172 select   S     -      0:04.76 (pinger) (pinger)
  100 34831 34350   0  20  0 1099884   5836 select   S     -      0:03.86 (pinger) (pinger)
  100 40627 34350   0  20  0 1099884   4988 select   S     -      0:05.14 (pinger) (pinger)
    0 46739     1   0  20  0 1074072   2776 select   Ss    -      0:03.43 /usr/local/sbin/apinger -c /var/etc/apinger.conf
  100 65045 34350   0  20  0 1099884   5840 select   S     -      0:02.68 (pinger) (pinger)
  100 88631 34350   0  20  0 1099884   5844 select   S     -      0:01.35 (pinger) (pinger)
    0 97831 75160   0  20  0 1080528   2860 piperd   S+    0      0:00.01 grep ping
```

**Comment by tpcr** [comment] 2018-03-02 16:40
apinger is not consistent for me. With two identical boxes with gateway monitoring off, apinger shows up on one box as a disabled server and has errors in the log and the other box does not show apinger at all.
Please get rid of apinger or replace with dpinger, or at least tell me how to uninstall apinger. I do not want it in my OPNsense box.

**Comment by fichtner** [comment] 2018-03-02 16:59
Gateway monitoring is off by default. Probably always has been for us... If it's disabled apinger is never started.

If anyone would like to start porting dpinger, please do.

**Comment by fichtner** [comment] 2018-03-02 17:01
Furthermore, I have no idea how to reproduce this. I use gateway monitoring in my installs and this never happened so it's some sort of setup or ISP oddity?

**Comment by brillb** [comment] 2018-03-02 17:02
I don't think ISP, both of my wan interfaces are just DHCP Ethernet.

**Comment by fichtner** [comment] 2018-03-02 17:03
Same for me. What's your gateway log file?

**Comment by fichtner** [comment] 2018-03-02 17:05
Sorry, I meant var/etc/apinger.conf

**Comment by fichtner** [comment] 2018-03-02 17:08
dmesg output would also help, it would indicate segfaults

**Comment by tpcr** [comment] 2018-03-02 18:08
Seems that a ghost gateway must have been present. I deleted the gateway and now it it fine.
I assume this happened because I manually entered the gateway after the install, then applied the configuration restore which added it in again. All is working fine now. Thanks

**Comment by ctshl** [comment] 2018-03-06 14:41
I had the same issue on a newly installed 18.1.3 today. I deleted the ghost gateway from the XML Backup and restored the gateway configuration to opnsense. Now the apinger is working.....

<gateways>
    <gateway_item>                                   ===> ghost gateway
      <descr>Interface OPT1 Gateway</descr>
      <ipprotocol>inet</ipprotocol>
      <interface>opt1</interface>
      <gateway>192.168.1.1</gateway>
      <monitor_disable>1</monitor_disable>
      <name>GW_OPT1</name>
      <interval>1</interval>
      <weight>1</weight>
    </gateway_item>
    <gateway_item>
      <interface>opt1</interface>
      <gateway>192.168.1.1</gateway>
      <name>GW_OPT1</name>
      <weight>1</weight>
      <ipprotocol>inet</ipprotocol>
      <interval>1</interval>
      <descr>Interface OPT1 Gateway</descr>
      <avg_delay_samples/>
      <avg_loss_samples/>
      <avg_loss_delay_samples/>
      <monitor>213.xxx.xxx.xxx</monitor>
    </gateway_item>
    <gateway_item>
      <interface>wan</interface>
      <gateway>10.212.178.1</gateway>
      <name>WANGW</name>
      <weight>1</weight>
      <ipprotocol>inet</ipprotocol>
      <interval/>
      <descr>WAN Gateway</descr>
      <avg_delay_samples/>
      <avg_loss_samples/>
      <avg_loss_delay_samples/>
      <monitor>217.xxx.xxx.xxxx</monitor>
      <defaultgw>1</defaultgw>
    </gateway_item>
    <gateway_group>
      <name>WAN_Trunk</name>
      <item>GW_OPT1|2|address</item>
      <item>WANGW|1|address</item>
      <trigger>down</trigger>
      <descr/>
    </gateway_group>
  </gateways>

**Comment by tpcr** [comment] 2018-03-06 15:11
18.1.3 must not be erasing/replacing the values when a restore configuration takes place. Only affected the Gateway because that was the only entered item after the fresh install.

**Comment by cordelster** [comment] 2018-03-06 21:43
What would be the advisable method for posting output from dmesg and more importantly various configs for review, or should I just sanitize them and put them here?
Any preference?

**Comment by jasonblewis** [comment] 2018-03-06 22:48
I believe I have this issue. @tpcr could you outline how one would go about findind and deleting the ghost gateway?

**Comment by tpcr** [comment] 2018-03-07 00:00
Just delete the gateway. It should reappear.

**Comment by aroldo-biz** [comment] 2018-03-29 13:13
After making several reinstallations and testing on VMware virtual machines, Xenserver and Bare metal.

I came to the conclusion that when active an interface to receive DHCPV6 the Apinger crashes and restarts constantly with the log output  "Apinger: Exiting on signal 15. "


System Information:
FreeBSD 11.1-RELEASE-p8  76d691b36(stable/18.1)
OPNsense 18.1.5-57287f86d [18.1-612a96e2e] OpenSSL 1.0.2n  7 Dec 2017 (amd64)
Plugins os-dyndns-1.6

**Comment by finish06** [comment] 2018-04-15 18:04
I am experiencing a similar issue.  Same "Apinger: Exiting on signal 15", however I have no rrd errors showing in the Gatway logs.  How would you recommend I proceed forward?  I have confirmed both gateways work, however the failover from fiber to LTE is not working.  It seems that the default gateway is not being changed.

**Comment by fichtner** [comment] 2018-04-16 06:37
We are about to include dpinger as an alternative to apinger. However, it could be that the error may be a spurious error of an underlying configuration mishap we have not yet found, which means two things: (a) it could be fixed by configuration alone and (b) will not be fixed by merely switching to dpinger.

**Comment by aroldo-biz** [comment] 2018-04-16 13:41
I like the philosophy of the project OPNsense than the Pfsense, but I did not get a stable operation of the Multi-WAN in these last versions tested and several 17.7 to the 18.1.6 and does not work.

Unfortunately after 1 month of testing my deadline is over and I have to leave the OPNsense.

**Comment by fichtner** [comment] 2018-04-16 13:50
I fully understand. :)

**Comment by fichtner** [comment] 2018-08-09 21:34
Dpinger was integrated a few months back and may even supersede Apinger in 19.1.

**Closed by fichtner** 2018-08-09 21:34 UTC
Labels: support
