### ISSUE TITLE
OpenSSH daemon does not bind correctly to IPv6

### ISSUE THREAD

**Issue by JulienDlq** [opnsense/core#5182] opened 2021-08-28 13:45 UTC
**Describe the bug**

When I activate IPv6 on OPNsense, and OpenSSH daemon, here is the result in /usr/local/etc/ssh/sshd_config for ListenAddress
```
ListenAddress 192.168.100.2
ListenAddress 2001:db8::dead:beaf:100:1
ListenAddress 127.0.0.1
ListenAddress ::1
```
Here is the result of netstat and I can't ssh to OPNsense with IPv6
```
user@OPNsense:~ % sudo netstat -Wnaf inet6 | grep '\.22 '
tcp6       0      0 ::1.22                 *.*                    LISTEN     
```
But, if I modify ListenAddress like this
```
ListenAddress 192.168.100.2
ListenAddress [2001:db8::dead:beaf:100:1]
ListenAddress 127.0.0.1
ListenAddress ::1
```
Everything is okay in netstat and I can ssh to OPNsense with IPv6
```
user@OPNsense:~ % sudo netstat -Wnaf inet6 | grep '\.22 '
tcp6       0      0 2001:db8::dead:beaf:100:1.22         2001:db8::dead:beaf:100:0.46894      ESTABLISHED
tcp6       0      0 2001:db8::dead:beaf:100:1.22         *.*                                           LISTEN     
tcp6       0      0 ::1.22                                        *.*                                           LISTEN     
```
I have masked my real IPv6 addresses in the output with `2001:db8::/32`.

This is explained here: https://www.cyberciti.biz/faq/linux-bsd-unix-configuring-ssh-listen-ipv6-addresses/

Is it possible to correct generation of OpenSSH daemon configuration? :smiley: 

**To Reproduce**

1. Activate IPv6
2. Activate OpenSSH
3. Try to connect via SSH using IPv6
4. Impossible to connect

**Expected behavior**

SSH with IPv6 works.

**Describe alternatives you considered**

I connect via SSH with IPv4, add `[` and `]` around IPv6 already configured address and restart OpenSSH daemon.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 21.7.1-amd64
FreeBSD 12.1-RELEASE-p19-HBSD
OpenSSL 1.1.1k  25 Mar 2021
Intel Core Processor (Skylake, IBRS) (4 cores)

**Comment by fichtner** [comment] 2021-08-28 14:12
I’m 100% sure this worked for OpenSSH at some point in time the way it is currently implemented, otherwise it would have not been implemented this way? Nevertheless I’ll take a look next week.


Cheers,
Franco

**Comment by fichtner** [comment] 2021-09-01 12:12
Can you try 6651a03a1 and see if that solves it?

    # opnsense-patch 6651a03a1

To me it looks like OpenSSL may have issues with ":port" parsing. Funnily we do not set ports so we don't need the braces, but if this works why not. :) 
 

Thanks,
Franco

**Comment by JulienDlq** [comment] 2021-09-01 15:28
Mmmh, that's weird, the patch configures OpenSSH using `[ ]` around IPv6 address after a reboot, that's cool.

But, OpenSSH is still showing :
```
% sudo netstat -Wnaf inet6 | grep '\.22 '
tcp6       0      0 ::1.22                 *.*                    LISTEN
```

… until I perform a :
```
sudo service openssh onerestart
Performing sanity check on openssh configuration.
Stopping openssh.
Waiting for PIDS: 25028.
Performing sanity check on openssh configuration.
Starting openssh.
```
… and then :
```
% sudo netstat -Wnaf inet6 | grep '\.22 '
tcp6       0      0 2001:db8::dead:beaf:100:1.22         *.*                                           LISTEN     
tcp6       0      0 ::1.22                                        *.*                                           LISTEN     
```

If I reboot again :
```
% sudo netstat -Wnaf inet6 | grep '\.22 '
tcp6       0      0 ::1.22                 *.*                    LISTEN
```

So, there is still something missing here.

2 Workarounds : using ssh with IPv4 to connect, then `sudo service opnssh onerestart`, or deactivate ssh via gui then reactivate it.

**Comment by fichtner** [comment] 2021-09-01 15:53
If your SSH won’t listen to a GUA it’s likely because of a dynamic IP situation. M

**Comment by JulienDlq** [comment] 2021-09-01 15:55
But, this IP is set static in my opnsense configuration for this interface, or I did not understand what you mean?

**Comment by fichtner** [comment] 2021-09-01 16:03
This IPv6 address is static on LAN?

**Comment by JulienDlq** [comment] 2021-09-01 16:10
My opnsense config :
- WAN : static IPv4/IPv6,
- LAN : static IPv4/IPv6,
- DMZ : static IPv4/IPv6.

I activate SSH in opnsense from LAN only.

As I said before, after applying the patch, the IPv6 is now protected with `[ ]` in OpenSSH configuration, but after system boot or reboot, it needs a restart of OpenSSH in opnsense or a deactivation/activation from opnsense webgui to take into account this IPv6 address as a listening one. :)

**Comment by fichtner** [comment] 2021-09-02 06:25
It looks good from my end with a virtual IP after reboot... if the IP is in the config as well I don't know what it could be. You can check system log for MAX_LISTEN_SOCKS error message, but I doubt it (since IP is in the configuration).


Cheers,
Franco

**Comment by JulienDlq** [comment] 2021-09-02 15:06
Unfortunately I have nothing about MAX_LISTEN_SOCKS error message.

After boot (as always, I have changed my real IPv6 address with the documentation dedicated one in this output):
```
2021-09-02T09:35:10	sshd[17182]	Server listening on 192.168.100.2 port 22.
2021-09-02T09:35:10	sshd[17182]	error: Bind to port 22 on 2001:db8::dead:beaf:100:1 failed: Can't assign requested address.
2021-09-02T09:35:10	sshd[17182]	error: Bind to port 22 on 2001:db8::dead:beaf:100:1 failed: Can't assign requested address.
2021-09-02T09:35:10	sshd[17182]	Server listening on 127.0.0.1 port 22.
2021-09-02T09:35:10	sshd[17182]	Server listening on ::1 port 22.
```
When I restart OpenSSH using WebGUI, manualy :
```
2021-09-02T17:03:09	sshd[72603]	Server listening on 192.168.100.2 port 22.
2021-09-02T17:03:09	sshd[72603]	Server listening on 2001:db8::dead:beaf:100:1 port 22.
2021-09-02T17:03:09	sshd[72603]	Server listening on 127.0.0.1 port 22.
2021-09-02T17:03:09	sshd[72603]	Server listening on ::1 port 22.
2021-09-02T17:03:09	sshd[76596]	Received signal 15; terminating.
```

**Comment by JulienDlq** [comment] 2021-09-02 15:14
I have made a little test :
- deactivate SSH,
- restart,
- activate SSH,
- IPv4/IPv6 works.

I really think there is a delay before IPv6 is attached to interface, even when static.

**Comment by fichtner** [comment] 2021-09-02 16:15
I’m not so sure. It reads the address from the interface and then binds to it. The whole problem can be avoided using :: binding, but selecting LAN for SSH makes this issue appear. It might be that the IPv6 address is still tentative and therefore not able to be bound to when SSH starts…

**Comment by JulienDlq** [comment] 2021-09-02 16:55
That's what I meant, the tentative part. :wink:

**Comment by fichtner** [comment] 2021-09-03 06:41
Yeah but DAD is not really our area of work. Maybe it works if you set tunable net.inet6.ip6.dad_count to 0.


Cheers,
Franco

https://lists.freebsd.org/pipermail/freebsd-questions/2014-January/255579.html

**Comment by JulienDlq** [comment] 2021-09-03 08:56
YES! That solved the thing. Thank you very much!
I know for sure that on my network there should not be any duplication of IPv6 address (there is so many, it would be a very bad luck…), so it's safe to deactivate it. :wink:

**Comment by fichtner** [comment] 2021-09-03 09:23
Ok, great I'll close this then. :)

**Comment by JulienDlq** [comment] 2021-09-03 09:30
The `[ ]` are still needed in sshd_config, however. 😉

**Comment by fichtner** [comment] 2021-09-03 09:30
What, why?

**Comment by JulienDlq** [comment] 2021-09-03 09:35
Because this was the first problem.
First problem : impossible to recognise IPv6 without braces.
Second problem : once using `[ ]` with your first patch, the IPv6 DAD was messing with sshd bind, and deactivate it solved this issue only, not the first one.

Both things are needed at the same time :
- `[ ]`
- DAD deactivation

**Comment by fichtner** [comment] 2021-09-03 09:35
I can't reproduce this issue...

**Comment by JulienDlq** [comment] 2021-09-03 09:39
When I go back on my opnsense I will try but I have to know how to revert the first patch you give me, I apply the second patch with commit https://github.com/opnsense/core/commit/a232fefaa2a348a1cf27e8d5f6750f8791424e43 ?

**Comment by fichtner** [comment] 2021-09-03 09:47
If you have the first applied just apply the second one and test. If not working reapply second patch again to verify it's fixing it. But I do expect the DAD issue was the only real problem as initially mentioned when you opened the ticket.


Cheers,
Franco

**Comment by JulienDlq** [comment] 2021-09-03 09:57
The initial problem of the ticket was the `[]`, we didn't know about the DAD issue until we faced it because we fixed the `[]` issue.

Reminder : 
- no `[]` : no IPv6 available for openssh after boot, even after a `sudo service openssh onerestart`,
- with `[]` : no IPv6 available for openssh after boot, but after a `sudo service openssh onerestart` IPv6 is available,
- with `[]` + DAD deactivation : IPv6 available for openssh after boot, yes!

We can try, in order to be sure : 
- no `[]` + DAD deactivation : but I'm not really sure that will work since it seems that openssh does not recognize correctly an IPv6 without `[]` because performing `sudo service openssh onestart` did not worked at this time (DAD had the time to confirm the IPv6 was not duplicated and interface had its IPv6 address…)

**Comment by fichtner** [comment] 2021-09-03 10:17
You will have to add the logs of your assumptions. I don't have a particular reason to assume "openssh does not recognize correctly an IPv6 without []". The braces are strictly needed when you add a port to an IPv6 address, but we do not add ports.

**Comment by JulienDlq** [comment] 2021-09-03 10:30
I will do, that's my job and hobby, test things. 👍

**Comment by JulienDlq** [comment] 2021-09-03 10:39
But actually, when you have `2001:db8::dead:beaf:100:1`. How do you (or a software) know without doubt that `2001:db8::dead:beaf:100:1` is an IPv6 without port, and `2001:db8::dead:beaf:100:1` is an IPv6 `2001:db8::dead:beaf:100` and port `1`. 😁
Because between `::` there are plenty of zero, it's .
That's why you need `[]` to be sure of what is an IPv6 and what is a port. 👍

**Comment by fichtner** [comment] 2021-09-03 10:41
I think the rule is you can't add a port without [] and otherwise the trailing :1 is part of the IPv6 address as it should be.

**Comment by JulienDlq** [comment] 2021-09-03 10:42
I will test that also : replace `::` with real `0`, I am nearly sure that without `[]` it will work, because there will be no doubt about the IPv6. 👍

**Comment by JulienDlq** [comment] 2021-09-03 13:17
So, I just applied the patch `sudo opnsense-patch a232fefaa`, then rebooted.

When boot is done: everything's work… IPv4/IPv6 for OpenSSH (this time : no `[ ]` in sshd_config, and DAD deactivated).
Dude, I don't understand! :rofl: 

Why do we have a different behavior here?! :fearful: 

Anyway, I would have preferred understand it (maybe I really missed something during my investigation on my side that would explain everything…), but this time, and for sure, everything is working (it just needs DAD deactivation, something to document somewhere? (please tell me there is not, or will feel very ashamed…)).

I'm very sorry this took so long… :bow: 
And of course thank you very much for your patience! :v:

**Comment by fichtner** [comment] 2021-09-03 18:05
@JulienDlq ha, no worries, appreciate all feedback! :)


Cheers,
Franco

**Closed by fichtner** 2021-09-03 18:05 UTC
Labels: cleanup
