### ISSUE TITLE
Selection of Carp Adresses in ipsec 

### ISSUE THREAD

**Issue by rkirmis** [opnsense/core#3732] opened 2019-09-28 17:02 UTC
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[+] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[+] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
If there are more than one CARP IPs defined, the selection box for the ipsec phase 1 interface
only lists the last entry of CARP IPs for that Interface. The other IPs are not in the list.

**To Reproduce**
1. Add 2 Carp IPs on WAN Interface
2. Edit IPSEC Tunnel Phase 1
3. Select IP Addresse

**Expected behavior**
All Carp IPs are in the list and selectable

**Screenshots**

**Relevant log files**

**Additional context**
A VPN use an virtual IP as VPN interface.
I have defined for the WAN interface multiple virtual IPs.
The IP written in /usr/local/etc/ipsec.conf is the last defined virtual WAN IP in Firewall -> Virtual IP -> Settings (not that one display in VPN->IPsec->Tunnel Settings->Phase 1)
It’s mandatory that we can choose in VPN settings every virtual IP defined and not randomly one from WAN interface

Path to file
/vpn_ipsec_phase1.php?p1 (URL)
/usr/local/etc/ipsec.conf (File path)

**Environment**

OPNsense 19.7.4_1 (amd64, LibreSSL)

**Comment by ampfinger** [comment] 2019-10-05 07:54
I have got the same problem here. Multiple virtual WAN addresses but can only choose one WAN address in ipsec phase 1 definition.
And the shown WAN address isn't the one which is entered in ipsec.conf, instead it is the last virtual WAN address in Firewall - Virtual IPs.
I can provide screenshots if necessary.

**Comment by rkirmis** [comment] 2019-10-25 14:38
Whta can i do, to complete the issue?
How do i get the incomplete flag removed?

**Comment by mimugmail** [comment] 2019-10-25 15:00
Screenshot would be a good start. Today I helped a customer with latest 19.7.5_5 and around 20 CARP aliases where everyone was selectable ...

**Comment by Kimotu** [comment] 2019-11-14 15:09
I am on 19.7.6 and having the same issue. But since running IPv6 configuration, I can confirm that with IPv6, the expected behavior works. All IPv6 CARP addresses get listed. Just IPv4 CARP adresses are missing.

Here a list what is listed and selectable:

- interface address (ipv4) (the physical one when you select an interface, WAN, LAN, ...)
- IPv4 IP-Aliases
- IPv6 IP-Aliases
- IPv6 CARP-Adresses

Not listed:

- IPv4 CARP addresses

![VPN](https://user-images.githubusercontent.com/45389306/68869210-1e1c0e80-06f9-11ea-83e1-4076126b7461.png)

**Comment by AdSchellevis** [comment] 2019-11-22 17:33
Same interface and same `vhid` used multiple times? (for the missing ones)

That would be the only thing I can think of looking at the code.
https://github.com/opnsense/core/blob/b2560c6eb46e2739a33c8e761db2b9efe541b776/src/etc/inc/util.inc#L866
^^ can't cope with overlap

**Comment by Kimotu** [comment] 2019-11-22 17:39
Hi,

yes ipv6 and ipv4 use same VHID per interface.

Kind regards,
     Kimotu Bates

Ad Schellevis <notifications@github.com> schrieb am Fr., 22. Nov. 2019,
18:33:

**Comment by AdSchellevis** [comment] 2019-11-22 18:30
ok we need to check the callers of `get_configured_carp_interface_list()` then, one tip for future issue tracking, try to be very specific about what's configured and how you expect it to appear (details matter a lot in these cases).

**Comment by AdSchellevis** [comment] 2019-11-22 19:42
There won't be an easy fix for this without breaking existing configurations or needing changes to existing setups. Since the schema `[interface]_vip[hid]` isn't unique and stored in multiple places. 

Marked the ticket as cleanup for now, it's an omission in the system, a workaround could be to use separate vhid's in cases you want to use them for binding.

**Comment by AdSchellevis** [comment] 2019-11-23 09:08
looking at the validations again, you shouldn't be allowed to add more than one carp vhid on an interface. https://github.com/opnsense/core/commit/754d483b868f9a46c05051b1881da8b4974d2ec2 Intended use is to use aliases for the non-primary one (which also prevents trying to set the password several times on the same interface).

**Comment by Kimotu** [comment] 2019-11-24 05:04
Within the same address family, I do use ip aliases. One ipv4 carp, rest
aliases. But I don't see an ipv6 address as alias for an ipv4 address.
Although the carp mechanism differs. Ipv6 uses protocol 112, ipv4 multicast.

Kind regards,
     Kimotu Bates

Ad Schellevis <notifications@github.com> schrieb am Sa., 23. Nov. 2019,
10:08:

**Comment by AdSchellevis** [comment] 2019-11-24 09:38
since the internal key is per interface+vhid it won't support overlap, the previous bug (https://github.com/opnsense/core/commit/754d483b868f9a46c05051b1881da8b4974d2ec2) allowed such entries to be made. Changing this would probably mean to support ip aliases with a vhid in these selections and add some sort of key to identify them, but unfortunately this probably involves quite some work to fix a pattern that's already quite flawed (mixing interfaces and addresses).

**Comment by AdSchellevis** [comment] 2020-04-21 14:10
This issue has been automatically timed-out (after 180 days of inactivity).

For more information about the policies for this repository,
please read https://github.com/opnsense/core/blob/master/CONTRIBUTING.md for further details.

If someone wants to step up and work on this issue,
just let us know, so we can reopen the issue and assign an owner to it.

**Closed by AdSchellevis** 2020-04-21 14:10 UTC
