### ISSUE TITLE
Enable Radius Attribute

### ISSUE THREAD

**Issue by K-razy** [opnsense/core#6712] opened 2023-08-05 18:11 UTC
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

Hello, hope you are fine.

I'm working on a OPNsense using freeradius to authenticate and do accounting during the visitor's connection regardless if it is Captive Portal or not.
However attributes **acct-input-octets** and **acct-input-octets**  avec 32-bit counters and are reset when 4 Go of data are reached.

Could you please implement Radius Extension, in particular **Acct-Input-Gigawords**, **Acct-Output-Gigawords** and their mechanisms to be able to monitor without losing the total amount of traffic ?
Link to the RFC linked to the request : https://datatracker.ietf.org/doc/html/rfc2869#page-22

Thanks in advance

Best Regards

**Comment by AdSchellevis** [comment] 2023-08-05 18:15
duplicate of https://github.com/opnsense/core/issues/6682 ?

**Comment by K-razy** [comment] 2023-08-05 18:23
Hello, 

Thanks for your answer, i've seen this request but in this case, he wanted a non Radius attribute

In my case, is to implement extension which complete existing monitoring in place.
My case is not for a commercial case, but only to monitor and applies some restrictions after that.

Perhaps it may exists, but i really don't know how to enable Gigawords in OPNsense.

Thanks for your time.

**Comment by AdSchellevis** [comment] 2023-08-05 20:54
If it's a question about Freeradius, we should probably move this to the plugin section.

**Comment by K-razy** [comment] 2023-08-05 21:05
Unfortunately no, i'm not using the freeradius plugin because some features are still experimental. I'm using an external FreeRadius server

I was looking about the accounting sent by OPNsense and i noticed that Gigawords are unfortunately not sent by OPNsense.

**Comment by AdSchellevis** [comment] 2023-08-05 21:09
ok, but then you're only looking at captive portal, there is no other process sending accounting messages...

**Closed** 2024-02-01 18:05 UTC
Labels: help wanted
