### ISSUE TITLE
Squid Proxy Log - timestap shows 1970?

### ISSUE THREAD

**Issue by opnsenseuser** [opnsense/core#3525] opened 2019-06-09 19:00 UTC
Using 19.1.9
Problem seems to be only in "Access" Tab. Cache an Store tabs - timestamps are ok.

![grafik](https://user-images.githubusercontent.com/34602360/59162918-7111ea00-8af9-11e9-80db-7e690c632e24.png)

**Comment by AdSchellevis** [comment] 2019-06-10 11:55
can you check the actual log file (tail /var/log/squid/access.log) and dump the contents here?

**Comment by opnsenseuser** [comment] 2019-06-11 11:08
@AdSchellevis in the access log, the timestap is correct!

**Comment by AdSchellevis** [comment] 2019-06-11 11:11
on my end the log looks normal. Without anything to reproduce your issue (actual content), it has a high chance of not being fixed......

**Comment by opnsenseuser** [comment] 2019-06-11 12:10
@AdSchellevis I have deleted all logs and squid restarts - unfortunately no change. even after a complete restart of the firewall, the problem persists.

**Comment by opnsenseuser** [comment] 2019-06-11 12:14
@AdSchellevis i also did a squid reinstall. no change

**Comment by opnsenseuser** [comment] 2019-06-11 12:15
![grafik](https://user-images.githubusercontent.com/34602360/59271044-4e93e400-8c53-11e9-961c-a825a432bad7.png)

**Comment by AdSchellevis** [comment] 2019-06-11 12:16
I think I know what your issues is, but why o why are you trying to make things so difficult. Just provide a screenshot (like you just did) **and** the same data in raw format.

**Comment by opnsenseuser** [comment] 2019-06-11 12:24
192.168.1.6 - 54:a0:50:50:a8:1c - [11/Jun/2019:14:13:22 +0200] "CONNECT 192.30.253.125:443 HTTP/1.1" 200 4272 "-" "-" TCP_TUNNEL:ORIGINAL_DST
192.168.1.6 - 54:a0:50:50:a8:1c - [11/Jun/2019:14:13:23 +0200] "CONNECT 192.30.253.124:443 HTTP/1.1" 200 3697 "-" "-" TCP_TUNNEL:ORIGINAL_DST
192.168.1.6 - 54:a0:50:50:a8:1c - [11/Jun/2019:14:13:24 +0200] "CONNECT 151.101.36.133:443 HTTP/1.1" 200 0 "-" "-" TAG_NONE:ORIGINAL_DST
192.168.1.6 - 54:a0:50:50:a8:1c - [11/Jun/2019:14:13:24 +0200] "CONNECT 151.101.36.133:443 HTTP/1.1" 200 0 "-" "-" TAG_NONE:ORIGINAL_DST
192.168.1.6 - 54:a0:50:50:a8:1c - [11/Jun/2019:14:13:24 +0200] "CONNECT 151.101.36.133:443 HTTP/1.1" 200 0 "-" "-" TAG_NONE:ORIGINAL_DST
192.168.1.6 - 54:a0:50:50:a8:1c - [11/Jun/2019:14:13:24 +0200] "CONNECT 151.101.36.133:443 HTTP/1.1" 200 0 "-" "-" TAG_NONE:ORIGINAL_DST
192.168.1.6 - 54:a0:50:50:a8:1c - [11/Jun/2019:14:13:24 +0200] "CONNECT 151.101.36.133:443 HTTP/1.1" 200 0 "-" "-" TAG_NONE:ORIGINAL_DST
192.168.1.6 - 54:a0:50:50:a8:1c - [11/Jun/2019:14:13:24 +0200] "CONNECT 151.101.36.133:443 HTTP/1.1" 200 0 "-" "-" TAG_NONE:ORIGINAL_DST
192.168.1.6 - 54:a0:50:50:a8:1c - [11/Jun/2019:14:13:24 +0200] "CONNECT 151.101.36.133:443 HTTP/1.1" 200 0 "-" "-" TAG_NONE:ORIGINAL_DST
192.168.1.6 - 54:a0:50:50:a8:1c - [11/Jun/2019:14:13:24 +0200] "CONNECT 151.101.36.133:443 HTTP/1.1" 200 0 "-" "-" TAG_NONE:ORIGINAL_DST
192.168.1.6 - 54:a0:50:50:a8:1c - [11/Jun/2019:14:13:24 +0200] "CONNECT 151.101.36.133:443 HTTP/1.1" 200 0 "-" "-" TAG_NONE:ORIGINAL_DST
192.168.1.6 - 54:a0:50:50:a8:1c - [11/Jun/2019:14:13:24 +0200] "CONNECT 185.199.110.154:443 HTTP/1.1" 200 0 "-" "-" TAG_NONE:ORIGINAL_DST
192.168.1.6 - 54:a0:50:50:a8:1c - [11/Jun/2019:14:13:24 +0200] "CONNECT 185.199.110.154:443 HTTP/1.1" 200 0 "-" "-" TAG_NONE:ORIGINAL_DST
192.168.1.6 - 54:a0:50:50:a8:1c - [11/Jun/2019:14:13:24 +0200] "CONNECT 185.199.110.154:443 HTTP/1.1" 200 0 "-" "-" TAG_NONE:ORIGINAL_DST
192.168.1.6 - 54:a0:50:50:a8:1c - [11/Jun/2019:14:13:24 +0200] "CONNECT 185.199.110.154:443 HTTP/1.1" 200 0 "-" "-" TAG_NONE:ORIGINAL_DST
192.168.1.6 - 54:a0:50:50:a8:1c - [11/Jun/2019:14:13:24 +0200] "CONNECT 185.199.110.154:443 HTTP/1.1" 200 0 "-" "-" TAG_NONE:ORIGINAL_DST
192.168.1.6 - 54:a0:50:50:a8:1c - [11/Jun/2019:14:13:24 +0200] "CONNECT 185.199.110.154:443 HTTP/1.1" 200 0 "-" "-" TAG_NONE:ORIGINAL_DST
192.168.1.6 - 54:a0:50:50:a8:1c - [11/Jun/2019:14:13:24 +0200] "CONNECT 185.199.110.154:443 HTTP/1.1" 200 0 "-" "-" TAG_NONE:ORIGINAL_DST
192.168.1.6 - 54:a0:50:50:a8:1c - [11/Jun/2019:14:13:24 +0200] "GET https://github.githubassets.com/assets/github-bootstrap-31df1646.js HTTP/1.1" 304 560 "https://github.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0" TCP_MISS:ORIGINAL_DST
192.168.1.6 - 54:a0:50:50:a8:1c - [11/Jun/2019:14:13:24 +0200] "GET https://github.githubassets.com/assets/frameworks-8cca4b9a.js HTTP/1.1" 304 559 "https://github.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0" TCP_MISS:ORIGINAL_DST

**Comment by AdSchellevis** [comment] 2019-06-11 12:27
and this is what the default log file looks like (which works):

```
1560166972.393     14 10.37.132.100 TCP_DENIED/407 3809 GWT http://www.nu.nl/ - HIER_NONE/- text/html
```

your log target is `file (extended)` ?

**Comment by opnsenseuser** [comment] 2019-06-11 12:30
yes, i didn´t change this. but even if i select only "file" its the same problem!

**Comment by AdSchellevis** [comment] 2019-06-11 12:31
stop/start squid, file should work (it does on my end, see my log example)

**Comment by opnsenseuser** [comment] 2019-06-11 12:35
no change even after restart of squid!

**Comment by AdSchellevis** [comment] 2019-06-11 12:37
I really don't understand the need for exclamation marks, but do the raw (new) access log entries still contain mac addresses? if yes, it's not applied.

**Comment by opnsenseuser** [comment] 2019-06-12 16:21
@AdSchellevis  sorry that i have to say that. but no matter what I do, the problem still exists.

**Comment by AdSchellevis** [comment] 2019-06-14 15:40
I don't think this ever worked properly, but long story short, our log view won't work with the extended format we have chosen in squid:

https://github.com/opnsense/core/blob/41d5cdb83dcd8396b96919ba977bede903f0200f/src/opnsense/service/templates/OPNsense/Proxy/squid.conf#L362

A fix could be to add `%ts.%03tu`, but since that will impact others, we can't do that now.

```
logformat opnsense      %ts.%03tu %>a %[ui %>eui %[un [%tl] "%rm %ru HTTP/%rv" %>Hs %<st "%{Referer}>h" "%{User-Agent}>h" %Ss:%Sh
```

**Comment by ruffy91** [comment] 2019-09-18 18:39
This is still broken using 19.7.4_1 out of the box.
I think this qualifies as bug, not support.
![image](https://user-images.githubusercontent.com/344634/65176068-5930f700-da54-11e9-81e4-f179091c62bf.png)

**Comment by fichtner** [comment] 2019-09-19 06:12
If that is so the easiest way to fix it is to remove the extended logging format for good. Look, qualifying as a bug does not mean it will be fixed automatically and you have to incorporate the scope of this which is cosmetic.

**Comment by AdSchellevis** [comment] 2019-12-05 16:43
likely fixed with https://github.com/opnsense/core/issues/3831

**Closed by AdSchellevis** 2019-12-05 16:43 UTC
Labels: support
