### ISSUE TITLE
rc.bootup error

### ISSUE THREAD

**Issue by L1ghtn1ng** [opnsense/core#888] opened 2016-04-12 00:17 UTC
opnsense: /usr/local/etc/rc.bootup: The command '/usr/local/bin/rrdtool update /var/db/rrd/system-cputemp.rrd N:U:U:U:U:U' returned exit code '1', the output was 'ERROR: expected 1 data source readings (got 5) from N:U:U:U:U:U'

**Comment by AdSchellevis** [comment] 2016-04-12 10:47
@L1ghtn1ng this seems to be caused by the collection of thermal data on machines with more cores or processors, does your health graph show any data for that topic? and how many cpu's does your machine have?

Maybe we we should change this title to something like "rrd: error collecting cpu temp"

**Comment by L1ghtn1ng** [comment] 2016-04-13 00:55
@AdSchellevis please see in issue #890 for the appliance that I am running. But it is a quad core. I do also see thermal data in my health graph when selecting the cputemp graph on the drop down

**Comment by fichtner** [comment] 2016-04-25 08:47
This was a typo, fixed in 16.1.12, thanks!

**Closed** 2016-04-25 08:46 UTC

**Comment by L1ghtn1ng** [comment] 2016-04-25 09:17
Awesome and I seem to finding all the bugs or ways to improve  Opnsense :-)
