### ISSUE TITLE
WAN_DHCP6 gateway fails in certain multi WAN setups

### ISSUE THREAD

**Issue by RehaagJ** [opnsense/core#3604] opened 2019-07-27 16:54 UTC
[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

WAN Gateway IPv6 issues started with 19.7. While this is similar to #3601 , I don't think it's the same (but maybe related; one big difference is that both my IPv6 gateways have valid IPv6 addresses, not just link local).

Setup: OPNsense 19.7.1 with WAN, LAN, DMZ and some more internal networks. WAN gets both IPv4 and IPv6 via DHCP, IPv6 sending prefix hint (size 56), directly send SOLICIT checked, prevent release checked. 
Then there is an OpenVPN client that builds a tunnel to a service that provides fixed IPv4 and IPv6 addresses that I use for the DMZ (policy based routing); all other internal networks follow WAN.

That worked up until (including) 19.1.10. With 19.7, I lost routing through the WAN_DHCP6 interface as soon as the VPN tunnel came up. In the seconds between establishing WAN connection and bringing up the tunnel, WAN_DHCP6 was good. A new PTYOPENVPN_VPNV6 interface was added automatically, and declared default (duplicating my existing openvpn ipv6 gateway, which I then removed). Once that happened, the WAN_DHCP6 interface was not only no longer default, but also not useable in policy based routing any longer. 
As a workaround, I introduced a route-up script for OpenVPN that removes the new wrong default ipv6 route and adds the WAN interface back as default route. With that, I had the old functionality back (even though the PTYOPENVPN_VPNV6 still gets displayed as active gateway). Dpinger correctly showed WAN_DHCP6 as online and measured times and loss.
With 19.7.1, WAN_DHCP6 vanished from the list of gateways, but the workaround still works. Dpinger now fails for WAN_DHCP6 because it cannot see the gateway. 

While this workaround makes it possible to stay on 19.7.x, it is lacking features (like gateway monitoring), and is not robust (there can be situations where the default ipv6 route goes back to the OpenVPN tunnel).

**Expected behavior**
Multiple IPv6 interfaces should coexist, not compete with each other. It should be possible to define the one that should be default freely. I understand that the change in gateway handling removed the default selection on purpose, but the options for priority and/or upstream gateway should be able to make the preferred gateway the active one.

**Environment**
OPNsense 19.7.1 (amd64, OpenSSL).

**Comment by AdSchellevis** [comment] 2019-07-27 18:25
`default` is called `upstream` now, which is evaluated in combination with priority.

You should be able to choose freely between gateways, the overview page should be ordered according to real priority now. (if no `upstream` is found, it considers non `upstream` as well, but always values upstream higher in priority)

It would be good to have some additional documentation, but unfortunately we haven't found the time yet to write an extra doc for this.

**Comment by RehaagJ** [comment] 2019-07-27 18:26
Well, the issue is - it’s not working. And with 19.7.1, WAN_DHCP6 is even removed from the list, so no chance anymore to configure it...

**Comment by RehaagJ** [comment] 2019-07-27 19:23
Hi again,

I believe the label "support" is not correct. This is clearly a bug. Please let me know how I can help to solve it (log excerpts, other testing etc...). Thanks!

**Comment by mr44er** [comment] 2019-07-28 00:57
I played a bit more with it. Giving priority works only on ipv4.

Setting upstream and/or (lower) priority when wan1ipv6gw is marked as 'down' does nothing. Leaving this setting and reenabling interface gives same 'nothing'-effect. Trying the other way round with settings on wan2ipv6gw does again nothing.

Btw. multiwan loadbalancing breaks with 3 upstreams on tier1, it then uses randomly only 2 of 3 upstreams regardless of the weight-setting.
I think I can rule out a config error, because it works regardless on which combination of 2 gateways I choose to be in tier1, but as said only with max. 2.

**Comment by cmb991** [comment] 2019-07-28 05:05
The issue is also in IPv4 when trying to assign gateways to dns servers.

**Comment by AdSchellevis** [comment] 2019-07-28 08:57
If there is an issue, first question is, what does the `system_gateways.php` page show exactly and what is the configured setting of "Gateway switching" in `system_general.php`

A lot of issues are related to misconfigured gateway monitoring, if the status overview shows its down, it's not a valid target to use for gateway switching.

**Comment by RehaagJ** [comment] 2019-07-28 10:14
Gateway switching is off, but I tried many iterations of different settings combinations with it being on also - didn't make any difference.
Here's the system_gateways.php page. Note that it does not show the WAN_DHCP6 gateway any more, which it still did in 19.7 (without being able to use it, though).
The missing gateway still exists in config.xml, and when it first went missing in 19.7.1, I tried to add it again - still not showing in the gateway page, but I ended up with three copies of the same gateway definition in config.xml (now cleaned up again so that only the original WAN_DHCP6 is there).

![Gateways](https://user-images.githubusercontent.com/20500243/62005234-8b973580-b130-11e9-9e79-977126fa6a16.png)

**Comment by AdSchellevis** [comment] 2019-07-28 12:02
@RehaagJ if it doesn't show the interface it doesn't consider it a valid alternative, which is slightly different than 19.1.x, which could show unusable gateways as well.

In this case it's likely an issue with the interface configuration, can you check the following on a console (and paste the output):

```
ls -als /tmp/*gw*
```

Then for all files returned, check the contents, if the interface gateway is there.

**Comment by RehaagJ** [comment] 2019-07-28 12:10
Here's the output:
`4 -rw-r--r--  1 root  wheel  21 Jul 28 11:56 /tmp/ovpnc1_defaultgwv6`
That's the only line, and the content of that file is the gateway address of the OpenVPN IPv6 gateway.

What you say about the WAN_DHCP6 gateway being considered invalid makes sense. So the question is: Why would it be considered invalid?

**Comment by AdSchellevis** [comment] 2019-07-28 12:39
It seems that your interface didn't receive a gateway (and thus misses a XXX_defaultgwv6 file), can you post your interface configuration page? maybe there are some clues in there. The gateway page itself seems to be doing the right thing here.

**Comment by RehaagJ** [comment] 2019-07-28 13:05
<img width="1376" alt="image" src="https://user-images.githubusercontent.com/20500243/62007028-ff453c80-b148-11e9-868d-14644e1adb06.png">
<img width="1376" alt="image" src="https://user-images.githubusercontent.com/20500243/62007038-14ba6680-b149-11e9-9995-f68fe78f5180.png">

**Comment by AdSchellevis** [comment] 2019-07-28 13:20
You probably have to check the logging when connecting to dhcpv6, if I'm not mistaken, the rtsold script should write the gateway after a successful lease (using  /var/etc/rtsold_*.sh).

If the interface itself has received a correct address, it might also be a provider specific thing, it doesn't look related to gateway switching.

**Comment by fichtner** [comment] 2019-07-28 13:28
This is the case where SOLICIT is sent directly because the ISP doesn't offer a router for radvd, hence no GW file.

**Comment by RehaagJ** [comment] 2019-07-28 13:32
OK. Since this worked fine until 19.1.10 with the same configuration: There probably never was a GW file then, but still it was possible to configure and use the gateway. Apparently, the new gateway handling relies on the GW files now. Understood correctly?

**Comment by fichtner** [comment] 2019-07-28 13:34
We should generate the gateway from dhcp6c as well if radvd. I've already promised to look into it elsewhere.

**Comment by mr44er** [comment] 2019-07-28 13:37
> it doesn't look related to gateway switching.

Right, the switching or policy base routing works for me. The problem starts when GWs are shown as offline for no reason.

The 'working' state:

![wan1](https://user-images.githubusercontent.com/46787531/62007306-3ec15800-b14c-11e9-93db-c0f90264afe4.png)
###################
![grafik](https://user-images.githubusercontent.com/46787531/62007320-60224400-b14c-11e9-9700-15d31b11d4b3.png)
###################
![grafik](https://user-images.githubusercontent.com/46787531/62007328-80520300-b14c-11e9-8555-ee26aa3b0d25.png)
###################
`root@fw1:/ # ls -als /tmp/*gw*
4 -rw-r-----  1 root  wheel  12 Jul 27 04:46 /tmp/pppoe0_defaultgw
4 -rw-r-----  1 root  wheel  26 Jul 28 04:00 /tmp/pppoe0_defaultgwv6`

######################

Now only activating ipv6 on wan2:
![wan2](https://user-images.githubusercontent.com/46787531/62007376-fce4e180-b14c-11e9-9229-d1af755044eb.png)
#######################
![grafik](https://user-images.githubusercontent.com/46787531/62007389-20a82780-b14d-11e9-88e7-0aaaf44a97ae.png)
Note that it immediately takes WAN2 as active, butI didn't set it to upstream nor changed any setting at all for this GW.

`root@fw1:/ # ls -als /tmp/*gw*
4 -rw-r-----  1 root  wheel  26 Jul 28 15:33 /tmp/em1_defaultgwv6
4 -rw-r-----  1 root  wheel  12 Jul 27 04:46 /tmp/pppoe0_defaultgw
4 -rw-r-----  1 root  wheel  26 Jul 28 04:00 /tmp/pppoe0_defaultgwv6
root@fw1:/ # `

At this state my routing is broken, because wan1gwipv6 is shown as dead.

**Comment by AdSchellevis** [comment] 2019-07-28 13:57
@RehaagJ I said `/tmp/*default*`, but I meant `/tmp/*router*` (which in this case is written at the same time). The dynamic entries follow approximately the same logic as the old version, with the exception that it will only show if valid now. for reference, the dynamic items are considered here

https://github.com/opnsense/core/blob/2ff5ec429d281ff9eddee00c261c18181d57901a/src/opnsense/mvc/app/library/OPNsense/Routing/Gateways.php#L190-L255

**Comment by mr44er** [comment] 2019-07-28 18:28
![grafik](https://user-images.githubusercontent.com/46787531/62011237-dab38980-b175-11e9-85b4-a38413667610.png)
##################################
![grafik](https://user-images.githubusercontent.com/46787531/62011240-fcad0c00-b175-11e9-88db-d268eac5dac7.png)
##################################
![grafik](https://user-images.githubusercontent.com/46787531/62011246-1b130780-b176-11e9-956e-9715757a948d.png)
##################################

I'm out of ideas here.

**Comment by AdSchellevis** [comment] 2019-08-01 18:49
@mr44er can you try https://github.com/opnsense/core/commit/732b5ff4c8ebb69724e7b47d771b2b15e6a123db on opnsense 19.7.1?

```
opnsense-patch 732b5ff
```

**Comment by mr44er** [comment] 2019-08-01 19:50
I used the patch, rebooted and activated DHCPv6 on wan2 again.

Nothing changed, GW of wan2 is still priorized, regardless of the lower prio-number and wan1gwv6 shown as dead.

But after some minutes, I could'nt access webif anymore. Reboot doesn't help, dmesg didn't show anything.
Only cutting physically connection to wan2 + reboot did help.

**Comment by AdSchellevis** [comment] 2019-08-02 07:16
@mr44er you might have other networking issues, but maybe you can install patches https://github.com/opnsense/core/commit/704dc96cf20fb5f8d6b5e0e692bb09619c723332 and https://github.com/opnsense/core/commit/eb4975e29779c98a8027ffd29bfc97f0b122678a as well and dump a screenshot again.

```
opnsense-patch 704dc96cf eb4975e
```

This will add priority, ipprotocol and upstream setting to the overview, which helps to evaluate if the settings are correct.

**Comment by AdSchellevis** [comment] 2019-08-02 08:34
@mr44er and install this https://github.com/opnsense/core/commit/a6264e5062da581814fecc0479c5b0dfe0f95239 one too please. 

```
opnsense-patch a6264e5
```

Although there is no relation to gateway status (which actually isn't changed), it considers the gateways from https://github.com/opnsense/core/commit/732b5ff4c8ebb69724e7b47d771b2b15e6a123db as valid defaults (kind of forgot that one yesterday).

**Comment by mr44er** [comment] 2019-08-02 10:31
With the other problems, I think maybe I had a routing-loop or Tor had bitten in between due to exposed host I am, I dunno.

Ok, let's roll:
All 3 patches added, reboot.

Overview for now (I like it that way):
![image](https://user-images.githubusercontent.com/46787531/62363578-ec9f7e80-b51f-11e9-8336-4bac842e881b.png)

Reaching IP and ping from outside to one from delegated net works fine.
#############################
Trying now:
![image](https://user-images.githubusercontent.com/46787531/62363805-4dc75200-b520-11e9-8a18-9ef9047842e9.png)

gives this immediately:
![image](https://user-images.githubusercontent.com/46787531/62363877-77807900-b520-11e9-9069-2c8d9e68ec96.png)

Now setting inactivity off from setting yesterday:
![image](https://user-images.githubusercontent.com/46787531/62363971-adbdf880-b520-11e9-8bbf-eab111a8fff4.png)

Pinging from outside is dead for now.

Setting wan1 as upstream, still no luck:
![image](https://user-images.githubusercontent.com/46787531/62364082-efe73a00-b520-11e9-885a-ef196408468b.png)

Complete reboot:
![image](https://user-images.githubusercontent.com/46787531/62364330-769c1700-b521-11e9-87d2-49512cca7275.png)

**Comment by AdSchellevis** [comment] 2019-08-02 12:14
@mr44er  did you push 2001:xxx:8888 and 2001:xxx:8844 through the correct gateway, this looks like a static routing issue (only one can be reachable at the same time, both can compete)

**Comment by mr44er** [comment] 2019-08-02 12:24
I don't understand what you mean with 'push through the correct gateway'.

But to rule out 'only one can be reachable at the same time, both can compete' I used now the ipv6 from quad9.com and cloudflare.com:

![grafik](https://user-images.githubusercontent.com/46787531/62369833-33e23b00-b531-11e9-95a0-43aa7151dc96.png)

**Comment by AdSchellevis** [comment] 2019-08-02 12:26
you should have a static route, using the correct gateway for both monitor ip's, otherwise both will use default, which very likely is your issue. if both are dns entries, you can set a gateway there, this should be visible in your static routes.

**Comment by mr44er** [comment] 2019-08-02 12:32
![netstat](https://user-images.githubusercontent.com/46787531/62370395-414bf500-b532-11e9-88ab-321c227aa96e.png)

Ah, I now understand. Nope, I use these IPs only for GW-Monitoring. DNS is done with other servers and routing table looks correct.

**Comment by AdSchellevis** [comment] 2019-08-02 12:38
just add static routes and you're probably fine.

**Comment by mr44er** [comment] 2019-08-02 12:53
Mhm? I think the routing table looks correct as it is with correct routes as it should.

More routes would double the entry and bring chaos into routing, or am I wrong here?

Could you give me an example how you mean the two static routes should look, maybe I can understand better what you mean?

**Comment by AdSchellevis** [comment] 2019-08-02 13:01
There should be static routes for the addresses your trying to monitor (unless these are within their own subnet range, your screenshots seem to have different monitors set). ipv4 shouldn't be different than ipv6 in that regard.

**Comment by mr44er** [comment] 2019-08-02 13:05
![grafik](https://user-images.githubusercontent.com/46787531/62372135-f84a6f80-b536-11e9-8ace-d38b7835ce1f.png)

![grafik](https://user-images.githubusercontent.com/46787531/62372144-026c6e00-b537-11e9-893d-0ac91070c850.png)

**Comment by AdSchellevis** [comment] 2019-08-02 13:11
if already there, you should be good. you probably have to do more debugging why you can't reach the endpoint. My community support time is limited

**Comment by mr44er** [comment] 2019-08-02 13:16
> My community support time is limited

I understand that for sure, but I must admit I see it as a bug and not a wrong configuration.

> more debugging

If I only knew, where to look.
Anyway please don't close this thread too fast, because I would like to hear what the others with this problem can reach with the patches etc.

**Comment by AdSchellevis** [comment] 2019-08-02 13:20
I'm not closing it (it's a support ticket), feel free to discuss, if there is an issue that one can point to I'll gladly take a look. 

There are some debugging tips in https://docs.opnsense.org/manual/gateways.html, maybe that helps.

**Comment by bimmerdriver** [comment] 2019-08-02 23:35
> We should generate the gateway from dhcp6c as well if radvd doesn't fly. I've already promised to look into it elsewhere.

Please let me know when this is ready. I will test it. (I have one opnsense system running the latest release version and one running the latest development version.)

**Comment by AdSchellevis** [comment] 2019-08-03 07:38
@bimmerdriver the patches mentioned earlier in this ticket will be included in 19.7.3 (https://github.com/opnsense/core/commit/9a772fd8accb921870ab51146c89528d998fd8cb), which should be Monday

**Comment by bimmerdriver** [comment] 2019-08-03 17:06
> @bimmerdriver the patches mentioned earlier in this ticket will be included in 19.7.3 ([9a772fd](https://github.com/opnsense/core/commit/9a772fd8accb921870ab51146c89528d998fd8cb)), which should be Monday

My development system is already at 20.1, so will the patch be in the release version?

**Comment by fichtner** [comment] 2019-08-03 18:04
“20.1” is not a version number so will have to be more specific.

**Comment by bimmerdriver** [comment] 2019-08-03 18:17
> “20.1” is not a version number so will have to be more specific.
> […](#)
> On 3. Aug 2019, at 19:06, bimmerdriver ***@***.***> wrote: @bimmerdriver the patches mentioned earlier in this ticket will be included in 19.7.3 ([9a772fd](https://github.com/opnsense/core/commit/9a772fd8accb921870ab51146c89528d998fd8cb)), which should be Monday My development system is already at 20.1, so will the patch be in the release version? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

The development version is running OPNsense 20.1.a_44-amd64, as of the most recent update. I updated it by setting the release type to development and then checking for updates. (Not using the command line.) Does that help?

**Comment by fichtner** [comment] 2019-08-03 18:34
Yes, the changes you are looking for are included with 20.1.a_72, which will be included in Monday's 19.7.2 release on the development track translating to roughly 20.1.a_75 or higher if further changes are pushed to the master branch.

**Comment by bimmerdriver** [comment] 2019-08-04 16:29
> Yes, the changes you are looking for are included with 20.1.a_72, which will be included in Monday's 19.7.2 release on the development track translating to roughly 20.1.a_75 or higher if further changes are pushed to the master branch.

I updated my test system yesterday. It's running 20.1.a_75. I can confirm that the problem is fixed.

**Comment by RehaagJ** [comment] 2019-08-04 17:23
For my system, these patches already helped a lot; once I set the default route manually on the WAN_DHCP6 gateway, it will now stick because I can make it default now. Also, monitoring is possible again.
Once the change @fichtner mentioned about writing the router files also for dhcp6c when radvd doesn't generate the gateway will be implemented, everything should be back to the functionality we had until 18.10.
Thanks!

**Comment by fichtner** [comment] 2019-08-04 18:27
@RehaagJ no, the change you mention will make the system more robust than it ever was. I do believe 19.7.2 will be back to where it was before. Just for perspective. ;)

**Comment by RehaagJ** [comment] 2019-08-04 18:33
Well, currently, 19.7.1 with the patches isn't where it was before for me. I didn't have to define a default route manually earlier, now I need to do that. But I can't exclude the possibility that something went wrong during my many tests and/or patching, so I'll try again on 19.7.2. I'll update this topic then.

**Comment by bimmerdriver** [comment] 2019-08-05 17:25
With regards to the gateway monitor, is there a reason that the dashboard displays ~ as the address instead of the actual WAN gateway address (which in this case is link-local)? The interface status on the dashboard doesn't have a problem displaying the link-local WAN interface address.

**Comment by RehaagJ** [comment] 2019-08-16 17:08
Sorry for the delay, I promised to update the situation after update to 19.7.2. No difference - the gateway still does not get populated (fits to what @bimmerdriver said) , and a manual route entry is needed here. This was different in 19.1.
So I'm still convinced that gateway functionality is not yet restored to the pre-19.7 level, and that this should be labeled bug and not support. But since I have a workaround, if this is still seen as a support ticket, I think it can be closed.

**Comment by AdSchellevis** [comment] 2019-08-17 07:50
@RehaagJ ok, thanks for your feedback.

**Closed by AdSchellevis** 2019-08-17 07:50 UTC
Labels: support
