### ISSUE TITLE
Network failures under load while using an LES compact 4L OPNsense appliance

### ISSUE THREAD

**Issue by br-olf** [opnsense/core#4971] opened 2021-05-04 12:00 UTC
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**
We are experiencing network failures under load using the OPNsense appliance [LES compact 4L](https://www.thomas-krenn.com/de/produkte/low-energy-systeme/les-compact-4l/les-compact-4-l.html).

The OPNsense appliance is configured as a simple NAT-Firewall behind a Fritzbox-Router from our ISP. No IDS nor IPS are activated.

During some network load all network connections managed by OPNsense break after approximately 40 seconds. 

The network load is produced by rsync from a local NAT-Client to a server in the internet.
During the upload a ping from the appliance to 8.8.8.8 increases steadily up to  ~ 1100ms. Then **all** TCP-Connections trough the appliance are terminated and the ping times normalize.

In the logs we only see these messages:
```
kernel: pflog0: promiscuous mode disabled
kernel: pflog0: promiscuous mode enabled
```

It seems that a network reset happened.

**To Reproduce**

1. Setup a NAT using the LES compact 4L appliance
2. Produce Network traffic using rsync over SSH
3. Monitor ping times on the OPNsense appliance

**Expected behavior**

A TCP Network load of  < 100 Mbit/s should not interfere with any other network connections and connections should not be terminated.

**Describe alternatives you considered**

We tried to disable/enable hardware offloading parameters without change.
We also tried to reproduce this behavior (same OPNsense-setup) in a virtual machine but did not succeed to do so.
Furthermore we tested this with older releases and kernels, see below.

**Additional context**
Due to the fact that we only see this behavior in the appliance (not in a virtual environment) and the lack of logs we suspect a driver or kernel issue. And would appreciate tips to confirm/debunk this hypothesis.

**Environment**

* Network: Intel Corporation I210 Gigabit Network Connection
* Processor: Intel(R) Celeron(R) CPU J3160 @ 1.60GHz
* OpenSSL: 1.1.1k 25 Mar 2021

We experience this behavior in the following OPNsense versions:
* 21.1.3
* 21.1.5

We also tested these Kernels:
* 12.1-RELEASE-p16-HBSD
* 12.1-RELEASE-p15-HBSD

Additional information about the hardware:
[hwlog.txt](https://github.com/opnsense/core/files/6420774/hwlog.txt)

**Comment by fichtner** [comment] 2021-05-04 12:12
> A TCP Network load of < 100 Mbit/s should not interfere with any other network connections and connections should not be terminated.

Has this been verified by the vendor of the device?

**Comment by br-olf** [comment] 2021-05-04 12:22
Not now, we'll reach out to the vendor for further information. But Thomas Krenn is a Gold Partner as far as I see.

**Comment by fichtner** [comment] 2021-05-04 12:32
The reason I ask is that I doubt TK will go as far as saying that is an issue with the hardware or software. It's likely network setup or configuration related.

**Comment by mimugmail** [comment] 2021-05-04 16:36
Do you use netflow, ntopng or GeoIP?
CPU load during traffic?

**Comment by br-olf** [comment] 2021-05-05 18:41
Hi @mimugmail, thanks for helping.

> Do you use netflow, ntopng or GeoIP?

We use neither of these. 

> CPU load during traffic?

During all times the CPU load is below 10%

**Comment by mimugmail** [comment] 2021-05-05 19:14
Do you have gateway monitoring enabled in System : Gateways : Single?

**Comment by pm-bernhard** [comment] 2021-05-07 13:23
Hello, I'm a Team-Member of br-olf.

Thanks a lot, the hint with the Gateway-Monitoring helped!
Seems it's not a hardware related issue.

We flashed OPNsense in two different versions (20.7 and 21.1.5) and did a minimal Setup: WAN-DHCP, LAN-DHCP, only one client attached.

When Gateway-Monitoring is enabled, under high load, the status in the Dashboard goes from "Online" -> "Latency" -> "Offline" (Loss is always 0.0%) -> Then all TCP-Connections getting closed.
When we turn the Gateway-Monitoring off all is fine under high network load.

We could identify the root cause of the Problem: The ISP-Router that the OPNsense appliance uses as upstream gateway.
When we enable QoS on the ISP-Router the ping time to 8.8.8.8 increases to 1110ms under high network load (upload only, on download ping keeps low). But when a Host is the connected directly to the ISP-Router the connection does not drop.

The OPNsense related question is now: 
1. Why all connections getting dropped when Monitoring of the one and only Gateway goes to "Offline"? The connection still usable in our case, it only has a bad ping.
2. Can we configure the ping thresholds for "Latency" and "Offline" somewhere?

**Comment by pm-bernhard** [comment] 2021-05-25 05:56
I think we can close this issue.
I would like to make two feature-requests:

- When Gateway-Monitoring changes state please write something to the logfiles
- Make ping thresholds of Gateway-Monitoring configurable.

**Comment by mimugmail** [comment] 2021-05-25 06:10
gateways.log includes this info and Tuning can be done via Advanced for each gateway

**Comment by pm-bernhard** [comment] 2021-05-25 06:39
Thank you! Behind the Advanced-Button i could configure a higher latency threshold.
With the default thresholds the gateways.log contains:

May 25 08:24:18 OPNsense dpinger[91222]: send_interval 1000ms  loss_interval 2000ms  time_period 60000ms  report_interval 0ms  data_len 0  alert_interval 1000ms  latency_alarm 500ms  loss_alarm 20%  dest_addr 8.8.8.8  bind_addr 144.208.192.26  identifier "WAN_GW " 
May 25 08:24:20 OPNsense dpinger[91222]: WAN_GW 8.8.8.8: Alarm latency 1105826us stddev 0us loss 0% 
May 25 08:24:20 OPNsense dpinger[42760]: GATEWAY ALARM: WAN_GW (Addr: 8.8.8.8 Alarm: 1 RTT: 1105826us RTTd: 0us Loss: 0%) 
May 25 08:24:36 OPNsense dpinger[91222]: WAN_GW 8.8.8.8: Clear latency 221207us stddev 407766us loss 5% 
May 25 08:24:36 OPNsense dpinger[52255]: GATEWAY ALARM: WAN_GW (Addr: 8.8.8.8 Alarm: 0 RTT: 221207us RTTd: 407766us Loss: 5%

I still would prefer if the gateway does not close all connections when only one gateway is configured.

**Comment by AdSchellevis** [comment] 2021-05-25 06:41
closed as requested

**Closed by AdSchellevis** 2021-05-25 06:41 UTC
Labels: support

**Comment by mimugmail** [comment] 2021-05-25 10:35
Firewall : Settings : Advanced, Disable state killing on gateway failure
