### ISSUE TITLE
creating a new user yields empty password error

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#143] opened 2015-04-17 15:45 UTC
related to 49c891985fc733e it moved the password setting to an if block...

@AdSchellevis assigning this to you since your commit but I can do it too :)

**Comment by AdSchellevis** [comment] 2015-04-17 16:08
No problem, I will look at it.

**Comment by AdSchellevis** [comment] 2015-04-17 16:53
I was not able to reproduce, and it doesn't look like it's in the commit. The password setting should be in the block, because it's mend to handle resetting of password for a existing user. ( it tried to reset an empty user before)

Is there a specific situation where it fails?

**Comment by fichtner** [comment] 2015-04-17 19:00
When creating a new user the password is not set. There is an error in the system log "opnsense: /system_usermanager.php: There is something wrong in your config because user test2 password is missing!" and when you log out and log in you cannot authenticate with the specified password. It is missing from the config.xml altogether. :/

**Comment by AdSchellevis** [comment] 2015-04-17 19:31
Then I misunderstood... I was looking for an error in the gui :-)
I will fix it.

**Comment by AdSchellevis** [comment] 2015-04-17 19:40
fixed in https://github.com/opnsense/core/commit/77dbb57464184476c4f275f519e1594a2bd54c29

**Closed by AdSchellevis** 2015-04-17 19:40 UTC
Labels: bug

**Comment by fichtner** [comment] 2015-04-18 08:42
thank you :D
