### ISSUE TITLE
pass in  quick from {any} to {any} label "USER_RULE" from nowhere...

### ISSUE THREAD

**Issue by peysche** [opnsense/core#2075] opened 2018-01-10 14:51 UTC
Hi,

I was Troubleshooting my Firewall the last night, because an Blocking Rule was not working.

There i found out, that in my "rules.debug" file there is a "any/any" rule... I do not know where this rule comes from 
"pass in  quick from {any} to {any} label "USER_RULE""

I can not finde this rule in the GUI and i have no rules without comment in the GUI.

It seams that this rule was created from GUI, i guess because of "USER_RULE"

In my exported configuration file this rule is also not existing...

I do not know since when this rule is there...
Pleas have a look at my last issue https://github.com/opnsense/core/issues/1903
it could be that this rule is there since i implemented the fix for this issue.

How can i get rid of this rule permanently ?

If you need more information please let me know. If it is a Bug i defenitly like to help.

Thx
Paul

**Comment by AdSchellevis** [comment] 2018-01-11 07:30
Hi Paul,

Which version are you using? Maybe there's a floating rule in there which for some odd reason isn't rendered on the page, but it's hard to tell without the actual configuration.

If you can share your config.xml (via email, to ad at project domain), I can take a look at it, maybe we should add some reference in the rules.debug for easier tracking to the config xml, although I'm not yet sure what the best approach is there.

Best regards,

Ad

**Comment by peysche** [comment] 2018-01-11 08:08
Hi Ad,

I use the latest version

OPNsense 17.7.11-amd64
FreeBSD 11.0-RELEASE-p17
OpenSSL 1.0.2n 7 Dec 2017

I have never implemented an floating rule, i have it on 2 Systems.

Config comes via Mail

Thx
Paul

**Comment by AdSchellevis** [comment] 2018-01-11 21:15
Hi Paul,

I haven't received the config yet, did you send it already?

Best,

Ad

**Comment by peysche** [comment] 2018-01-11 23:12
hi, I send the mail but i got an replay from SMTP that delivery is Delayed, i try again 

Projectd Domain is the Opensense domain or ?

Thx
Paul

**Comment by peysche** [comment] 2018-01-11 23:20
Hi,

i had an typo in the Domain name... now you should have the config..

Thx
Paul

**Comment by AdSchellevis** [comment] 2018-01-12 07:33
got it :)

**Comment by AdSchellevis** [comment] 2018-01-12 08:24
Hi Paul,

Could it be the case that this config was imported or manually crafted?
It contains a duplicate of the rules section within a new rule... issue is that the ui doesn't render these entries, leaving the engine to generate an allow any rule.

![image](https://user-images.githubusercontent.com/9783985/34865760-2eede516-f77a-11e7-94d9-3edd23740120.png)

We should probably show the cases without an interface in the floating section, so we know for sure you can actually see and delete these cases.

Best,

Ad

**Comment by AdSchellevis** [comment] 2018-01-12 08:46
ok, step by step for the next time this happens. 

```
grep USER /tmp/rules.debug | grep -v on
pass in quick from {any} to {any} label "USER_RULE" # efdd56cc2fd628ffcba161e1e22e154b
```

Click 
![image](https://user-images.githubusercontent.com/9783985/34866274-558bf58a-f77c-11e7-9370-22065cb4378b.png) at the description heading.

![image](https://user-images.githubusercontent.com/9783985/34866295-6c8df396-f77c-11e7-8c0a-e8261b4a600c.png)

Code committed in https://github.com/opnsense/core/commit/c49d9ddc25adaa8e93d21607e6486c9429601914

**Comment by peysche** [comment] 2018-01-12 09:50
Hi,

No the config was not manually crafted, and i was recognizing this strange rule things as well.
I thought this is like it is and have to be there.

Following changes I have done in the last time

•	Switched the Outbound NAT from Automatic to Hybrid, and added an static outbound NAT rule for a single device.
•	Activated an second Wan Interface for an Fallback Internet Line in an Getaway group
•	And implemented the patch from case https://github.com/opnsense/core/issues/1903

I have checked this 18 rules and no of this rules are known by me… so I do not have created any of these rules.
I also not missing any other rules.

And yes for sure I have exported the config several times, and reimported the config again to revert changes I have done for test.

So as I do not know this rules, is it save to delete the rules in the config now, and restoer this modified config without this strange Rules ?

Thx
Paul

**Comment by AdSchellevis** [comment] 2018-01-12 09:58
Hi Paul,

I'm not sure what I can do here further, if there's a step by step scenario starting with the default installation which leads to this rule, I'm happy to dig in it further. For now I can only make sure the rule is visible and trackable I guess.

Best,

Ad

**Comment by peysche** [comment] 2018-01-12 10:09
Hi Ad,

I think i am fine when i remove this rules in the config and restore this crafted config. I do rely not know where this comes form. to see such rules in the GUI is perfect, and there it can be deleted as well.

I think this strange config comes from a strange Bug. To find this Bug is hard without possible repro. Reason for my thinking is because it is happen on wo different systems. one system is my playground, and the other one is let’s say "prod", and on the prod i do changes after test on the first system. If I have Time, and will be able to repro this topic, I will let you know.

Let’s say, maybe someone has the same problem, then he will find the reason in this Thread.

May be an of topic Question, is it possible to enable/disable Rules with the REST API ?

THX Ad, and have a nice Weekend !

**Comment by AdSchellevis** [comment] 2018-01-12 10:15
Hi Paul,

Api support isn't yet available, we're still working on that area.

Have a nice weekend,

Best,

Ad

**Closed by AdSchellevis** 2018-01-12 10:15 UTC
Labels: bug, cleanup
