### ISSUE TITLE
paging function IDS Alerts

### ISSUE THREAD

**Issue by gbonny1982** [opnsense/core#4076] opened 2020-04-29 09:45 UTC
I'm running OPNsense 20.1.5 and run into a problem that exists in many previous releases too.

When you have IDS set up and alerts are getting registered after a while. By default OPNSense shows 7 alerts per page. 

1.) I have many alerts, on the bottom right side it shows "Showing 15 to 21 of 22 entries" while there are more then 22 entries. When I click next page (page# or ">"), it shows "Showing 22 to 28 of 29 entries" and so on. 
Where I had expected it shows "Showing 22 to 28 of 22.000 entries" for instance.

2.) When I change max alerts to 250 and search for a specific IP, it shows "Showing 1 to 7 of 26 entries" while all 26 entries are listed. 
Where I had expected it shows "Showing 1 to 26 of 26 entries"

3.) still at the point of problem 2, it shows paging numbers 1, 2 ,3 ,4 > and >> 
Where I had expected just page 1 was clickable.

**Comment by AdSchellevis** [comment] 2020-04-29 09:55
duplicate https://github.com/opnsense/core/issues/4053, which is a duplicate of https://github.com/opnsense/core/issues/756, explanation why this works the way it does can be found in both tickets.

**Closed by AdSchellevis** 2020-04-29 09:55 UTC
