### ISSUE TITLE
Routes configuration uses wrong interface in multi-wan with duplicate gateway ips

### ISSUE THREAD

**Issue by Teruell** [opnsense/core#5780] opened 2022-05-16 21:52 UTC
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [Y] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [Y] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Multi-WAN set up with two system gateways which have the same gateway IP (same ISP), as follows:

Name: WAN4_Gateway (active), Interface: WAN4_igb4 Priority: 100 (upstream), Gateway: 100.64.0.1
Name: WAN5_Gateway, Interface: WAN5_igb5 Priority: 101 (upstream), Gateway: 100.64.0.1

Trying to set a static route for 192.168.100.1 to the WAN5_Gateway, via webUI System/Routes/Configuration:

Routes before (no configuration in webUI):

route get 192.168.100.1
route to: 192.168.100.1
destination: default
gateway: 100.64.0.1
interface: igb4

Which seems correct. Via WebUI, add this:

Network Address: 192.168.100.1
Gateway: WAN4_Gateway - 100.64.0.1

which results in the expected route:

route get 192.168.100.1
route to: 192.168.100.1
destination: 192.168.100.1
gateway: 100.64.0.1
interface: igb4

However, if I add this via the WebUI:

Network Address: 192.168.100.1
Gateway: WAN5_Gateway - 100.64.0.1

I get the same route:

route get 192.168.100.1
route to: 192.168.100.1
destination: 192.168.100.1
gateway: 100.64.0.1
interface: igb4

**Expected behavior**

I would expect a route for 192.168.100.1 added for gateway 100.64.0.1 via interface igb5

**Describe alternatives you considered**

I can manually add the route with:

route add -net 192.168.100.1/32 -interface igb5

which results in the expected route:

route get 192.168.100.1
route to: 192.168.100.1
destination: 192.168.100.1
interface: igb5

**Environment**

OPNsense 22.1.7_1-amd64

**Comment by fichtner** [comment] 2022-05-17 04:26
Duplicate of #5779

**Closed by fichtner** 2022-05-17 04:26 UTC
