### ISSUE TITLE
no default route when changing to static IPv4 WAN interface and default gateway applied

### ISSUE THREAD

**Issue by RobertVanPapeveld** [opnsense/core#17] opened 2015-01-07 15:21 UTC
When changing WAN interface to a static IPv4 WAN and apply a default gateway then no default route is created.

**Comment by jschellevis** [comment] 2015-01-07 17:15
confirmed, the issue appears when there is not default route. In that case a route change -inet cannot work. solution seems to be add a default route when none exists.

**Comment by jschellevis** [comment] 2015-01-08 14:30
fixed in d2fa9a5

**Closed by jschellevis** 2015-01-08 14:30 UTC
Labels: bug
