### ISSUE TITLE
[BUG] Watchdog timeout - interface link state DOWN UP loop

### ISSUE THREAD

**Issue by aronmal** [opnsense/core#5602] opened 2022-02-26 14:00 UTC
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

I have OPNsense 22.1 installed on a mini pc **MSI Cubi N 8GL-079DE** and have connection issues. When doing a speed test or it is consistently "crashing" and also sometimes while browsing or using the web GUI. I can see the following on the monitor after boot:

```
*** SecondaryFw.localdomain: OPNsense 22.1.1_3 (amd64/OpenSSL) ***

 LAN (re0)      -> v4: 10.1.0.3/24
 WAN (re0_vlan10)   -> v4/DHCP: [...IP...]
                      v6/DHCP: [...IP...]

 HTTPS: SHA256 [... hexadecimal numbers ...]
               [... hexadecimal numbers ...]

FreeBSD/amd64 (SecondaryFw.localdomain) (tttyv0)

login:
``` 
after "forcing" the problem with a speed test it adds following lines:
```
re0: watchdog timeout
re0: link state changed to DOWN
re0_vlan10: link state changed to DOWN
re0: link state changed to UP
re0_vlan10: link state changed to UP
```
After a few seconds (I guess 10-30s) the connection is back and the problem can happen again. That's why the monitor looks like this:  

```
[...]

FreeBSD/amd64 (SecondaryFw.localdomain) (tttyv0)

login: re0: watchdog timeout
re0: link state changed to DOWN
re0_vlan10: link state changed to DOWN
re0: link state changed to UP
re0_vlan10: link state changed to UP
re0: watchdog timeout
re0: link state changed to DOWN
re0_vlan10: link state changed to DOWN
re0: link state changed to UP
re0_vlan10: link state changed to UP
re0: watchdog timeout
re0: link state changed to DOWN
re0_vlan10: link state changed to DOWN
re0: link state changed to UP
re0_vlan10: link state changed to UP
re0: watchdog timeout
re0: link state changed to DOWN
re0_vlan10: link state changed to DOWN
re0: link state changed to UP
re0_vlan10: link state changed to UP
```
***

**To Reproduce**

1. Installed 22.1 on my device
2. Created VLans and other settings
3. making a speed test (for example fast.com)
4. Network connection issue

**Expected behavior**

Continuous working internet connection

**Relevant log files**

Dashboard -> System -> Log Files -> General
[system.log](https://github.com/opnsense/core/files/8146693/system.log)

**Additional context**

I tried updating from 21.7 to 22.1 the first time and fresh install two times after. I do not have this problem with 21.7 and before, I did also a fresh install of it and worked without a problem. I am currently running 22.1 with an Intel NIC 4x 1GB (pcie passthrough) on my home server in a VM. I am not using VLans there and was not able to test VLans yet due to needed uptime. I am guessing it has to do with the VLan, because i have no problem with the VM on my server without them.

**Environment**

OPNsense 22.1 and 22.1.1 testet not working
OPNsense 21.7 tested working

MSI Cubi N 8GL-079DE:
- Intel Pentium N5000 1.1Ghz Quad Core
- 4GB RAM
- LAN Realtek RTL8111H

**Comment by AdSchellevis** [comment] 2022-02-26 14:14
duplicate of https://github.com/opnsense/src/issues/155

**Closed** 2022-02-26 16:12 UTC
Labels: support
