### ISSUE TITLE
Support for RFC4638

### ISSUE THREAD

**Issue by andrew-s** [opnsense/core#572] opened 2015-12-27 15:40 UTC
Been trying to get MTU > 1492 to work on PPPoE connections (my ISP supports that along with the modem i'm using), from some initial investigation I thought it would be the PPP daemon (mpd) but it looks like a few months ago they implemented this;

http://sourceforge.net/p/mpd/bugs/54/

But it seems it requires FreeBSD 10.2 to work (assuming it does work when all the pieces come together) - I believe, everything else has the support for the larger MTU's.

Thanks!

**Comment by fichtner** [comment] 2015-12-27 16:29
Hi Andrew,

Thanks for the pointers. The kernel support will be in the upcoming 16.1 in late January *and* the stable release 15.7.24 in early Januar. :)

The last MPD bump I can see was in August, I don't believe the patches are in the FreeBSD ports tree yet. I've contacted David Wood, but so far I haven't gotten a response.

I think it brings us down to 2 out of 3 issues:

* ~~kernel support in FreeBSD src~~
* daemon support in FreeBSD ports
* config glue in OPNsense

**Comment by andrew-s** [comment] 2015-12-27 23:17
Thanks for the response @fichtner - I installed opnsense yesterday, it seems to suggest the mpd5 version installed is 5.7 (4-nov-2015) - but I agree, I couldn't really see if that version did contain an MTU fix.

Will try and find some information myself unless anyone else can comment with greater details.

**Comment by sthen** [comment] 2015-12-27 23:59
Hi Franco, the mpd support didn't make it in yet (and I see the last commit to the port was done with maintainer timeout).. looks like you're already in cc list for the PR containing the port patches (https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=203695)

**Comment by fichtner** [comment] 2015-12-28 09:14
Hi Stuart, you're right. Maybe @koobs can advise as far as FreeBSD ports committing goes?

@andrew-s I will build a test version for you including these patches. I'm not against merging them into OPNsense prior to FreeBSD, but need user confirmation that they work as expected. :)

**Comment by koobs** [comment] 2015-12-28 09:22
@fichtner @sthen How can I help?

**Comment by fichtner** [comment] 2015-12-28 09:23
@koobs how should https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=203695 be proceeded? Prodding, timeout? Build logs, etc?

**Comment by fichtner** [comment] 2015-12-28 09:29
@koobs thanks, I will provide portlint and poudriere output

**Comment by andrew-s** [comment] 2015-12-28 16:01
@fichtner Yeah no problem, happy to test and make sure it's all working :)

**Comment by davidjwood** [comment] 2015-12-28 16:54
Kernel support was [introduced to FreeBSD 11-CURRENT in r287654](https://svnweb.freebsd.org/base?view=revision&revision=287654) and [MFCed to 10-STABLE in r288918](https://svnweb.freebsd.org/base?view=revision&revision=288918). The change should apply to any recent FreeBSD kernel (including 9.x, if that's what you're still using) without changes, as the kernel netgraph code is fairly static and mature.

mpd5 support is yet to be committed to FreeBSD ports, though there is a patch in [FreeBSD bug 204695](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=203695). The revised patch follows comments from @koobs in the bug, and makes the incorporation of the RFC 4638 patches conditional on __FreeBSD_version high enough to indicate the relevant kernel support exists. If you add the RFC 4638 patch to an older kernel, you'll need to change net/mpd5/Makefile so that the RFC 4638 patches are included unconditionally.

Once you have kernel and mpd5 support available, the FreeBSD bug tells you how to configure the PPPoE parent interfaces and mpd5.


I believe your interfaces.inc has diverged quite significantly from pfSense's version. My experience of adding RFC 4638 support to pfSense suggests that careful design is needed of the logic for setting and testing parent interface MTUs. You need to support both physical interfaces and vlans as PPPoE parent interfaces whilst respecting the Principle of Least Astonishment. The vlan case is trickier to get right, not least as other vlans on the same physical interface having MTU > 1500 without explicit configuration is a bad idea!

**Comment by fichtner** [comment] 2015-12-29 08:49
@andrew-s test package for mpd5 is now available. you'll also have to use the new kernel...

    # opnsense-update -bkr 15.7.24
    # pkg add -f https://pkg.opnsense.org/snapshots/mpd5-5.7_4.txz

Manual config is necessary still, but it should be functional at least.

**Comment by gonzopancho** [comment] 2016-01-05 07:49
@andrew-s 

On top of what @davidjwood mentions above, he has recently issued a pull request which is now a part of pfSense 2.3.

https://github.com/pfsense/pfsense/commit/bba669d9cbe52bd84e02f749df0fd83aac6871c2

pfSense now has complete code and solution for RFC4638 support.  Given this, perhaps you can help OPNsense with an implementation.

**Comment by fichtner** [comment] 2016-01-07 08:53
mpd 5.8 has been released with thus fix and will be available in 15.7.24. The only missing piece is the GUI code additions for writing the proper config file. :)

**Comment by davidjwood** [comment] 2016-01-08 10:26
@andrew-s (or anyone else working on this) My implementation of RFC 4638 support for pfSense has now been [merged into pfSense 2.3](https://github.com/pfsense/pfsense/commit/bba669d9cbe52bd84e02f749df0fd83aac6871c2).

The logic used is documented in the [pull request](https://github.com/pfsense/pfsense/pull/1959). I hope that information is helpful.

**Comment by fichtner** [comment] 2016-01-08 10:30
@davidjwood thanks for checking back and congrats for getting the feature merged finally :) I don't think this will make it in time for 16.1, but it'll be shipped in one of the minor updates that follow.

**Comment by andrew-s** [comment] 2016-01-09 19:30
@fichtner I haven't managed to get this to work, still seem to be getting 1492 regardless - doing "onsense-update -kr 15.7.24 && reboot" did upgrade, but the version numbers still seem to be off on the kernel - any ideas?

**Comment by fichtner** [comment] 2016-01-09 22:45
Off how? 10.1-RELEASE-p25 is the kernel version. The real 15.7.24 is out on Monday along with MPD 5.8. The core adjustments are missing too, Ad will look at those after his well-deserved holiday. :)

**Comment by syserr0r** [comment] 2016-01-15 13:59
Running 15.7.24 and editing `/usr/local/etc/inc/interfaces.inc` around line 1750 as follows has allowed me to have a 1500 MTU PPPoE connection.

```
EOD;

                if (empty($mtus[$pid]))
                        $mtus[$pid] = $defaultmtu;
                        $mpdconf .= <<<EOD
        # set link mtu {$mTus[$pid]}
        set pppoe max-payload 1500

EOD;

                if (!empty($mrus[$pid]))
                        $mpdconf .= <<<EOD
        # set link mru {$mrus[$pid]}
        set link mru 1500
EOD;```

**Comment by fichtner** [comment] 2016-03-01 19:25
Confirmed by multiple users, will ship this tomorrow in 16.1.5. Thanks everyone!!! :)

**Closed by fichtner** 2016-03-01 19:25 UTC
Labels: feature
