### ISSUE TITLE
system: switch default gateway by optionally selected group

### ISSUE THREAD

**Issue by mimugmail** [opnsense/core#2279] opened 2018-03-21 14:00 UTC
Hi,

is it possible to set a metric in routes or better in gateway config? 
The problems is when you have more than 2 lines you can not set an order which line follows after primary down (with gateway switching). 

With Cisco you can set as many default gateways and use metrics to set the priority. 

Is this also possible with FreeBSD / OPN?

**Comment by fichtner** [comment] 2018-03-21 14:14
I think route metrics are not in FreeBSD https://github.com/opnsense/core/issues/123

**Comment by mimugmail** [comment] 2018-03-21 17:56
Hm, OK, Not used by recent kernels. In Gateway - Advanced you can set a priority, would it be possible to patch the Script for adding routes to respect this setting?

**Comment by fichtner** [comment] 2018-04-01 17:19
@mimugmail what exactly do you mean?

**Comment by mimugmail** [comment] 2018-04-01 19:56
Via Advanced in gateways you can set a priority. When you have 3 you can set them 1 to 3 and when failover occurs, the script changing the routes could (if possible) check if the gateway which is down is a lower number, and if yes is there another gateway with a lower number, then use this as next default gateway, if not, self default gateway.

**Comment by fichtner** [comment] 2018-04-01 21:05
You mean „weight“?

Yes, we could use that during default gateway switching. But the default gateway will be highest in priority, no matter the weight value.

AFAIK, the weight is for load balancing on multi-wan to distribute traffic using a non 50-50 distribution.

**Comment by mimugmail** [comment] 2018-04-02 04:55
Oh, weight, correct. But that doesn't matter since in setups were weight is activly used, you don't care which default gateway the system has. But when you have a 1G, a 100M and a LTE line you don't want to see the firewall switch from 1G to LTE. Sure, the default gw is highest and there can only be one at a time. But it would be good to have a choice :) 

In the long term (20.1, 20.7) I'd love to see the way Cisco does this with monitoring groups and tracked interfaces. 👍

**Comment by fichtner** [comment] 2018-04-02 07:11
Okay, i think we’re on the same page then. 😊

**Comment by mimugmail** [comment] 2018-07-30 06:47
@AdSchellevis this was the topic we talked via IRC lately :)

**Comment by AdSchellevis** [comment] 2018-07-30 06:52
@mimugmail ok, to summarize what we've discussed (if I remember correctly). 

If @fichtner agrees, we could add a marker for "backup default" with a weight and use the weights to sort the gateways. This would allow us to prioritise default gateway switching. Ideally we would like to use policy based routing for local traffic too, but that is more of a long run solution. agreed? (if so, I'm offering todo the work for this item)

**Comment by fichtner** [comment] 2018-07-30 06:55
yes, but I want to see how https://github.com/opnsense/core/commit/da4d25e629 works out on 18.7... it's preliminary work to exclude certain gateways from default gateway switching. it's not practical to mark a gateway down and should probably be a separate option, but if this separate option is what we talk about here with a priority setting that would be best.

**Comment by fichtner** [comment] 2018-07-30 06:56
(it's correct to exclude down gateways from switching, I just mean it's impractical if you don't want it down and still not use it for default switching)

**Comment by mimugmail** [comment] 2018-07-30 06:56
Full agree with this! :) 

Just to have it here: The need for local PBR traffic would cover all transparent stuff like Squid, siproxd, ftp-proxy etc. 

Local PBR can be a mind/long term task :)

Thanks guys, very appreciated!

**Comment by fichtner** [comment] 2018-11-24 11:52
- [x] Add gateway group selection for IPv4 and IPv6
- [ ] Move gateway switching back to System: Settings: General (not deprecated, not part of firewall)
- [ ] Possibly move fixup_default_gateways() to routing setup
- [ ] Pass down gateways in order for fixup_default_gatways() to use them only or any available one

**Comment by mimugmail** [comment] 2018-11-24 12:01
If you need root access to some Multi WAN systems, ping me <3

**Comment by fichtner** [comment] 2018-11-24 12:02
@mimugmail I'll let you know when to test. Still some things to figure out.

**Comment by fichtner** [comment] 2019-01-20 10:50
Unfortunately 19.1 is too close now and the seemingly simple changes are too dangerous to implement in the current spaghetti code without risking regressions. We may be to rework some of it first... :(

**Comment by mimugmail** [comment] 2019-01-20 12:57
Indeed, No risk, Just fun :)

**Comment by niziak** [comment] 2019-04-05 07:29
Similar issue was here: #2563

**Comment by AdSchellevis** [comment] 2019-04-10 16:12
@mimugmail the gateway status/edit pages are changed now, could you check on your end? system_gateways.php is ordered by priority now and marks the gateways "(default)" according to the new logic. 

The routing itself is still setup with the old code, but the status page should reflect how it would react when finished.

It's quite a project to reimplement all the logic here and keep user impact as low as possible, so a pair of extra eyes while working on it would be highly appreciated. Thanks!

**Comment by mimugmail** [comment] 2019-04-10 20:15
Priority selection looks good. Currently my test system don't like to monitor my first default gateway, strange. Other two gateways are monitored. What I observed is, that when I set a second gateway as default, the checkbox in the first gateway isn't deselected. Also not sure if this was the case before, but doesn't make sense.

**Comment by mimugmail** [comment] 2019-04-10 20:20
Another observation. Default gateway prio1, has IP 192.168.0.1 ... when I change IP to 192.168.0.2 it get's saved. But when I change prio of this gateway to 4 ... the IP is back at 192.168.0.1.

**Comment by mimugmail** [comment] 2019-04-11 04:41
I'm not sure if it's a good idea to make prio 1 the default when adding new gateway, as it would break a setup when adding a new internal one. This is one part of the problematic, since when you have two or more WAN gateways and an internal to a VoIP net or whatevery, it could be chosen as your default one (if not marked as down)

**Comment by fichtner** [comment] 2019-04-11 06:03
I’m not sure if we need a prio after all. My idea was to use the gateway group ordering. It fulfils the same requirement in the end.

So you could choose one default gateway group for IPv4 and IPv6 or leave the default behaviour (which can already be steered by force down).

**Comment by AdSchellevis** [comment] 2019-04-11 06:53
@mimugmail @fichtner some feedback:

- "What I observed is, that when I set a second gateway as default, the checkbox in the first gateway isn't deselected"

That's on purpose, you can have multiple defaults, which are selected by priority. The form shows the active default. The previous auto deselect was quite wonky to start with.  We could reimplement something similar, although I don't think we should, since part of the gateways are automatic and could be default (dhcp for example), which always leads to some weirdness in the logic underneath.

- "Default gateway prio1, has IP 192.168.0.1 ... when I change IP to 192.168.0.2 it get's saved. But when I change prio of this gateway to 4 ... the IP is back at 192.168.0.1."

I'm not sure I can reproduce this, it doesn't make sense it knows previous state.  Just to be sure, was this a manually added gateway or a dynamic one?

- "I'm not sure if it's a good idea to make prio 1 the default when adding new gateway, as it would break a setup when adding a new internal one. This is one part of the problematic, since when you have two or more WAN gateways and an internal to a VoIP net or whatevery, it could be chosen as your default one (if not marked as down)"

Higher priority would make it more attractive, you would like to set this to 0 when new/dynamic (same as localhost networks)?

- "I’m not sure if we need a prio after all. My idea was to use the gateway group ordering. It fulfils the same requirement in the end." 

I think we should have a priority, since it prevents twisted logic while selecting gateways. Most of the misery now seems to be a result of not being able to properly select which gateway is default now, this at least provides the option to make it explicit. Don't the groups already support this kind of priority using the Tiers by the way?

**Comment by mimugmail** [comment] 2019-04-11 06:53
Would this work if you have more than one FO group.

**Comment by fichtner** [comment] 2019-04-11 06:58
Does this mean we're not doing "default gateway group" idea anymore? I seems cleaner to me but happy to delete the remaining code to not have conflicting systems of operation.

More than one default gateway is going to introduce side effects in other code unless everything is neatly refactored. The groups avoid all this and you don't actually have multiple gateways in our system just one according to rotation so double or triple check default gateway depends on settings default gateway switching in the first place. What happens if it is turned off? Or are we going to remove this feature checkbox as well?

**Comment by AdSchellevis** [comment] 2019-04-11 07:08
I'm not sure which code you mean now, which code would need to be deleted?

As for refactoring the rest of the gwlb.inc, I am going to fix that too, we can't have different decision options about what's "default". so getDefaultGW() should be the only call to determine this.
I want to prevent being haunted by gateway misery indefinitely :) it's flawed by design now.

**Comment by fichtner** [comment] 2019-04-11 07:13
https://github.com/opnsense/core/blob/master/src/www/system_general.php#L445-L477

then let's ditch all of this. from what I can understand none of these config.xml related settings will be needed?

**Comment by AdSchellevis** [comment] 2019-04-11 07:15
except the "gw_switch_default" I presume, since we don't have a good option to fix the local default using policy based routing.

**Comment by AdSchellevis** [comment] 2019-04-11 07:16
let me rework fixup_default_gateway() first, so you know what I mean.

**Comment by fichtner** [comment] 2019-04-11 07:18
if we can have multiple default gateways selected in their settings we don't need gw_switch_default :)

**Comment by AdSchellevis** [comment] 2019-04-11 07:19
there is no trigger to change gateways now when the gateway is down.... we can change its name, but the function isn't there by my knowledge.

**Comment by mimugmail** [comment] 2019-04-11 08:04
IMHO, there are two options:

1. Have a default gw group, like with gateway groups for failover
2. Have priorities like Ad started, but the we could/should just rename "Default Gateway" to something like "WAN Gateway". So, it's clear that it's for outside connections, and of course, you can have multiple of them.

**Comment by AdSchellevis** [comment] 2019-04-11 08:09
I like the idea of "WAN Gateway", but that's more a naming thing we can sort out when finished with the code.

I think it will be pretty difficult to have a default group, since in the end, the group itself would need a priority then (within the tier) so we can select one default active gateway. Maybe I'm missing something obvious, but to me it looks like the problem is always the same, but more related to the gateway than the group.

**Comment by mimugmail** [comment] 2019-04-11 08:13
It's indeed just a naming confusion. A default gateway can only be one gateway (the default). What we do/want here is a tiering for it, so there still can be only ONE default gateway. That's why I was confused yesterday when testing the code as in status view there is only one gw marked as default, but in edit mode the checkbox for "Default Gatway" was ticked on multiple gateways :) 

Back to the default prio, I'd say a default of 0 or none would be best, so when adding new gateways (automatic or manually) won't break your current configuration, especially when working remote.

**Comment by AdSchellevis** [comment] 2019-04-11 08:16
default is 1 now, for both automatic and manual, changing both to 0 would do the same. right? I don't mind what it is, as long as the mechanism doesn't change drastically.

**Comment by mimugmail** [comment] 2019-04-11 08:22
1 is highest priority right? So GW with prio 1 has most chance to be default? Then it doesn't make sense to me to have default 1 when adding new GW. A default that gateway is not in the decision process (like 0?) would make more sense to me.

**Comment by AdSchellevis** [comment] 2019-04-11 08:23
no higher is more important, so it would prefer 2 over 1, the sorting order in the form matches preference (for easy tracking)

**Comment by mimugmail** [comment] 2019-04-11 08:34
Oh, but this is reversed compared to Tier's in Failover Groups, wouldn't this confuse the end user?

**Comment by AdSchellevis** [comment] 2019-04-11 08:49
I'm not sure, weights work the same in the same form... I don't have a strong preference, although we need to calculate it to keep max --> low to prevent the order changing from what it was (dynamic preferred over manual).

Order seems to be quite important, and quite obscure how it was.

**Comment by mimugmail** [comment] 2019-04-11 09:20
It's only related to UX, as an enduser working with Tiering I'd expect that Prio1 would be chosen first.

**Comment by AdSchellevis** [comment] 2019-04-11 09:21
default 255 and 1 highest then?

**Comment by mimugmail** [comment] 2019-04-11 09:25
Perfect! :)

**Comment by AdSchellevis** [comment] 2019-04-13 15:43
@mimugmail The complete gateway code is refactored, I did some testing locally and all looks more consistent now. Eventually we could consider to also migrate `return_gateway_groups_array()`, which would make `gwlb.inc` the `dpinger.inc` package.

As soon as you have some time for testing, let me know.

**Comment by AdSchellevis** [comment] 2019-04-13 15:51
some notes, for future reference:

- `system_routing_configure()` doesn't (and didn't) consider gateways that are down, we might want to rethink that at some point in time, since its not only called on bootup.
- `legacy_interfaces_details()` is pushed as a parameter into the constructor, which is needed at the moment to keep interfaces clean. we might want to consider moving `legacy_interfaces_details()` into its own class and use it directly from the `Gateways()` class

**Comment by fichtner** [comment] 2019-04-13 17:38
I'm ok with changing the name to dpinger.inc -- gwlb.inc shouldn't be in interfaces.inc anymore and related code should be moved either to system.inc or interfaces.inc.

Shall I opportunistically change the file name right away?

**Comment by fichtner** [comment] 2019-04-13 18:11
(my IPv4 is completely broken on master as it seems to stuff an extra default gateway into the mix for the HE tunnel, which is IPv6 only and requires another IPv4 gateway. Some other issues along the way as far as I can see now. I can look into it on Monday.)

**Comment by AdSchellevis** [comment] 2019-04-13 19:38
it's probably something small, just let me know if I can help debugging it.

**Comment by AdSchellevis** [comment] 2019-04-14 12:46
@fichtner can you try this https://github.com/opnsense/core/commit/7a8b12f030a851a801f55c27ee2a90635805020c ? I might have been a bit to enthusiastic here by adding tunnel endpoints automatically as possible gateways. The old code only included the ones which wrote a `/tmp/XX_router` file. Other possible suspect is https://github.com/opnsense/core/commit/bfca97e2e0d821e3e9ad38833fd99f4a302bee83, which accidentally returned a gateway without an address.

**Comment by mimugmail** [comment] 2019-04-15 06:05
When manually disabling gw with prio 1 it's changing correctly, after enabling it seems to recognize the correct gw (188) but sets 127.0.0.1 as default:

```
Apr 15 07:58:30 OPNsense opnsense-devel: /system_gateways.php: ROUTING: entering configure using defaults
Apr 15 07:58:30 OPNsense opnsense-devel: /system_gateways.php: ROUTING: IPv4 default gateway set to wan
Apr 15 07:58:30 OPNsense opnsense-devel: /system_gateways.php: ROUTING: setting IPv4 default route to 81.24.66.188
Apr 15 07:58:30 OPNsense opnsense-devel: /system_gateways.php: ROUTING: removing /tmp/em0_defaultgw
Apr 15 07:58:30 OPNsense opnsense-devel: /system_gateways.php: ROUTING: creating /tmp/em0_defaultgw using '81.24.66.188'
Apr 15 07:58:30 OPNsense opnsense-devel: /system_gateways.php: ROUTING: IPv6 default gateway set to loopback
Apr 15 07:58:30 OPNsense opnsense-devel: /system_gateways.php: ROUTING: setting IPv6 default route to ::1
Apr 15 07:58:30 OPNsense opnsense-devel: /system_gateways.php: ROUTING: keeping current default gateway '::1'
Apr 15 07:58:30 OPNsense opnsense-devel: /usr/local/etc/rc.filter_configure: ROUTING: removing /tmp/em0_defaultgw
Apr 15 07:58:30 OPNsense opnsense-devel: /usr/local/etc/rc.filter_configure: ROUTING: creating /tmp/lo0_defaultgw using '127.0.0.1'
Apr 15 07:58:30 OPNsense opnsense-devel: /usr/local/etc/rc.filter_configure: ROUTING: keeping current default gateway '::1'

```

**Comment by AdSchellevis** [comment] 2019-04-15 06:45
@mimugmail ok, I'll have to check where `/tmp/lo0_defaultgw` comes from in this case.

**Comment by AdSchellevis** [comment] 2019-04-15 08:05
ok, it seems that I missed a race condition, this is all just too stupid. When a file exists with the name `/tmp/[intf]_defaultgw[v6]`, it's considered "default" (as it was before), but the file itself is written when setting a default route...

https://github.com/opnsense/core/blob/c4d42929fb7c76f528c023c4286b2e23355e659f/src/etc/inc/system.inc#L430

**Comment by AdSchellevis** [comment] 2019-04-15 09:52
@mimugmail @fichtner I'm not exactly sure yet why the gateway switched to localhost (other than the fact that localhost is in our list now, but with a very low priority), I'll have to do some more testing over here as well.  The interaction with dhclient looks a bit fragile, so I rather not touch that one if possible. 

In https://github.com/opnsense/core/commit/dd8d3444f5bdc301fdf2ab49517729e5f24f4926 I've deleted the `_defaultgw` as prioritisation, which looks more logical, but I can't find any consumers for the `_defaultgwv6` file. any ideas where that is/should be used?

**Comment by AdSchellevis** [comment] 2019-04-15 11:32
For reference, the `_defaultgw` originates from quite some time ago:

Add "new status file" in https://github.com/pfsense/pfsense/commit/924f202ee818c72b10855d3a1c06b34a9e7aa595 and then at some point in time, create a loop to read the same back to determine "default" https://github.com/pfsense/pfsense/commit/999111cb73957679debbe5831e1b7d01c3985b1f

Then ipv6 came in https://github.com/pfsense/pfsense/commit/5a5413bb5227e084703515007cc28fd746183c9b , which copied the same `_defaultgw` to `_defaultgwv6`, which for as far as I can find is only written, not really used in a similar way as a dhclient to renew an address

**Comment by AdSchellevis** [comment] 2019-04-15 14:57
@mimugmail this https://github.com/opnsense/core/commit/497f523f6e86fbbd229793a6ffafd6e0f61ab78c might be your issue, although I did commit some other small fixes as well. 

While testing, I noticed my gateway overview reported a gateway down right after apply,  where it actually didn't know the status yet. If a filter reload would be started at the same time (which your logs seem to suggest), it would mean that this gateway would not be considered anymore.

**Comment by mimugmail** [comment] 2019-04-15 15:21
I'll fetch latest master tonight on a fresh machine. Seems my test machine has 2 gateways with same name in config.xml

**Comment by AdSchellevis** [comment] 2019-04-15 15:23
thanks!

**Comment by hippi-viking** [comment] 2019-04-15 15:23
Thanks for all the hard work on this guys!
To chime in I have some problems with the current (19.1.6) gateway-switching logic which might be relevant for the reworked code as well.

My setup has a (tier 1) cable modem connection considered to work most of the time, when it doesn't I plug in my mobile (tier 2) to use them as a failover group. (The mobile's interface is locked to prevent removal, just marked as down and the gateway disabled when the cable modem works normally and the mobile is not connected.)

The problem is that when the cable modem is offline it still reacts to the DHCP request from the OPNsense box, which in turn accepts is as the default gateway without any further checks.
Steps to reproduce the issue:
 - tier 1 cable modem connection offline, tier 2 mobile connection online (dpinger thinks this as well), default gw is the mobile
 - DHCPREQUEST to cable modem (192.168.100.1)
 - DHCPACK from cable modem (192.168.100.10)
 - default route changed to 192.168.100.1
 - uplink connection is lost

The bad think is that this happens every few minutes, even if I forcefully mark the cable modem's gateway as down. Would it be possible to insert a check in the logic to determine if the would-be default gateway is online at all? (Dpinger should already know about this.)

Thanks very much!

**Comment by AdSchellevis** [comment] 2019-04-16 12:25
@fichtner we could probably move `gwlb.inc` now, I have gathered the last todo's in https://github.com/opnsense/core/issues/3423 about the two functions that might be used in older plugins, not sure when we can kill those.

**Comment by mimugmail** [comment] 2019-04-16 21:11
Fetched latest master, only had one gateway with Prio1:

```
    <gateway_item>
      <interface>wan</interface>
      <gateway>81.24.66.129</gateway>
      <name>GW_WAN</name>
      <priority>1</priority>
      <weight>1</weight>
      <ipprotocol>inet</ipprotocol>
      <interval>1</interval>
      <descr>Interface WAN Gateway</descr>
    </gateway_item>
```

Then I added a second one with Prio2 and now it's active and new default:

```
  <gateways>
    <gateway_item>
      <interface>wan</interface>
      <gateway>81.24.66.129</gateway>
      <name>GW_WAN</name>
      <priority>1</priority>
      <weight>1</weight>
      <ipprotocol>inet</ipprotocol>
      <interval>1</interval>
      <descr>Interface WAN Gateway</descr>
    </gateway_item>
    <gateway_item>
      <interface>wan</interface>
      <gateway>81.24.66.188</gateway>
      <name>NOCDialin</name>
      <priority>2</priority>
      <weight>1</weight>
      <ipprotocol>inet</ipprotocol>
      <interval/>
      <descr/>
      <defaultgw>1</defaultgw>
    </gateway_item>
  </gateways>

```


```
Apr 16 23:06:37 OPNsense opnsense-devel: /system_gateways.php: Successful login for user 'root' from: 81.24.66.132
Apr 16 23:07:22 OPNsense opnsense-devel: /system_gateways.php: ROUTING: entering configure using defaults
Apr 16 23:07:22 OPNsense opnsense-devel: /system_gateways.php: ROUTING: IPv4 default gateway set to wan
Apr 16 23:07:22 OPNsense opnsense-devel: /system_gateways.php: ROUTING: setting IPv4 default route to 81.24.66.188
Apr 16 23:07:22 OPNsense opnsense-devel: /system_gateways.php: ROUTING: removing /tmp/em0_defaultgw
Apr 16 23:07:22 OPNsense opnsense-devel: /system_gateways.php: ROUTING: creating /tmp/em0_defaultgw using '81.24.66.188'
Apr 16 23:07:22 OPNsense opnsense-devel: /usr/local/etc/rc.filter_configure: ROUTING: keeping current default gateway '81.24.66.188'

```

**Comment by fichtner** [comment] 2019-04-17 05:22
@AdSchellevis thanks, it works out of the box now, but I have a few questions later today about the code and backwards-compat

**Comment by mimugmail** [comment] 2019-05-07 13:24
@AdSchellevis finally got my pppoe running. I think I've tested most possible combination including DHCP, pppoe, static, mixed als with IPv6.
Only thing I noticed was that a HE gif interface was set per default as upstream and took over (IPv6) while current v6 gateway was also prio 255.

**Comment by AdSchellevis** [comment] 2019-05-07 13:36
@mimugmail ok, thanks for testing, I don't think we can fix choosing the gif interface with the current logic, since it's a gateway like all the others now (same applies for the old code by the way).

**Comment by mimugmail** [comment] 2019-05-07 13:53
@AdSchellevis one thing I noticed is that new code differs a bit in the logic gateway selection/assuming like discussed in #3464 
With 19.1 code when I use optX as a WAN and don't choose upstream gateway (or even have one), I don't get a default route. The new code base also sets a default gateway no matter if I want one or not, it seems just to look for if optX has a related gateway and uses this one. 
I for myself am not sure what is best here .. the OP of other thread needs a system with multiple WANs but none gateways set and is unable to do so. Maybe it's easy to exclude opt interfaces from gateway assuming process?

**Comment by AdSchellevis** [comment] 2019-05-07 14:09
I think we can incorporate something simple when this is in, although as far as I know, 19.1 (without the new code) acts basically the same in this perspective, otherwise there probably wouldn't be an issue in https://github.com/opnsense/core/issues/3464. 

Not sure what the eventual logic should look like, but it should involve phasing out "Allow default gateway switching" in favour of selecting multiple gateways as upstream (as @fichtner suggested) and likely some option to ignore default gateways at all.

**Comment by mimugmail** [comment] 2019-05-07 14:15
Agree! What are the next steps? CFT? Shall I write a small guide with some screenshots on a unofficial place or in docs so users can try this (if there are some 😄)

**Comment by AdSchellevis** [comment] 2019-05-08 11:18
@mimugmail if you have a list of test scenario's it might be practical to find a spot in the docs for it, I don't think we have a lot of documentation about it. Maybe a call for testing on the gateway priority feature itself @fichtner what do you think?

**Comment by mimugmail** [comment] 2019-05-16 07:17
@fichtner ? :)

**Comment by fichtner** [comment] 2019-05-17 12:41
19.1.8 happened... I will come up with a plan for 19.1.9...

**Comment by fichtner** [comment] 2019-07-11 12:32
this is done, thanks all! ❤️

**Closed by fichtner** 2019-07-11 12:32 UTC
Labels: feature
