### ISSUE TITLE
VLAN device naming has changed

### ISSUE THREAD

**Issue by kabaga** [opnsense/core#5713] opened 2022-04-16 14:50 UTC
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

I am running 22.1.6. I created a new VLAN and its device name is vlan01. The VLAN that I created in the past are named after the physical interface such as cxl1_vlan10, cxl1_vlan11, etc.
When I created another VLAN for testing, the name just incremented which was vlan02. Is this the norm now with OPNSense?

**To Reproduce**

1. Create a new VLAN interface
2. Under the "Device" column, the VLAN name is vlan01

**Expected behavior**

The name should be based on the physical interface such as cxl1_vlan10, cxl1_vlan11, etc

**Describe alternatives you considered**

N/A

**Screenshots**

N/A

**Relevant log files**

N/A

**Additional context**

See description

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 22.1.6-amd64
FreeBSD 13.0-STABLE
OpenSSL 1.1.1n 15 Mar 2022

**Comment by fichtner** [comment] 2022-04-16 14:56
Working as intended. Discussed a number of times now. I’m closing this.

**Closed by fichtner** 2022-04-16 14:56 UTC
Labels: support

**Comment by kabaga** [comment] 2022-04-16 15:48
So does it mean that it is the new normal now?
What is going to happen to VLANs that were created before that are still using the old device names?

**Comment by AdSchellevis** [comment] 2022-04-16 16:58
existing vlans use their old names, only new (or changed) ones will use the new scheme.
