### ISSUE TITLE
Dashboard: Interface widget auto resize or adjustable

### ISSUE THREAD

**Issue by KGBist2000** [opnsense/core#7711] opened 2024-08-02 16:55 UTC
**Important notices**
V24.7.9

**Describe the bug**

With in the new dashboard, the interface widget it not able to show all interface in the same time. a resize of the widget is not possible.

**To Reproduce**

1. try to select the buttom of the interface widget to resize -> not possible

**Expected behavior**

The interface widget is able to show all interfaces at the same time or is adjustable by the size.

**Comment by Monviech** [comment] 2024-08-02 18:53
Probably duplicate of this: https://github.com/opnsense/core/issues/7628

**Comment by igormiktor** [comment] 2024-08-04 17:26
Not OP, but I also notice this issued and I believe it is not quite same as [#7628](https://github.com/opnsense/core/issues/7628)

So here is the template info:

- [ x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue  
 - Note that I believe it is related to, but partially different from issue #7628. (Perhaps they should be combined?) 

**Describe the bug**

To "Lobby:Dashboard" add the "Interfaces" widget.  There is room for only at most 4 interfaces to display because the widget is too short (I have 6 physical plus various Wireguard and VLAN interfaces).  Moving the mouse over the bottom border zone of the widget does not allow me to make the Interfaces widget longer to show more interfaces.

**To Reproduce**

Steps to reproduce the behavior:
1. Add "Interfaces" widget on a system with at least 5 interfaces
2. Attempt to use the mouse to stretch the bottom of the widget to make it longer
3. No "move-the-bottom-edge-cursor" appears.  And it is impossible to click and drag the bottom edge downwards.

**Expected behavior**

A "drag-the-bottom-edge" cursor appears that allows me to "drag" the bottom edge of the widget downward and make the widget longer to display more interfaces.  Similar to the behavior of the "Services" widget.

Note that I do not desire the "Interface" widget to "auto-size": I desire the adjust the size of the widget and have it set ("locked") at that size.

**Describe alternatives you considered**

No real work-around except living with the very short Interfaces widget and having to scroll within the widget itself to review all my interfaces.

**Screenshots**

Attached  
![Screenshot_20240804_125826](https://github.com/user-attachments/assets/d5a56b1d-9fe3-4d05-b00a-fb7cbd0ed039)

**Relevant log files**

N/A

**Additional context**

N/A

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 24.7_9 (amd64).
Intel Core i3-10105 3.7 GHz  Quad Core
Intel I219-V 1GbE NIC (motherboard)
Intel EXPI9404PTL Quad-Port 1GbE NIC
10Gtek (Intel 82576) Dual-Port 1GbE NIC 


**Thanks**

Really appreciate all your work on OPNsense and commend the excellent job with 24.7.  Really nice!  
This is a very minor, cosmetic issue so completely understand if it is relatively low priority.  But it is hopefully not a hard thing to fix.

**Comment by swhite2** [comment] 2024-08-05 09:15
@igormiktor https://github.com/opnsense/core/issues/7628 does the describe the same issue, albeit with a different proposed solution. The patch mentioned there should also fix the behavior you're seeing.

```
# opnsense-patch 4bd6ad3
```

**Comment by fichtner** [comment] 2024-08-06 06:36
Confirmed fixed in upcoming 24.7.1.

**Closed by fichtner** 2024-08-06 06:36 UTC
Labels: support
