### ISSUE TITLE
Problems with ":" in backup filename

### ISSUE THREAD

**Issue by EagleWolfpack** [opnsense/core#3765] opened 2019-10-14 12:49 UTC
Hi,

":"s in filename is a problem on MS Windows Clients because ":"s are not allowed.
So the Nextcloud Client isn't able to sync these files directly.

Regards
Chris

**Comment by fabianfrz** [comment] 2019-10-14 17:32
duplicate of #2498

**Comment by EagleWolfpack** [comment] 2019-10-15 06:25
Sry, didn't saw it.
I looked @ #2489 but didn't found a solution.
Is there a way to edit the filename by my self?

Regards
Chris

**Closed** 2019-10-15 14:27 UTC
Labels: support

**Comment by fabianfrz** [comment] 2019-10-15 15:01
if you change it in the web interface or another interface of nextcloud, then yes.

**Comment by EagleWolfpack** [comment] 2019-10-15 15:10
> if you change it in the web interface or another interface of nextcloud, then yes.
I know that way;

With my question I ment the way via opnsense web-interface to define the name of the backup file.
It seems the name is hard-coded in nextcloud.php (Line 140)
https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/library/OPNsense/Backup/Nextcloud.php

but I can't find this file at my opnsense box.

Regards
Chris

**Comment by fabianfrz** [comment] 2019-10-15 15:34
That file does not exist - it will be directly written to nextcloud without writing something to the local file system. It only exists in memory.

**Comment by EagleWolfpack** [comment] 2019-10-15 20:48
OK, THX

Any idea to change the backup filename inside of opnsense?

**Comment by fabianfrz** [comment] 2019-10-15 21:22
you would have to change the code in the file you have linked. There is no UI option.

A ready to use workaround is available via the linked ticket.
