### ISSUE TITLE
Disabled static route removes routes with same network learned from another service

### ISSUE THREAD

**Issue by pabe-github** [opnsense/core#4672] opened 2021-02-04 17:37 UTC
- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I have searched the existing issues and I am convinced that mine is new.

**Describe the bug**
Adding a disabled route and saving or
disabling a route and saving
or saving with a disabled route already configured deletes routes with the same network but different gateways.
This means it deletes routes otherwise used/configured, for example routes from/to openvpn or wireguard peers.

**To Reproduce**

1. Have an existing route, like a wireguard peer with allowed IP
2. Go to System->Routes->Configuration and add a disabled route with this IP, Save
![image](https://user-images.githubusercontent.com/42635243/106931644-13db9b00-6717-11eb-95b1-42eca4ef7fcb.png)

After restarting the VPN the route gets added again, until someone hits the save button in the static route configuration.

**Expected behavior**

Not removing existing routes that were not manually added under System->Routes->Configuration
Or not removing routes that have the same destination-network but different gateways.

**Relevant log files**
root@home:~ # netstat -rn | grep 10.43.0.10
10.43.0.10/32      wg1                US          wg1
*steps to reproduce*
root@home:~ # netstat -rn | grep 10.43.0.10
root@home:~ # 
*disabling and enabling wg1 Local*
root@home:~ # netstat -rn | grep 10.43.0.10
10.43.0.10/32      wg1                US          wg1
*just clicking save in the static routes screen still having the disabled route configured*
root@home:~ # netstat -rn | grep 10.43.0.10
root@home:~ # 

Software version used and hardware type if relevant, e.g.:

OPNsense 20.7.8-amd64
FreeBSD 12.1-RELEASE-p12-HBSD
OpenSSL 1.1.1i 8 Dec 2020

OPNsense 20.1.8_1-amd64
FreeBSD 11.2-RELEASE-p20-HBSD
OpenSSL 1.1.1g 21 Apr 2020

**Comment by AdSchellevis** [comment] 2021-02-04 18:20
the core system doesn't add disabled routes, only deletes them. 

https://github.com/opnsense/core/blob/9121ee88cecfbad31e35fe4353a497c1d235f034/src/etc/inc/system.inc#L554-L556

**Comment by pabe-github** [comment] 2021-02-04 21:06
Here is an easier way for reproducing: Just adding two Hostroutes to something like 1.1.1.1/32
If tried adding them in different orders.

Also, confirmed on 21.1, bug exists:
OPNsense 21.1-amd64
FreeBSD 12.1-RELEASE-p12-HBSD
OpenSSL 1.1.1i 8 Dec 2020

The expected behavior would still be that opnsense wouldn't delete routes with the same destination-net and different gateways.


This configuration successfully adds a route:
root@home:~ # netstat -rn | grep 1.1.1.1
1.1.1.1/32         192.168.1.1        UGS         re1
![image](https://user-images.githubusercontent.com/42635243/106954367-f5d06380-6733-11eb-84dc-4350d26e7ab7.png)

This configuration removes the top route:
![image](https://user-images.githubusercontent.com/42635243/106954301-e224fd00-6733-11eb-89f1-c4edfad58af9.png)


This configuration adds the route to the routing table:
The routes are added to the configuration as seen in the screenshot, the disabled route was added first.
So on clicking "Save" opnsense is trying to delete routes to 1.1.1.1/32 and afterwards the route to 1.1.1.1/32 is added
![image](https://user-images.githubusercontent.com/42635243/106954824-9f175980-6734-11eb-8d44-c811949e9477.png)

**Comment by pabe-github** [comment] 2021-02-04 21:14
> the core system doesn't add disabled routes, only deletes them.
> 
> https://github.com/opnsense/core/blob/9121ee88cecfbad31e35fe4353a497c1d235f034/src/etc/inc/system.inc#L554-L556


Thanks for your response, just to be clear, I think the delete in line 556 needs to include the gateway ip for it to stop deleting routes of openvpn or wireguard. or other static routes like in my screenshots

**Comment by AdSchellevis** [comment] 2021-02-05 08:21
that's probably the misunderstanding here, in FreeBSD (without using fibs), you can only have a single destination set, when defining it twice, there's no guarantee which one it will use. adding a constraint to prevent duplicates might be a good idea, but obviously won't fix your issue.

**Comment by pabe-github** [comment] 2021-02-05 12:58
> that's probably the misunderstanding here, in FreeBSD (without using fibs), you can only have a single destination set, when defining it twice, there's no guarantee which one it will use. adding a constraint to prevent duplicates might be a good idea, but obviously won't fix your issue.

I am not trying to have two routes with the same destination.
Imagine this scenario:
You have two gateways (DefaultGW & ExpensiveFallbackGW) to reach a destination.
DefaultGW is rather cheap, ExpensiveFallbackGW uses a path that charges a ridiculous amount of money per MB.
Your boss prohibits some kind of autofailover because of fear of costs.
So you add the static route using DefaultGW and you add the route using ExpensiveFallbackGW but check the disabled-checkbox, so some other tech just needs to disable the route using the DefaultGW and un-disable (enable) the route using the ExpensiveFallbackGW.

When you add the two static route in the order "DefaultGW" and then "ExpensiveFallbackGW", no route gets added to the system. The second route deletes the first route, even though it is disabled.
If you add the routes in reversed order, first the disabled and then the enabled route, the "default" works, but when trying to failover (enable the first, disable the second) no route gets added.

And the problem is not having a enabled(!) static route that deletes the route of some other process, but having a disabled(!) route doing this.

**Comment by AdSchellevis** [comment] 2021-02-05 13:10
I wouldn't advise doing this, but if the problem is that the system can't always keep track if the differences, this is a duplicate of https://github.com/opnsense/core/issues/4621. 

To keep it safer, we should probably prevent duplicates from being added (we can't just keep system and static ones in sync since it will interfere with dynamic routing protocols which are more suitable for the job anyways).

I'll leave the ticket open marked support for now, in case anyone else would like to discuss this further.

**Comment by AdSchellevis** [comment] 2021-05-26 12:33
https://github.com/opnsense/core/commit/d24eeea7de7953fafd68a0e88b2d418aee33ed91 solves https://github.com/opnsense/core/issues/4621, let's close this issue as well with it.

**Closed by AdSchellevis** 2021-05-26 12:33 UTC
Labels: support
