### ISSUE TITLE
GUI web-proxy writes bad squid-conf

### ISSUE THREAD

**Issue by steffda** [opnsense/core#3255] opened 2019-02-26 23:13 UTC
1. In "Proxy Auto-Config" --> Rules / Matches / Proxies the GUI does not accept "-" in Names and Descriptions. Clicking save the GUI is hanging several Minutes but does not save the settings.
2. In Forwarding Proxy ("Weiterleitungsproxy"), configured Ports  are not saved and not written to the squid.conf.
3. In General Settings ("Allgemeine Proxyeinstellungen")  clicking apply causes hanging the GUI for several minutes but squid is not starting.
In cache.log i find that:
"FATAL: No HTTP, HTTPS, or FTP ports configured
Squid Cache (Version 3.5.28): Terminated abnormally."

Version is 19.1

**Comment by fabianfrz** [comment] 2019-03-22 22:28
@fichtner the can go back to one of you as my part (1) is done (the others are unrelated)

**Comment by fichtner** [comment] 2019-03-23 07:59
@steffda I can't reproduce 2. -- it's true that they are not written when you don't have an interface selected, but that's expected. 3. would point to the same issue but I also cannot reproduce.

**Comment by steffda** [comment] 2019-04-04 20:27
I can not select any interface. I can write one into the GUI-field, but it does not take it.
![opnsense-squid](https://user-images.githubusercontent.com/48035684/55586266-d4158800-5728-11e9-8bcc-6d761df553ba.png)

**Comment by fichtner** [comment] 2019-04-04 20:29
You can only use static interfaces there. They will show up automatically.

**Comment by steffda** [comment] 2019-04-04 21:07
I have only one physical Interface on my Server, thats WAN. This is not offered by the GUI.
In between i could create a VLAN on the WAN-Interface and then the offered in the interfaces-section a interface called OPT1 which is assigned to VLAN.
This OPT1 the is offered in the squid preferences, but squid does not work. 
![opnsense-interfaces](https://user-images.githubusercontent.com/48035684/55588528-4c327c80-572e-11e9-9052-dfa00daab9b9.png)
![opnsense-squid-1](https://user-images.githubusercontent.com/48035684/55588535-505e9a00-572e-11e9-9bf6-f6ed4431cb62.png)
![opnsense-squid-2](https://user-images.githubusercontent.com/48035684/55588537-52c0f400-572e-11e9-9a5e-60db322ba045.png)

**Comment by fichtner** [comment] 2019-04-05 05:08
What matters here is your configuration of Interfaces: [WAN] and [OPT1]

"IPv4 Configuration Type" and/or "IPv6 Configuration Type" need to be set to static IP addressing.

**Comment by darrelclute** [comment] 2019-04-26 20:21
Specifying `http_port 3128` in the config will listen to all addresses.  I see this as an adequate default when no interfaces are selected, since you would still need to open explicitly the port in the firewall rules when not using the default LAN->WAN ruleset.  With the default LAN->WAN ruleset you are only exposing this on the internal interfaces anyway.

With using `http_port 3128` you also open the possibility of using an IP Alias on lo0 to reach the Squid service.  When you have multiple internal interfaces but want to use the same address for all, the current interface options are only for the assigned interfaces with static config.  As lo0 doesn't get assigned, but can host IP Aliases, the current configuration engine template rendering means you can't use a service address on lo0.

Contrast the current behavior with the Unbound DNS configuration where you can bind to all when no interfaces are selected and you can then utilize an IP Alias on lo0 to serve as your DNS address for all internal networks.  Have the option of using `http_port 3128` in the config when no interfaces are selected would be consistent with other services as well, and cut down on some of the confusion that can arise when behavior is different.

**Comment by fichtner** [comment] 2019-06-04 15:05
@darrelclute if you want to suggest a feature please do not recycle support tickets. I'm closing this particular issue after no more feedback.

**Closed by fichtner** 2019-06-04 15:05 UTC
Labels: support
