### ISSUE TITLE
Strong authentication options for the web GUI

### ISSUE THREAD

**Issue by mvglasow** [opnsense/core#6334] opened 2023-02-16 16:46 UTC
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

Currently, if I need to make the web GUI available on the external interface and accessible from a public network, I have the following options:

* Simple password authentication.
  * Pros: Easy to set up and use, all necessary resources are bundled with OPNsense, low risk of getting locked out due to a malfunction, not tied to a particular client device.
  * Cons: Highest risk of abuse, through shoulder surfing, brute forcing etc. – which is why most organizations consider password-only authentication insufficiently secure to access sensitive resources from a public network.
* Require external admins to come in through VPN (block access from the public interface but allow it from VPN).
  * Pros: All necessary resources are bundled with OPNsense. As secure as the VPN login (e.g. OpenVPN allows for certificate-based authentication).
  * Cons: Somewhat complex to set up and use, risk of getting locked out in case of a malfunction, potentially tied to a specific client device.
* Use a one-time password solution as an authentication backend.
  * Pros: Easy to use, low risk of getting locked out due to a malfunction, good security, not tied to a particular client device.
  * Cons: Complex to set up, requires resources not bundled with OPNsense.

**Describe the solution you like**

I would like OPNsense to come with native support for some kind of stronger authentication on the web GUI. One option I have in mind is SSL-based authentication with a client/user certificate.

Pros: Easy to use, low risk of getting locked out due to a malfunction, good security. Potentially easy to set up, all necessary resources could be bundled with OPNsense.

Cons: Somewhat tied to a particular client device (the user/client certificate must be installed). Certificates stored on disk could be extracted if the client is compromised, but that could be mitigated by storing certificate keys in dedicated hardware where this is a major risk.

**Describe alternatives you considered**

See above for alternatives already available today. Other options might be:

* One-time passwords sent via text message – but that requires extra hardware (or IP access to a SMSC), and can be attacked by obtaining a replacement SIM card.
* Integrating a one-time password solution – might be an alternative to certificate-based authentication. Users would need to have a code generator available, e.g. on their laptop or mobile phone.

**Additional context**

None.

**Comment by mvglasow** [comment] 2023-02-16 17:29
> just hook a one time password authenticator to the gui.

That would be an option if certs are not feasible for some reason.

Do I need any third-party components (plugins, external systems) for that (if so, which)? Is there any documentation on that? If so, a pointer would be appreciated.

**Comment by kulikov-a** [comment] 2023-02-16 17:51
@mvglasow something like https://www.sunnyvalley.io/docs/network-security-tutorials/how-to-enable-2fa-in-opnsense-with-google-authenticator ?

**Comment by mvglasow** [comment] 2023-02-17 16:42
That worked for me. For more FOSS-minded people, there are plenty of FOSS alternatives to the passcode generators mentioned in the article – FreeOTP+ (on Android) and GNOME Authenticator work for me. Being a cautious person, I made sure to enable SSH (requiring public key authentication) and ensuring I can connect, so I have a second path of access into the system in case TOTP authentication fails for some reason (system clock out of sync, token lost etc.).

I notice the TOTP server allows me to choose between 6 and 8 digits, but after scanning the QR code into FreeOTP+, it always generates 6-digit codes, regardless of what is set for the TOTP server. (Scanning the code with a QR code scanner and looking at the URL reveals there is no digits parameter, at least for the 6-digit code I am now using.) There’s also no warning when there’s no user with a seed code which satisfies the requirements of the TOTP server. I haven’t tested everything thoroughly and may have missed something, but unless the QR code specifies the digits parameter at least when it is not equal to 6, and unless you have a check in place that prevents one from requiring TOTP without at least one (sufficiently privileged) user set up properly, I see a potential lockout issue here.

These would be two potentially unrelated issues:
* QR code not specifying the number of digits
* no check when modifying user or authentication settings whether this will result in anyone getting locked out of the system, and/or if any users are still able to log in

Let me know if you would like me to file separate issues for these.

**Comment by AdSchellevis** [comment] 2023-02-17 17:40
can we close this issue?

> QR code not specifying the number of digits

Only makes sense to open a ticket when clear what the issue is and a direction of a.fix, otherwise it's highly unlikely anyone will spend time on it.

> no check when modifying user or authentication settings whether this will result in anyone getting locked out of the system, and/or if any users are still able to log in

To be honest, I don't think you can reliably nor should we try in that case. Your web session will remain active while changing options, easy to try on a separate (private) browser if you can still login yourself.

**Comment by mvglasow** [comment] 2023-02-17 18:12
> can we close this issue?

As far as I am concerned, yes – I have found a secure way to set up Internet access to my system.

**Closed** 2023-02-17 20:55 UTC
Labels: support
