### ISSUE TITLE
Alias group problem

### ISSUE THREAD

**Issue by advcron** [opnsense/core#3431] opened 2019-04-19 10:02 UTC
**OPNsense Version:**
OPNsense 19.1.6-amd64
Clean install from OPNsense-19.1.4-OpenSSL-dvd-amd64.iso

More detail:

1. Host Alias with content of ip/net working/update well. Except situation in point 3.
2. Host Alias with content of anather alias (alias group). Not working.

![1](https://user-images.githubusercontent.com/38749228/56419543-dafcd880-629a-11e9-9642-a2b5edbab8b7.PNG)

a) Max entries of exist alias in alias group is five.
With max 5 entires files contains correct list of addresses. :
/var/db/aliastables/self.txt
/var/db/aliastables/md5.txt
/var/db/aliastables/*.txt
3. More then 5 entries couse that the anather host aliases (not group alias)  stop working well. Not update.
4. ALL alias group files (even witch three entries) dosen't update when we click Apply. We have to delete or change md5 sum file in /var/db/aliastables.
5. Delete alias not erase files in /var/db/aliastables and still exist in pftable.

########################################################

Removing all three "**|encode_idna**" in file
`/usr/local/opnsense/service/templates/OPNsense/Filter/filter_tables.conf`
fix Problem in point 2,3

But problem still exist in point 4,5

**Comment by AdSchellevis** [comment] 2019-04-19 11:58
[2,3] duplicate of https://github.com/opnsense/core/issues/3399, [5] delete seems to mis a cleanup indeed, we'll take a look at that. For point [4], please create a new issue containing a step by step procedure how to reproduce. I can't reproduce the issue that none of the updates work.

**Closed** 2019-04-19 12:38 UTC
Labels: bug
