### ISSUE TITLE
Unbound DNS doesn't reload if new overrides added

### ISSUE THREAD

**Issue by schlegel11** [opnsense/core#6188] opened 2022-12-11 19:03 UTC
**Describe the bug**

If I go to Services -> Unbound DNS -> Overrides -> Add new entry in Host Overrides table -> apply the change

Unbound DNS doesn't reload, it just stops without any notification. This is highly annoying and leads to long troubleshooting.

**To Reproduce**

go to Services -> Unbound DNS -> Overrides -> Add new entry in Host Overrides table -> apply the change

**Expected behavior**

Unbound DNS just restarts and is in running state.

**Environment**

OPNsense 22.7.9_3 (amd64, OpenSSL).

**Comment by codiflow** [comment] 2022-12-11 20:17
What kind of entry did you add there? If it was a wildcard entry like * it most likely does not reload because it failed to start because of a duplicate primary zone.

Some more information would be helpful here. And did you already check the logs of Unbound after you added your entry to the Overrides? Please also mind the drop-down for the severity in the upper right corner of the log viewer which can be changed to **Information** or **Debug**.

**Comment by schlegel11** [comment] 2022-12-11 23:21
Hi :smiley: 
Yep I checked also the log but there was nothing special included so nothing which looks like an error.
When I try to reproduce the issue now everything is working so the service gets reloaded. Weird.

I think I will try something different to reproduce and will update the issue.
If Im not able to reproduce it anymore I can close this ticket.
  
Anyway maybe it would be helpful for users to get a more "noticeable" message if the service can't be started after a reload.

**Comment by erdnuesse** [comment] 2022-12-16 12:57
Hi, just wanted to confirm, I just experienced the same thing, and 5 minutes in troubleshooting, found this open issue. If help with reproduction is needed, I'm also willing to help. 
What I did: 
- added 1 forward for a single internally hosted DNS zone (intra.mydomain.tld -> myDNS) , 
- hit apply, (my unbound on OPNsense is currently SPOF) and 
- found that it didn't properly reload and 
- was marked red on the dashboard. 
- starting manually on the dashboard worked

**Comment by pictosun** [comment] 2023-01-20 05:37
Hi. Can confirm this issue.
- OPNsense: 22.7.11
- Unbound:  1.17.1_1

Behaviour same like @erdnuesse wrote.

**Comment by pictosun** [comment] 2023-01-20 06:09
Maybe I found the issue.
@erdnuesse @schlegel11 please check if changing the 'domain' name within System: Settings: General to another name solve the bug.

I did change the domain name and then back to my name before and now Unbound will not stop anymore.

**Comment by pictosun** [comment] 2023-01-20 10:54
The corresponding error I could find is Error configd.py "[XYZ]Script action stderr returned "b'pgrep: Cannot get process list (kvm_getprocs: No such process)'"

**Comment by kulikov-a** [comment] 2023-01-20 12:34
@pictosun imho this error can be safely ignored (unbound status requested when unbound not working). pgrep sends this message to stderr when requested proc not found (no way to make pgrep do this quiet)
on the main question - it is difficult to understand what could cause errors (perhaps the validation regez allow an incorrect domain name and a configuration error occurs?)

**Comment by schlegel11** [comment] 2023-01-23 22:31
> Maybe I found the issue. @erdnuesse @schlegel11 please check if changing the 'domain' name within System: Settings: General to another name solve the bug.
> 
> I did change the domain name and then back to my name before and now Unbound will not stop anymore.

The thing is I can not reproduce this bug anymore. I'm not sure what causes this behavior.

**Comment by fichtner** [comment] 2023-01-24 16:22
@swhite2 or me are happy to look into it if the need arises and this is easily reproducible.

That being said I've seen some races earlier in 22.7.x and also Unbound not being ready when the legacy page reloads so that it looks like it didn't start but already was. I'm not sure what force-starting does to the situation in those early 22.7.x but it can't be good as witnessed by #6028 earlier. But that code is in 22.7.11 for sure and therefore also in 23.1.


Cheers,
Franco

**Comment by berndulum** [comment] 2023-02-22 16:05
Hi @fichtner, @swhite2, I am experiencing the same bug. Creating a new override and clicking on apply stops the unbound server and it is not restarting. Here are the relevant logs:

- [unbound (level 5)](https://gist.github.com/berndulum/1a2b2a2047f5a50ef87bbd37d28d6e9e)
- [confd](https://gist.github.com/berndulum/1c4b8ed0468651a3bdac61358eba8f6e)

For me it really looks like that the restart process is stopped with the log
```
Script action stderr returned "b'pgrep: Cannot get process list (kvm_getprocs: No such process)'"
```

I am running 
- OPNsense 22.7.4-amd64
- FreeBSD 13.1-RELEASE-p2
- OpenSSL 1.1.1q 5 Jul 2022

Please let me know if you need addition information.

**Comment by fichtner** [comment] 2023-02-22 16:08
Well the indicator is red but unbound is slow to start is all what I am seeing.

**Comment by kulikov-a** [comment] 2023-02-22 16:15
looks similar to https://forum.opnsense.org/index.php?topic=32514.0 for me (some custom .conf messing up the settings from the GUI?)

**Comment by berndulum** [comment] 2023-02-22 16:25
@fichtner What is the expected time for startup of unbound? I can try it again and wait a bit longer.

@kulikov-a There are no logs about errors in the config. If the custom config is the problem, I would expect that I cannot start unbound at all. But a normal start is possible without any problems. Is there some logic which is only applied during a restart?

**Comment by kulikov-a** [comment] 2023-02-22 16:33
> But a normal start is possible without any problems.

so it starts normal with new overrides and only refuses to start on Apply click  ? (then it's something else. if any)

**Comment by berndulum** [comment] 2023-02-22 16:37
Yes, it starts normally with the new overrides.

I tested it again and waited 10 minutes. But unbound did not came back. I had to start it manually.

**Comment by kulikov-a** [comment] 2023-02-22 16:41
sounds weird indeed.
would be interesting to see what will appear in the logs (if any) for the same actions after applying the 
`opnsense-patch -a kulikov-a 26bec82`

**Comment by swhite2** [comment] 2023-02-24 08:31
alternatively `kill` the current unbound process (`ps -faxd | grep unbound`)

and start it up in verbose mode `unbound -vvvdd -c /var/unbound/unbound.conf`.

**Comment by signifywinter** [comment] 2023-03-07 05:28
I experience this issue as well.  Happens when I edited "Overrides", as others have noted.  Also happens when I change any items on the "Query Forwarding" page.

Once "Apply" is hit, it looks like it's reloading, but the service control buttons (Start, Restart, Stop) disappear.  When I go to a different page in the Unbound service, the buttons reappear and Unbound has stopped.  I don't see any errors or messages that would indicate what is happening.

**Comment by fichtner** [comment] 2023-03-30 05:55
This shouldn't happen anymore since 23.1.4?

**Comment by schlegel11** [comment] 2023-03-30 15:36
I never had experienced this reload behavior again. So for me it is fine :smiley:

**Comment by fichtner** [comment] 2023-03-30 15:55
Closing then, thanks for the feedback ❤️

**Closed by fichtner** 2023-03-30 15:55 UTC
Labels: incomplete
