### ISSUE TITLE
Unbound dns over https DOH 

### ISSUE THREAD

**Issue by akilamin** [opnsense/core#6157] opened 2022-11-26 08:02 UTC
under unbound there is no option for dns over https(doh) as of now we have dot (dns over tls) this is a important service in my opinion, since doh masks the dns request better than dot.
As of now we have to use DNS CRYPT PROXY plug in but the custom options window is disabled in the newer version of opnsense so its unsuccesful unless someone has knowledge of editing the config files

**Comment by cristian-ciobanu** [comment] 2022-11-26 13:23
This issue is a duplicate of https://github.com/opnsense/core/issues/5104.
There is also a pull request opened for this feature which should land in version 23.1 according to the milestone.

**Closed** 2023-05-25 06:05 UTC
Labels: incomplete
