### ISSUE TITLE
NAT in IPsec with multiple Phase2

### ISSUE THREAD

**Issue by mimugmail** [opnsense/core#4460] opened 2020-11-13 19:04 UTC
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

**Is your feature request related to a problem? Please describe.**
As we have learned in https://github.com/opnsense/core/issues/440 and https://github.com/opnsense/core/issues/2173 and a couple if others, it's unpredictable to get the ID in from setkey to add the correct commands and there we use `require`
This leads to the problem that every natted packet travels through the last added SA and only when also the other side allows sending packets from a different SA the connection will work.

**Describe the solution you'd like**
I did a couple of testing it figure out in which cases it work and when it doesnt, but also when using OPN to OPN at first in doesn't work and after couple of tests it worked.

The solution about how to get it work was described here: https://github.com/opnsense/core/issues/2173#issue-294879610

I think I found a simple solution for this. It seems to be so easy that maybe I'm totally wrong talking nonsense or just overseen it.
We could add a new Field near SPD to set a `reqid` manually. I took an existing IPsec, added `reqid = 100` and restarted. Via `setkey -PD` it was just 100 and I'd guess @AdSchellevis may have an idea how to tweak the setkey command when reqid field is not empty? :)

**Describe alternatives you've considered**
Also considered ipfw nat but it's quite hacky in combination with pf

What do you think?

**Comment by AdSchellevis** [comment] 2020-11-13 19:32
@mimugmail if pinning the reqid fixes the issue, we might consider removing the `$is_route_base` in 

https://github.com/opnsense/core/blob/87efd07831bc136416a5bd435e6bb67716c16ce7/src/etc/inc/plugins.inc.d/ipsec.inc#L1651-L1653

https://github.com/opnsense/core/blob/87efd07831bc136416a5bd435e6bb67716c16ce7/src/etc/inc/plugins.inc.d/ipsec.inc#L1657-L1659

https://github.com/opnsense/core/blob/87efd07831bc136416a5bd435e6bb67716c16ce7/src/etc/inc/plugins.inc.d/ipsec.inc#L1683-L1685

https://github.com/opnsense/core/blob/87efd07831bc136416a5bd435e6bb67716c16ce7/src/etc/inc/plugins.inc.d/ipsec.inc#L1704-L1706

and change the spdadd, I can provide a patch, but someone needs to test the different IPsec connection options to prevent regressions. at a first glance it doesn't seem to matter if we lock it ourselves (https://wiki.strongswan.org/issues/2264)

**Comment by mimugmail** [comment] 2020-11-13 19:49
I have a test Lab and a customer with about 100 different connections. Testing shouldnt be a Problem

**Comment by AdSchellevis** [comment] 2020-11-14 08:27
@mimugmail if I prepare a patch, can you make a list of the different scenario's you have tested for backtracking? I rather don't make reqid optional if that's not really required, but if people report issues, it helps a lo to know which scenario's have been tested.

**Comment by AdSchellevis** [comment] 2020-11-14 09:01
ok, this doesn't appear to be the 30 minute job I was hoping for, we first need to refactor code to split logic how "left" networks are generated, since the same logic is needed in spd policies. 

https://github.com/opnsense/core/blob/87efd07831bc136416a5bd435e6bb67716c16ce7/src/etc/inc/plugins.inc.d/ipsec.inc#L1463-L1606

Unfortunately the IPsec code to generate a config is still quiet messy...

**Comment by mimugmail** [comment] 2020-11-14 09:41
I'll set up a xls with different scenarios. 
Not sure if make reqid mandatory/automatic would break some setups, most important is to limit it to 1000 so it dont break routebased. 
Would also Limit huge setups with many tunnels and SA's.

**Comment by mimugmail** [comment] 2020-11-14 09:42
I think we can sponsor 4 hours for sure, will get in touch with Robert next week.

**Comment by mimugmail** [comment] 2020-11-16 09:28
Just for the record: When settings Interface in P1 to %any it seems also when setting My Identifier to IP Address the spdadd doesn't seem to add this. Maybe we can also check this during code refactoring.

**Comment by AdSchellevis** [comment] 2020-11-22 15:04
@mimugmail it needs a migration, but this might fix your issue.

To install, use the following on a stick 20.7.5:
```
opnsense-patch  4f27c80  b9becfe 143832e
/usr/local/opnsense/mvc/script/run_migrations.php
```

**Comment by mimugmail** [comment] 2020-11-25 19:55
I installed the patch on the test system and it looks fine, also with tunnel isolation and combined with route-based.
Will do final testing on Friday.

Thx!

**Comment by mimugmail** [comment] 2020-11-30 07:00
We tested it in Friday on production Firewall with 130 IPs and over 350 SAs, worked pretty fine 👍

**Comment by AdSchellevis** [comment] 2020-11-30 07:58
@mimugmail I think we can merge the changes to master in that case or are there other things you would like to test?

**Comment by mimugmail** [comment] 2020-11-30 08:27
I think master is fine then and would also others allow to test it. Thx for your efforts, really enjoyed this one 👍

**Comment by AdSchellevis** [comment] 2020-11-30 08:42
@mimugmail ok, merged in https://github.com/opnsense/core/commit/7be00bc067c0ae570b07b77cf16a71fd3afeac13

**Closed** 2020-11-30 08:42 UTC
Labels: feature
