### ISSUE TITLE
Feature request: Protocol Definition

### ISSUE THREAD

**Issue by DukeSniper** [opnsense/core#1956] opened 2017-11-24 11:51 UTC
The current design only aliases Port Numbers to names. Designing a proper ruleset for protocols that utilize both UDP and TCP (on different ports) would require at least two rule definitions (one for the TCP rule, one for the UDP rule) and at least two Ports Alias definitions (one for the TCP ports, one for the UDP ports). Creating a proper "protocol" Alias (which contains both proto and port definitions) would simplify the ruleset.

Example:

Protocol foo uses TCP port 4711 and UDP port 1234. With the current architecture, there's the following definitions

Port alias FOO_UDP -> 1234
Port alias FOO_TCP -> 4711
rule FOO_TCP -> uses Proto TCP and references Port alias FOO_TCP
rule FOO_UDP -> uses Proto UDP and references Port alias FOO_UDP

With my suggested design, there would only be one rule and one alias:

Proto Alias FOO -> TCP/4711, UDP/1234
rule Foo -> uses Proto alias FOO

**Comment by AdSchellevis** [comment] 2017-11-24 12:54
it doesn't work like that, port aliases are also aliases in pf, they don't contain protocols, for some background information about pf, see https://www.freebsd.org/doc/handbook/firewalls-pf.html

**Comment by DukeSniper** [comment] 2017-11-24 16:37
I'm not asking you to change the core BSD and pf. I'm suggesting a higher layer of abstraction within the OPNSense configuration GUI. The *configured* rules would be leaner, and the actual rule creation code could take care of "translating" that into seperate rules per protocol as needed by pf.

**Comment by AdSchellevis** [comment] 2017-11-24 16:45
Which would imho add more complexity then we should for this subject, the next person might ask for other filter flags in the same context and before you know the alias is a duplicate of the filter rule. Lets try to keep things as simple as possible.

**Closed** 2018-03-25 15:20 UTC
