### ISSUE TITLE
[feature request] Import LDAP groups for System Access

### ISSUE THREAD

**Issue by gvecchicert** [opnsense/core#3444] opened 2019-04-26 16:09 UTC
Please consider adding LDAP groups import in system_groupmanager.php.
Privileges could be granted to an imported LDAP group and children LDAP users inherit them.

Thanks

**Comment by AdSchellevis** [comment] 2019-05-07 20:08
probably now duplicate of https://github.com/opnsense/core/issues/3471

**Closed by AdSchellevis** 2019-05-07 20:08 UTC
Labels: incomplete
