### ISSUE TITLE
VOIP via VPN

### ISSUE THREAD

**Issue by h4p4t3** [opnsense/core#4332] opened 2020-09-08 07:49 UTC
Since updating to 20.7 Connection from outside our network via OpenVPN to our VOIP-Server ist poor. The status of 'inside'-clients is not shown on the clients connected via vpn. Phone calls get interrupted as described here: https://forum.opnsense.org/index.php?topic=18854.0

It seems, the rtp-packets are too big and get fragmented.

Downgrade to 20.1.9 solves the problem.

Works with 
OPNsense 20.1.9_1-amd64
FreeBSD 11.2-RELEASE-p20-HBSD
OpenSSL 1.1.1g 21 Apr 2020
Hardware is a Deciso-Appliance: AMD GX-210UA SOC (2 cores)

Capture 20.7 -> https://forum.opnsense.org/index.php?topic=18854.msg86689#msg86689
Capture 20.1.9 -> https://forum.opnsense.org/index.php?topic=18854.msg87070#msg87070

**Comment by h4p4t3** [comment] 2020-09-09 05:35
Ok, as the problem disappeared I expected the issue to be a bug. The label says something different. ;-)

As community support seems to be at its end, what could be the next step? Commercial support? Not that I am not willing to pay for commercial support - but I see that there was something introduced with the upgrade which limited the functionality. Isn't that a bug?

**Comment by fichtner** [comment] 2020-09-09 07:38
Fragmentation is just a side effect. It would be good to compare ifconfig output on 20.1.9 and 20.7.2.

This is still community support until we know what the issue is and if it can be fixed with code or just a configuration quirk. 20.1 vs. 20.7 is a new operating system and things may be subject to change.


Cheers,
Franco

**Comment by h4p4t3** [comment] 2020-09-09 10:24
Since we are in productive operation, I cannot switch between the versions as often as I like. We are considering purchasing a second firewall to get around these problems. Can we exchange information in more detail in the forum? Since I'm not an IT professional, I can deal better with more precise requests in German.

**Comment by h4p4t3** [comment] 2020-09-18 12:02
ifconfig output -> https://forum.opnsense.org/index.php?topic=18854.msg88070#msg88070

Any help is appreciated!

**Comment by fichtner** [comment] 2020-09-18 13:32
Suspecting the e1000 driver changes are involved here for your NICs. You could try to disable HW features (especially TSO), but I'm not entirely sure this is the right toggle (yet).

**Closed** 2021-03-23 14:18 UTC
Labels: support
