### ISSUE TITLE
Suricata shows a warning on boot

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/core#1233] opened 2016-10-21 17:27 UTC
![virtualbox_opnsense_21_10_2016_19_03_36](https://cloud.githubusercontent.com/assets/3713914/19606706/743351a4-97c4-11e6-98bf-df268b58b13d.png)

**Comment by fichtner** [comment] 2016-10-30 09:26
What should we do here? Mute the output and potentially remove useful hints as to why Suricata may not work as expected?

**Comment by fabianfrz** [comment] 2016-10-30 09:30
I would prefer if It would be changed like described in the warning as it says it is faster and always the fastest option should be used if it does not break anything else ;)

**Comment by fichtner** [comment] 2016-10-30 09:40
It complains about not having selected IPS mode, which is a valid configuration option...

**Comment by fabianfrz** [comment] 2016-10-30 09:47
Maybe suricata wants to use netmap regardless of running IPS or not. Maybe there is something in the configuration where IPS can be disable while using netmap.

**Comment by fichtner** [comment] 2016-10-30 10:16
PCAP mode is sane and safe. Netmap requires newer hardware. I don't see how we should switch because there is a warning in Suricata. If anything it would help to report this to Suricata as a bug. We set suricata.yaml correctly and still have this warning ;)

**Comment by speed47** [comment] 2016-11-02 17:42
I think the warning is not referencing the yaml file but directly the command line. I also noticed I have this warning, and the current command line of my suricata (running in IDS, not IPS) is:

`/usr/local/bin/suricata -D -i re0 --pidfile /var/run/suricata.pid -c /usr/local/etc/suricata/suricata.yaml`

It seems to be complaining that we didn't explicitely told it to use netmap or pcap, and warns us.
I suppose the `/usr/local/etc/rc.d/suricata` file should be modified to add the `--pcap` option when `$suricata_netmap = "NO"` ?

**Comment by fichtner** [comment] 2016-11-02 17:48
@speed47 the launcher scrip is from FreeBSD ports so ideally this needs to be fixed in coordination with them

**Comment by fichtner** [comment] 2016-11-02 22:05
Actually, I think this patch might do the trick coupled with using "$suricata_pcap"

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=212192

**Comment by speed47** [comment] 2016-11-03 11:37
Indeed, it should do the trick. I'll test by patching my rc with their diff and report if it works.

**Comment by speed47** [comment] 2016-11-03 12:11
I can confirm it works by applying their patch (https://bugs.freebsd.org/bugzilla/attachment.cgi?id=174112&action=diff).
My new command-line, even without defining $suricata_pcap, is:
`/usr/local/bin/suricata -D --pcap=re0 --pidfile /var/run/suricata.pid -c /usr/local/etc/suricata/suricata.yaml`.

**Comment by fichtner** [comment] 2016-11-04 17:55
Thanks for testing 👍 I've prodded the bug report, maybe it can be included in FreeBSD soon. 😊

**Comment by fichtner** [comment] 2016-12-10 23:20
still delayed in FreeBSD...

**Comment by fichtner** [comment] 2017-06-09 17:50
The suricata rc script is so royally inflexible that it's simply not possible to fix this warning from our end.

**Closed** 2017-06-09 17:51 UTC
Labels: upstream
