### ISSUE TITLE
DHCP renew drops connection 

### ISSUE THREAD

**Issue by atxbyea** [opnsense/core#6869] opened 2023-09-20 17:28 UTC
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Suddenly whenever the WAN IP is supposed to renew the connection drops because the default gateway disappears

When looking at the logs I see `newwanip` called every 600s, the same as the ISP DHCP lease time (600s)

If following `route show ` from shell the gateway disappears every 600s

If pinging the internet 3-5 packets are lost every 600s

Connecting a laptop running popos to the GPON refreshes the IP every 300s as normal 

Last known version (unknown)

A clear and concise description of what the bug is, including last known working version (if any).

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**

**Expected behavior**

Expected lease to renew at 300s (T1) and not drop packages

**Describe alternatives you considered**

Tried setting supersede dhcp-lease-time 500 but no difference
Tried setting gateway monitoring off, but no difference 

A clear and concise description of any alternative solutions or workaround you considered.

**Screenshots**

**Relevant log files**

If applicable, information from log files supporting your claim.

**Additional context**

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.7.4 (amd64, OpenSSL).
HPE Edgeline 300
Network Intel® I210-AT

**Comment by fichtner** [comment] 2023-09-21 06:03
Can you share a system log from the box? While it should be added and removed it should also be added back on a renew. At least that is how it works for everyone.

You could mail it to franco AT opnsense DOT org


Cheers,
Franco

**Comment by atxbyea** [comment] 2023-09-21 06:13
Thanks @fichtner  I'm guessing this is what you want? It repeats every 10 minutes in `/var/log/system/latest`

```
<13>1 2023-09-21T08:09:21+02:00 sasuke.eirikzlab.local dhclient 5856 - [meta sequenceId="8"] New IP Address (igb1): <WANIP>
<13>1 2023-09-21T08:09:21+02:00 sasuke.eirikzlab.local dhclient 8564 - [meta sequenceId="9"] New Subnet Mask (igb1): 255.255.252.0
<13>1 2023-09-21T08:09:21+02:00 sasuke.eirikzlab.local dhclient 10813 - [meta sequenceId="10"] New Broadcast Address (igb1): 195.1.63.255
<13>1 2023-09-21T08:09:21+02:00 sasuke.eirikzlab.local dhclient 11884 - [meta sequenceId="11"] New Routers (igb1): 195.1.60.1
<13>1 2023-09-21T08:09:21+02:00 sasuke.eirikzlab.local dhclient 15407 - [meta sequenceId="12"] Creating resolv.conf
<13>1 2023-09-21T08:09:22+02:00 sasuke.eirikzlab.local opnsense 17395 - [meta sequenceId="13"] /usr/local/etc/rc.newwanip: IP renewal starting (new: <WANIP>, old: <WANIP>, interface: wan, device: igb1, force: yes)
<13>1 2023-09-21T08:09:22+02:00 sasuke.eirikzlab.local opnsense 17395 - [meta sequenceId="14"] /usr/local/etc/rc.newwanip: ROUTING: entering configure using 'wan'
<13>1 2023-09-21T08:09:22+02:00 sasuke.eirikzlab.local opnsense 17395 - [meta sequenceId="15"] /usr/local/etc/rc.newwanip: ROUTING: configuring inet default gateway on wan
<13>1 2023-09-21T08:09:22+02:00 sasuke.eirikzlab.local opnsense 17395 - [meta sequenceId="16"] /usr/local/etc/rc.newwanip: ROUTING: setting inet default route to 195.1.60.1
<13>1 2023-09-21T08:09:22+02:00 sasuke.eirikzlab.local opnsense 17395 - [meta sequenceId="17"] /usr/local/etc/rc.newwanip: plugins_configure monitor (,WAN_DHCP)
<13>1 2023-09-21T08:09:22+02:00 sasuke.eirikzlab.local opnsense 17395 - [meta sequenceId="18"] /usr/local/etc/rc.newwanip: plugins_configure monitor (execute task : dpinger_configure_do(,WAN_DHCP))
<13>1 2023-09-21T08:09:23+02:00 sasuke.eirikzlab.local opnsense 17395 - [meta sequenceId="19"] /usr/local/etc/rc.newwanip: plugins_configure vpn (,wan)
<13>1 2023-09-21T08:09:23+02:00 sasuke.eirikzlab.local opnsense 17395 - [meta sequenceId="20"] /usr/local/etc/rc.newwanip: plugins_configure vpn (execute task : ipsec_configure_do(,wan))
<13>1 2023-09-21T08:09:23+02:00 sasuke.eirikzlab.local opnsense 17395 - [meta sequenceId="21"] /usr/local/etc/rc.newwanip: plugins_configure vpn (execute task : openvpn_configure_do(,wan))
<13>1 2023-09-21T08:09:23+02:00 sasuke.eirikzlab.local opnsense 17395 - [meta sequenceId="22"] /usr/local/etc/rc.newwanip: Resyncing OpenVPN instances for interface WAN.
<13>1 2023-09-21T08:09:23+02:00 sasuke.eirikzlab.local opnsense 17395 - [meta sequenceId="23"] /usr/local/etc/rc.newwanip: plugins_configure vpn (execute task : wireguard_configure_do(,wan))
<13>1 2023-09-21T08:09:23+02:00 sasuke.eirikzlab.local opnsense 38674 - [meta sequenceId="24"] /usr/local/etc/rc.routing_configure: ROUTING: entering configure using defaults
<13>1 2023-09-21T08:09:23+02:00 sasuke.eirikzlab.local opnsense 38674 - [meta sequenceId="25"] /usr/local/etc/rc.routing_configure: ROUTING: configuring inet default gateway on wan
<13>1 2023-09-21T08:09:23+02:00 sasuke.eirikzlab.local opnsense 38674 - [meta sequenceId="26"] /usr/local/etc/rc.routing_configure: ROUTING: keeping current inet default gateway '195.1.60.1'
<13>1 2023-09-21T08:09:23+02:00 sasuke.eirikzlab.local opnsense 38674 - [meta sequenceId="27"] /usr/local/etc/rc.routing_configure: plugins_configure monitor (1)
<13>1 2023-09-21T08:09:23+02:00 sasuke.eirikzlab.local opnsense 38674 - [meta sequenceId="28"] /usr/local/etc/rc.routing_configure: plugins_configure monitor (execute task : dpinger_configure_do(1))
<13>1 2023-09-21T08:09:24+02:00 sasuke.eirikzlab.local opnsense 17395 - [meta sequenceId="29"] /usr/local/etc/rc.newwanip: plugins_configure newwanip (,wan)
<13>1 2023-09-21T08:09:24+02:00 sasuke.eirikzlab.local opnsense 17395 - [meta sequenceId="30"] /usr/local/etc/rc.newwanip: plugins_configure newwanip (execute task : dnsmasq_configure_do())
<13>1 2023-09-21T08:09:24+02:00 sasuke.eirikzlab.local opnsense 17395 - [meta sequenceId="31"] /usr/local/etc/rc.newwanip: plugins_configure newwanip (execute task : dyndns_configure_do(,wan))
<11>1 2023-09-21T08:09:25+02:00 sasuke.eirikzlab.local opnsense 17395 - [meta sequenceId="32"] /usr/local/etc/rc.newwanip: Dynamic DNS: updating cache file /var/cache/dyndns_wan_jiraya.homelinux.com_0.cache: <WANIP>
<11>1 2023-09-21T08:09:25+02:00 sasuke.eirikzlab.local opnsense 17395 - [meta sequenceId="33"] /usr/local/etc/rc.newwanip: Dynamic DNS: (Success) No change in IP address
<13>1 2023-09-21T08:09:26+02:00 sasuke.eirikzlab.local opnsense 17395 - [meta sequenceId="34"] /usr/local/etc/rc.newwanip: plugins_configure newwanip (execute task : ntpd_configure_do())
<13>1 2023-09-21T08:09:26+02:00 sasuke.eirikzlab.local opnsense 17395 - [meta sequenceId="35"] /usr/local/etc/rc.newwanip: plugins_configure newwanip (execute task : opendns_configure_do())
<13>1 2023-09-21T08:09:26+02:00 sasuke.eirikzlab.local opnsense 17395 - [meta sequenceId="36"] /usr/local/etc/rc.newwanip: plugins_configure newwanip (execute task : openssh_configure_do(,wan))
<13>1 2023-09-21T08:09:26+02:00 sasuke.eirikzlab.local opnsense 17395 - [meta sequenceId="37"] /usr/local/etc/rc.newwanip: plugins_configure newwanip (execute task : unbound_configure_do(,wan))
<12>1 2023-09-21T08:09:28+02:00 sasuke.eirikzlab.local opnsense 17395 - [meta sequenceId="38"] /usr/local/etc/rc.newwanip: warning: ignoring missing default tunable request: debug.pfftpproxy
``

**Comment by atxbyea** [comment] 2023-09-21 06:40
example of output from the lease

```
  interface "igb1";
  fixed-address <WANIP>;
  option subnet-mask 255.255.252.0;
  option routers 195.1.60.1;
  option domain-name-servers 195.1.0.1,195.1.0.2;
  option host-name "sasuke";
  option domain-name "customer.as2116.net";
  option dhcp-lease-time 600;
  option dhcp-message-type 5;
  option dhcp-server-identifier 193.69.2.40;
  option dhcp-renewal-time 150;
  option dhcp-rebinding-time 300;
  option dhcp-client-identifier 1:20:67:7c:ea:31:e7;
  option domain-search "customer.as2116.net.";
  renew 3 2023/9/20 11:17:31;
  rebind 3 2023/9/20 11:19:20;
  expire 3 2023/9/20 11:25:01;
  ```
  
  if I manage to do `route show default` at the precise moment
  
  ```
root@sasuke:~ # route show default
     route to: default
destination: default
       mask: default
    gateway: 195.1.60.1
        fib: 0
  interface: igb1
      flags: <UP,GATEWAY,DONE,STATIC>
 recvpipe  sendpipe  ssthresh  rtt,msec    mtu        weight    expire
       0         0         0         0      1500         1         0 
done: Command not found.
root@sasuke:~ # route show default
route: route has not been found
``

**Comment by fichtner** [comment] 2023-09-21 09:56
Doesn't seem to be dropping the default route in the log snippet. Not sure what actually does. What plugins do you have installed? Any other WAN  type interfaces here as well (that have a gateway set)?

**Comment by atxbyea** [comment] 2023-09-21 16:55
Only gateway I have configured currently is WAN_DHCP

I have 10 internal interfaces and one wireguard interface

```
	igb0_vlan2307 [WeroVLAN]igb0 (20:67:7c:ea:31:e6)	2307 	
	igb0_vlan300 [LAN]	igb0 (20:67:7c:ea:31:e6)	300
	igb0_vlan2500 [vcf]	igb0 (20:67:7c:ea:31:e6)	2500	 	
	igb0_vlan506 [EIrikVLAN]igb0 (20:67:7c:ea:31:e6)	506	
	igb0_vlan2000 [k8s]	igb0 (20:67:7c:ea:31:e6)	2000
	igb0_vlan10 [VCFVLC]	igb0 (20:67:7c:ea:31:e6)	10
	vlan01 [routernet]	igb0 (20:67:7c:ea:31:e6)	203
	vlan02 [Ezmeral]	igb0 (20:67:7c:ea:31:e6)	2005	 	
	igb0_vlan3100 [ipv6vlan]igb0 (20:67:7c:ea:31:e6)	3100
``

No bridge\gif\gre\lagg\vxlan\loopback
No RIP \ OSPFv3
OSPF\BGP\BFD on one internal network


Any log or config snippet you need, or if I need to change verbosity somewhere, let me know, this is getting very annoying, especially on teams calls.

**Comment by fichtner** [comment] 2023-09-21 18:31
The routes are not touched if already applied. However, FreeBSD has the nagging behaviour of removing a route attached to an IP and dhclient will reset the IP and thus the route is lost. But from your snippet it was added:

<13>1 2023-09-21T08:09:22+02:00 sasuke.eirikzlab.local opnsense 17395 - [meta sequenceId="16"] /usr/local/etc/rc.newwanip: ROUTING: setting inet default route to 195.1.60.1

And then it was still there:

<13>1 2023-09-21T08:09:23+02:00 sasuke.eirikzlab.local opnsense 38674 - [meta sequenceId="26"] /usr/local/etc/rc.routing_configure: ROUTING: keeping current inet default gateway '195.1.60.1'

I'm guessing running `/usr/local/etc/rc.routing_configure` will fix it. I need a better snippet of the system log to see when it was reapplying and when the route was actually missing to get a clue about when it. Is <WANIP> in the subnet of the router? Or is this a "far" gateway setup? I can't tell due to the redacted IP.

**Comment by atxbyea** [comment] 2023-09-21 18:43
This is a regular Norwegian FTTH install, I get a publicly routable IP address from my ISP directly, through a GPON on the wall.

Is it `/var/log/system/latest.log` you want ?

**Comment by fichtner** [comment] 2023-09-21 19:02
There is one more mention here... https://forum.opnsense.org/index.php?topic=32347.msg159215#msg159215 also FTTH, but what I find stranger is that this also says "Resyncing OpenVPN instances for interface wan." and this code aims to remove clear a route based on some sort of IP derivation. I wonder if it kills the default route by accident? Could you turn of the OpenVPN on WAN if you had any? Or modify /usr/local/etc/rc.newwanip to omit the call to `plugins_configure('vpn', false, [$interface]);` for testing?

**Comment by fichtner** [comment] 2023-09-21 19:04
> Is it /var/log/system/latest.log you want ?

Yeah, via mail if possible.

**Comment by atxbyea** [comment] 2023-09-22 14:19
Mail sent, I'll try to do the change this evening when I'm back home

**Comment by atxbyea** [comment] 2023-09-22 16:59
No OpenVPN configured, but I've omitted the line

/*      
 * plugins_configure('vpn', false, [$interface]);
 */

**Comment by atxbyea** [comment] 2023-09-22 17:03
Issue still happened after commenting out, not sure if I need to restart some service after modifying the script

**Comment by atxbyea** [comment] 2023-09-22 19:10
Is it normal to have two dhclient processes for the WAN interface ?

```
root@sasuke:/usr/local/etc # ps xaf | grep dhclient
64042  -  Ss       0:00.70 dhclient: system.syslog (dhclient)
65509  -  Ss       0:01.95 dhclient: igb1 [priv] (dhclient)
82440  -  SCs      0:00.99 dhclient: igb1 (dhclient)
28865  0  S+       0:00.00 grep dhclient
```

**Comment by fichtner** [comment] 2023-09-23 06:41
> Issue still happened after commenting out, not sure if I need to restart some service after modifying the script

okay that's not it then. thanks for testing. The dhclient process list looks ok, same on my end.

I've looked at the log and there isn't much more than what you already posted. I noticed you use intrusion detection... which interfaces is it set for and is it in IPS mode? Do you maybe have Zenarmor installed as well?


Cheers,
Franco

**Comment by fichtner** [comment] 2023-09-23 06:45
Ok, checking your WAN IP you are definitely affected by far gateway behaviour... Can you try this patch? Some people had related issues with the interface route not set, see 3788e996e6ed328df5

    # opnsense-patch 3788e99

**Comment by fichtner** [comment] 2023-09-23 06:52
Discard that last part, I had the wrong subnet mask in the IP calculator. Sorry.

**Comment by atxbyea** [comment] 2023-09-23 07:17
> > Issue still happened after commenting out, not sure if I need to restart some service after modifying the script
> 
> okay that's not it then. thanks for testing. The dhclient process list looks ok, same on my end.
> 
> I've looked at the log and there isn't much more than what you already posted. I noticed you use intrusion detection... which interfaces is it set for and is it in IPS mode? Do you maybe have Zenarmor installed as well?
> 
> Cheers, Franco

Only IDS, but I've disabled it now to see, do you need any config dumps?

**Comment by fichtner** [comment] 2023-09-23 07:21
I'm out of ideas, but I'd really like to fix this. Would it be possible to get SSH/remote access to this box? Monday or Tuesday, supervised of course.

**Comment by atxbyea** [comment] 2023-09-23 07:31
Sure, I'm working from home on both Monday and Tuesday, I will try a few things today and see if it makes any difference, i.e disable everything except the basic wan and LAN and services

**Comment by atxbyea** [comment] 2023-09-23 07:52
disabled all interfaces except LAN and WAN, disabled all services except unbound and dhcpv4

Still happens

**Comment by atxbyea** [comment] 2023-09-23 13:55
I've now
- disabled all my incoming firewall rules on the WAN interface
- disabled the outbound NAT rules
- disabled the shaper pipes, queues and rules
- unchecked the block bogon and private addresses on the WAN interface
- disabled BFD,BGP,OSPF
- removed the GIF tunnel to HE I had


Still happens exactly the same as always, when the lease expires it drops 3 packets then returns

**Comment by atxbyea** [comment] 2023-09-23 14:09
I've now grepped the older system logs, appears to have started with the "newwanip" script calls on the 18th of September, before that there was nothing from the 1st till the 17th of september

**Comment by atxbyea** [comment] 2023-09-23 15:25
The weirdest bit is, it started 01:34 on the 18th of september, which makes very little sense, since I was very much asleep at that point, so I definitivly didn't do anything..

**Comment by atxbyea** [comment] 2023-09-23 15:28
Interesting also.... on the 17th and earlier my WAN ip was in the range `195.1.27.x` whereas on the 18th forward it is `195.1.63.x`

**Comment by atxbyea** [comment] 2023-09-23 16:23
ISP wanted me to try their gateway (which is still in a box..)

after 20 minutes there is no packet loss, so DHCP renew appears to work correctly, and is the same `195.1.63.x` address that I got on opnsense and on my laptop, so it appears that the ISP allocates IP based on GPON, not MAC address of router.

That said, the ISP gateway is almost double the ping compared to opnsense.

1.27 min \ 2.22 average on opnsense
2.30 min \  3.39 average on the ISP gateway

**Comment by NOYB** [comment] 2023-09-23 21:57
I've also experienced a few losses of DHCP obtained WAN IP since upgrade to 23.7.  First couple of times was about a week apart.  Third time about a month later.
At the console, can see that the wan address is gone.
Maybe related, maybe not.  But certainly not as often or on demand reproducible as seems to be for the OP (atxbyea).

ISP provides 4 hour DHCP lease.

Hasn't happened so far with 23.7.4.  But it's only been a week.

OPNsense 23.7.4
FreeBSD 13.2-RELEASE-p3
OpenSSL 1.1.1v 1 Aug 2023
11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz
Some Realtek NIC

**Comment by atxbyea** [comment] 2023-09-24 07:38
Fresh install on another box (23.7, Aliexpress dual nic fanless box), still happens, gonna try an older version of OPNsense

**Comment by atxbyea** [comment] 2023-09-24 08:29
The behavior is actually worse on 23.1, the lease just times out and doesn't renew unless I do a reload on the interface from the Interface -> Overview screen.

Gonna try Untangle..

**Comment by atxbyea** [comment] 2023-09-24 09:56
Untangle gives me more log output in syslog...

I  believe the issue is entirely on the ISP side, I still lose one packet on untangle, when the interface drops.

So...

Currently I have an IP in the `195.1.63.x/22` subnet, however.. the DHCP offer comes from `195.1.185.1` which isn't inside my broadcast domain, and when the client sends out requests on `255.255.255.255` that would obviously not reach the DHCP server unless there is some relay in place.

Since this happened exactly the same time that my IP range changed from my ISP, I'm fully blaming them, and they need to resolve this.

Doesn't happen with the ISP gateway, but I'm guessing that one gets special information that other clients do not.

Client sends the following every 15-30 seconds in the 10 minute interval at periods

`Sep 24 11:48:21 arista dhclient[9123]: DHCPREQUEST for 195.1.63.x on eth1 to 255.255.255.255 port 67
`


```
Sep 24 11:48:27 arista dhclient[9123]: DHCPDISCOVER on eth1 to 255.255.255.255 port 67 interval 4
Sep 24 11:48:28 arista dhclient[9123]: DHCPOFFER of 195.1.63.x from 195.1.185.1
Sep 24 11:48:28 arista dhclient[9123]: DHCPREQUEST for 195.1.63.x on eth1 to 255.255.255.255 port 67
Sep 24 11:48:28 arista dhclient[9123]: DHCPACK of 195.1.63.x from 195.1.185.1
Sep 24 11:48:29 arista ntpd[2010]: Listen normally on 14 eth1 195.1.63.x:123
Sep 24 11:48:29 arista ntpd[2010]: new interface(s) found: waking up resolver
```

**Comment by atxbyea** [comment] 2023-09-24 12:14
So I've tried putting 

`supersede dhcp-server-identifier 255.255.255.255,supersede dhcp-lease-time 120` in  Option Modifiers but that just results in it renewing every 2 minutes with packet loss occuring still

**Comment by atxbyea** [comment] 2023-09-24 12:20
Putting in `supersede dhcp-server-identifier 255.255.255.255,supersede dhcp-lease-time 120` does the renew without any loss every 1 minutes it seems with 

`<13>1 2023-09-24T14:19:42+02:00 sasuke.eirikzlab.local dhclient 98673 - [meta sequenceId="1"] Creating resolv.conf`

repeating as the only entry in the log

**Comment by fichtner** [comment] 2023-09-24 14:51
Ok I have an idea based on your tests… Does the file /tmp/igb1_router disappear?

**Comment by atxbyea** [comment] 2023-09-24 16:51
Yes, if I remove the `supersede` directives the file vanishes every 10 minutes

**Comment by atxbyea** [comment] 2023-09-24 18:40
I agree, the solution works fine, but the ultimate problem is the ISP doesn't adhere to standard DHCP practice, albeit the log handling could be better on opnsense, Linux default records every DHCPREQUEST in syslog, not sure if that is possible on freebsd

**Comment by fichtner** [comment] 2023-09-24 18:41
@atxbyea can you try https://github.com/opnsense/core/commit/633399de85

# opnsense-patch 633399de85

It shouldn't change behaviour, but the logging should clearly indicate that dhclient gave up.

**Comment by atxbyea** [comment] 2023-09-26 06:42
Sorry had a full work day yesterday, didn't have time to do anything at all, patching now, will try disabling the supersede option when the wife isn't in any teams calls

**Comment by fichtner** [comment] 2023-09-26 06:43
@atxbyea no rush and thanks for your help so far :)

**Comment by atxbyea** [comment] 2023-09-26 06:58
New behavior with my current supersede options give me one more log entry at least 
```
<13>1 2023-09-26T08:55:17+02:00 sasuke.eirikzlab.local dhclient 58811 - [meta sequenceId="1"] dhclient-script: Reason RENEW on igb1 executing
<13>1 2023-09-26T08:55:17+02:00 sasuke.eirikzlab.local dhclient 59337 - [meta sequenceId="2"] dhclient-script: Creating resolv.conf
<13>1 2023-09-26T08:56:17+02:00 sasuke.eirikzlab.local dhclient 88996 - [meta sequenceId="1"] dhclient-script: Reason RENEW on igb1 executing
<13>1 2023-09-26T08:56:17+02:00 sasuke.eirikzlab.local dhclient 89271 - [meta sequenceId="2"] dhclient-script: Creating resolv.conf
<13>1 2023-09-26T08:57:17+02:00 sasuke.eirikzlab.local dhclient 19731 - [meta sequenceId="1"] dhclient-script: Reason RENEW on igb1 executing
<13>1 2023-09-26T08:57:17+02:00 sasuke.eirikzlab.local dhclient 20036 - [meta sequenceId="2"] dhclient-script: Creating resolv.conf
``

**Comment by atxbyea** [comment] 2023-09-26 17:01
after removing the supersede settings I see the following after 10 minutes (nothing from the renew -> timeout)

```
<13>1 2023-09-26T18:59:35+02:00 sasuke.eirikzlab.local dhclient 58334 - [meta sequenceId="1"] dhclient-script: Reason EXPIRE on igb1 executing
<13>1 2023-09-26T18:59:35+02:00 sasuke.eirikzlab.local dhclient 59683 - [meta sequenceId="2"] dhclient-script: Reason PREINIT on igb1 executing
<13>1 2023-09-26T18:59:35+02:00 sasuke.eirikzlab.local dhclient 60205 - [meta sequenceId="3"] dhclient-script: Reason ARPSEND on igb1 executing
<13>1 2023-09-26T18:59:37+02:00 sasuke.eirikzlab.local dhclient 60856 - [meta sequenceId="4"] dhclient-script: Reason ARPCHECK on igb1 executing
<13>1 2023-09-26T18:59:37+02:00 sasuke.eirikzlab.local dhclient 61337 - [meta sequenceId="5"] dhclient-script: Reason BOUND on igb1 executing
<13>1 2023-09-26T18:59:37+02:00 sasuke.eirikzlab.local dhclient 61889 - [meta sequenceId="6"] dhclient-script: New IP Address (igb1): 195.1.63.x
<13>1 2023-09-26T18:59:37+02:00 sasuke.eirikzlab.local dhclient 62056 - [meta sequenceId="7"] dhclient-script: New Subnet Mask (igb1): 255.255.252.0
<13>1 2023-09-26T18:59:37+02:00 sasuke.eirikzlab.local dhclient 62656 - [meta sequenceId="8"] dhclient-script: New Broadcast Address (igb1): 195.1.63.255
<13>1 2023-09-26T18:59:37+02:00 sasuke.eirikzlab.local dhclient 63032 - [meta sequenceId="9"] dhclient-script: New Routers (igb1): 195.1.60.1
<13>1 2023-09-26T18:59:37+02:00 sasuke.eirikzlab.local dhclient 63761 - [meta sequenceId="10"] dhclient-script: Creating resolv.conf
<13>1 2023-09-26T18:59:37+02:00 sasuke.eirikzlab.local opnsense 64349 - [meta sequenceId="11"] /usr/local/etc/rc.newwanip: IP renewal starting (new: 195.1.63.x, old: 195.1.63.x, interface: wan, device: igb1, force: yes)

**Comment by fichtner** [comment] 2023-09-28 08:36
It should but maybe it’s never triggering dhclient-script in the first place. I suppose the default route still disappears? Is dhclient process gone as well?

**Comment by fichtner** [comment] 2023-09-28 08:45
Still strange. So EXPIRE would remove the file but BOUND would add it and it says that it has a router and then also executes the reconfiguration.

**Comment by fichtner** [comment] 2024-01-24 07:24
We did a number of cleanups in the dhclient-script area so I'm closing this, also because nobody posted here since September (appears to be a good sign). If there is still trouble open a new ticket based on version 24.1.x or later and provide the improved log output.


Cheers,
Franco

**Closed by fichtner** 2024-01-24 07:24 UTC
Labels: cleanup
