### ISSUE TITLE
[Firewall] Add ruleset for SMB ports

### ISSUE THREAD

**Issue by enoch85** [opnsense/core#1151] opened 2016-08-21 14:19 UTC
Would be nice to be able to choose SMB ports in the TCP/IP ruleset, ports: 137,138,139 and 445.

Would that be possible to add?

**Comment by fichtner** [comment] 2016-08-21 15:30
You're Looking for a port alias? Should be working as expected after defining it under Firewall: Aliases

**Comment by enoch85** [comment] 2016-08-21 21:04
Yes, that was it. But still, would be nice to have included in the pre-defined rules. :)

**Comment by fichtner** [comment] 2016-08-22 06:32
The name-based selection in the ports comes from the known system ports, but they are single port descriptions. The aggregations are port aliases, and for them to show up we'd have to include them into the default config.xml, which only materialises for new users with 17.7 image installs.

The issue is not having them there in the first place, but wanting others in as well, and as soon as one description is wrong in the eyes of someone else we will be forced to negotiate over what is right. I want to try to keep this as simple as possible, so I'll close it. ;)

**Closed by fichtner** 2016-08-22 06:32 UTC

**Comment by enoch85** [comment] 2016-08-22 08:31
Makes sense.
