### ISSUE TITLE
Kea: Support DHCP Vendor Option codes

### ISSUE THREAD

**Issue by bagobones** [opnsense/core#7591] opened 2024-07-01 18:56 UTC
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

Kea is missing Vendor option codes which are used for various network devices such as Unifi devices to discover controllers or SIP phones to discover servers etc.

**Describe the solution you like**

Expose the Option codes in the GUI, Kea should already support them.

**Describe alternatives you considered**

Go back to the old DHCP server

**Additional context**

None

**Comment by AdSchellevis** [comment] 2024-07-01 19:22
duplicate https://github.com/opnsense/core/issues/7550

**Comment by bagobones** [comment] 2024-07-01 22:18
Probably better to link to https://github.com/opnsense/core/pull/7361

I searched open issues but not PRs, issues should probably not be closed till the linked / related PR is merged .

**Comment by fichtner** [comment] 2024-07-02 07:01
The feature request was already a duplicate of the PR. It would be nice if people trusted us running the bug tracker here in an efficient and useful way for the project. 😉

**Closed** 2024-12-28 18:05 UTC
Labels: support
