### ISSUE TITLE
Setting a Policy on abuse.ch ThreatFox set in Intrusion Detection never completes?

### ISSUE THREAD

**Issue by gctwnl** [opnsense/core#6520] opened 2023-04-22 11:31 UTC
**Describe the bug**
Using the abuse.ch ThreatFox ruleset makes Apply on Policies never finish

**To Reproduce**
1. Enable abuse.ch ThreatFox in your set of rules to download in Administration/Download. 
2. Add a policy
3. Hit Apply

**Expected behavior**
Policy saved, Apply button returns to non-working status.

**Actual behavior**
Button keeps showing 'working' status ad infinitum

OPNsense 22.10.2-amd64
FreeBSD 13.1-RELEASE-p7
OpenSSL 1.1.1t 7 Feb 2023

**Comment by gctwnl** [comment] 2023-04-24 09:51
Good plan.

The confusions I experienced were a nasty combination of this 'gui crash', OPNsense UX of ET Telemetry Pro ('Save' button that ET Open doesn't have — I would really look at that one), the fact that you need the 'Telemetry special ET Open rule set' because ET Telemetry ships with 'empty' sets, and the fact that Policy is required after turning IPS on because the rules generally ship as 'alerts'.  Quite a killing combo. I understand it now, but I can imagine I am not the only one who will experience this difficult learning curve.

**Comment by kulikov-a** [comment] 2023-04-24 17:21
hm. if i may, im not sure that this is the gui bug only: if `data` is` undefined` because of `cannot parse response (reconfigure, line 0)`, then it would be very useful to know (via network tab of dev console) what kind of _unparseable_ response was received on `reconfigure` request (if I understand correctly, one of the configd actions returns something unexpected). and i think something useful should arrive in system\backend logs at this moment?

**Comment by AdSchellevis** [comment] 2023-04-24 18:24
https://github.com/opnsense/core/commit/5280cb346bc40fe9dc221dcdae6c9eb4543de74e should prevent it crashing out, but as @kulikov-a suggested, it would still be interesting to know what is being returned here.

**Comment by gctwnl** [comment] 2023-04-24 19:26
> hm. if i may, im not sure that this is the gui bug only: if `data` is `undefined` because of `cannot parse response (reconfigure, line 0)`, then it would be very useful to know (via network tab of dev console) what kind of _unparseable_ response was received on `reconfigure` request (if I understand correctly, one of the configd actions returns something unexpected). and i think something useful should arrive in system\backend logs at this moment?

I'd be happy to check (isn't this easier for Ad who has access to much more than I have?). What exactly do you want? I have been using Safari on macOS with Develop turned on. I have a Network tab, but I have no idea how to get 'what kind of _unparseable_ response was received on `reconfigure` request'. Basically, what I do is enable ThreatFox, then hit the Policy apply button.

**Comment by kulikov-a** [comment] 2023-04-24 19:39
it would be greate, thanks. its should be something like https://jun711.github.io/web/how-to-inspect-network-request-and-response-headers-on-safari/ i think.
when you hit Apply button, the 'reconfigure' request waiting for a response shold be visible in network tab. after a while the response will be received. usually the response body for this kind of request contains {"status":"OK"} or {"status":""}. but if the error is reproduced, then the response may contain something that breaks the script, so the response cannot be parsed.

**Comment by AdSchellevis** [comment] 2023-07-02 16:40
fixed in https://github.com/opnsense/core/commit/5280cb346bc40fe9dc221dcdae6c9eb4543de74e

**Closed by AdSchellevis** 2023-07-02 16:40 UTC
Labels: cleanup
