### ISSUE TITLE
IPv6 connection problems on the OPNsense itself

### ISSUE THREAD

**Issue by Tuxtom007** [opnsense/core#6885] opened 2023-09-26 14:46 UTC
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

No IPv6 connection from the OPNSense itself possible, although IPv6 is active and also works in the complete network behind the OPNSense.

The problem has existed for some time, I can't even say whether it used to work and with which release.

**To Reproduce**

Configuration:
- Vodafone Cable Internet with AVM FritzBox 6591 in bridge mode. ( FritzOS 7.57 )
- DualStack active with IPv4, IPv6 and 759 prefix delegation
- OPNSense receives the IP addresses of the connection on the WAN interface.
- Router Advertisements is active on all VLAN and distributes link local addresses
- DHCPv6 is active per VLAN and distributes one /64 network in each VLAN
- On the client in the VLAN everything works fine

**Expected behavior**

I'm trying to set up DynDNS for IPv6 on the OPNSense, but I can't get any IP address updates from the provider.
After some tests I noticed the following:

Interfaces -> Overview -> WAN
IPv4 address	84.x.x.x/22     ( my public IPv4 )
IPv4 gateway	auto-detected: 84.x.x.254   ( Provider Gateway IPv4 )
IPv6 link-local	fe80::227c:14ff:fea0:3502/64
IPv6 address	2a02:908:f000:c7:x:x:x:x/64    ( my public net )
2a02:908:f000:c7::x/128                      ( my public IPv6 adress)
IPv6 prefix	2a02:8071:x:x::/59               ( /59 Prefix Delegation )
IPv6 gateway	auto-detected: fe80::1212:ff:fe00:6598

System → Gateway → Single
WAN_DHCP6(actice) fe80::1212:ff:fe00:6598
WAN_DHCP (active): 84.x.x.254

System → Router → Status
ipv6 - default - fe80::1212:ff:fe00:6598%igb0 - wan
( Ping6 to the Gateway is fine )

Check external IPv6 Adress directly from the OPNSense runs in timeout:

dig @resolver1.ipv6-sandbox.opendns.com AAAA [[myip.opendns.com](http://myip.opendns.com/)](http://myip.opendns.com/) +short -6
;; communications error to 2620:0:ccc::2#53: timed out
;; communications error to 2620:0:ccc::2#53: timed out
;; communications error to 2620:0:ccc::2#53: timed out

; <<>> DiG 9.18.19 <<>> @resolver1.ipv6-sandbox.opendns.com AAAA [[myip.opendns.com](http://myip.opendns.com/)](http://myip.opendns.com/) +short -6
; (1 server found)
;; global options: +cmd
;; no servers could be reached

the same test from a client in my network works fine:

dig @resolver1.ipv6-sandbox.opendns.com AAAA [[myip.opendns.com](http://myip.opendns.com/)](http://myip.opendns.com/) +short -6
2a02:8071:6310:x:x:x:x:x
( get the right IPv6 adress )

Error:

- Cannot update DynDNS via IPv6
- Updating the OPNSense firmware repositories takes an extremely long time, sometimes even timeouts.
Only when I activate "Prefer to use IPv4 even if IPv6 is available" do they run normally.

**Describe alternatives you considered**

"Prefer to use IPv4 even if IPv6 is available" is not a solution

**Screenshots**

I will be happy to deliver it on request

**Relevant log files**

I will be happy to deliver it on request

**Additional context**

./.

**Environment**
OPNsense 23.7.5-amd64.   ( It already did not work in the previous versions )
FreeBSD 13.2-RELEASE-p3
OpenSSL 1.1.1w 11 Sep 2023
Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (4 cores, 8 threads), 32 GB RAM, SSD
8x Intel i211AT Gigabit LAN

**Comment by fichtner** [comment] 2023-09-28 04:31
To be honest IPv6 seems functional on your end and the ISP's. Make sure you don't have any firewall rules that interfere...


Cheers,
Franco

**Comment by fichtner** [comment] 2023-09-28 15:31
Ok, I'm not sure how to reproduce or make if it. The only way to gather insight here would be to look at the box some more. Try different pings and look at live log output or trying separate ping pass rules (ICMPv6). I'm relatively sure the firewall discards these packets or sends them somewhere they shouldn't be. Maybe a packet capture on the WAN would help to see if the packets exit there or if the reply is never received... etc.

**Comment by Tuxtom007** [comment] 2023-09-28 16:40
Hi,

I did a TCP dump on WAN, filtered by destination IP: 2606:4700:4700::1111 ( heise.de ).
The first part is the ping6 from my notebook in the LAN (works), the second part is to the same destination from the OPNSense, i get "no response found":

from Notebook:
1	0.000000	2a02:8071:6310:1442:2dac:9478:2cfa:86fb	2606:4700:4700::1111	ICMPv6	70	Echo (ping) request id=0x155e, seq=0, hop limit=63 (reply in 2)
2	0.037726	2606:4700:4700::1111	2a02:8071:6310:1442:2dac:9478:2cfa:86fb	ICMPv6	70	Echo (ping) reply id=0x155e, seq=0, hop limit=60 (request in 1)


from OPNSense:
30	22.868063	2a02:908:f000:c7:227c:14ff:fea0:3502	2606:4700:4700::1111	ICMPv6	70	Echo (ping) request id=0x9214, seq=1, hop limit=64 (no response found!)

If desired, I can upload the trace file

Is it possible that I may need a rule or route that works with the way back to the OPNSense?

**Comment by fichtner** [comment] 2023-09-28 18:26
I'm a little unclear on something.

You state your WAN overview shows:

    IPv6 address	2a02:908:f000:c7:x:x:x:x/64    ( my public net )
    2a02:908:f000:c7::x/128                      ( my public IPv6 adress)

The /128 is probably from the provider via DHCPv6 IA-NA and the /64 is probably SLAAC.

Which one is the ping using?

Because sometimes the SLAAC one doesn't work for outgoing and the IA-NA can also be problematic (although your provider doesn't think so handing you both this and the prefix IA-PD).

Personally I'd try to enable "Only request a prefix" in the WAN IPv6 settings and see if that improves the situation already so we can see if the IA-NA address is a problem or not.

Also, pinging with the source address of one of your delegated /64  LANs should work fine...

ping -6 -S address:to:ping:from heise.de

The fact of the matter is the kernel will select the first suitable address but it might not be working due to filtering (worst case at the ISP level).


Cheers,
Franco

**Comment by Tuxtom007** [comment] 2023-10-10 10:35
Hello,

anyone else have an idea how to fix the problem ?

best regards
Thomas

**Comment by fichtner** [comment] 2023-10-10 10:41
I've told you to try `ping -6 -S address:to:ping:from heise.de` to find out which addresses work and which do not.

If the SLAAC one (/64) doesn't work it may be due to the provider dropping it. If you would try this on your LAN GUA it must work because that one is from your delegated prefix but the SLAAC one is not. The IA-NA one (/128) is also not from your prefix but it could work.

The kernel selects the "best" address from the WAN interface. In most cases that means it's the first. If that one doesn't work autoselect is just broken... that's where `-S` option of ping comes in...

**Comment by Tuxtom007** [comment] 2023-10-10 10:59
Hi,

on the OPNSense: 

ping6 with /128 WAN-adress is working:

# ping6 -S 2a02:908:f000:c7::42f  2606:4700:4700::1111
PING6(56=40+8+8 bytes) 2a02:908:f000:c7::42f --> 2606:4700:4700::1111
16 bytes from 2606:4700:4700::1111, icmp_seq=0 hlim=60 time=29.813 ms
16 bytes from 2606:4700:4700::1111, icmp_seq=1 hlim=60 time=17.834 ms
16 bytes from 2606:4700:4700::1111, icmp_seq=2 hlim=60 time=36.567 ms
^C
--- 2606:4700:4700::1111 ping6 statistics ---
3 packets transmitted, 3 packets received, 0.0% packet loss
round-trip min/avg/max/std-dev = 17.834/28.071/36.567/7.746 ms


ping6 with /64 WAN-adress is not working:
# ping6 -S 2a02:908:f000:c7:227c:14ff:fea0:3502   2606:4700:4700::1111
PING6(56=40+8+8 bytes) 2a02:908:f000:c7:227c:14ff:fea0:3502 --> 2606:4700:4700::1111
^C
--- 2606:4700:4700::1111 ping6 statistics ---
8 packets transmitted, 0 packets received, 100.0% packet loss


( on Client-side no problemlos )

**Comment by fichtner** [comment] 2023-10-10 11:01
Can you confirm the LAN GUA works as well? It definitely looks like an ISP issue...

**Comment by Tuxtom007** [comment] 2023-10-10 12:16
do you mean a ping6 from the OPNSense with LAN-Gateway-IP ?

This works also fine ( /64 Gateway-IP of one VLAN )

ping6 -S 2a02:8071:6310:1442:227c:14ff:fea0:3505 2606:4700:4700::1111

PING6(56=40+8+8 bytes) 2a02:8071:6310:1442:227c:14ff:fea0:3505 --> 2606:4700:4700::1111
16 bytes from 2606:4700:4700::1111, icmp_seq=0 hlim=60 time=14.820 ms
16 bytes from 2606:4700:4700::1111, icmp_seq=1 hlim=60 time=14.796 ms
16 bytes from 2606:4700:4700::1111, icmp_seq=2 hlim=60 time=12.161 ms
16 bytes from 2606:4700:4700::1111, icmp_seq=3 hlim=60 time=15.032 ms

In the LAN I have no problems, all clients, regardless of whether they are Linux or MacOS, can access the Internet with IPv6 without any problems using the /64 address via prefix delegation

**Comment by fichtner** [comment] 2023-10-10 12:18
Ok, so it's your ISP messing up the SLAAC /64 not routing it further.

**Comment by Tuxtom007** [comment] 2023-10-10 12:18
The only thing I could try is to connect my MacBook directly to the BridgePort of the route so that it gets the public addresses and test this briefly.
Then the behaviour should be the same if it is an ISP problem.

**Comment by fichtner** [comment] 2023-10-10 12:24
Yep

**Comment by Tuxtom007** [comment] 2023-10-10 18:02
MacBook directly connected to the bridge port of the router, same behaviour:

ping6 with the /128 address works fine
ping6 with the /64 address does not work - 100% packet loss

therefore a problem of the ISP or the behaviour of the AVM FritzBox in bridge mode

**Comment by fichtner** [comment] 2023-10-10 18:32
Ok, thanks for confirming. Close this issue or leave open for follow up from your end?


Cheers,
Franco

**Closed** 2024-02-28 15:40 UTC
Labels: support
